### ISSUE TITLE
ENH: Make trial build URLs real, not require replacement

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/ncov#1019]
When making trial builds, the URL we output at the moment for where one can view is actually not a URL where one can see anything.

I'd prefer if we just output one example URL where one can see something, rather than `REGION_NAME`

<img width="986" alt="image" src="https://user-images.githubusercontent.com/25161793/196675798-27fd0028-d165-49d8-ae70-09b3e03a7052.png">

I've been confused by this in the past, and so has at least @emmahodcroft 

This should be a simple change?

**Comment by joverlee521** [comment]
#991 should resolve this.
