### ISSUE TITLE
Proposal: elevate XBB.1.5 as 22G

### ISSUE THREAD

**Issue by AnonymousUserUse** [nextstrain/ncov#1040]
Apparently, XBB.1.5 shows >0.05 growth advantage per day and has reached >5% regional frequency in North America, thus fulfilling criteria 4 for designating a Nextstrain clade.
https://cov-spectrum.org/explore/North%20America/AllSamples/Past2M/variants?nextcladePangoLineage=XBB.1.5*&
![image](https://user-images.githubusercontent.com/113214374/210159594-62ce73b8-ba57-40fc-a0af-a3d133011da7.png)

Also the relative growth advantage of XBB.1.5 to designated parental Nextstrain clade 22F (XBB) is beyond 5% per day.
https://cov-spectrum.org/explore/North%20America/AllSamples/Past2M/variants?nextcladePangoLineage=XBB*&nextcladePangoLineage1=XBB.1.5*&analysisMode=CompareToBaseline&
![image](https://user-images.githubusercontent.com/113214374/210159615-7844af47-9264-48d7-88a0-b5a279baf3bf.png)

Therefore, I think a rapid designation of XBB.1.5 as 22G makes sense.
@corneliusroemer

**Comment by joverlee521** [comment]
Thank you for the proposal @AnonymousUserUse, XBB.1.5 has been elevated to 23A in #1043.
