### ISSUE TITLE
Query Contains a Column That Does Not Exist in Metadata.

### ISSUE THREAD

**Issue by Samiah-Kanwar** [nextstrain/ncov#1052]
Hello Developers,
I have recently updated the Nextstrain pipeline on `Ubuntu 20.04.5 LTS` which failed with the following error:

```
`ERROR: Query contains a column that does not exist in metadata.
[Tue Mar 21 15:04:39 2023]
Error in rule filter:
    jobid: 23
    output: results/Pakistan-Contextual/filtered.fasta, results/Pakistan-Contextual/filtered_log.tsv
    log: logs/filtered_Pakistan-Contextual.txt (check log file(s) for error message)
    shell:
        
        augur filter             --sequences results/Pakistan-Contextual/masked.fasta             --metadata results/Pakistan-Contextual/metadata_with_index.tsv             --include defaults/include.txt             --query '(`root_ref` == '"'"'yes'"'"' & _length >= 27000) | (`pakistan` == '"'"'yes'"'"' & _length >= 27000) | (`global` == '"'"'yes'"'"' & _length >= 27000)'             --max-date 2023-03-22             --min-date 2019-12-01             --exclude-ambiguous-dates-by any             --exclude defaults/exclude.txt results/Pakistan-Contextual/excluded_by_diagnostics.txt             --exclude-where division='USA'            --output results/Pakistan-Contextual/filtered.fasta             --output-log results/Pakistan-Contextual/filtered_log.tsv 2>&1 | tee logs/filtered_Pakistan-Contextual.txt;
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job filter since they might be corrupted:
results/Pakistan-Contextual/filtered_log.tsv
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /nextstrain/build/.snakemake/log/2023-03-21T150435.599947.snakemake.log

````
I ran the following command:
 `nextstrain build --docker . --cores 72 --configfile my_profiles/Pakistan_contextual/builds.yaml`

The pipeline was working fine before the update. Can you please explain and help what could be the possible reason for the failure of pipeline and how can I resolve this?
I am attaching the builds.yaml file, before and after metadata_with_index.tsv files
[metadata_with_index_afterUpdate.csv](https://github.com/nextstrain/ncov/files/11030151/metadata_with_index_afterUpdate.csv)
[metadata_with_index_beforeUpdate.csv](https://github.com/nextstrain/ncov/files/11030153/metadata_with_index_beforeUpdate.csv)
[builds.yaml.txt](https://github.com/nextstrain/ncov/files/11030170/builds.yaml.txt)

**Comment by tsibley** [comment]
Hi @Samiah-Kanwar, thanks for the excellent report and detailed information.

The error you're getting:

    Query contains a column that does not exist in metadata.

is referring to the `--query` option given to `augur filter`:

    --query '(`root_ref` == '"'"'yes'"'"' & _length >= 27000) | (`pakistan` == '"'"'yes'"'"' & _length >= 27000) | (`global` == '"'"'yes'"'"' & _length >= 27000)'

That references four fields:

    root_ref
    pakistan
    global
    _length

All should be automatically calculated as part of the workflow. The first three come from the names of your `inputs` in [builds.yaml][] and indicate which input a metadata/sequence record came from. The last, `_length`, is computed from the actual sequence content. and they are all included in your example [metadata_with_index_beforeUpdate.csv][]. However, in [metadata_with_index_afterUpdate.csv][], `global` is missing.

It's not clear why without more information, unfortunately. Can you share the `logs/combine_input_metadata.txt` file?

[builds.yaml]: https://github.com/nextstrain/ncov/files/11030170/builds.yaml.txt
[metadata_with_index_beforeUpdate.csv]: https://github.com/nextstrain/ncov/files/11030153/metadata_with_index_beforeUpdate.csv
[metadata_with_index_afterUpdate.csv]: https://github.com/nextstrain/ncov/files/11030151/metadata_with_index_afterUpdate.csv

**Comment by Samiah-Kanwar** [comment]
Thank you @tsibley for you response and pointing out `global` missing in [metadata_with_index_afterUpdate.csv](https://github.com/nextstrain/ncov/files/11030151/metadata_with_index_afterUpdate.csv) file. Sure, I have attached `logs/combine_input_metadata.txt` and `snakemake.log` files for more information.
[combine_input_metadata.txt](https://github.com/nextstrain/ncov/files/11037233/combine_input_metadata.txt)
[snakemake.log.txt](https://github.com/nextstrain/ncov/files/11037237/snakemake.log.txt)

**Comment by joverlee521** [comment]
Hi @Samiah-Kanwar,

Looking at the `combine_input_metadata.txt` file, your workflow only included the `root_ref` and the `pakistan` inputs when it generated the combined metadata file `results/combined_metadata.tsv.xz`. 

The `snakemake.log` did not include the `combine_input_metadata` rule in this run of the workflow, meaning it used a previously existing `results/combined_metadata.tsv.xz` file. I suspect the `builds.yaml` file was updated between a previous run of the workflow and the current run but the current run is still using a previously generated combined metadata file that lacks the `global` input. 

You can force the workflow to run all rules instead of using existing intermediate files by adding the `--forceall` flag to your command:
```
nextstrain build --docker . --cores 72 --configfile my_profiles/Pakistan_contextual/builds.yaml --forceall
```

Please let us know if that does not fix the issue for you!

**Comment by tsibley** [comment]
Thanks @joverlee521 for jumping in here. I concur with you. A mismatch of old vs. new results files with different build configs was my suspicion, but I wanted to see the logs to confirm it. Glad you did!
