### ISSUE TITLE
botocore/boto3 SSL certificate error when using self-signed certificates

### ISSUE THREAD

**Issue by jacaravas** [nextstrain/ncov#1055]
This is an issue that @tsibley and @j23414 have already helped me to resolve in an extended troubleshooting session.  I wanted to be sure to document it in case anyone else encounters the same error in the future.  It probably would have been better to write the issue before the solution, but the behavior was so infuriatingly erratic that it almost defied description.

#### Behavior
```botocore.exceptions.SSLError: SSL validation failed for https://cognito-idp.us-east-1.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)```

Error is encountered when using ```nextstrain remote``` commands on a system with self signed certificates.  Self signed certificates had been assigned to environment variable REQUESTS_CA_BUNDLE (```export REQUESTS_CA_BUNDLE=<PATH TO CERT FILE>```).  The above exception occurred during ```nextstrain remote``` commands.  Similar errors sometimes occurred during login using ```nextstrain login```.  A workaround of overwriting the ```.nextstrain/secrets``` file with an older "known good" copy seemed to sometimes fix the problem with the ```nextstrain remote``` command, but the "fix" worked inconsistently.

#### Resolution
On my system, the ```nextstrain login``` commands used system certificates not found in my self-signed bundle.  The ```nextstrain remote``` commands, on the other hand, required the self signed certificates.  If I set the environment variable before logging in, the login would fail because it could not find valid certificates (certs not in the self-signed bundle).  If I did not set the environment variable before attempting an upload, the remote upload would fail because *it* did not have the correct certificates.  The solution is to either generate a certificate file that has both self signed and system certificates in it and assign it to the ```REQUESTS_CA_BUNDLE``` environment variable, **or** to allow the system default certificates to be used during login, **then** set the ```REQUESTS_CA_BUNDLE``` after logging in, but before running the ```nextstrain remote``` commands. 

#### Explanation of apparently random behavior
The behavior was difficult to troubleshoot because I was often using ```nextstrain logout``` -> ```nextstrain login``` to test whether the certificate files were working.  If I had already set the ```REQUESTS_CA_BUNDLE``` value, login would fail.  If I had copied a known good ```.nextstrain/secrets``` file into the .nextstrain directory **and** did not try to "test" the certificates by logging out **and** I remembered to set the ```REQUESTS_CA_BUNDLE``` variable, the good login information in the restored secrets file was used (no login required) and the ```nextstrain remote``` commands used the self signed certificates and worked as expected.

In retrospect, the observed behavior makes perfect sense, but at the time, it was mystifying.

Thanks again to @j23414 and @tsibley for going above and beyond helping me troubleshoot this problem!  Please feel free to add anything I missed and close the ticket for posterity (or for me the next time I forget how everything works).

**Comment by tsibley** [comment]
Great description, thank you for writing it up!

One additional thing that's worth noting for posterity is that AWS' botocore and boto3 libraries respect the `AWS_CA_BUNDLE` environment variable (and [document that](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html)), but they _also_ respect the `REQUEST_CA_BUNDLE` env var if neither `AWS_CA_BUNDLE` nor the AWS `ca_bundle` config var is set. This last bit _isn't_ documented as far as I can tell, and it was the source of some of our confusion during troubleshooting!
