### ISSUE TITLE
Translate Situation Report to Korean

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#107]
The narrative from 2020-03-05 should be translated to Korean. A branch exists as `sit-rep_ko` where this can be done, and the file to translate is `ncov_sit-rep_ko_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_ko/narratives/ncov_sit-rep_ko_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links! (Links to other-language versions of articles on Wikipedia are ok.)

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

Please also write your twitter handle and/or full name if you'd like to be attributed when we announce!

**Comment by emmahodcroft** [comment]
@hmkim Can you work on this branch to start a translation? After pushing you should be able to preview on the link above. Feel free to use this thread for comments/questions! I'll add you to the repo now. (Note you will not be able to push to master.)

**Comment by emmahodcroft** [comment]
@hmkim - My apologies. I can't add you to this repo right now. Could you fork the `sit-rep_ko` branch and then make PRs? I can merge them pretty quick and you can preview live on the link above. Sorry about that!

**Comment by emmahodcroft** [comment]
@hmkim - You can preview the PR I just pushed here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-05

It looks like the first slide is translated, but that's all. If that's all you got to, that's fine! Just checking that's what you expected :)

**Comment by cassiawag** [comment]
@hmkim - I've given you access to push to the `sit-rep_ko` branch directly without having to make a PR. That should allow you to view previews at the link Emma just mentioned. Let me know if you've got any questions.

**Comment by emmahodcroft** [comment]
@hanbin973  Thank you for your kind offer to review the translation! You can see a preview of the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-05

If you'd like to make changes, you can make them to the `sit-rep_ko` branch - once you push, you can use the same link to review your edits. I'll add you to the branch now.

Then, just let us know when you feel it's ready! Thank you so much!

(Note to self for release tweet, Twitter name is @HAAANBIN !)

**Comment by hanbin973** [comment]
I've switched to sit-rep_ko (git checkout sit-rep_ko) and executed 


> git add
> git commit -m 'some message' 
> git push`

Then I get a permission error as below

> Username for 'https://github.com': hanbin973
> Password for 'https://hanbin973@github.com': 
> remote: Invalid username or password.
> fatal: Authentication failed for 'https://github.com/nextstrain/ncov.git/'

am I missing something?

**Comment by cassiawag** [comment]
Hi @hanbin973, you do have permission to write to `sit-repo_ko`. I think your error _might_ be a wrong password. Can you try pushing again?

**Comment by hanbin973** [comment]
Thanks. My system had some input problem. It was resolved.

**Comment by hanbin973** [comment]
I have completed a first complete draft. Can anyone have a try and check whether the translations are good enough?

**Comment by cassiawag** [comment]
@minkyuxyz or @Bolloknoon -- can either of you take a look? You can use this link here to preview: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-05

**Comment by minkyuxyz** [comment]
Just read. They are overall very well translated. I'll try to fix just a few bits in upcoming hours.

**Comment by cassiawag** [comment]
@minkyuxyz, let me know when you're finished and we can we publish this.

**Comment by cassiawag** [comment]
@hmkim & @hanbin973, I'm not sure if you saw issue #118, but we're gearing up to start publishing weekly situation reports. Are either of you interested in joining?

**Comment by hanbin973** [comment]
yes i'd like to join. i have spare time untill may

**Comment by minkyuxyz** [comment]
Made some changes. Now they look good to go. Happy to contribute to the first Korean situation report. Will keep joining. @cassiawag

**Comment by cassiawag** [comment]
@hanbin973 -- can you quickly preview? Once I've got a thumbs up from you, we'll publish it live.

**Comment by hanbin973** [comment]
i've read read through. It is much better with @minkyuxyz 's contribution

**Comment by cassiawag** [comment]
The translation is live: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-03-05 !

Thank you so much @hanbin973 & @minkyuxyz. Please share it with your Korean-speaking colleagues.

**Comment by minkyuxyz** [comment]
Sorry, I had to update one line that contained a minor mistake. Could you reflect the change please?

**Comment by cassiawag** [comment]
Updated!
