### ISSUE TITLE
Proposal: elevate XBB.1.9 as 23C

### ISSUE THREAD

**Issue by NkRMnZr** [nextstrain/ncov#1073]
**Description**

Over the past few months, XBB.1.9* has shown steady growth.
![growth](https://github.com/nextstrain/ncov/assets/125747944/57f54d50-10a7-4961-912c-f50b38c4d2a6)

By the time next week it will satisfy criteria 2: ≥ 20% global sequences over 2 months.

https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?nextcladePangoLineage=XBB.1.9*

![Proportion](https://github.com/nextstrain/ncov/assets/125747944/1ab169ea-123c-4c46-86f7-03538410573d)

Therefore, it is time to prepare the elevation.

**Comment by Mydtlwn** [comment]
Regarding the options for lifting the main branch, option 1: lifting XBB.1.9* to 23C

Option 2: upgrade XBB.1.9.1* to 23C and XBB.1.9.2 to 23D.

EG.5, EG.5.1, EG.5.2 all have very fast growth rates and some of the XBB.1.9.1* strains are also likely to have fast growth rates. If the main branches are not raised as soon as possible, they may be caught in the confusion of facing some of the main branch raises.
@corneliusroemer

**Comment by Memorablea** [comment]
I also saw it, and I think it's right.Because their speed is indeed very fast.

**Comment by Mydtlwn** [comment]
EG.5.1/EG.5.1.1 and FL.1.5.1 are two or three important branches of XBB.1.9*. Currently, EG.5.1.1 is growing rapidly. In addition, there are other XBB.1.9*s that are also growing rapidly. With the subsequent development, we may face the problem of children and grandchildren lifting the main branch at the same time. The fact that EG.5.1.1 is now being upgraded so quickly means that the chances of this happening are increasing.
