### ISSUE TITLE
Aliased & Unaliased Search Options for 21L

### ISSUE THREAD

**Issue by ryhisner** [nextstrain/ncov#1076]
**Context**
This feature would make a huge difference in how quickly one is able to locate a given sublineage on the 21L tree. 

**Description**
Currently, if I don't know exactly where a lineage is located on the 21L tree, it can be extremely time-consuming to find. I realize that one can do a search on the Pango Designation Github page for the lineage of interest and try to find the mutations unique to that lineage. However, this is also time consuming, and it is not always easy or even possible when you don't know what lineage an aliased sublineage belongs to. For example, if you want to find something like (hypothetical example) HK.1.1.3, the documentation will say something like "HK.1.1.3 - HK.1.1 + S:P1143S," which is not particularly helpful.  

**Examples**
If I want to find XBB.1.38 in the 21L tree pictured below, I would almost certainly have to run my mouse over a huge number of nodes before finding it. And if I happen to miss it, as is easy to do, then I have to start all over. It's usually not possible to use the Nextclade Pango lineage guide on the upper left because there are a huge number of lineages that do not appear there, and there is no way to scroll down to find them.
<img width="1505" alt="image" src="https://github.com/nextstrain/ncov/assets/33738461/e2bde522-0e33-45f7-be1f-6278ce8ff1d7">

**Possible solutions**
1) Include a "search by lineage" option on the left-hand side of the screen (similar to the search by genotype option, which is wonderful)
2) Make the Nextclade Pango lineage key on the upper-left scrollable so that it is possible to run your mouse over any lineage you want to find (since the node visibly enlarges on the tree when you do so)
3) Label all Nextclade Pango lineages on the tree, no matter how tiny the font has to be. In this case, a simple control-F text search will highlight the lineage you want to find, making it easily found.

Lastly, thank you for the wonderful (and I'm sure thankless) work you do to provide these tools for everyone to use, free of charge. I and many others deeply appreciate it.

**Comment by rneher** [comment]
Hi Ryan,

you should be able to search/filter by aliased pango lineage using the filter field on the left. 

![image](https://github.com/nextstrain/ncov/assets/8379168/161329f7-6ead-44f8-a8d3-7c44ae820991)

Selecting a filter will highlight the corresponding nodes. You can then 'zoom to selected' and toggle the filters on and off a the top. 

Is this what you are looking for, or did I misunderstood your request?

**Comment by ryhisner** [comment]
No, that's what I was looking for! I just didn't realize I could do that with the filter. Thanks, Richard!
