### ISSUE TITLE
Missing input files for rule align:

### ISSUE THREAD

**Issue by liamxg** [nextstrain/ncov#1092]
nextstrain build . --configfile ncov-tutorial/genomic-surveillance.yaml
Config file defaults/parameters.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
MissingInputException in rule align in file /Volumes/simon/ncov/workflow/snakemake_rules/main_workflow.smk, line 60:
Missing input files for rule align:
    output: results/aligned_custom_data.fasta.xz, results/insertions_custom_data.tsv, results/translations/seqs_custom_data.gene.ORF1a.fasta.xz, results/translations/seqs_custom_data.gene.ORF1b.fasta.xz, results/translations/seqs_custom_data.gene.S.fasta.xz, results/translations/seqs_custom_data.gene.ORF3a.fasta.xz, results/translations/seqs_custom_data.gene.E.fasta.xz, results/translations/seqs_custom_data.gene.M.fasta.xz, results/translations/seqs_custom_data.gene.ORF6.fasta.xz, results/translations/seqs_custom_data.gene.ORF7a.fasta.xz, results/translations/seqs_custom_data.gene.ORF7b.fasta.xz, results/translations/seqs_custom_data.gene.ORF8.fasta.xz, results/translations/seqs_custom_data.gene.N.fasta.xz, results/translations/seqs_custom_data.gene.ORF9b.fasta.xz
    wildcards: origin=custom_data
    affected files:
        data/idaho.sequences.fasta

**Comment by tsibley** [comment]
@liamxg You haven't provided the two required input files `data/idaho.sequences.fasta` and `data/idaho.metadata.tsv` in the `ncov/` directory. Doing so is covered in the tutorial it seems you're trying to run under the ["Curate data from GISAID" section](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/genomic-surveillance.html#genomic-surveillance-curate-data-from-gisaid).

Separately, speaking for myself (though I suspect many of the Nextstrain team would also agree), you should know that it comes off as fairly rude and demanding to open issues with just log lines and no other context on what you're trying to do or how you've tried to troubleshoot the problem so far. I'm pretty happy to help folks with issues, but it's harder to help when I have to guess at details that have been omitted. And I'm a bit less inclined to want to help if someone hasn't at least tried to fix or understand the problem themselves first and demonstrated that.
