### ISSUE TITLE
Workflow fails on Snakemake 8.x

### ISSUE THREAD

**Issue by ggonnella** [nextstrain/ncov#1114]
**Current Behavior**

```
InputFunctionException in rule colors in file /home/erik/ncov/workflow/snakemake_rules/main_workflow.smk, line 1097:
Error:
  TypeError: unsupported operand type(s) for /: 'method' and 'int'
Wildcards:
  build_name=Cambodian_build
Traceback:
  File "/home/erik/ncov/workflow/snakemake_rules/main_workflow.smk", line 1114, in <lambda> (rule colors, line 2221, /home/erik/ncov/workflow/snakemake_rules/main_workflow.smk)
```

**Expected behavior**
No errors

**Your environment: if running Nextstrain locally**
 - Operating system: Linux
 - Browser: Chrome
 - Version (e.g. `auspice 2.7.0`): auspice 2.54.1; nextclade2 2.14.0; nextalign 2.14.0; pangolin 1.1.5; pangolearn 2022.03.22

**Additional context**
After updating to the latest version of the pipeline (we run it in "ambient" mode), the error appears, when we are running nextstrain build. The latest version we had installed was in last December. Can you give an indication what could be the problem?

**Comment by victorlin** [comment]
Hi @ggonnella,

The relevant line in the workflow is this one:

https://github.com/nextstrain/ncov/blob/6f58ff7a049fce61d714592d841c718f6d0062ba/workflow/snakemake_rules/main_workflow.smk#L1114

My guess is that you are using Snakemake 8.x. https://github.com/snakemake/snakemake/commit/353a71cba1d3dfcc48136b2d6cb744cc1252623b seems to have changed the representation of `_IOFile.size` from a value to a function (a.k.a. `'method'` in your error message), which is something that would cause your error.

It's not stated anywhere in this repository, but this workflow currently does not support Snakemake 8.x and is only routinely run on Snakemake 7.32.3.

The easiest solution here would be for you to use a compatible Snakemake version. You could downgrade to version 7.x in your ambient environment or use one of Nextstrain's [managed runtimes](https://docs.nextstrain.org/projects/cli/en/stable/runtimes/).

**Comment by ggonnella** [comment]
Thank you, indeed the problem was caused by the Snakemake version. I downgraded and it run correctly. Maybe it should be mentioned in the manual.

**Comment by victorlin** [comment]
We don't plan to support Snakemake 8.x at the moment.

Opened a separate issue to document the compatibility requirements: #1118

**Comment by victorlin** [comment]
Clarification: we don't plan to support Snakemake 8.x at the moment but could do so in the future. Timeline is unclear.
