### ISSUE TITLE
Remove `nextstrain_profiles/nextstrain-country`

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov#1120]
From discussion below, we've decided to just remove `rebuild_country.yml` + `nextstrain_profiles/nextstrain-country` since they are not actively being used

---

### Context
I originally flagged this in https://github.com/nextstrain/ncov/pull/1119#issuecomment-2192314780:

> I don't think this profile ever worked as intended, since the build names have [three parts delimited by underscores](https://github.com/nextstrain/ncov/blob/eb488d62c7eadd8e7e1497276c41e81350e95db5/nextstrain_profiles/nextstrain-country/builds.yaml#L41) (e.g. `nextstrain_country_1m`), while our auspice config rule only expects two parts: 
https://github.com/nextstrain/ncov/blob/eb488d62c7eadd8e7e1497276c41e81350e95db5/workflow/snakemake_rules/export_for_nextstrain.smk#L145-L146

### Possible solutions

Easiest change would be to switch build names from `nextstrain_country_1m` to `country_1m`. However, this would change Auspice JSON file names which would change the build URLs on nextstrain.org

### TODOs

- [ ] update build names from `nextstrain_country_1m` to `country_1m`
- [ ] enable [rebuild-country.yml workflow](https://github.com/nextstrain/ncov/actions/workflows/rebuild-country.yml)

**Comment by joverlee521** [comment]
> However, this would change Auspice JSON file names which would change the build URLs on nextstrain.org

I cannot find any builds in `s3://nextstrain-data` with the `nextstrain_country_<time>` name so maybe this is a non-issue? 

@trvrb, could you comment on whether the proposed change would affect your work? I think you might be the only one who has used this profile?

**Comment by victorlin** [comment]
If there's no evidence that `rebuild_country.yml` + `nextstrain_profiles/nextstrain-country` are actively used, I'd vote to remove them (as briefly mentioned in https://github.com/nextstrain/ncov/pull/1119#issuecomment-2192314780)

**Comment by joverlee521** [comment]
Asking for feedback on [Slack](https://bedfordlab.slack.com/archives/CSKMU6YUC/p1719962738898259)

**Comment by trvrb** [comment]
I haven't used this in a long while (I'm not even sure it was ever working correctly). I do think it's good functionality to be able to look at what's circulating in a particular country. This would be for one-off analyses that are not uploaded to data.nextstrain.org. It's generally not currently much of a priority for this to be working.

**Comment by joverlee521** [comment]
Thanks for the feedback! I'll just remove `rebuild_country.yml` + `nextstrain_profiles/nextstrain-country` then.
