### ISSUE TITLE
Hindi Translation has no Drop-down

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#113]
See : https://nextstrain.org/narratives/ncov/sit-rep/hi/2020-03-05

![image](https://user-images.githubusercontent.com/14290674/76221001-ad08e580-6218-11ea-80e5-673138017ce7.png)

At the top the Language menu drop-down is 'English' - and there's no option for Hindi. Can we extend support?

**Comment by cassiawag** [comment]
It looks good on my side (I think): 
![Capture](https://user-images.githubusercontent.com/41387591/76234305-27bd0b00-61ef-11ea-8b95-c805221bde25.PNG)

**Comment by emmahodcroft** [comment]
Oh what! Ok great! I don't know by what kind of black magic this works, but maybe it just need to catch up! Excellent!

**Comment by emmahodcroft** [comment]
It might be tied to the site rebuild... I did all this before it had finished - so that could well be why! I'll close this now, I think it's not an issue after all :)
