### ISSUE TITLE
Remove redundancy in config file values

### ISSUE THREAD

**Issue by victorlin** [nextstrain/ncov#1144]
Options such as [`subsampling.<sample>.min_date`](https://docs.nextstrain.org/projects/ncov/en/latest/reference/workflow-config-file.html#min-date-2) must contain the option flag to `augur filter`, e.g.

```yaml
min_date: --min-date 2020-01-01
```

This is redundant and requires knowledge about an extra set of syntax on top of config file syntax. It also causes confusion resulting in PRs such as #886.

**Comment by victorlin** [comment]
Based on https://github.com/nextstrain/ncov/pull/886#pullrequestreview-1165909150 this is a "won't fix":

> The min and max date parameters in ncov's filter logic don't behave like you'd expect due to an implementation choice we made at the beginning of the pandemic that we were then unable to change without breaking everyone's workflows.

Couldn't we release another major version of the ncov workflow to make this breaking change? Maybe this has been considered before – of course we could, but doesn't mean we should. But then what is the point of versioning this workflow?

**Comment by jameshadfield** [comment]
There are quite a few of these throughout ncov, e.g.

https://github.com/nextstrain/ncov/blob/9e9f3d4e950ad48f9497183daff8b30286b9655e/workflow/snakemake_rules/main_workflow.smk#L166-L173

and I think we learned from this for other pathogen worflows. There seems to be a few possible choices here:
1. Move everything to `subsampling.<sample>.min_date: <date>` and deal with the fall-out of many peoples' breaking configs
2. Leave it as it is.
3. Leave it as it is and add some syntax checking, e.g. `if not subsampling.<sample>.min_date.startswith("--min-date"): raise...`
4. Allow both, e.g. `if not subsampling.<sample>.min_date.startswith("--min-date"): subsampling.<sample>.min_date=f"--min-date {...}"`

I'd go with 3, but 2 also seems fine.

**Comment by victorlin** [comment]
Had a good discussion during dev chat. Consensus:

- It's not worth making breaking changes in the ncov workflow for consistency's sake, such as in this situation. We could still (3) add better error handling as a nice touch.
- More broadly, we may still make other breaking changes to this workflow which would warrant a new version tag.
