### ISSUE TITLE
Better GISAID → metadata → Fauna data flow

### ISSUE THREAD

**Issue by tsibley** [nextstrain/ncov#12]

**Comment by acx01b** [comment]
Hi,  Please get the Ragt13 bat virus https://www.gisaid.org/CoV2020/ which is 96% close to nCov and add it to https://nextstrain.org/groups/blab/sars-like-cov

(the bat virus found in Wuhan's virology institute main paper https://www.biorxiv.org/content/10.1101/2020.01.22.914952v2 )

**Comment by tsibley** [comment]
@acx01b Thanks for your interest! I think your request is more suitable for the https://github.com/blab/sars-like-cov repository, which is what is used to produce https://nextstrain.org/groups/blab/sars-like-cov. This repository is for https://nextstrain.org/ncov. I'd encourage you to see if you can adapt the build there to include the bat virus you mention.

**Comment by trvrb** [comment]
Resolved in #50.
