### ISSUE TITLE
Testing full-width marks in Japanese & Mandarin

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#127]
I've set back up the `sit-rep_zh` branch so that @fzhang12 can test full-width marks in the narratives to ensure they work correctly in Markdown.

Both the `zh` and the `ja` files could be modified here if that's helpful! (To test both, if you want)

The files are here:
https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-05.md (Mandarin)

https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_ja_2020-03-05.md (Japanese)

And you can preview them live (after pushing) here:
https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05 (Mandarin)

https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/ja/2020-03-05 (Japanese)

**Comment by fzhang12** [comment]
@emmahodcroft I corrected the Mandarin file and made it more readable for non-scientists (because some feedback on Twitter said too professional for them). Could you push it online?
Thx very much.

For the Japanese one, I will directly edit on sit-rep_ja branch after the other Japanese translator merged his comments. Thx again :)

**Comment by cassiawag** [comment]
@fzhang12 thank you! 

@alvinxhan or @wdingx, can either of you take a look at this? @fzhang12 has added some resources and links to make the narrative more accessible, and I just want to get at least two people's eyes on everything we publish :)

**Comment by fzhang12** [comment]
Hi @lxy0107 , I added more resources to the currently narrative. Could you have a look at the preview:
https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05
Any comment will be welcome :)

**Comment by lxy0107** [comment]
Yes, happy to take a look. Any deadlines? How do I make edits? Do I check the accuracy of science or also fluency? Sorry I’m new to this pipeline.

**Comment by fzhang12** [comment]
> Yes, happy to take a look. Any deadlines? How do I make edits? Do I check the accuracy of science or also fluency? Sorry I’m new to this pipeline.

No problem. You may directly edit the file below through browsers.
https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-05.md

I am not sure about the deadline but usually it is a time-sensitive report. The text itself I've edited twice so it should be fluent enough. But please do check on the additional links I added later (they are from zh wikipedia, China CDC and a 360 document explaining how to read a tree)

**Comment by emmahodcroft** [comment]
Hi @fzhang12 - I really appreciate your being so incredibly helpful about this! 

I notice above you reference some extra links - and on the slides I can see that there are some extras compared to the current version we have live on Nextstrain.org:
(the version above): https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05?n=5

(the live version) : https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-05?n=5

I 100% understand that you were trying to be helpful by adding these, but can I ask you to remove them? The thing is, we need to know that all the content is the same across the narratives, and be sure the things we link to are things we are happy with. And unfortunately none of us on the team speak Mandarin! I'm definitely not trying to say that we think these links are bad - it's just, to ensure we know exactly what we're providing to the public, we're being a bit strict about trying to keep things the same across translations. I hope you understand! 

We are happy if you want to change any English-language Wikipedia pages to the Mandarin (or other) equivalent, though!

We recognise we're lacking Mandarin versions of things like 'How to Read a Phylogeny' and etc - we're hoping to start getting these translated soon - that should help provide this resource for everyone!

Thank you once again for all of your hard work, and thank you for being understanding about this!

**Comment by fzhang12** [comment]
@emmahodcroft No problem, all clear. I have removed the additional links above but kept just two edited one. The two are the Mandarin version of the original links (one is from wikipedia and the other is from US CDC).

**Comment by emmahodcroft** [comment]
@fzhang12 thank you so much for being so understanding! 🙏 
After @lxy0107 has a look and @cassiawag feels we're good, we can include this :)

**Comment by lxy0107** [comment]
> @fzhang12 thank you so much for being so understanding! 🙏
> After @lxy0107 has a look and @cassiawag feels we're good, we can include this :)

working on it right now

**Comment by lxy0107** [comment]
> @fzhang12 thank you so much for being so understanding! 🙏
> After @lxy0107 has a look and @cassiawag feels we're good, we can include this :)

Hi all, I finished proofreading. It looks good to me now. @fzhang12 , thanks for the hard work! You did an excellent job. I made some changes, hopefully they do not offend you... I put some explanation of major changes in the commit notes. You can check again if you want. We can also discuss privately if there are any questions.

**Comment by cassiawag** [comment]
Thanks @lxy0107 !

@fzhang12 -- let me know if you're good with the Mandarin, and I will publish it. 

I've pushed also @tomoyuki-nezu & @satotake on the the Japanese translation; did you want to test full-width marks or shall I push it live?

**Comment by fzhang12** [comment]
@lxy0107 thanks for the comments :)

@cassiawag I've looked her comments and it's good to be online. Happy working with you both

the full-width mark works with Mandarin as long as it stays inside translation blocks, I expect it also fine with Japanese.

**Comment by satotake** [comment]
I've checked full-width mark (your mean `。` ,  don't you ?) of Japanese version.
It is fine, thank you.

**Comment by cassiawag** [comment]
Both Mandarin (https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-05) and Japanese updates are live (https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-03-05)! Thanks for your hard work all.
