### ISSUE TITLE
How to construct phylogenetic tree

### ISSUE THREAD

**Issue by Hikoyu** [nextstrain/ncov#143]
I want to know the method for constructing phylogenetic tree used in this project.
Is it NJ or MP or ML?
Are there any informations?
Thank you.

**Comment by jameshadfield** [comment]
The full pipeline is detailed here: https://github.com/nextstrain/ncov/blob/master/Snakefile

We use ML methods for both inferring topology and temporal branching. Please see https://nextstrain-augur.readthedocs.io/en/stable/ for more information.
