### ISSUE TITLE
Translate March 13 sit-rep to French

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#150]
Happy weekend @meriemelkaroui, @Maijin, @DanielThedie, @Simon-LoriereLab !

The situation report from March 13 is ready to be translated to French. A branch exists as `sit-rep_fr`  where this can be done, and the file to translate is `ncov_sit-rep_fr_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_fr/narratives/ncov_sit-rep_fr_2020-03-13.md. 

You can translate directly in this file, but please remember to _push often_ as other people may be working on the translation! You should have access to push to the `sit-rep_fr`, so there’s no need to create a pull request.

Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) 

Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_fr/sit-rep/fr/2020-03-13

Please add your name in parentheses to the end of the author list, so we can credit your work!

After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your French-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in French; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.

@Simon-LoriereLab, since you have a background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.

Thank you so very much for your hard work; you all are amazing!

**Comment by Maijin** [comment]
Awesome, like last week I have created an hackmd started working on it - https://hackmd.io/tS0vrA4lT5yI_w9BM1o-Wg
To recap Hackmd is an online system that allows multiple users to collaborate on the same document with instant preview the changes.

I also opened an instant message chat / IRC - https://webchat.freenode.net/#nextstrain-fr-translation so we can coordinate on the translation. (You don't need password but just need to choose a nickname to join)

**Comment by meriemelkaroui** [comment]
Hi all, I am starting now on hackmd.

**Comment by Maijin** [comment]
Draft ready for review 👍  We'll likely also continue reviewing tomorrow.

**Comment by cassiawag** [comment]
Fast work! @Simon-LoriereLab , would you mind taking a look?

**Comment by Simon-LoriereLab** [comment]
Apologies for the delay, it is all good, very impressed by the speed of @Maijin and @meriemelkaroui !

**Comment by meriemelkaroui** [comment]
Great! Speed was thanks to @Maijin who suggested  the combination of using hackmd and google translate which is surprisingly (at least to me) good at scientific texts. 
@cassiawag may be this should be suggested to other translators?

**Comment by cassiawag** [comment]
I've updated in internal links and added all of your names in parentheses as authors. I'll publish it now. AMAZING work everyone. Thank you so much!

**Comment by Maijin** [comment]
👍

**Comment by Maijin** [comment]
Erf forgot I need to use fix in a commit and not the title.

**Comment by cassiawag** [comment]
It's live at: https://nextstrain.org/narratives/ncov/sit-rep/fr/2020-03-13.

Posting on Twitter now. Pardon my absolute terrible language skills, but can one of you give me a translation for "Read our latest situation report on COVID-19 in French." I could go for Google Translate, but you all seem like a a better option :)

**Comment by Simon-LoriereLab** [comment]
Lisez notre dernier rapport de situation sur COVID-19 en français!

**Comment by DanielThedie** [comment]
Hi, amazing to see that's it's already done! If using google translate for the first round of translation, I can suggest also trying DeepL (https://www.deepl.com/en/translator), which I've found quite amazing for other translations before. But whatever works best, of course... :)

**Comment by cassiawag** [comment]
The hackmd does seem to work very well when multiple people are working at the same time. Feel free to share the info with other translating groups @Maijin & @meriemelkaroui

**Comment by Maijin** [comment]
@DanielThedie that's what I used this time indeed ;)
