### ISSUE TITLE
Translate March 13 sit-rep into German

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#151]
Happy weekend @astridgall, @rneher, @nicfel !
 
The situation report from March 13 is ready to be translated to German. A branch exists as `sit-rep_de`  where this can be done, and the file to translate is `ncov_sit-rep_de_20202-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_de/narratives/ncov_sit-rep_de_2020-03-13.md. 
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! 
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_de/sit-rep/de/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your German-speaking colleagues, so we can get the information out there!
 
Thank you so very much for your hard work; you all are amazing!

**Comment by rneher** [comment]
@astridgall Did we just edit this at the same time? You deleted my first edits in 3731e091e18c106ed9160520ee650b5d061bbbd5

I pushed my version (finished but in need of polishing) to `sit-rep_de2`

**Comment by astridgall** [comment]
@rneher It looks like it. Sorry about that. I can proofread your version?

**Comment by rneher** [comment]
Have a look at this file:
https://raw.githubusercontent.com/nextstrain/ncov/ddf3512d36f418855fc72f89988cd77a384fd52a/narratives/ncov_sit-rep_de_2020-03-13.md
it is in a separate branch `sit-rep_de2` bc I couldn't push into the original one in which you deleted the file.

**Comment by astridgall** [comment]
Needs a few commas etc. Can I edit here:
https://github.com/nextstrain/ncov/blob/sit-rep_de2/narratives/ncov_sit-rep_de_2020-03-13.md
?

**Comment by rneher** [comment]
yes, edit this file!

**Comment by astridgall** [comment]
Done!

**Comment by cassiawag** [comment]
Super! Thank you. @rneher, can you take a final look, merge your PR into master, and ping me when it's done. I'll push it live and get it posted.

**Comment by rneher** [comment]
Yes, looks great.
