### ISSUE TITLE
Translate March 13 sit-rep to Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#152]
Happy weekend @al-epo, @enkelejdamiho, @whispererindarkness, @aliceLedda!
 
The situation report from March 13 is ready to be translated to Italian. A branch exists as `sit-rep_it`  where this can be done, and the file to translate is `ncov_sit-rep_it_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_it/narratives/ncov_sit-rep_it_2020-03-13.md. 
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_it`, so there’s no need to create a pull request. Please make sure you’ve accepted an invitation from me to join the `ncov` repo.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_it/sit-rep/it/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Italian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@aliceLedda, since you have a background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for your hard work; you all are amazing!

**Comment by aliceLedda** [comment]
Hello Cassia,
I've committed just the beginning.
Can you tell me if the format is fine or not?
(I copied each translated line and commented the English version below, so
it's easier to check the translation)

Thanks!
Alice

**Comment by whispererindarkness** [comment]
Hi @cassiawag, can you please check my access to the sit-rep_it branch? I didn't received any invitation from you, at the moment.

**Comment by cassiawag** [comment]
@aliceLedda -- I love the way you've commented the English version. It's such a fantastic way for other people to check accuracy of your translation. This works everywhere except the very first slide -- the header/title page. The narratives program can be a little finicky, and comments just don't work in the title slide.. I pushed a commit that's fixed that error, and you should now be able to preview what you've translated at the above link.

@whispererindarkness -- On my side, it's showing that you have an invitation but haven't yet accepted it. This [forum post](https://github.community/t5/How-to-use-Git-and-GitHub/Where-do-I-see-all-incoming-invitations-collaborator/td-p/4280) might help you troubleshoot finding the invitation.

**Comment by aliceLedda** [comment]
Thanks!
I'll keep working on it today!
Alice

**Comment by al-epo** [comment]
@cassiawag,  @aliceLedda  @whispererindarkness  
Hello all !
I am starting to traslate now, I will use same strategy used by cassiawag. 
I am new to github, so I am a bit slow. Sorry! Trying  my best!
Alessia

**Comment by aliceLedda** [comment]
Ciao Alessia,
 can you start for the most general parts and leave the more phylogenetic
parts to the end? I think it makes more sense if I translate the
phylogenetics parts and you check if it makes sense in Italian, while you
translate all the parts that do not require specific knowledge. Not that
you cannot translate the technical part, just that's harder for my brain to
correct a translation than to do it. (Sorry I am not used to translating
job into Italian).
Also (I think you want to do this, I am just checking if I understood
correctly) can you translate by line/paragraph and leave the commented
English version below, so that's easier for the others to check?
Thanks for your help!
Alice

**Comment by al-epo** [comment]
Ciao Alice, 

sure! I agree with you. 
Could you tell me from what lines you will traslate so I stay away from it? :-) 

Alessia

**Comment by al-epo** [comment]
I have committed a part translated until [COVID-19 Resources] . 
please, let me know if there is something  I can improve
Best, 

Alessia

**Comment by whispererindarkness** [comment]
@cassiawag, I did not get any email or notification with an invitation from you. I just switched to another email address, can you please try to re-invite me? Maybe the email address is the problem?
I can work through pull requests, but it would be terribly inconvenient for other translators...

**Comment by cassiawag** [comment]
@whispererindarkness, I just resent your invitation. Ping me again if you're still having problems.

**Comment by whispererindarkness** [comment]
@cassiawag, it's ok now. Thanks!

@aliceLedda, @al-epo: "FAQs & Misconceptions" and "Scientific credit" sections are more or less the same as my last translation, I will take care of it. I'll leave the rest to you, ping me if you need help. I'll ask a friend (who is a professional translator) to help with the final proofreading.

**Comment by al-epo** [comment]
@whispererindarkness  ok!

**Comment by aliceLedda** [comment]
Cool!
I started my part.
How do we put accents?
Thanks for anybody who will answer!
Alice

**Comment by al-epo** [comment]
@aliceLedda  I have an italian keybord ( not a useful answer..I know) 
I start now the Takeaways  section to avoid overlaps, ok? 

Alessia

**Comment by aliceLedda** [comment]
Yes Alessia, amazing...
I am still trying to figure out accents...
I have to change my keyboard configuration
Alice

**Comment by whispererindarkness** [comment]
@aliceLedda I think I can fix the accents at the end using my Italian keyboard :)

**Comment by al-epo** [comment]
@cassiawag , @aliceLedda @whispererindarkness  I am going to traslate the parts that are still in english, if someone can check them after it would be great!

Thanks,

Alessia

**Comment by aliceLedda** [comment]
Sorry I have just read this!

**Comment by al-epo** [comment]
@cassiawag , @whispererindarkness  and @aliceLedda 
I finished, it should be ok. If you could  double check for typos would be great !

Thanks!

**Comment by whispererindarkness** [comment]
@al-epo, @aliceLedda, I'm fixing HTML comments tags by now. Multi-line HTML comments breaks the display of the narrative (you can check the link provided in the first message by @cassiawag to check out how the translation is displayed). I'll let you know when I'll finish this.

**Comment by whispererindarkness** [comment]
Done, it takes less than expected :)

**Comment by al-epo** [comment]
Cool! Well done!

**Comment by whispererindarkness** [comment]
@cassiawag, @sarameiqi can help us with proofreading as a professional translator. Can you please add her as a contributor? Thanks!

**Comment by cassiawag** [comment]
Thanks for the hard work everyone! I've added @sarameiqi. Is this report ready to publish?

**Comment by sarameiqi** [comment]
Hi all, thank you for adding me.
In 90 minutes I should complete the proofreading.
I'll ping you back when I'm done.
I'll write here to @aliceLedda and @al-epo if I have any problem in understanding contents.

**Comment by aliceLedda** [comment]
I haven't checked that yet...
I am sorry... I am running late translating the other one!
Alice

**Comment by sarameiqi** [comment]
Hi all, 3 questions:
1) I'd like to specify that SARS-CoV-2 is a virus writing "il virus SARS-Cov-2" instead of "il SARS-CoV-", because here in Italy many people are confusing coronavirus, SARS-CoV-2, Covid-19 etc. Do you have any objection?

2) In a few cases you write that cases intercalate with others, but in Italian "intercalare" ha un significato too different to be properly understood. Can

**Comment by cassiawag** [comment]
@sarameiqi -- I'm fine with you clarifying the virus in #1. And please translate the image captions in. Thank you very much!

**Comment by al-epo** [comment]
@cassiawag  Thank you for reopening  it!

@sarameiqi : thank you for proofreading it!
1. I agree. Also in "indice dei contenuti" : "della SARS-CoV2" is confusing 
2. you are absolutely  right , but so far I don’t  have a better word...maybe @aliceLedda  that has a specific  knowledge  on the argument  can suggest a better word for intercalate ?

**Comment by sarameiqi** [comment]
@al-epo if you can try to explain the meaning with one sentence or two I can try to figure something out! (You can write in Italian, the important is for me to understand the meaning so that I can render it in the best way!)

**Comment by aliceLedda** [comment]
Yes!
I translated this way
Notably, sequences from many different countries intercalate,
E' interessante notare che le sequence provenienti da molti paesi diversi
si mischiano tra di loro

It's not perfect...

**Comment by aliceLedda** [comment]
The meaning is that instead of having clusters on the tree defined by
geographical origin, sequences group independently from their geographical
origin.
I reread it now, so that I can tell you if there is anything that does not
make sense from the phylogenetic point of view
Alice

**Comment by sarameiqi** [comment]
Ok thanks, I think about it and propose something in a few minutes.
I'm doing the last proofreading, directly from the preview. When I finish I amend this "intercalate" issue and I'm done.

**Comment by aliceLedda** [comment]
Sara, please can you get rid of all the campionato-campionare.
It's better to use raccogliere campioni.
You do not campionare blood or urine, you raccogli campioni. Since this is
human too, although from the throat, I think it's better to change this
verb.
Thanks!

**Comment by sarameiqi** [comment]
Yes, ok.
Give a look at lines 162 and 233, I solved the "intercalate" issue in two different ways because of the context.

**Comment by aliceLedda** [comment]
162 amazing!
233 I changed it (the way you wrote was misleading from the genetic point
of view)

**Comment by aliceLedda** [comment]
Ok! I've changed a couple of things that were really important for the
understanding.
No problems with the italian, it was just technical jargon.
Correlare-correlato has a very precise scientific meaning, for example!
Good work everyone!!
I need to finish the other one now!
Cheers!
Alice

**Comment by sarameiqi** [comment]
I'm done with the proofreading and the request about "campionamento".
I read all the preview twice, I hope I found all the occurrences.

**Comment by cassiawag** [comment]
Thank you @sarameiqi. @aliceLedda -- is the translation good from your end?

**Comment by sarameiqi** [comment]
I added our names as @cassiawag asked to do, I wrote "trad.it. (meaning Italian translation)+ names".
I listed the translators' names in alphabetical order, I hope that you're ok with it. If not, feel free to change.
@al-epo please add your name by yourself, I don't know your surname! =)

**Comment by al-epo** [comment]
@sarameiqi 
Sorry I don’t  find  where I should  add it! I am Alessia Lepore btw  :-)

**Comment by sarameiqi** [comment]
Added! =)

**Comment by al-epo** [comment]
Grazie!

**Comment by cassiawag** [comment]
Thank you everyone for your hard work on this! I really appreciate everyone's attention to detail. Early this morning, the developers added a feature to the program, so we can make a separate field for translators. I updated this narrative accordingly.

The translation is now live here: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-13

I'm going to post it to Twitter. @sarameiqi, do you have a Twitter account I can tag?

**Comment by aliceLedda** [comment]
Oh no!!
I had just finished reviewing and I could not commit!
Alice

**Comment by cassiawag** [comment]
I'll pull it no problem. We haven't posted yet, so no one has likely seen it. I'll also re-open the branch

**Comment by cassiawag** [comment]
I'm so sorry @aliceLedda. I looked at the commit history and saw you'd committed content changes last and assumed that you were finished. I won't do it again. Thankfully it barely went live. I re-opened the branch and you should be able to push your changes there.

**Comment by aliceLedda** [comment]
No problem!
Sorry that I am working just in bit and pieces!
That's finished!
It was an amazing work really!!
Alice

**Comment by cassiawag** [comment]
Yeah, it is really amazing. I'm glad you all are part of it. To double confirm, I can publish the Italian translation?

**Comment by aliceLedda** [comment]
Yes!

**Comment by cassiawag** [comment]
And now it's finalized _and_ live at: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-13
