### ISSUE TITLE
Translate March 13 sit-rep into Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#153]
Happy weekend @tomoyuki-nezu, @satotake, @fzhang12!
 
The situation report from March 13 is ready to be translated to Japanese. A branch exists as `sit-rep_ja`  where this can be done, and the file to translate is `ncov_sit-rep_ja_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ja/narratives/ncov_sit-rep_ja_2020-03-13.md. 
 
You can translate directly in this file, but please remember to _push often_ as other people may be working on the translation! You should have access to push to the `sit-rep_ja`, so there’s no need to create a pull request. Please make sure you’ve accepted an invitation from me to join the `ncov` repo.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ja/sit-rep/ja/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Japanese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@fzhang12, since you have a background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for your hard work; you all are amazing!

**Comment by tomoyuki-nezu** [comment]
Hello folks, and good morning (Japan is 9:00 in the morning, Saturday)
I can take about an hour from now, so I'll try to roughly translate it into Japanese.
Push every 1-2 page.

**Comment by tomoyuki-nezu** [comment]
@cassiawag Looks like you don't have push permission yet. Can you add it to me? I checked the email and GitHub, but there was no invitation message etc.

**Comment by cassiawag** [comment]
@tomoyuki-nezu: I just re-invited you. Try navigating to the `nextstrain/ncov` repo to see if your invitation pops up.

**Comment by tomoyuki-nezu** [comment]
Hmm...  No pop-ups. I tried switching the branch to sit-rep_ja from master, but didn't come out.

**Comment by tomoyuki-nezu** [comment]
When I try to a git push, you get this message:

$ git branch
  master
* sit-rep_ja

$ git push
remote: Permission to nextstrain/ncov.git denied to tomoyuki-nezu.
fatal: unable to access 'https://github.com/nextstrain/ncov.git/': The requested URL returned error: 403

**Comment by tomoyuki-nezu** [comment]
When I try to a git push, get this message:

$ git branch
master

sit-rep_ja
$ git push
remote: Permission to nextstrain/ncov.git denied to tomoyuki-nezu.
fatal: unable to access 'https://github.com/nextstrain/ncov.git/': The requested URL returned error: 403

**Comment by tomoyuki-nezu** [comment]
When I try to a git push, I get this message:

```
$ git branch
master
* sit-rep_ja

$ git push
remote: Permission to nextstrain/ncov.git denied to tomoyuki-nezu.
fatal: unable to access 'https://github.com/nextstrain/ncov.git/': The requested URL returned error: 403
```

**Comment by cassiawag** [comment]
On my side, it's still showing that you haven't accepted the invitation, which is why you're getting the permissions errors. This [forum post](https://github.community/t5/How-to-use-Git-and-GitHub/Where-do-I-see-all-incoming-invitations-collaborator/td-p/4280) might help you troubleshoot finding the invitation.

**Comment by tomoyuki-nezu** [comment]
@cassiawag The invitation has been confirmed. I apologize for the trouble.
About half of them are roughly translated and commit. I'll take a little more time, so I'm going to get everything rough translate...

**Comment by tomoyuki-nezu** [comment]
All pages were translated roughly and committed.
I would like professional correction from @satotake and @fzhang12.
Questions were annotated as Translator notes.
best.

**Comment by tomoyuki-nezu** [comment]
PR (https://github.com/nextstrain/ncov/pull/166) from @satotake has been merged.

Re-post the comments written on the PR thread:

@satotake Thank you for the review and pointing out the fine nuances and details.
I committed again to merge the points you pointed out and I changed only one place (https://github.com/nextstrain/ncov/pull/166#discussion_r392593165)

@fzhang12 Thank you for your continued review.

I have a little time tomorrow morning and night, so I can do something. I am working on JST +9.

**Comment by fzhang12** [comment]
Thank for @tomoyuki-nezu and @satotake 's excellent job. The text was already great and I just modified some typo. Happy working with you again :)

@cassiawag the JP translated narrative is ready to be pushed. Thanks for your effort.

**Comment by cassiawag** [comment]
Thank you all, incredibly fast work! Can I get a translation of this for the twitter post:

The latest situation report on #COVID19 is now available in Japanese! Thank you to @tommy_nezy, @fengjun_zhang, and Takeshi Sato for their quick translation.

**Comment by tomoyuki-nezu** [comment]
@cassiawag I read this post. How do we write the translator's name in translated document?
https://github.com/nextstrain/ncov/issues/155#issuecomment-599086636

**Comment by cassiawag** [comment]
You did it just right, @tomoyuki-nezu. I'm adding everyone else's name and will publish.

**Comment by fzhang12** [comment]
@tomoyuki-nezu good question!
@cassiawag sorry I am busy with CN translation and totally forgot this... Another question, is there any possibility to put translators' name in somewhere else? It now looks like we are all from the first author's group. I could be okay with that, but I am not sure if it is right to do so.

**Comment by cassiawag** [comment]
@fzhang12, I'll consult with team here, but that's what we decided to do a week ago. Could consider putting them in the abstract too.

**Comment by cassiawag** [comment]
Translation is live: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-03-13

Can someone please translate the following for me for the twitter post?

The latest situation report on #COVID19 is now available in Japanese! Thank you to @tommy_nezy, @fengjun_zhang, and Takeshi Sato for their quick translation.

**Comment by fzhang12** [comment]
@cassiawag I will give a try
コロナウィルス及び #COVID19 についての状況報告（日本語）更新されました！
翻訳担当の @tommy_nezy さん、 @fengjun_zhang さんとTakeshi Satoさん、お疲れ様です。

**Comment by cassiawag** [comment]
Thank you! And thank you to all for your amazing work!

**Comment by tomoyuki-nezu** [comment]
Thank you all. It was fun to be together :)
