### ISSUE TITLE
Translate March 13 situation report into Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#154]
Happy weekend @hanbin973, @minkyuxyz, @Bolloknoon!

The situation report from March 13 is ready to be translated to Korean. A branch exists as `sit-rep_ko`  where this can be done, and the file to translate is `ncov_sit-rep_ko_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ko/narratives/ncov_sit-rep_ko_2020-03-13.md. 

You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_ko`, so there’s no need to create a pull request. Please make sure you’ve accepted an invitation from me to join the `ncov` repo.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-13

Please add your name in parentheses to the end of the author list, so we can credit your work!

After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Korean-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Korean; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.

Thank you so very much for your hard work; you all are amazing!

**Comment by cassiawag** [comment]
@kyobinkang is also going to help out with the translation!

**Comment by minkyuxyz** [comment]
Thanks! 

Pardon my Korean, I'd like to discuss how we can collaborate simultaneously. 

첫 상황보고서는 @hanbin973 님이 초벌 번역하고, 제가 감수하는 방식으로 진행했습니다. 
현재 4명의 기여자가 있는데, 어떻게 진행하는 게 좋을까요? 마구잡이로 번역하다가 일관성이 떨어지거나 푸시가 충돌하는 경우가 있을 것 같아서요. 한 분이 초벌번역 맡는 게 저는 좋다고 생각하는데, 어떻게 생각하시나 궁금합니다. 계속 진행하기 전에 미리 원칙을 세워두는 편이 좋을 것 같아서요. :) 

그리고 이하는 첫 보고서를 번역하면서 세웠던 몇 가지 원칙입니다. 

- Sequence (명사) 는 모두 "염기서열"로, Sequencing (동사)는 "해독"으로 통일함. 
- "from ..."은 해당 지역에서 '유입된'인지 '수집된'인지 구별지어 번역함
- 염기서열의 이름의 국가명은 원문을 유지함
- Cluster 는 때에 따라 '무리', '무리짓다', '클러스터' 등으로 번역함
- 단어와 괄호 사이 띄어쓰기 삭제함 
- 한국어 맞춤법에 사용되지 않는 dash 는 별개의 문장으로 분리함.

**Comment by KyobinKang** [comment]
초벌 번역 후 감수하는 방식에 동의합니다. @hanbin973님께서 괜찮으시면 일관성 유지를 위해 초벌 번역을 위해 수고해 주시고 나머지 contributor들이 감수하는 방식이 좋지 않을까요?

**Comment by minkyuxyz** [comment]
저도 그게 좋은 방식이라 생각하고, @hanbin973 님이 바쁠 경우 제가 초벌번역을 맡거나 일정부분 분담하는 것도 가능합니다.

@hanbin973 : 보시면 답변 주세요.

**Comment by hyouka315** [comment]
Hello. I am Hyunseok, a pre-med student in SNU. 
As a native Korean speaker, I am willing to work as a Korean translator.
If there is anything I need to know, feel free to contact me.

**Comment by hyouka315** [comment]
Hello. I am Hyunseok, a pre-med student in SNU. 
As a native Korean speaker, I am willing to work as a Korean translator.
If there is anything I need to know, please feel free to contact me. 

안녕하십니까. 저는 서울대 의예과 학부 재학 중인 서현석입니다. 번역 작업에 미약하나마 보탬이 됨과 동시에 여러 훌륭하신 분들께서 협업하시는 것을 보고 싶어 이렇게 자원하게 되었습니다. 폐가 되지 않도록 최선을 다하겠습니다.

**Comment by hanbin973** [comment]
> 저도 그게 좋은 방식이라 생각하고, @hanbin973 님이 바쁠 경우 제가 초벌번역을 맡거나 일정부분 분담하는 것도 가능합니다.
> 
> @hanbin973 : 보시면 답변 주세요.

Ok. I expect to finish the initial draft before tommorow.

**Comment by hanbin973** [comment]
I'll commit right after updating each page.

**Comment by hanbin973** [comment]
Finished the first draft. Some remaining untranslated parts at the end of the narrative is identical to the early few pages of the previous report. We can just simply copy and paste for them.

**Comment by minkyuxyz** [comment]
On it!

**Comment by Bolloknoon** [comment]
I just want to make a minor changes in the files but I cannot commit the file without PR since I don't have writing assess on this file.

How can I get writing asscess on the file?
https://github.com/nextstrain/ncov/blob/sit-rep_ko/narratives/ncov_sit-rep_ko_2020-03-13.md.

@cassiawag

**Comment by cassiawag** [comment]
@Bolloknoon -- on my end it's showing an open invitation to the `ncov` repo that you haven't yet accepted. Maybe this [forum post](https://github.community/t5/How-to-use-Git-and-GitHub/Where-do-I-see-all-incoming-invitations-collaborator/td-p/4280) can help you troubleshoot?

**Comment by Bolloknoon** [comment]
Oh I found the invitation email now. Thank you! @cassiawag

**Comment by cassiawag** [comment]
Hello all -- thank you for your hard work! What's the status on this? I'd love to get it published soon.

**Comment by minkyuxyz** [comment]
Hey, @cassiawag, is it possible to make a few minor edits after publishing as well? Or, do you prefer not to edit anything beyond the point it is published? I'd say: it's generally good to go. But I would like to fine-tune a few sentences, however, I am occupied for the next few hours. I would not object if you think timely publication is more important and publish it anyway.

**Comment by cassiawag** [comment]
A couple hours is no problem :) Thanks for your help in the midst of what I'm sure is an already busy schedule.

**Comment by minkyuxyz** [comment]
Perfect, I'll wrap things up by 9pm PT.

**Comment by minkyuxyz** [comment]
It's okay to publish, now.

**Comment by taehoonh** [comment]
Hi all,
My names is Taehoon Ha and I am working as an assistant research biostatistician at Weill Cornell Medicine. If you need anything, feel free to let me know. Also, @cassiawag, I would appreciate if you send me an invitation. Thank you. Again, great to work with you all.

**Comment by cassiawag** [comment]
Thank you all for the hard work! It's now live at: https://nextstrain.org/community/narratives/nextstrain/ncov/sit-rep/ko/2020-03-13

**Comment by cassiawag** [comment]
@hyouka315 & taehoonh, thank you so much both for your offer to help with translations. It's really incredible to see how the global community has come together to fight against COVID-19; you are part of that, and we really appreciate it. However, at this time, we have enough Korean translators. May I add your names to our backup list of translators? I will contact if we need any more help.

**Comment by hyouka315** [comment]
I am glad to hear that many are willing to work together in this project. And I am willingly to join as a backup member.
I must say that it's truly an honor to take part.

Android용 Outlook<https://aka.ms/ghei36> 받기
________________________________

**Comment by taehoonh** [comment]
@cassiawag 
Not a problem at all. I would be more than happy to be a back-up. Glad as well that many are contributing to this. Please let me know if you need anything.

**Comment by cassiawag** [comment]
Thank you both for understanding. Stay well.

**Comment by KyobinKang** [comment]
@hyouka315, @taehoonh, @hanbin973, @minkyuxyz, @Bolloknoon 
If anyone have a background on evolutionary biology, bioinformatics, or systems biology, please help me to translate the "How to read a tree" document. Because of its content, it needs a little bit of knowledge on the fields above. You can find the document at: https://github.com/nextstrain/ncov/blob/background_ko/narratives/ncov_trees-background_ko.md

**Comment by taehoonh** [comment]
Hello @KyobinKang, 
I still have a lot to learn, but let me give it a try if you don't mind.

**Comment by KyobinKang** [comment]
@taehoonh Please give a translation directly to the document above. Thanks.

**Comment by taehoonh** [comment]
@KyobinKang, 
It seems that I do not have a write access to **nexstrain/ncov**. It would be grateful if you give me an access to it. Thank you in advance.
