### ISSUE TITLE
Translate March 13 situation report into Mandarin

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#155]
Happy weekend @fillorkill, @alvinxhan, @lxy0107, @fzhang12!

The situation report from March 13 is ready to be translated to Mandarin Chinese. A branch exists as `sit-rep_zh`  where this can be done, and the file to translate is `ncov_sit-rep_zh_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-13.md. 
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_zh`, so there’s no need to create a pull request. Please make sure you have accepted an invitation from me to join the `ncov` repo.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Mandarin-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
Thank you so very much for your hard work; you all are amazing!

**Comment by lxy0107** [comment]
Hi all,  @fillorkill, @alvinxhan, @fzhang12
maybe we can get a head count who have time to translate this weekend? I propose we have at least one person translate and one person proofread it. If one than two people have time, we can split the report into two or three parts for the ‘translators’, and the ‘proofreader’ will still proof the entire article.

If anyone wants to do it reply by Saturday night and let’s aim to finish by Sunday night, latest Monday night, East coast time US. (I’m in Germany though;)

I’m willing to either translate or proofread this week.

Xueying

**Comment by alvinxhan** [comment]
Will be a busy weekend for me - happy to proofread.

-----

Cheers,
A

On 14 Mar 2020, at 9:16 AM, lxy0107 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi all, @fillorkill, @alvinxhan, @fzhang12
maybe we can get a head count who have time to translate this weekend? I propose we have at least one person translate and one person proofread it. If one than two people have time, we can split the report into two or three parts for the ‘translators’, and the ‘proofreader’ will still proof the entire article.

If anyone wants to do it reply by Saturday night and let’s aim to finish by Sunday night, latest Monday night, East coast time US. (I’m in Germany though;)

I’m willing to either translate or proofread this week.

Xueying

Sent from my iPhone

> On 14. Mar 2020, at 00:13, cassiawag <notifications@github.com<mailto:notifications@github.com>> wrote:
>
> ﻿
> Happy weekend @fillorkill, @alvinxhan, @lxy0107, @fzhang12!
>
> The situation report from March 13 is ready to be translated to Mandarin Chinese. A branch exists as sit-rep_zh where this can be done, and the file to translate is ncov_sit-rep_zh_2020-03-13.md under the narratives folder: https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-13.md.
>
> You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the sit-rep_zh, so there’s no need to create a pull request. Please make sure you have accepted an invitation from me to join the ncov repo.
>
> Note that this file is in Markdown. In general, it is important not to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like <! -- Comment -->.
>
> After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-13
>
> Please add your name in parentheses to the end of the author list, so we can credit your work!
>
> After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Mandarin-speaking colleagues, so we can get the information out there!
>
> Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
>
> Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
>
> Thank you so very much for your hard work; you all are amazing!
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnextstrain%2Fncov%2Fissues%2F155%23issuecomment-599026771&data=02%7C01%7Cx.han%40amsterdamumc.nl%7Ccd27bad49d674e3c405808d7c7eff278%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C637197705682116343&sdata=WD3o0zofNaR6BnLq0doFPx22kcZ0Hz6X54hSWxZW6JM%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEB37F72ITUVEJRNDX6QTJ3RHM4MNANCNFSM4LHSBL7Q&data=02%7C01%7Cx.han%40amsterdamumc.nl%7Ccd27bad49d674e3c405808d7c7eff278%7C68dfab1a11bb4cc6beb528d756984fb6%7C0%7C0%7C637197705682126338&sdata=5sCJ5Ze86Orx7gbl8R%2FYrOEJlNQgejWtVUFE2NX7%2FHg%3D&reserved=0>.

______________________________________________________
VUmc disclaimer : www.vumc.nl/disclaimer
AMC disclaimer : www.amc.nl/disclaimer

**Comment by fzhang12** [comment]
I am here in Germany too. Happy to take one part of the translation. 
@lxy0107 which part do you prefer? I will start later.
Either way I need to go over the whole since I need to proofread the JP.

**Comment by lxy0107** [comment]
It seems @fillorkill already did half it, maybe I can do the rest today and you can proofread?

**Comment by fillorkill** [comment]
I just pushed the rest of the translation, if anyone could proofread?

**Comment by lxy0107** [comment]
Hi all, I will start proofreading now since I have some time.

**Comment by fzhang12** [comment]
I updated till summary part. but be careful with content list. I found removing half-width dot in that page will break the slides.

> Hi all, I will start proofreading now since I have some time.

**Comment by lxy0107** [comment]
Yes, and I will push after going through each page.

**Comment by lxy0107** [comment]
Hi all, I finished proofreading.
@fillorkill @fzhang12 please check if you agree with all the changes - great work!
We should also put our names in, right? I noticed none of you has done it.
@cassiawag you mean we add our names in parentheses to the author list on the front page, right? Do we need to add any note like "translators"?

**Comment by cassiawag** [comment]
Yes, @lxy0107, exactly right. The parantheses is to signify translators. In the future we're hoping to add another field for translators in the future, but that still requires some code development on our end.

**Comment by fzhang12** [comment]
I have read through the whole. both @lxy0107 and @fillorkill have done a great job.
@alvinxhan may give us more comments. Let us wait for her update :)

**Comment by lxy0107** [comment]
I added my name in Chinese and @fzhang12 's name in English.
@fillorkill you can add your name before us (sorry I don't know your name).

**Comment by lxy0107** [comment]
Hi all, I thought maybe it’s a good idea to share the translated report (screenshots) on Chinese social media, e.g. Weibo, the Twitter substitute in China, to help science communication. @cassiaweg, do people agree with this? The authors will of course be credited. @others, if so, should we coordinate Weibo posts as well (like to make screenshots and annotate the figures)?

**Comment by fzhang12** [comment]
It could be a possible approach but I strongly suggest we should leave the scientific credits in English, in case we have any consequence later.
I dont know who added 'Chinese Taiwan' after the laboratory from Taiwan. Please, DO NOT bring any political opinion into their scientific report.

**Comment by cassiawag** [comment]
Well said, @fzhang12. I strongly echo that statement; we CANNOT bring anything political into these reports. Please adjust the document accordingly. Thank you.

**Comment by fillorkill** [comment]
I agree we can leave the credits in English. I did the previous commits including the translated credits. However if they are left in English, you may want to take out "R.O.C" altogether from the English narrative anyway. The correct name for the agency is Taiwan Centers for Disease Control, without any suffix. R.O.C itself is political.

**Comment by tsibley** [comment]
@fillorkill For context here, `Centers for Disease Control, R.O.C. (Taiwan)` is what is reported on GISAID. I think our reports' attribution/credit of the various labs need to use what is submitted to and reported by GISAID.

**Comment by alvinxhan** [comment]
> I have read through the whole. both @lxy0107 and @fillorkill have done a great job.
> @alvinxhan may give us more comments. Let us wait for her update :)

Hey, gave it a read - I think all of you did a great job. I don't really have any substantive comments. There is no need to credit me - I didn't do anything other than proofreading.

**Comment by lxy0107** [comment]
Hi all, I think having the contribution page in English makes sense. I asked my friend in China and found nextstrain.org can be accessed there. Then it makes things easy. Maybe when the Chinese version is up, I will ask a friend I trust who works actively in science communication and has a background in plant phylogenetics to write a post on Weibo, something like your PR Tweet. Does that work with the team? @cassiawag

**Comment by cassiawag** [comment]
I think that sounds great @lxy0107! I am publishing this now. Thanks to all for the hard work!

**Comment by cassiawag** [comment]
Thanks to our amazing developers. We can now add translators in a separate field, and we can include links to the translators professional pages or twitter if they'd like. See for example: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-13

Do you have a webpage you would like me to link to?

**Comment by cassiawag** [comment]
It's now live at: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-13
Let me know if you have a web page, you'd like linked to.
