### ISSUE TITLE
Translate March 13 situation report into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#156]
Happy weekend @7glaucio, @andersonbrito !
 
The situation report from March 13 is ready to be translated to Portuguese. A branch exists as `sit-rep_pt`  where this can be done, and the file to translate is `ncov_sit-rep_pt_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_pt/narratives/ncov_sit-rep_pt_2020-03-13.md. 
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! 
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pt/sit-rep/pt/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Portuguese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Thank you so very much for your hard work; you all are amazing!

**Comment by 7glaucio** [comment]
Hello, @cassiawag . The first version is ready to be revised. @andersonbrito, it's all yours.

**Comment by cassiawag** [comment]
I've had an offer for more help with Portuguese translations. You two seem to have a system down, which is why I'm asking first, but weekly translation could be a big burden. I can send more people your way if helpful.

**Comment by andersonbrito** [comment]
@cassiawag, from my side, no worries. Please, bring her/him in.

**Comment by andersonbrito** [comment]
The 2020-03-13 report, Portuguese translation is ready to go.
Thank you  for translating the largest part of it, @7glaucio. Great job.

**Comment by cassiawag** [comment]
I'll add him on to the next round of translations. Thank you for the fast work! It's now posted at: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-03-13
