### ISSUE TITLE
Translate March 13 situation report into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#157]
Happy weekend @dtaliun, @frogtraveler, @vpuller, @irina95511!

The situation report from March 13 is ready to be translated to Russian. A branch exists as `sit-rep_ru`  where this can be done, and the file to translate is `ncov_sit-rep_ru_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ru/narratives/ncov_sit-rep_ru_2020-03-13.md. 

You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_ru`, so there’s no need to create a pull request.

Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ru/sit-rep/ru/2020-03-13

Please add your name in parentheses to the end of the author list, so we can credit your work!

After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Russian-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.

Thank you so very much for your hard work; you all are amazing!

**Comment by frogtraveler** [comment]
I could work on translation tomorrow

**Comment by vpuller** [comment]
As I had time, I have translated a part of it. If I have time later, I will do more.

**Comment by vpuller** [comment]
I've think that I have finished translating it. However, somebody has to proofread.

**Comment by cassiawag** [comment]
@irina95511 -- any chance you can take a look? Thanks so much @vpuller, fast work!

**Comment by irina95511** [comment]
Yes, happy to read now! Let you know as soon as I am done!

**Comment by irina95511** [comment]
Have finished -- the translation looks great to me!

**Comment by cassiawag** [comment]
Amazing work everyone!

I'm going to add your  names in parentheses to give you credit. @dtaliun, do you have a name you'd like me to use. I also don't have your twitter handle for when we post to twitter.

Also, can someone translate this for me for the twitter post?

The latest #COVID19 situation report is now available in Russian. Many thanks to @Meklab, Vadim Puller and [dtaliun] for their fast translation!

**Comment by dtaliun** [comment]
Thank you @cassiawag! I don't have twitter handle but you can use my name Daniel Taliun.
Below is the translated twitter post.

Последний отчет о ситуации по #COVID19 теперь доступен на русском языке. Большое спасибо @Meklab, Vadim Puller и Daniel Taliun за их быстрый перевод!

**Comment by cassiawag** [comment]
Thank you all for your fast work! It's live here: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-03-13 Please share with your colleagues.
