### ISSUE TITLE
Translate March 13 situation report into Spanish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#158]
Happy weekend @miparedes, @Chjulian, @Cholokiwi!

The situation report from March 13 is ready to be translated to Spanish. A branch exists as `sit-rep_es`  where this can be done, and the file to translate is `ncov_sit-rep_es_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_es/narratives/ncov_sit-rep_es_2020-03-13.md. 

You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_es`, so there’s no need to create a pull request.

Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) 
Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_es/sit-rep/es/2020-03-13

Please add your name in parentheses to the end of the author list, so we can credit your work!
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Spanish-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Spanish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use an online editor like hackmd to translate together, whatever works best for you. But when finished, please push it to GitHub for proofreading and review.

Thank you so very much for your hard work; you all are amazing!

**Comment by Cholokiwi** [comment]
Sweet as, working on it.

**Comment by miparedes** [comment]
Sounds good! @Cholokiwi @Chjulian How do we want to divide this?

**Comment by Cholokiwi** [comment]
Hi Miguel,
I just emailed Juliana about this but I didn't have your email. How about I
do the summary plus the first two headings (up to Circulation in Europe)
and you do the rest? Then we proof-read each other's part?
Cheers,

Roy

**Comment by miparedes** [comment]
Hey!
That works for me! My email is paredesm@uw.edu for future use!

**Comment by Cholokiwi** [comment]
Awesome Miguel. Apologies Julian! Don’t know why the autocorrection changed
your name.
Cheers,
Roy

**Comment by Cholokiwi** [comment]
Hi @miparedes @Chjulian just finished. Please have a look when you have a chance (and be patient as it is my first time :) ).

Hey @cassiawag, could the background info (links below) be also translated?
https://nextstrain.org/help/general/how-to-read-a-tree
https://nextstrain.org/help/coronavirus/SARS-CoV-2
https://nextstrain.org/help/coronavirus/human-CoV#seasonal-cov

Cheers,

Roy

**Comment by cassiawag** [comment]
@Cholokiwi -- we've got a little bit of code development before we can translate the general pages. See this [this issue](https://github.com/nextstrain/nextstrain.org/issues/130). But I'll be opening a request soon to get the background narrative on "How to read phylogenies" translated.  Thanks for your quick work! That was very fast.

**Comment by miparedes** [comment]
Hey y'all @Cholokiwi @Chjulian, just finished the translation. It should be available for you to proofread. Would love to hear your comments as well! (I had a bit of trouble when uploading to github so please let me know if anything seems regarding the files) 

@cassiawag I had a little github trouble and seem to have broken the nextstain.org narratives preview -- can you fix it? (I'm not too sure how to do it)

**Comment by cassiawag** [comment]
Fixed it @miparedes.

We now have a new field for translators on the first page (yay!), and you can add a link to your name. I put in all your Twitter accounts, but if you'd like to update that to another professional page, please do so.

**Comment by cassiawag** [comment]
@Cholokiwi or @Chjulian, any updates? I would love to get this published.

**Comment by Chjulian** [comment]
I just proof-read. Just minor changes. Reads good. Cheers

**Comment by Cholokiwi** [comment]
Hi all,

It looks good to me too. I just made other small changes.

However, the links in the table of contents do not properly work in the
preview though as they go to the English version. @cassiawag, could we do
something at our end?

Cheers,

Roy

**Comment by cassiawag** [comment]
@Cholokiwi, thanks for noticing that; most people don't! I just changed the internal links. I leave those to the end because prior to publishing, the correct language links don't actually this. 

Can we change the UK back to Great Britain and Ireland? With all the politics that have gone, I want to be safe and leave it as it was.

**Comment by Cholokiwi** [comment]
Done @cassiawag ! Sorry about that newbie mistake.
Cheers,

Roy

**Comment by cassiawag** [comment]
And it's live at: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-03-13

Thank you all for the excellent translation!
