### ISSUE TITLE
Translate March 13 situation report into Hindi

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#159]
The situation report from March 13 is ready to be translated to Hindi. A branch exists as `sit-rep_hi`  where this can be done, and the file to translate is `ncov_sit-rep_hi_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_hi/narratives/ncov_sit-rep_hi_2020-03-13.md. 
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_hi/sit-rep/hi/2020-03-13
 
Please add your name in parentheses to the end of the author list, so we can credit your work!
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Hindi-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Hindi; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

**Comment by cassiawag** [comment]
@wonkyshree, all of the information you need should be above. Let me know if you have any questions!

**Comment by roanvanscheppingen** [comment]
I've asked @palmrinmoy (a labmate) to also have a look into this. Last time he was too late, but maybe he has some time right now :)

**Comment by wonkyshree** [comment]
Thank you. Just read this. @cassiawag

**Comment by wonkyshree** [comment]
Is there a deadline for this?

**Comment by cassiawag** [comment]
@wonkyshree, we're publishing reports every Friday; thus, the content quickly becomes outdated. So the sooner the better?
