### ISSUE TITLE
Translate March 13 situation report into Arabic

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#160]
Happy weekend @SalehA74 !

If you feel like the narrative format will work with Arabic, the situation report from March 13 is ready to be translated. I remade the `sit-rep_ar`  branch where this can be done, and the file to translate is `ncov_sit-rep_ar_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ar/narratives/ncov_sit-rep_ar_2020-03-13.md. 

You can translate directly in this file, but please remember to push often as other people may be working on the translation! 

Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ar/sit-rep/ar/2020-03-13

If you have any other colleagues who might be interested in working on this translation, feel free to tag them there.

Please add your name in parentheses to the end of the author list, so we can credit your work!
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Arabic-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Arabic; please don’t add them to the 
situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Thank you so very much for your hard work!

**Comment by kairstenfay** [comment]
Hi @wammar! Thanks for agreeing to take a look at the Arabic translation of our hCoV-19 narrative. I'm connecting you with @cassiawag who will take it from here.

**Comment by cassiawag** [comment]
Hi @wammar! Excited to have your help! I just sent you an invitation to join the repo, so you should be able to push to this branch. Please review the above translation for grammatical correctness as well as accuracy to the English version here: https://nextstrain.org/narratives/ncov/sit-rep/2020-03-13. Translate any sentences that haven't yet been translated. Please push your edits up to the branch, and then they can be previewed on the narratives platform. Thanks very much, and let me know if you have any questions.

**Comment by SalehA74** [comment]
Hi @cassiawag and @wammar. The first draft of the Arabic translated situation report is ready for proofreading! Any comments are welcome.

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-03-13

Well done @SalehA74 and @hamarsheh. Thank you for the hard work. I couldn't get the link on slide 2 to work so if either of you wants to edit that tomorrow, please do. But I decided the information was worth publishing to keep a link error from stopping us.
