### ISSUE TITLE
Added OGP settings for sharing information on SNS.

### ISSUE THREAD

**Issue by tomoyuki-nezu** [nextstrain/ncov#165]
When sharing a post on Twitter or Facebook, if information according to the OGP is added in the contents header, it will be displayed when sharing, and people who see the shared information will understand it better.

The Open Graph protocol
https://ogp.me/

OGP Guidelines on Facebook
https://developers.facebook.com/docs/sharing/webmasters/

OGP Guidelines on Twitter
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

I think that ncov is distributed using Gatsby, so it will be added to the settings of Gatsby some template. Are there any plans for OGP? And who should I talk about this context?

**Comment by glasnt** [comment]
This issue has been opened over on https://github.com/nextstrain/nextstrain.org/issues/134, which is the repo for the static website. I think this issue can be closed and discussions moved there.

**Comment by tomoyuki-nezu** [comment]
Thanks!!!
