### ISSUE TITLE
The substitution rate estimate under 'clock' view appears incorrect

### ISSUE THREAD

**Issue by emvolz** [nextstrain/ncov#17]
It states in the graph: "rate estimate: 1.40e+1 subs per site per year"
Surely not. Is this rate per genome?

**Comment by jameshadfield** [comment]
Hey Erik -- yes, this data has been scaled to represent "mutations per genome" as we felt that would be more generally interpretable, but the visualization hasn't caught up!

**Comment by trvrb** [comment]
Thanks Erik! I've created an issue in Auspice here: https://github.com/nextstrain/auspice/issues/858, which is the place in the codebase that this would be addressed.

**Comment by emmahodcroft** [comment]
Hi Erik - just to let you know, we've pushed through a fix for this and it should be displaying correctly now:
![image](https://user-images.githubusercontent.com/14290674/73445185-69d66f80-435a-11ea-90a6-300f7fe62c03.png)
But thanks again for bringing this to our attention!
