### ISSUE TITLE
Translate March 13 situation report to Polish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#172]
Hello @balwierz!

The situation report from March 13 is ready to be translated to Polish. A branch exists as `sit-rep_pl` where this can be done, and the file to translate is `ncov_sit-rep_pl_2020-03-13.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_pl/narratives/ncov_sit-rep_pl_2020-03-13.md.

You can translate directly in this file, but please remember to push often as other people may be working on the translation! If you have any other Polish-speaking colleagues who would like to help you in this endeavor, please feel free to tag them at this issue.

Note that this file is in Markdown. In general, it is important not to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.)
Comments to help with translation are noted in comment symbols like <! -- Comment -->.

After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pl/sit-rep/pl/2020-03-13

Please add your name in parentheses to the end of the author list, so we can credit your work!
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Polish-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Polish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Thank you so very much for your hard work!

**Comment by cassiawag** [comment]
@aniafijarczyk is going to join in on these translations! Thanks so much for your help. I'll let you and @balwierz coordinate together.

**Comment by balwierz** [comment]
Lots of tasks to do these days. I asked some additional people for help.

**Comment by balwierz** [comment]
It is basically finished, apart from some formatting issue at FAQ part after auspiceMainDisplayMarkdown

I dont know how to fix it. Could you have a look?

**Comment by cassiawag** [comment]
@balwierz -- thanks for the good work on this!

I fixed the formatting error. It did not like the comment in the same line as the heading of the FAQ slide, for future reference. We also have the option to add translatorLinks to your professional websites (some translators use their twitter) if you'd like to add those. Finally, if you can translate the text under "Scientific Credit" and "Detailed Scientific Credit," that would be much appreciated. Labs and sequence names should not be translated, but the other text should be.

@aniafijarczyk -- let me know when it's good to go from your end.

**Comment by balwierz** [comment]
@aniafijarczyk Thanks a lot for your work!

**Comment by balwierz** [comment]
@cassiawag All done. 
translatorLinks were not transformed to hyperlinks

**Comment by cassiawag** [comment]
translatorLinks only works if everyone has an entry. Until then, they'll just be names.

**Comment by aniafijarczyk** [comment]
@cassiawag @balwierz I'll go through everything last time

**Comment by aniafijarczyk** [comment]
I'm done with the proofs. I think it looks good!

**Comment by cassiawag** [comment]
I'll send it live. Thank you so much for the good work @balwierz and @aniafijarczyk!

**Comment by cassiawag** [comment]
@balwierz: Do you have a twitter account I can tag in the post?

And can someone please translate one final bit of text for me for the twitter post:

Pleased to announce that the #COVID19 report from March 13 is now available in Polish. A big thank you to Piotr Balwierz, @afijarczyk, and Bartosz Lisowski for their translation.

**Comment by aniafijarczyk** [comment]
Sure! "Miło mi poinformować, że raport #COVID19 z 13 marca jest teraz dostępny w języku polskim. Ogromne podziękowania dla Piotra Balwierza, @afijarczyk i Bartosza Lisowskiego za tłumaczenie."

**Comment by cassiawag** [comment]
It's now live at: https://nextstrain.org/narratives/ncov/sit-rep/pl/2020-03-13 ! Cheers all! The next report will be coming out tomorrow (Friday) around 5p PDT if you want to translate that one to Polish.

**Comment by balwierz** [comment]
Sorry, I am in London time zone. My Twitter account: PiotrBalwierz
