### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to French

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#175]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into French. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_fr.md` in branch `background_fr` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_fr/narratives/ncov_trees-background_fr.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_fr/trees-background/fr/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative is a bit more technical, it would be great if the phylogenetics experts can especially keep their eyes on this translation :)

As always, THANK YOU! It’s an honor to work with you all.

@Maijin, @meriemelkaroui, @PierreBarrat, @Simon-LoriereLab, @DanielThedie

**Comment by Maijin** [comment]
Hi Everyone!

I have created an hackmd started working on it - https://hackmd.io/h9jCGoD3T2uTeOdtKMVi2w
To recap Hackmd is an online system that allows multiple users to collaborate on the same document with instant preview the changes.

I also opened an instant message chat / IRC - https://webchat.freenode.net/#nextstrain-fr-translation so we can coordinate on the translation. (You don't need password but just need to choose a nickname to join)

**Comment by meriemelkaroui** [comment]
Hi Everyone, 
Today I am super busy so I cannot help with the translation, sorry. 
@DanielThedie, @Simon-LoriereLab, @PierreBarrat , can you take over?
Thanks 
meriem

**Comment by DanielThedie** [comment]
Hi, yes I will get to it later this morning.

**Comment by Maijin** [comment]
First draft pushed - ready for review!

**Comment by Simon-LoriereLab** [comment]
So quick! I will check now.

**Comment by Simon-LoriereLab** [comment]
Once again terrific, I only changed minor things.
This can be released!

**Comment by cassiawag** [comment]
Thank you everyone! I am again amazed by your fast work.

Note: In the narratives format, all links must be followed by some type of text (can be punctuation), or else it will break the narrative. The exception to this is headers! Links in headers cannot be followed by punctuation b/c the lack of punctuation signal that this is a new slide. Letting you all know for future reference.

**Comment by cassiawag** [comment]
It's live at: https://nextstrain.org/narratives/trees-background/fr
