### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Dutch

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#176]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Dutch. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_nl.md` in branch `background_nl` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_nl/narratives/ncov_trees-background_nl.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_nl/trees-background/nl/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@roanvanscheppingen, @rvosa, @Van-Doorslaer, @pleunipennings, @JSHuisman, @JiscaH, @shenii

**Comment by JiscaH** [comment]
I'm working on it, but it definitely needs checking by one of the phylogenetic experts.

@cassiawag there's a typo at the very end of the "How do I read a tree" slide. It reads " A & B are more closely related to C than they are to D & C." - the last 'C' should be 'E'.

**Comment by JiscaH** [comment]
@cassiawag spotted another typo: end of slide "how does the map relate to the tree" reads:
"you can play an animation of how the inferred spread of the virus over the course of the outbreak."  - 'how'  should be deleted.

**Comment by JiscaH** [comment]
I've submitted a rough complete draft, with considerable contribution by google translate.

**Comment by roanvanscheppingen** [comment]
Ill check within an hour! 
@cassiawag do you have plans to further translate for example the explanations or background, or is it made by someone else?

**Comment by roanvanscheppingen** [comment]
Some edits:

Added Dutch translation of the first page
Added Dutch translation of the alternative texts (for the other Dutch people, this is the description of a picture, for the visually impaired people using reading software!)
Some spelling errors 
Changed some wording

**Comment by JiscaH** [comment]
@cassiawag  The very last slide ('End of Narrative') appears to be coded in another file

**Comment by JSHuisman** [comment]
I will go through it now as well (also looking at the narrative). This will be my first experience with git in a public repository, so bear with me :'

**Comment by rvosa** [comment]
My bad, we were crossing paths, I will take my hands off it now to let @JSHuisman do their thing. We are now at commit https://github.com/nextstrain/ncov/commit/b610223077fce4fdca66c9f2cc6eea034fbd4bdf

**Comment by JSHuisman** [comment]
Just finished - it seems quite ready (at least from a phylogenetics perspective the explanations make sense)

**Comment by cassiawag** [comment]
Thank you everyone for the fast translation! Wow, I continue to be very impressed by all. I'm publishing it now.

Thanks to our amazing developers, we can now add translators in a separate field, and translators can have a link to their own professional page. Example: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-13 Do you have any pages you would like me to link to?

**Comment by roanvanscheppingen** [comment]
You guys are more awesome though.

My twitter is enough :)

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/trees-background/nl Well done all.

I will update with translator links once/if everyone sends in a web page.
