### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#177]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Japanese. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_ja.md` in branch `background_ja` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_ja/narratives/ncov_trees-background_ja.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_ja/trees-background/ja/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@tomoyuki-nezu, @satotake, @fzhang12

**Comment by tomoyuki-nezu** [comment]
@cassiawag Thank you for your attention.

@satotake @fzhang12
I have a little time to translate a few pages. If someone can translate at in this time, please start after "Measuring differences with genetic divergence". I think I can translate this section.

**Comment by tomoyuki-nezu** [comment]
Translated and committed to Measuring differences with genetic divergence.
Questions are written as translator notes.

**Comment by satotake** [comment]
@tomoyuki-nezu Thanks.
I am translating the parts from `Measuring differences over time` to `About the dataset`

**Comment by satotake** [comment]
pushed mine and put comment about your notes

**Comment by tomoyuki-nezu** [comment]
@satotake Where are the comments written for me? It doesn't seem to be in the document.

**Comment by tomoyuki-nezu** [comment]
@satotake Found in commit history. I'll check it.

**Comment by tomoyuki-nezu** [comment]
Apply received comments from @satotake and committed.

**Comment by fzhang12** [comment]
Thank both of you. I will start proofread it right now.

**Comment by fzhang12** [comment]
Hi @tomoyuki-nezu @satotake , I've integrated all my comments. Your work is great as usual. Could any of you take a look at my changes (mainly on divergence part)?

**Comment by tomoyuki-nezu** [comment]
@fzhang12 I checked the my part. It is easier to understand and more accurate. Thank you!!!

**Comment by satotake** [comment]
Checked. Thanks @fzhang12 !

**Comment by tomoyuki-nezu** [comment]
@cassiawag I think, ready to publish :)

**Comment by cassiawag** [comment]
So fast! I'm having trouble keeping up with you all :)

This is published here: https://nextstrain.org/narratives/trees-background/ja

I've also updated the latest situation report with the appropriate link: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-03-13

Thanks again for the excellent work.
