### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#178]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Russian. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_ru.md` in branch `background_ru` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_ru/narratives/ncov_trees-background_ru.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_ru/trees-background/ru/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@irina95511 @dtaliun @frogtraveler @vpuller @ivan-aksamentov

**Comment by frogtraveler** [comment]
I think there is a typo in English version in line 80: "Based on this tree, we would conclude that A & B closely related to each other, and D & E are closely related to each other. A & B are more closely related to C than they are to D & C". The last sentence should be: "A & B are more closely related to C than they are to D & E".  @cassiawag

**Comment by cassiawag** [comment]
Thank you @frogtraveler for noticing that typo. It's now fixed in the English version. @ivan-aksamentov or @vpuller, any chance either of you could proofread this? I know you're both quite busy, and I'd like to have it proofread by someone who does phylogenetics. Thank you!

**Comment by vpuller** [comment]
Hi, I have proofread it and translated a few remaining bits.

**Comment by cassiawag** [comment]
Thank you @vpuller!

@irina95511 -- any chance you could take one final look? Since this text will be used for a while, I want to make sure plenty of eyes see it.

**Comment by irina95511** [comment]
Yes, can do right now! Sorry for not being able to help earlier, was quite busy during the day...

**Comment by irina95511** [comment]
I went through the translation, great work guys! Everything is very clear and accessible for Russian community :)

**Comment by cassiawag** [comment]
It's live at: https://nextstrain.org/narratives/trees-background/ru. The link in the most current situation report has also been updated. Thank you all for the quick and excellent translation :)
