### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Farsi

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#179]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Farsi. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_fa.md` in branch `background_fa` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_fa/narratives/ncov_trees-background_fa.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_fa/trees-background/fa/

Please add your name in parentheses to the end of the author list, so we can credit your work!

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you both.

@mg878 @dahaj1897

**Comment by mg878** [comment]
yes, we will start working on this shortly!

**Comment by mg878** [comment]
Hey @cassiawag, just letting you know that @dahaj1897 and are now pushing the translation out. 
However, looking at the preview right now, unfortunately, the issue with R--->L text is still there.
I am going to report this in the auspic thread #954.

**Comment by dahaj1897** [comment]
Hi,
I pushed full translated file.

**Comment by mg878** [comment]
@cassiawag just letting you know that the translation for "How to interpret phylogenetic trees" to Farsi is now completed (just pushed it now for the last time) and should be on the background_fa branch and following directory:
narratives/ncov_trees-background_fa.md

Let me know if there was any issues. thanks!

**Comment by cassiawag** [comment]
Thanks so much for both of these @mg878 & @dahaj1897. It's now live here: https://nextstrain.org/narratives/trees-background/fa
