### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to German

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#180]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into German. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_de.md` in branch `background_de` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_de/narratives/ncov_trees-background_de.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_de/trees-background/de/

Please add your name in parentheses to the end of the author list, so we can credit your work!

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@astridgall, @nicfel, @rneher

**Comment by tolot27** [comment]
Pull requests should still be created and submitted to https://github.com/nextstrain/narratives, right?

**Comment by tolot27** [comment]
I'm also wondering why the origin of the sequences is part of the narratives and not generated dynamically.

**Comment by tolot27** [comment]
Any progress on this translation? If not, I'd be happy to finish the translation.

**Comment by astridgall** [comment]
@cassiawar, @nicfel, @rneher The left-hand text is done, subject to proofreading

**Comment by astridgall** [comment]
Hi @nicfel, @rneher
This is done subject to proof-reading and editing by you.
Also, the links in the table of content point to the English pages.
Astrid

**Comment by cassiawag** [comment]
Thanks @astridgall!

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/trees-background/de !

Thanks @astridgall for taking the lion's share of the work, and thank you @nicfel for the proofread.
