### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Mandarin

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#184]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Mandarin Chinese. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_zh.md` in branch `background_zh` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_zh/narratives/ncov_trees-background_zh.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_zh/trees-background/zh/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@alvinxhan @fillorkill @fzhang12 @lxy0107

**Comment by fillorkill** [comment]
I finally had sometime today to finish the translation. I'm no phylogenetics experts so please can someone proofread this?

**Comment by fzhang12** [comment]
Thanks, @fillorkill . I will take a look when I have more time during the weekend. 
Just a suggestion: read a little more online resources if you have no idea what the word means :)

**Comment by lxy0107** [comment]
I've been working on it slowly;) glad to see you finished it @fillorkill 
I will also take a look.

**Comment by lxy0107** [comment]
@cassiawag can you ask the team to check this page 'https://nextstrain.org/narratives/trees-background?n=8'. This sentence: 

> In the last example, we have only one sequence from orange, which could lead us to think that there was one introduction from orange into blue.

I think there's a mistake - it should be "there was one introduction from **blue** to **orange**", right?

I corrected it in the Chinese version, but let me know if I'm wrong.

**Comment by cassiawag** [comment]
This is correct @lxy0107 -- good catch!

**Comment by alvinxhan** [comment]
Went through the translation, looks good! Great job.

**Comment by lxy0107** [comment]
I just finished the proofreading, but no major changes since your read @alvinxhan

**Comment by cassiawag** [comment]
It's now live at: https://nextstrain.org/narratives/trees-background/zh

Thanks everyone for the collaborative translation!
