### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#185]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Portuguese. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_pt.md` in branch `background_pt` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_pt/narratives/ncov_trees-background_pt.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_pt/trees-background/pt/

Please add your name in parentheses to the end of the author list, so we can credit your work!

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you both.

@andersonbrito @7glaucio

**Comment by 7glaucio** [comment]
@cassiawag You're right. I've been thinking about it while translating the last report. The phylogeny is a fundamental part of the analysis. On the other hand, it's a very technical guide, so I think someone more involved in this area should do it to have a better translation. What do you think, @andersonbrito ? If you're too busy to do I can start but only in the next few days, because I got a lot of work and studying to do right now.

**Comment by andersonbrito** [comment]
@cassiawag, I'm in a similar situation. Due to COVID-19, activities in my lab will intensify this week, so, I predict things will be a bit hectic.

I can help translating some bits at each day, in my free time (if I have some, hoping things will not get too wild in CT).

**Comment by cassiawag** [comment]
Definitely understand @7glaucio & @andersonbrito. It's a crazy time for us all. I'm going to see if the new Portuguese translator wants to work on this, and then maybe you can proofread as your schedule allows? We've already published to situation reports without this and another week or so is not going to be a problem.

**Comment by andersonbrito** [comment]
The help of the third translator will be really welcomed.
I'm happy to proofread it.

**Comment by 7glaucio** [comment]
Feel free to bring her/him. I gonna try start translating tonight, then I gonna commit it, in case someone else wants to step in and translate other parts.

**Comment by 7glaucio** [comment]
Hey @cassiawag , I had some free hours tonight, then I did it myself. When it's ready remember to include it replacing the URLs on the narratives. 

@andersonbrito feel free to proofread when you have the chance. How it's too technical for me, I tried my best. But I quite sure you gonna have a few things to fix.

**Comment by cassiawag** [comment]
Thanks @7glaucio!

**Comment by cassiawag** [comment]
@EricaBarroso, if you want to give this a proofread, that would be great!

**Comment by cassiawag** [comment]
Per conversation with @andersonbrito, this is now published here: https://nextstrain.org/narratives/trees-background/pt

Thanks for the excellent translation: @7glaucio & @andersonbrito.
