### ISSUE TITLE
Narratives affiliation 

### ISSUE THREAD

**Issue by roanvanscheppingen** [nextstrain/ncov#190]
Hi, 

When scrolling through the different languages, I saw the names of the translators within the parenthesis, but the affiliation superscript is behind the parenthesis, as if we are all working in Seattle. To avoid confusion, that one could perhaps be moved? 

Cheers :)

**Comment by cassiawag** [comment]
Hey @roanvanscheppingen, yes, it is a bit confusing. We haven't yet developed the code to have multiple affiliations, but we're actively working on it. Within the last 12 hours, we added a feature to allow a separate translators field. See https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-13. I'm actively working on updating the already published narratives to reflect this.

**Comment by jameshadfield** [comment]
@roanvanscheppingen this is https://github.com/nextstrain/auspice/issues/951 -- feel free to take it if possible 😄
