### ISSUE TITLE
"How to interpret phylogenetic trees" in english has 2 typo's + last slide isn't translatable

### ISSUE THREAD

**Issue by JiscaH** [nextstrain/ncov#191]
- at the very end of the "How do I read a tree" slide it reads " A & B are more closely related to C than they are to D & C." - the last 'C' should be 'E'.
- end of slide "how does the map relate to the tree" reads: "you can play an animation of how the inferred spread of the virus over the course of the outbreak." - 'how' should probably be deleted.
- The very last slide ('End of Narrative') appears to be coded in another file

**Comment by Simon-LoriereLab** [comment]
Also, in the "How does the "diversity" panel relate to the tree?", 3rd paragraph
"In this "divisity" panel," should be "In this "diversity" panel," no?

**Comment by cassiawag** [comment]
Thank you very much @JiscaH & @Simon-LoriereLab for noticing these and letting us know! In regards to the final slide, that text is hardcoded in auspice, and at this point can't be translated.

@sidneymbell, I've created a PR [here](https://github.com/nextstrain/narratives/pull/3) that should address them.
