### ISSUE TITLE
minor: Strasbourg (France) location is shifted west on the map

### ISSUE THREAD

**Issue by Simon-LoriereLab** [nextstrain/ncov#192]
Hello,
Looking at the map of the recent French cases, the location of Strasbourg seems a bit off (same on different browsers and on mobile), while the lat long coordinate appear correct in the file.
With more sequences coming  for the eastern part of the country, would be great if it was possible to check?
<img width="835" alt="2020-03-15_Nextstrain_Map" src="https://user-images.githubusercontent.com/60473383/76699888-0017e800-66b2-11ea-9384-450b3867f5a5.png">

Thanks again for the amazing work!

**Comment by Simon-LoriereLab** [comment]
cannot reproduce this anymore.

**Comment by Maijin** [comment]
It's still there see -

<img width="514" alt="image" src="https://user-images.githubusercontent.com/1408600/77062768-d413a400-69dc-11ea-9e8e-be9bd95af702.png">

**Comment by emmahodcroft** [comment]
Just looking into this. This is dependant on what you have set as 'Geographic resolution' on the left. In the view pictured I believe it's set as 'division' which is the default. This isn't town-level resolution, but canton/region/state/admin division:
![image](https://user-images.githubusercontent.com/14290674/77063210-95cab480-69dd-11ea-96d1-7ec4d626c034.png)


If you set to 'location' this is city/town view, and this puts Strasbourg correctly:
![image](https://user-images.githubusercontent.com/14290674/77063232-a24f0d00-69dd-11ea-9f4e-71e3d5a9e91b.png)

Does this make sense, and hopefully resolve the problem?

**Comment by Maijin** [comment]
Ok yes it makes sense thanks then!
