### ISSUE TITLE
Suggestion: Meta tags for social media

### ISSUE THREAD

**Issue by minkyuxyz** [nextstrain/ncov#198]
Thank you for your tremendous contribution on spreading scientific findings & connecting researchers around the world with your awesome platform. 

Your service currently lacks a set of meta tags that are critical for sharing & advertising your site over social medial. As a result, there is no thumbnail image or proper headlines appearing when a link is shared on Twitter or Facebook. 

This is my humble suggestion to add those tags, making your site easier to spread -- or should I say, 'contagious' -- over the internet! Thanks.

**Comment by cassiawag** [comment]
@minkyuxyz, thanks for suggestion; we are agreed on it. If you have the background, try tackling the issue here: https://github.com/nextstrain/nextstrain.org/issues/134
