### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by tolot27** [nextstrain/ncov#20]
Like for French and Portugese, there exists a branch [sit-rep_de](/ncov/tree/sit-rep_de) for German translation, already.
I wonder why the file names contain the date. I know, they are linked to different versions according to the date. But for a highly dynamic document updating frequently, it looks a bit strange to me.

**Comment by tolot27** [comment]
What about the more recent analyses, i. e. from 28th, January? Shall the document link to the most recent version of the analyses? If yes, is it possible to create the links dynamically?

**Comment by jameshadfield** [comment]
@tolot27 -- we have made the decision to encode the date in the filename (and therefore the URL) for most nCoV datasets & narratives. This allows us to both preserve a historical record of analysis, easily viewable by anyone, as well as ensuring that the narrative content is referring to the correct data.

There is one exception: nextstrain.org/ncov will represent the latest dataset (you can see that currently this is the same as https://nextstrain.org/ncov/2020-01-28). 

We will create new narratives as time allows, and we will ensure that the frontpage of nextstrain.org is updated accordingly.
