### ISSUE TITLE
Translate March 13 situation report into Greek

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#202]
I'm creating this issue as a place to discuss the Greek translation of the situation report. @codergr has already done the hard work on the translation, but we'll want a proofread on it (as we do for all translations), preferably by someone with a background in phylogenetics.

The translated file exists on `sit-rep_el` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_el/narratives/ncov_sit-rep_el_2020-03-13.md.

After pushing to GitHub, the report can be previewed here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_el/sit-rep/el/2020-03-13

Translators: please add your name under the title page as well as a link to your professional self, e.g. twitter, university page, etc. 

After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Greek-speaking colleagues, so we can get the information out there!

Note: You may know of other great resources available in Greek; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.

Thank you so very much for your hard work!

**Comment by cassiawag** [comment]
@codergr, if you have any Greek-speaking colleagues with technical backgrounds, feel free to tag them here!

**Comment by codergr** [comment]
Sure @cassiawag , @afilp can you please take a look into this. Thanks

**Comment by cassiawag** [comment]
I'm going to close this issue b/c we're opening a new issue for this week's report, and I'd like proofreading/translation efforts to be directed to the newest report.
