### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Hindi

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#206]
We’d like to translate “How to interpret phylogenetic trees” into Hindi. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_hi.md` in branch `background_hi` under the narratives folder: https://github.com/nextstrain/ncov/blob/background_hi/narratives/ncov_trees-background_hi.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_hi/trees-background/hi/

Please add your name to the translators field, so we can credit your work! Also, if you have a professional website that you'd like your name to link to, please add that as well.

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like hackmd (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@wonkyshree

**Comment by pallavmehta** [comment]
I'm working on this now :)

**Comment by sidneymbell** [comment]
Closed per discussion with @pallavmehta and @cassiawag
