### ISSUE TITLE
add clade column to metadata.tsv

### ISSUE THREAD

**Issue by pwrose** [nextstrain/ncov#207]
The`clade` column is present in the nextstrain_ncov.tsv file available for download from the nextstrain website, however, it's missing in this info in the metadata.tsv file.

Alternatively, can the files available for manual download (no url) from the nextstrain website also be made available in this git repo so these files can be downloaded programmatically?

**Comment by seangrant82** [comment]
@pwrose can you point me that dataset? I cant seem to find it

**Comment by pwrose** [comment]
The data file that doesn't contain the clade column is this one:
https://github.com/nextstrain/ncov/blob/master/data/metadata.tsv

**Comment by seangrant82** [comment]
@pwrose what about the **nextstrain_ncov.tsv** dataset? I would be curious to look at the and see if there is a way to replicate the tree and map they have

**Comment by emmahodcroft** [comment]
Just to be clear - the clade definitions here are purely for us to have 'zoom' capability when we do our Situation Report narratives. They have no functional meaning - no meaning at all, except they are little clusters we are interested in highlighting in reports. Please be cautious that you do not over-interpret this data. It is not meaningful.

**Comment by seangrant82** [comment]
@emmahodcroft thanks for the clarification. I have mainly been looking at the metadata.tsv and will looking that some more then. I was wondering is there is an explanation/data dictionary of the field "length" is as it seem this is a connecting "node" between different strains

**Comment by emmahodcroft** [comment]
The 'length' is just the length of the sequence (number of bases) as given by GISAID. This may not be the exact length of bases that aren't 'N' (unknown). We use this as a first filter for our requirements (we only take nearly-full-length) sequences. This value alone isn't meaningful in an analytic sense, if anything at all it may indicate different technologies (minION/Illumina) being used to sequence, or different assembly techniques.

**Comment by pwrose** [comment]
I understand that the clade info is not official and may change over time.

However, for our analysis, it would be useful if the nextstrain_ncov.tsv file (as well as the tree files) had a URL so we can download it programmatically. Right now we need to download it manually from the Nextstain.org page.

**Comment by jameshadfield** [comment]
> it would be useful if the nextstrain_ncov.tsv file (as well as the tree files) had a URL so we can download it programmatically. Right now we need to download it manually from the Nextstain.org page.

This functionality doesn't currently exist. This could be added to nextstrain/auspice (which is the codebase of the visualisation app), however I don't see this happening in the short term as it would require shifting the code which makes this file into the server which is not in our current plans.

Much quicker would be to programmatically download `data.nextstrain.org/ncov.json`, which is what nextstrain.org/ncov is using, and parse the clade definitions from there into whatever format you need. Good luck!

> The data file that doesn't contain the clade column is this one:
https://github.com/nextstrain/ncov/blob/master/data/metadata.tsv

As that's the input metadata, and clades are inferred via the analysis pipeline, clades won't be available in that file.
