### ISSUE TITLE
why is clade info not available for some strains?

### ISSUE THREAD

**Issue by pwrose** [nextstrain/ncov#208]
The file nextstrain_ncov.tsv does not have clade info for some strains. Are these strains excluded from the Nextstrain.org visualization? Why don't these strains have a clade assignment?

**Comment by emmahodcroft** [comment]
The clade information given by Nextstrain is there to allow us to quickly visualise interesting clusters of branches in the tree, it has no functional or official meaning - these clades are not officially recognised and should not be interpreted as meaningful. This is why they are not included in any files - they are simply a visualisation aid.

**Comment by pwrose** [comment]
Thanks for the clarification.
