### ISSUE TITLE
Rule download fails

### ISSUE THREAD

**Issue by t-neumann** [nextstrain/ncov#209]
Hi,

I haven't yet gotten access to the GISAID dataset, but I wanted to do a dry run locally with `snakemake -p`.

Now it always seems to try to copy files from the remote `s3` which I understand is private. But what that step also always be executed if the proper files are already in the `data` subfolder?

```
Error in rule download:
    jobid: 13
    output: data/sequences.fasta, data/metadata.tsv
    shell:

        aws s3 cp s3://nextstrain-ncov-private/sequences.fasta data/
        aws s3 cp s3://nextstrain-ncov-private/metadata.tsv data/

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
```

Because this should be an optional step right?

**Comment by brianpardy** [comment]
If the required files are in place in the data subfolder the download rule does not get executed in my environment.

**Comment by trvrb** [comment]
We've just added an example sequences file to `example_data`. If you start by running
```
cp example_data/sequences.fasta data/
```
you should then be able to run `snakemake -p`. Please try this out. I'll close the issue, but feel free to re-open if there's still a problem.
