### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Arabic

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#214]
We’d like to translate “How to interpret phylogenetic trees” into Arabic. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_ar.md` in branch `background_ar` under the narratives folder: https://github.com/nextstrain/ncov/blob/background_ar/narratives/ncov_trees-background_ar.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_ar/trees-background/ar/

Please add your name to the translators field, so we can credit your work! Also, if you have a professional website that you'd like your name to link to, please add that as well.

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like hackmd (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you all.

@falnaji @SalehA74

**Comment by SalehA74** [comment]
Dear colleagues...
I finished the translation of the Phylogenetics interpretation guide into Arabic. Colud you please Dr Fadi @falnaji contact me here or via Twitter @Ahmadsa96201545 to coordinate with each other. Regards
Dr. Ahmad Saleh

احصل على Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cassiawag** [comment]
This is now live here: https://nextstrain.org/narratives/trees-background/ar.
Links are updated to it in the most recent situation report: https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-03-20 
Thanks @falnaji and @SalehA74!
