### ISSUE TITLE
GISAID EpiCoV fasta download

### ISSUE THREAD

**Issue by t-neumann** [nextstrain/ncov#219]
Hi,

I got my GISAID account and also navigated to the EpiCoV page as instructed, but when I click on download, only a PDF is downloaded and not the actual fasta sequences. Has this moved someplace?

I would be very grateful for any directions (see screenshot).

![image](https://user-images.githubusercontent.com/17272623/77040677-acaae000-69b8-11ea-976e-ea86cc33f5fe.png)

**Comment by rvosa** [comment]
Click on browse (below the radial tree). Then click the database icon at the bottom right of the next page.

**Comment by bassanio** [comment]
@rvosa hi There is no such icon on my page 

![Screenshot 2020-03-19 at 5 40 15 PM](https://user-images.githubusercontent.com/11612433/77074276-0be51080-6a0a-11ea-9f34-77a260e26590.png)

**Comment by bassanio** [comment]
@rvosa  What I was looking for is bulk download of these files. Is there a way to do that Instead
of doing individual download

**Comment by t-neumann** [comment]
@rvosa I also don't have this button. Are you using different browsers? I tried Chrome and Safari, but I none of them shows it.

**Comment by trvrb** [comment]
This seems to be an issue with some users in GISAID where not everyone has this download button. I think you may need to contact GISAID support. See further discussion here: https://github.com/nextstrain/ncov/issues/53.

**Comment by bassanio** [comment]
The issue is solved for me. I thank gisaid developers for this resolve.
