### ISSUE TITLE
going gisaid share data with the global public ?

### ISSUE THREAD

**Issue by pedroelbanquero** [nextstrain/ncov#223]
seems normal people can't register to gisaid

**Comment by rvosa** [comment]
I don't speak on behalf of nextstrain but my understanding of the situation is that GISAID is in somewhat restrictive data sharing agreements with the institutions that upload to them, so they have to control (and want some oversight over) who downloads from them. Nextstrain, in turn, is therefore unable to simply redistribute these data.

Processing times for account applications at GISAID seem to vary quite a bit and may or may not be rejected based on reasons that are unclear to me. This is something that is totally outside of the control of nextstrain, though.
