### ISSUE TITLE
Translate March 20 report into Arabic

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#226]
Hello @falnaji, @hamarsheh, @SalehA74 !
 
The situation report from 2020-03-20 is ready to be translated to Arabic. A branch exists as `sit-rep_ar`  where this can be done, and the file to translate is `ncov_sit-rep_ar_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ar/narratives/ncov_sit-rep_ar_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_ar`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ar/sit-rep/ar/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Arabic-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Arabic; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by SalehA74** [comment]
Dear colleagues.... @falnaji and @hamarsheh  
The Arabic translated copies of both the situation report for March 20 and the Phylogenetics interpretation guide are now ready at the GitHub...Please try to proofread them as soon as possible....let us show the world how enthusiastic are we Palestinisns.

**Comment by cassiawag** [comment]
Very fast work @SalehA74! 

We've discovered that the color of the Canadian sequence on slide 6 seems to be showing up as a different color on different displays. I've updated the English text to eliminate any reference of color. It now says: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle, we see that they have a reported travel history to Europe." Can you please update the Arabic translation accordingly?

**Comment by cassiawag** [comment]
The narrative is published live here: https://nextstrain.org/narratives/ncov/sit-rep/ar/2020-03-20

Thanks for the translation @SalehA74 & @falnaji
