### ISSUE TITLE
Translate March 20 report into Dutch

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#227]
Hello  @roanvanscheppingen, @rvosa, @Van-Doorslaer, @shenii, @pleunipennings,  @JSHuisman, @JiscaH !
 
The situation report from 2020-03-20 is ready to be translated to Dutch. A branch exists as `sit-rep_nl`  where this can be done, and the file to translate is `ncov_sit-rep_nl_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_nl/narratives/ncov_sit-rep_nl_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_nl`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_nl/sit-rep/nl/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Dutch-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Dutch; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@rvosa, @Van-Doorslaer, @shenii, @pleunipennings,  @JSHuisman, since you have significant background in the field, I won’t send it live without a review from one of you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by roanvanscheppingen** [comment]
Goedemorgen iedereen!

Ik ga er nu een half uurtje tot uurtje aan werken in ieder geval. Succes weer iedereen :)

**Comment by roanvanscheppingen** [comment]
Okay. I've done a bit. 
Unfortunately I'm a bit busy arranging my life back in Amsterdam again (while last week I was still hiking the alps) and trying to still graduate in time. 

Last few things are for someone else. Good luck. 
I've kept two things I was not sure of the correct translation. They are there in CAPS. It is about INTERMINGLING, EXECUTIVE SUMMARY, and INTERFERENCES OF TRANSMISSION.

Tag me when it is done and I could check it again 👍

**Comment by JiscaH** [comment]
I'll continue where roan left off, unless someone else is working on translating just now?

**Comment by JiscaH** [comment]
Alright, I've translated the second half. I haven't gone over Roan's bit, so whomever is going next should spell/grammar check the whole document please. 

Following Roan's tactic, I've put terms that I'm not sure how to translate in CAPS: SURVEILLANCE TESTING
SEEDING EVENT

Thank you all, stay safe!

**Comment by rvosa** [comment]
I'll continue.

**Comment by JiscaH** [comment]
I've translated a couple of titles that I forgot earlier, and translated "INTERFERENCES OF TRANSMISSION" as " reconstructie van de besmettingsroutes ". 

I've also updated links to "how to interpret a phylogenetic tree" to the dutch version. 

I'm happy with it as is, @roanvanscheppingen do you want to give it a read-over to double check?

**Comment by cassiawag** [comment]
Ahh @JiscaH, I missed this. I pushed it live here: https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-03-20

@roanvanscheppingen if you have any more edits, please add them as a PR to the master. Amazing work everyone!
