### ISSUE TITLE
Translate March 20 report into French

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#229]
Hello  @meriemelkaroui @Maijin @DanielThedie @Simon-LoriereLab !
 
The situation report from 2020-03-20 is ready to be translated to French. A branch exists as `sit-rep_fr`  where this can be done, and the file to translate is `ncov_sit-rep_fr_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_fr/narratives/ncov_sit-rep_fr_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_fr`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_fr/sit-rep/fr/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your French-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in French; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@Simon-LoriereLab, since you have significant background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by Maijin** [comment]
Great! 

Hackmd is here https://hackmd.io/LL50-sucTImEqFx_fBFJJw but I will personally start tomorrow! 🥱
Instant messaging as usual here - https://webchat.freenode.net/#nextstrain-fr-translation

**Comment by meriemelkaroui** [comment]
@Maijin, @DanielThedie, @Simon-LoriereLab, I am starting to work on the translation on hackmd.

**Comment by Simon-LoriereLab** [comment]
Hi all, the translation can be pushed! Thanks to all!

**Comment by cassiawag** [comment]
And it's now live at: https://nextstrain.org/narratives/ncov/sit-rep/fr/2020-03-20 !

Thanks for the excellent (and per usual speedy) work everyone!
