### ISSUE TITLE
Translate March 20 report into German

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#230]
Hello @astridgall @rneher @nicfel !
 
The situation report from 2020-03-20 is ready to be translated to German. A branch exists as `sit-rep_de`  where this can be done, and the file to translate is `ncov_sit-rep_de_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_de/narratives/ncov_sit-rep_de_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_de`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_de/sit-rep/de/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your German-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in German; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@nicfel, @rneher, since you have significant background in the field, I won’t send it live without a review from one of you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by cassiawag** [comment]
@jenslaufer is going to help out on translations too! Thanks for joining us.

**Comment by cassiawag** [comment]
@Hirthe is joining the German translations team! Thanks for your help!

**Comment by astridgall** [comment]
@Hirthe - I saw you were still working on this translations while I was editing. Let me know when you are done and I'll proofread

**Comment by Hirthe** [comment]
@astridgall I would be done. Sorry and thanks.

**Comment by astridgall** [comment]
Great!

**Comment by cassiawag** [comment]
Excited to announce that this is live: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-20 .

Thanks for that fast translation @Hirthe  and quick proofread @astridgall & @nicfel
