### ISSUE TITLE
Translate March 20 report into Greek

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#231]
Hello @akifoss @codergr !
 
The situation report from 2020-03-20 is ready to be translated to Greek. A branch exists as `sit-rep_el`  where this can be done, and the file to translate is `ncov_sit-rep_el_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_el/narratives/ncov_sit-rep_el_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_el`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_el/sit-rep/el/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Greek-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Greek; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by codergr** [comment]
Thanks @cassiawag , welcome @akifoss . Please check above pull request @akifoss perhaps we can do the edit using github review?

**Comment by cassiawag** [comment]
Fast work @codergr! Thank you!

Please do reviews however you want @akifoss & @codergr. You should both have permission to approve the pull request once it's done. 

We found a bug that needs to be addressed in the text. On slide 6, the text originally said: "Looking at the Canadian sequence in green in the middle..." This color seems to be showing up differently on different displays, so I've revised the English text to be: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle..." Can you update the Greek translation accordingly? Thanks sorry for the extra hassle!

**Comment by codergr** [comment]
Done

**Comment by codergr** [comment]
@cassiawag can you please create an issue for Translate "How to interpret phylogenetic trees" into Greek have some time today can work on it.

**Comment by cassiawag** [comment]
@codergr -- opened!

**Comment by akifoss** [comment]
Hi both and thanks for the welcome :) I have made changes and reviewed the report, you have a go from my side!

**Comment by cassiawag** [comment]
@akifoss -- thank you! I'm putting your full name under Translators if that's okay, and do you want to link to your GitHub or would you prefer a different professional page?

@codergr, do I have a thumbs up to publish from you as well?

**Comment by codergr** [comment]
@cassiawag yup +1 looks good to me

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/el/2020-03-20

Amazing job everyone!! The Nextstrain main page should update in a few minutes with a link to the report, and I'm about to post on Twitter. @codergr, do you have a twitter handle I can tag?

**Comment by akifoss** [comment]
Thanks for the update and happy to see the report online :) 
I am not sure why, but the file that went online is not the same as the one that I corrected.. There are some terms that are not reflecting the english ones (e.g. on the title "genomic" is translated in greek with the meaning of "gene-based"), and other terms that do not correspond to the ones widely used in the greek media (e.g. "case" is translated like "occasion" where it should be a particular word that greek media and medicine uses for this purpose: κρούσμα). Is there any chance to make corrections now? Thanks again!

**Comment by cassiawag** [comment]
Yes, we absolutely can make those corrections. I'm not sure why that happened; I added the file I linked to above. Can you make those edits as PR to master `ncov_sit-rep_el_2020_2020-03-20.md`?

Thanks for being on this.

**Comment by akifoss** [comment]
Thanks a lot @cassiawag ! I can't commit the changes to master, should I make a new branch? I am done with editing :)

**Comment by cassiawag** [comment]
Yes a new branch would be good and then pull-request to master.

**Comment by akifoss** [comment]
It's there: sit-rep_el_update2

**Comment by akifoss** [comment]
Thanks a lot again @cassiawag !! Let me know when it will be updated online so I can share with people back in Greece :)

**Comment by cassiawag** [comment]
I've merged into master here, and in the process of publishing live: https://nextstrain.org/community/narratives/nextstrain/ncov/sit-rep/el/2020-03-20

Can you confirm that this is the correct one @akifoss?

**Comment by akifoss** [comment]
Yes, that's correct.

**Comment by cassiawag** [comment]
Updated here https://nextstrain.org/narratives/ncov/sit-rep/el/2020-03-20 ! Thanks for catching that @akifoss
