### ISSUE TITLE
Translate March 20 report into Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#232]
Hello @hanbin973  @kyobinkang @minkyuxyz, @Bolloknoon !
 
The situation report from 2020-03-20 is ready to be translated to Korean. A branch exists as `sit-rep_ko`  where this can be done, and the file to translate is `ncov_sit-rep_ko_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ko/narratives/ncov_sit-rep_ko_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_ko`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Korean-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Korean; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@kyobinkang, since you have significant background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by hanbin973** [comment]
I finished the first draft and uploaded it. 
Other people can now review the draft.

**Comment by minkyuxyz** [comment]
Thanks! I'll review it today.

**Comment by cassiawag** [comment]
Thanks @hanbin973 & @minkyuxyz!

Two problems with this narrative that are my fault, and I have now addressed:
- I accidentally created a file with the wrong name - `ncov_sit-rep_ko_2020_03-20.md`. I've now moved that file to `ncov_sit-rep_ko_2020-03-20.md`, and the preview link should now work.
- The color of the Canadian sequence on slide 6 seems to be showing up as a different color on different displays. I've updated the English text to eliminate any reference of color. It now says: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle, we see that they have a reported travel history to Europe." Can you please update the Korean translation accordingly?

**Comment by minkyuxyz** [comment]
Done revision. Ready to go.

If you want @KyobinKang to review it, please feel free to do so.

**Comment by cassiawag** [comment]
@KyobinKang -- are you available to get it soon? Otherwise, I will publish.

**Comment by cassiawag** [comment]
I'm going to go ahead and publish this; @KyobinKang, if you have an edits, please add them as a PR.

**Comment by cassiawag** [comment]
And it's now live at: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-03-20

Thank you for the excellent translation -- it's pleasure working with all of you.

**Comment by KyobinKang** [comment]
Sorry, I was busy this weekend because of writing grant proposal :(

All the translation looks great, but only one point: there are two pages with a head title of "Sequence data can cross-check travel histories", but the title is translated in only one page. Could you fix it?

**Comment by cassiawag** [comment]
Thanks for pointing that out! Will fix. Good luck with the grants!
