### ISSUE TITLE
Translate March 20 report into Mandarin

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#233]
Hello @fillorkill @alvinxhan @lxy0107 @fzhang12 !
 
The situation report from 2020-03-20 is ready to be translated to Mandarin. A branch exists as `sit-rep_zh`  where this can be done, and the file to translate is `ncov_sit-rep_zh_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_zh`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Mandarin-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@alvinxhan, since you have significant background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by lxy0107** [comment]
@cassiawag it seems the file https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-20.md does not exist?

And don't worry, I know it's hard to evaluate the translation if you don't know the language... but trust me, it is as accurate as it can get, with our teamwork so far. To reassure you, I have a PhD in evolutionary genetics and I've translated a [book](https://g.co/kgs/GQZVNx) into Chinese. When I read through the translation here I'm really impressed with people's work; there can be minor mistakes in one person's translation, but after proofreading it's all good. It's a great team!

A piece of unrelated news: my post about the Mandarin Nextstrain report last week on Weibo (I ended up posting it with my account and asked my friend in sci. com. to promote it) is seen 1.06 million times, reposted 964 times, has 246 comments and 752 likes as of now! Thanks for making the knowledge seen to Mandarin-speaking people, everyone!

If anyone here is interested in joining Weibo discussion, let me know your Weibo username and I can mention you in my post this week:)

**Comment by alvinxhan** [comment]
Link to the new zh file - https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020_03-20.md - typo with an underscore between 2020 and 03 instead of a dash. 

I agree that the translation is pretty rad, much better than when we first started in January. Happy to help proofread.

**Comment by fillorkill** [comment]
I just pushed a commit with ncov_sit-rep_zh_2020-03-20.md. Working on translations now.

**Comment by lxy0107** [comment]
Can we all agree to use full-width marks, i.e. “。” instead of ".“ , etc, for the Mandarin version? @fillorkill @fzhang12 @alvinxhan 

Also, I realized that the links in the index page need to be changed to link the pages in the corresponding language. If we only translate the text, the links always point to the English page. Maybe this is worth the attention of other translation groups as well @cassiawag ?

**Comment by fillorkill** [comment]
Full translation pushed. Please proofread.
Agree on the punctuation. But @cassiawag could you please confirm if two-byte punctuation marks are handled correctly by the compiler? Coming from a programming background I've seen quite a few times compilers throw exceptions on this.
@lxy0107 Thanks for the Weibo post, I've seen it circulating and was wondering who posted it. Feel free to mention me at derek_fillorkill on Weibo.

**Comment by lxy0107** [comment]
I will read now and push as it goes.

**Comment by lxy0107** [comment]
@cassiawag a problem in the [index](https://nextstrain.org/narratives/ncov/sit-rep/2020-03-20?n=1): there's FAQ in the index but the FAQ page is not in the report.

**Comment by lxy0107** [comment]
@cassiawag possible typo in this [page](https://nextstrain.org/narratives/ncov/sit-rep/2020-03-20?n=6), it should be **blue** Canadian sequence instead of green

**Comment by lxy0107** [comment]
I finished proofreading, everything is good except the links to the 'How to Read Phylogenies' narrative that we are translating. If we publish the how-to page before this report, we can change the link.
Great job @fillorkill !

**Comment by cassiawag** [comment]
You all have gotten **very** good at this!

I'm in the process of publishing the how-to, and then can update the phylo links.

@lxy0107, it's a display error -- it's looking different colors on different monitors, so I've update the English text to say: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle..."
Can you update the translation accordingly?

Also in regards to FAQ in TOC, you're correct! Please update the link to say: Scientific Credit, and you can eliminate the Scientific Credit link below it completely.

**Comment by cassiawag** [comment]
@fillorkill I can confirm that full-width marks work! @fzhang12 tested it out a few weeks ago.

**Comment by cassiawag** [comment]
@lxy0107 -- Didn't realize your background, sorry! Thank you for all doing an AMAZING job. We are so fortunate to have all of you working on these translations.

**Comment by lxy0107** [comment]
> You all have gotten **very** good at this!
> 
> I'm in the process of publishing the how-to, and then can update the phylo links.
> 
> @lxy0107, it's a display error -- it's looking different colors on different monitors, so I've update the English text to say: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle..."
> Can you update the translation accordingly?
> 
> Also in regards to FAQ in TOC, you're correct! Please update the link to say: Scientific Credit, and you can eliminate the Scientific Credit link below it completely.

Done:)

**Comment by lxy0107** [comment]
> @lxy0107 -- I didn't realize your background; I'm sorry! Thank you for all doing an AMAZING job. We are so fortunate to have all of you working on these translations.

No worries:) I've never directly worked with phylogenetics but learned how to read the tree. It's always good to have experts whose work directly is directly related.

**Comment by lxy0107** [comment]
I've finished all my edits, maybe @alvinxhan @fzhang12 want to take another look?
A small comment: the hand-drawn diagram can be a little misleading in this [page](https://nextstrain.org/narratives/ncov/sit-rep/2020-03-20?n=9). Where do the seeding infections on the top and bottom around mid January come from? They should be from the Wuhan population (based on the single origin of the virus), but the drawing makes it look like from elsewhere.
This may not be super important for the point you want to make with the diagram, but to provide some social context, there is ongoing debate in China about the origin of the virus, and many people are looking for evidence that it is originated outside China, to support certain (conspiracy) theories. I think the chance that the diagram get misread is very small, but we might still want to be more careful.

**Comment by cassiawag** [comment]
@lxy0107 -- that social context is super helpful. I'm going to pass this feedback on to the rest of the team. I think it's unlike that we'll want to change anything this week, but we'll be extra mindful of that in future reports.

Ping me when it's ready to publish

**Comment by alvinxhan** [comment]
@lxy0107 and @fillorkill did a stellar job. Proofread the narrative and it is ready to go IMO.

**Comment by cassiawag** [comment]
And it's published here: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-20

Thanks so much all!
