### ISSUE TITLE
Translate March 20 report into Polish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#234]
Hello @aniafijarczyk @balwierz !
 
The situation report from 2020-03-20 is ready to be translated to Polish. A branch exists as `sit-rep_pl`  where this can be done, and the file to translate is `ncov_sit-rep_pl_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_pl/narratives/ncov_sit-rep_pl_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_pl`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pl/sit-rep/pl/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Polish-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Polish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by cassiawag** [comment]
@M-nied7 is going to join the Polish translation team! Feel free to jump in wherever.

**Comment by M-nied7** [comment]
@aniafijarczyk and @balwierz, I had some time today so I translated the slides. I will appreciate it if one of you can go through it and double-check it :) I made some small changes in the first 5 slides that had been translated earlier (typos, smaller grammar issues). However, it is so much easier to miss my own typos and grammar issues...

**Comment by aniafijarczyk** [comment]
great! thanks a lot @M-nied7 I'll have time today to go through it

**Comment by aniafijarczyk** [comment]
Thank you @M-nied7 and @balwierz for translations! I made just a few corrections, looks good and ready for me.

**Comment by cassiawag** [comment]
@balwierz & @aniafijarczyk -- do you have professional links that you'd like to add under `translatorLinks:`. Otherwise, it just goes to a broken auspice page.

**Comment by cassiawag** [comment]
Amazing work everyone! Thank you! I will publish this if if that's okay with @balwierz & @M-nied7?

**Comment by aniafijarczyk** [comment]
links added!

**Comment by M-nied7** [comment]
@cassiawag, yes, everything looks good.

**Comment by cassiawag** [comment]
Woohoo! It's now live here: https://nextstrain.org/narratives/ncov/sit-rep/pl/2020-03-20

I published the "How to interpret phylogenetic trees" first, so this now links to the Polish version of that. Thanks to all!
