### ISSUE TITLE
Translate March 20 report into Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#235]
Hello @dtaliun @frogtraveler @vpuller @irina95511 !
 
The situation report from 2020-03-20 is ready to be translated to Russian. A branch exists as `sit-rep_ru`  where this can be done, and the file to translate is `ncov_sit-rep_ru_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ru/narratives/ncov_sit-rep_ru_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_ru`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ru/sit-rep/ru/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Russian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
I require two sets of eyes on every translation, but only two. Although if you have more, that’s fine too. Please coordinate amongst yourselves on how to best complete the translations. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together. Whatever works best for you. But when finished, please push it to GitHub for proofreading and review.
 
@vpuller, since you have significant background in the field, I won’t send it live without a review from you. This is to ensure we provide accurate information.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! May you and your loved ones stay well.

**Comment by frogtraveler** [comment]
@cassiawag I had a question about line 134: "Looking at the green Canadian sequence in the middle, we see that they have a reported travel history to Europe. "  I don't see "green Canadian sequence", I believe it should be "blue". Also, I'm not sure that the legend for that tree is up-to-date.

**Comment by cassiawag** [comment]
Yes, blue is correct. Thank you!

**Comment by vpuller** [comment]
I have translated the remaining section and proofread the rest. I couldn't however visualize it on the nextstrain - the link doesn't seem to work, it directs to the general narratives page. And when I try to get the Russian  version from there, it is still displayed in English.

**Comment by cassiawag** [comment]
Really fast work @vpuller & @frogtraveler! Thank you very much!

Two errors that are definitely our fault:
- The wrong color above is a some type of bug in auspice -- when we wrote the document the sequence was green, now the sequence seems to blue or yellow depending on what display is used. I've updated the English text to now read: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle..." Can you update the translation accordingly?
- I created the file with a wrong name `ncov_sit-rep_ru_2020_03-20.md` rather than `ncov_sit-rep_ru_2020-03-20.md`. I've updated the file name to be correct and now preview does work.

**Comment by cassiawag** [comment]
Otherwise, it looks great on preview!

**Comment by vpuller** [comment]
I have updated the Canadian sentence.

**Comment by cassiawag** [comment]
And it's now live here: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-03-20

Amazing job @vpuller & @frogtraveler!
