### ISSUE TITLE
Colour on slide 6

### ISSUE THREAD

**Issue by roanvanscheppingen** [nextstrain/ncov#241]
Disclaimer, I am colourblind so not the best reference.

In slide 6 of the new sitrep, the green Canada sequences are named in text. To me, it seems blueish. 

Might be of use to all translators!

**Comment by roanvanscheppingen** [comment]
Also found a pull request stating this. Colours change based on browser.

**Comment by emmahodcroft** [comment]
Sorry about this. It is indeed blue! (Last time I checked, anyway.) This
needs to be corrected in all translations. Sorry! And thanks!

**Comment by cassiawag** [comment]
Yes, I think colors change based on the browser... I've updated the English text to refer to the sequence by name: "Looking at the Canadian sequence (Canada/BC_78548/2020) in the middle..." Thanks for pointing this out @roanvanscheppingen
