### ISSUE TITLE
Problems using next strain/ncov

### ISSUE THREAD

**Issue by JosephLee815** [nextstrain/ncov#243]
Hi sorry to bother you but right now I'm now facing some problems with the code. 

For the data uploaded in GISAID in different time, they were named in different ways. Sequences were named with "Country/XXXXXX/XXXX" previously however they were named with a prefix of "hCov-19/" which made it impossible to match with the sequence in the metadata.tsv (which we could download from nextstrain). I'm wondering if the difference in names would effect the final results and if we want to make some change with fasta file, how can we do that or which program we could use?

Thank you so much for that!

**Comment by tolot27** [comment]
@JosephLee815 Did you try `scripts/normalize_gisaid_fasta.sh`? This script should solve your problems. If not, please report back the exact strain name which causes the problem. Be aware of #212.

**Comment by JosephLee815** [comment]
@tolot27 Thanks so much for your reply. We have already solve the problem with hCov-19 but now facing a new problem. We still have some errors with the tree. There are a few sequences in the metadata file. However they didn't appear on your tree nor your exclude.txt. So how did you remove them from the dataset?

**Comment by tolot27** [comment]
@JosephLee815 Please provide some strain names your are missing on the tree.

**Comment by JosephLee815** [comment]
@tolot27 Sorry for my mistake. It is because we didn't update the new exclude.txt so that we missed some strains in the file. 
Actually we are encountering a confusing problem now. We are using the latest code and metadata file from your git. However we are not using the whole dataset from GISAID. Some strains with exclamatory mark on their website are not considering in our project. Because some of them are not complete or with many gaps in the sequence and they were excluded from our *.fasta file manually. However we couldn't get a same result with your tree for these left strains. 
But when we want to download all the sequences from GISAID, they closed the download-all button and we could not conveniently get the whole dataset now. We are wondering that is it possible to get the complete *.fasta file from your git and we could test if we manage the whole process in a right way? Just asking. 
Thank you very much!!

**Comment by emmahodcroft** [comment]
Hi! I'm glad you've had some success in running the data and I'm sorry you've run into some problems. The Terms of Use Agreement from GISAID prohibit onward sharing of the data, so we are not able to provide you with the data ourselves. However, all data is available through GISAID!

**Comment by JosephLee815** [comment]
@emmahodcroft OK I totally understood. But thank you all the same for your kind reply.

**Comment by trvrb** [comment]
With `metadata.tsv` and `sequences.fasta` available through GISAID.org this issue has been resolved.
