### ISSUE TITLE
Translate "How to interpret phylogenetic trees" into Greek

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#245]
We’d like to translate [“How to interpret phylogenetic trees”](https://nextstrain.org/narratives/trees-background) into Greek. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_el.md` in branch `background_el` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/background_el/narratives/ncov_trees-background_el.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_el/trees-background/el/

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

As always, THANK YOU! It’s an honor to work with you both.

@codergr @akifoss

**Comment by codergr** [comment]
@akifoss ready for review

**Comment by cassiawag** [comment]
@akifoss -- any chance you're available to review this?

**Comment by akifoss** [comment]
@cassiawag yes, of course! This is on my to do list for today/tomorrow :) Sorry for late replies, I have been very busy with work.

**Comment by akifoss** [comment]
Hi @cassiawag  ! I have added a pull request #306 to merge the greek translation of how to interpret a phylogenetic tree. I noticed that the rest of the files in the 'narratives' directory are pulled as well, so let me know if I should proceed differently to make this file available :)

**Comment by cassiawag** [comment]
Hi @akifoss. It looks like your pull request is to merge into `background_el`? I'm seeing all the file changes too; I do think that will cause problems.  I recommend this (although it might be a little git unorthodox):
- Copy the translated file with your edits outside of the github repo on your computer
- Delete your current, local `background_el` branch
- Remake and pull the `background_el` from master
- Copy the translated file back into the narratives folder.
- Add and commit the changes to your local `background_el` branch.
- Then push changes to origin background_el (here on GitHub).

I'm not sure what your git comfort-level is, but I'm happy to give you the specific terminal commands if you need.

**Comment by akifoss** [comment]
@cassiawag  that would be great, because what you suggest seems to be what I have already done before (?) :P

**Comment by cassiawag** [comment]
Commands in order:
- `cp file_original_location file_outside_of_repo`
- from in the ncov repo, `git checkout master`
- `git branch -D background_el`
- `git checkout background_el`
- `git pull origin background el`
- `cp file_from_outside_of_repo location_of_file_in_narratives_folder`
- `git add file_name`
- `git commit -m "Edits to Greek phylo"
- `git push origin background_el`

**Comment by akifoss** [comment]
Thanks a lot @cassiawag ! After deleting my background_el branch, even though I followed the commands that you wrote, I get an error at the commit command. But anyways my background_el branch is up to date with the file edits. Should I rather use hard copy paste on the browser on the relative file straight on the background_el branch?

**Comment by cassiawag** [comment]
Hmm. Yes, go for it. If it doesn't work, we can always roll back -- that is the beauty of git.

**Comment by akifoss** [comment]
Done! Let me know if it worked, the file is committed with the message "Edits to Greek phylo"

**Comment by cassiawag** [comment]
@akifoss -- it looks like it worked, but check the preview link above. I'll merge into master and publish with your approval.

**Comment by akifoss** [comment]
Yes, that's the right file! Thanks @cassiawag ! 
What would be the link to this file (so that I update it in the sit-rep too)?

**Comment by cassiawag** [comment]
As soon as I publish it, it will be: https://nextstrain.org/narratives/trees-background/el

**Comment by cassiawag** [comment]
And it's live! Thank you for the good work @codergr & @akifoss
