### ISSUE TITLE
Update Portuguese Translation

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#25]
This is an issue for updating the Portuguese version of the Situation Report to match the 30 Jan 2020 English version, when possible! Tagging @7glaucio @andersonbrito 

**I have already created a branch `sit-rep_pt` with the new file to be translated: `ncov_sit-rep_pt_2020-01-30.md`**

To make it easier to see what's changed, I've created a 'fake' diff file which shows the changes **only in the text**. You still *must* use the latest `ncov_sit-rep_`(lang)`_2020-01-30.md` file as your basis, because the code parts of the file have changed!

You can view the **text differences** [here](https://github.com/nextstrain/ncov/commit/a01f2622a74dde56e650578fe6ffabb1a05dc610).

Note there are two entirely new slides - these I've put in the diff file *with code* so that you can spot them more easily. You see them in the newer version from line 207. 

Sequence numbers now sometimes followed by `</tag>` - you do not have to this if you don't want - it was just to make it easier for us - in the time it took to update the narrative the number of sequences kept changing so this makes it easier to search and replace! 

There may be multiple people working on this translation. so I recommend committing and pushing often to help avoid the work being done twice! Thank you all for your efforts!

**Comment by andersonbrito** [comment]
Thank you for letting us know, Emma.
I'm working on that now.

*Anderson Brito*

**Comment by andersonbrito** [comment]
@emmahodcroft, I have just pushed a new version of the narrative into **sit-rep_pt** branch.
Please let me know if you can see it.

Your use of </tag> is indeed a good idea. I was wondering if we could use hidden tags to number the start and end point of sections: it would make translations easier (sometimes it's hard to guess which part belongs to which section).

Finally, is there a way to visualize the final .md file, so that we can preview how it would look like?

The nCoV build and narratives are looking great. ✨

**Comment by emmahodcroft** [comment]
Thank you so much! Sorry, it's a bit nuts here and I'm catching up. Will try to get you a preview link asap :)

**Comment by andersonbrito** [comment]
Just now a saw there's more content to translate (I stopped half way through 💢). I'll ping you when it is (actually) finished.

**Comment by emmahodcroft** [comment]
Ok!

**Comment by emmahodcroft** [comment]
So I just took a look at what you have so far, and there's a super weird thing (that's probably a bug on our side) but that stops it from working. In the text that shows up on the left, it seems this cannot finish with a link. So for example when you have the list of links:
![image](https://user-images.githubusercontent.com/14290674/73482008-3cf77c00-439d-11ea-888f-873877278fa6.png)
You currently don't have the date after every link - while I agree that these aren't so important, it turns out that without the last one, the whole thing breaks! 

If it's easier I can just add these in whenever you are done - don't feel you have to figure it out! :) Thanks for the work!

**Comment by andersonbrito** [comment]
@emmahodcroft, the translation is now finished. Please let me know if you encounter any inconsistencies concerning content presence or absence.

**Comment by emmahodcroft** [comment]
@andersonbrito This looks good! Had to fix one minor bug in spacing, but that's all. Check out the preview here and let me know if it looks good!
https://nextstrain.org/community/narratives/nextstrain/ncov/sit-rep/pt/2020-01-30

**Comment by 7glaucio** [comment]
@andersonbrito I'm running late this time. Long day. Are you guys all set or is there something else that I can do to help?

**Comment by emmahodcroft** [comment]
If you could look at the preview link above and let me know if all looks ok, that would be great! Feel free to push changes to the `sit-rep_pt` branch, or let me know here (tag me if possible so I'll see it faster!) if it's all good, and I'll push live :)

(You can preview any changes you make to the branch after pushing, here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pt/sit-rep/pt/2020-01-30)

**Comment by emmahodcroft** [comment]
@andersonbrito 

>Your use of is indeed a good idea. I was wondering if we could use hidden tags to number the start and end point of sections: it would make translations easier (sometimes it's hard to guess which part belongs to which section).

This is a great suggestion! I am working on putting tags of this sort into the next narrative, so this will be easier in future!

**Comment by emmahodcroft** [comment]
@andersonbrito If you have a minute, could you look at the raw version of the 'next' update file on the `sit-rep_update` branch, here: https://github.com/nextstrain/ncov/blob/sit-rep_update/narratives/ncov_sit-rep_2020-01-31.md

I've added commented 'slide break's and also annotated whether the text below goes on the left of the screen, or the right (or, if there is none of the right).

I didn't want to clutter with too much, but are these the kinds of breaks that would be helpful when translating? Thanks again for the idea!

**Comment by 7glaucio** [comment]
@emmahodcroft @andersonbrito We're good to go. I fixed a few errors (an English sentence leftover, and 2 concordance errors), now I think we can publish it.

**Comment by 7glaucio** [comment]
@andersonbrito Let me ask you a silly question, yet useful to clarify for the next reports: How do we know when to use **numerals or number in words**? Just asking because some parts we've been using both, others we are using only one of them (numerals or numbers written). Let's set a guideline for now on.

**Comment by emmahodcroft** [comment]
Fantastic! I will do this now! 
I'll post a link here, and do a tweet on the Nextstrain account, tagging you both. 

Is this a reasonable translation for a tweet?: 
Temos agora disponível em português o nosso último relatório de situação de 30 Jan Nextstrain sobre o surto #nCoV #nCoV2019: <link>

Muito obrigado ao rápido trabalho de <tags>

**Comment by emmahodcroft** [comment]
Here's the live link: https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-01-30

I've tweeted here: https://twitter.com/nextstrain/status/1223247025392713730

I've updated the links on the main Nextstrain page - it'll take a few minutes for the server to run checks and then start serving the latest versions - but should be up soon!

**Comment by emmahodcroft** [comment]
Thank you both so much for your speedy work on this! :)
I will close the issue but you can still add comments to continue any conversation - and it would be great to hear if you think the tags I've added for the next update are the right direction!

**Comment by 7glaucio** [comment]
@emmahodcroft About the tweet: Sounds good to me.

**Comment by andersonbrito** [comment]
> @andersonbrito Let me ask you a silly question, yet useful to clarify for the next reports: How do we know when to use **numerals or number in words**? Just asking because some parts we've been using both, others we are using only one of them (numerals or numbers written). Let's set a guideline for now on.

Thanks for asking, @7glaucio. At least in Portuguese scientific language (and probably English), I usually see numbers below 10 being written as words. But that's more of a convention. As long as we are consistent, that's fine.

This is a good guide for that: http://www.bristol.ac.uk/arts/exercises/grammar/grammar_tutorial/page_33.htm

**Comment by andersonbrito** [comment]
@emmahodcroft, your 'slide break' proposal looks great. To make it event better, I would add slide numbers as well: since the wording content is sometimes very similar, I found myself editing Slide 8 on top of Slide 9 by mistakes. Or when some slides are eventually added, or inverted in order, things can get a bit confusing, for example.

Something like this would solve the issue:
!-- ############ SLIDE BREAK 7 ############# --
!-- This is left-side text 7 --

**Comment by emmahodcroft** [comment]
@andersonbrito Thank you for taking a look! I did consider this, but my concern is that if we add or delete slides during the next update... it's a pain to go through and re-number (I think people just won't do it).

What I can try to do though, is once we've finalized the English version for sure, I can make a version that's 'for translation' and add the numbers then - when I know they won't change! I will try to remember to do this, as I agree it's helpful!

**Comment by 7glaucio** [comment]
> > @andersonbrito Let me ask you a silly question, yet useful to clarify for the next reports: How do we know when to use **numerals or number in words**? Just asking because some parts we've been using both, others we are using only one of them (numerals or numbers written). Let's set a guideline for now on.
> 
> Thanks for asking, @7glaucio. At least in Portuguese scientific language (and probably English), I usually see numbers below 10 being written as words. But that's more of a convention. As long as we are consistent, that's fine.
> 
> This is a good guide for that: http://www.bristol.ac.uk/arts/exercises/grammar/grammar_tutorial/page_33.htm

I see! I get it now. I didn't know that, thanks for the lesson. For now on we're in the same page.
