### ISSUE TITLE
Update text in French translation

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#258]
@meriemelkaroui @DanielThedie @Maijin @Simon-LoriereLab 

An astute reader pointed out a potential error in the March 20 French translation on slide 9: 

"Le COVID-19 à Wuhan est passé d'un cas index en ~ novembre 2019 à plusieurs milliers de cas à la mi-janvier 2020, passant ainsi de l'introduction initiale à une transmission locale généralisée en environ 10 semaines. Nous pensons que les événements d'introduction internationaux ont commencé à se produire à la mi-janvier. Nous avons donc un délai critique de ~ 10 semaines à partir de la fin de mars pour contenir ces épidémies naissantes avant qu'elles ne deviennent importantes." - Trevor Bedford, Feb 2020

I wonder if there is not an error in the March 20 report. We therefore have a critical timeframe of ~ 10 weeks from the end of March to contain these emerging epidemics before they become significant. wouldn't it be from the end of January?"

Is this correct? If so, can someone please make a PR  to address this. 

Thanks very much! We couldn't do this without you.

**Comment by Simon-LoriereLab** [comment]
Indeed there is an error. it should read: "...~10 semaines de là à la fin mars pour contenir..."
Will try to correct the text shortly

**Comment by cassiawag** [comment]
Thanks @Simon-LoriereLab! That was fast.
