### ISSUE TITLE
Translate March 20 report into Turkish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#261]
Hello @zeynephrc !
 
The situation report from 2020-03-20 is ready to be translated to Turkish. A branch exists as `sit-rep_tr`  where this can be done, and the file to translate is `ncov_sit-rep_tr_2020-03-20.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_tr/narratives/ncov_sit-rep_tr_2020-03-20.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation! You should have access to push to the `sit-rep_tr`, so there’s no need to create a pull request.
 
Note that this file is in Markdown. In general, it is important **not** to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_tr/sit-rep/tr/2020-03-20
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Turkish-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Turkish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Because Nextstrain team members only speak so many languages, this is our best system for doing so. Thanks for understanding.
 
Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.

**Comment by cassiawag** [comment]
@oyku-gencay will also be joining on this translation. @zeynephrc, please coordinate together on how to best move forward. Excited to have you both!

**Comment by zeynephrc** [comment]
Sure, thanks!

**Comment by zeynephrc** [comment]
Hello @cassiawag !
I've finished the translation for March 20 report and now still working on that during some extra time before the March 27 report. 
When will the March 20 report be published in Turkish?

**Comment by cassiawag** [comment]
Thanks @zeynephrc! I need to get a proofread on this before publication. It's our policy for all translations, and I'd also like to have it read by someone with a background in the field. 

@oyku-gencay, can you please proofread?

**Comment by erenada** [comment]
Hi all,

Thanks for translating the report @zeynephrc and @oyku-gencay it looks great! 

I will be proof-reading the report if @oyku-gencay hasn't started yet.

**Comment by zeynephrc** [comment]
Hello @erenada ,

It would be great if you can proofread the report. In the meantime, I can start working on the March 27 translation.
Thanks!

**Comment by erenada** [comment]
Hi @zeynephrc,

Thanks for your efforts in translating this. It looked great. I made some major but mostly minor changes in translation structure, grammar, and the technical language to eliminate/minimize the differences in some concepts. Good job!

**Comment by zeynephrc** [comment]
Hi @erenada 

I just checked it. It looks awesome! Thank you for all the things you've done.

**Comment by erenada** [comment]
> Hi @erenada
> 
> I just checked it. It looks awesome! Thank you for all the things you've done.

@zeynephrc, one more thing before this gets ready for the publication: I think we should provide only one link for the "translatorLinks" section. This way .rmd file doesn't conflict with other versions.

**Comment by zeynephrc** [comment]
@erenada, sure! I attached two links in the previous report since I was the only translator working on that at that time. I didn't know that .rmd file may conflict with other versions.
But for now, one link would be optimal.
Thanks for letting me know!

By the way, should we divide the sections for translating the March 27 report in order to finish up quickly?

**Comment by cassiawag** [comment]
Amazing work @zeynephrc & @erenada! I'm working to get this published asap. 

You can only have one link per translator; otherwise, the display breaks. @zeynephrc, do you want your LinkedIn or your Twitter?

**Comment by zeynephrc** [comment]
Hello @cassiawag,
Sorry, I forgot to delete my LinkedIn link in the report. I deleted it.

**Comment by cassiawag** [comment]
I noticed in my preview review that some text on slide 12 in the header isn't translated. Can someone do translate that quickly? Maybe @zeynephrc? Otherwise, it looks great.

**Comment by zeynephrc** [comment]
@cassiawag I translated it. Thanks for letting me know.

**Comment by cassiawag** [comment]
Super! Thanks for all the hard work! I'm going to publish this at the same time as the March 27 report.

**Comment by cassiawag** [comment]
Here's the published version: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-03-20
