### ISSUE TITLE
[BUG] author and title are missing in metadata.tsv

### ISSUE THREAD

**Issue by pwrose** [nextstrain/ncov#263]
**Current Behavior**  
A clear and concise description of what is happening / what the bug is.  

**Expected behavior**  
A clear and concise description of what you expected to happen instead.  

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open / run ...  
2.   
3.  

**Possible solution**  
(optional)  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   
 - Browser:  
 - Version (e.g. `auspice 2.7.0`):  

**Additional context**

**Comment by trvrb** [comment]
Cleaner `metadata.tsv` file produced by `ncov-ingest` and made available through GISAID.org should have resolved this issue.
