### ISSUE TITLE
[Feature request] About link from a older reports to the latest report.

### ISSUE THREAD

**Issue by tomoyuki-nezu** [nextstrain/ncov#269]
**Context**  
It is useful if all older versions of the report have a link to the latest version or a link to the report summary page.

**Description**   
When a weekly report is published in each language, it will be posted to SNS with a link to report. As the post continues to remain on SNS. Then, past weekly reports are still re-RT today.

When SNS user look at old reports, that have no link to the latest reports. SNS user need to return to the top page once or re-write URL in the browser navigation text box, but it is unknown how many people are doing that action and reached the latest version.

I think it will be easier to navigate if there is a link to the latest version in the old report or a link to the list of the all reports. Of course, the subjects in each report are different, but some data exist only in the latest version. How can it be easier to navigate?

**Comment by tomoyuki-nezu** [comment]
It might be easiest to add navigation links to the page template.

**Comment by emmahodcroft** [comment]
I would agree, this would be a very useful feature. One thing we've discussed is if there could be a drop-down menu alongside the 'language selector' drop-down which allows you to pick older/newer situation reports. Would something like this work, or do you think there are even better implementations? We'd like to people to more easily be able to access our whole archive of situation reports!

**Comment by Maijin** [comment]
The current language selector is too hidden imho so I wouldn't put it there.

With all the translations now there is probably a more important update to the main page to be done I think to make 👍

**Comment by jameshadfield** [comment]
👍 

These features should be implemented in the nextstrain.org repo so that they are available for all narratives, not just ncov. As a related example, the nextstrain.org repo contains [the code for the language dropdown](https://github.com/nextstrain/nextstrain.org/blob/master/auspice-client/customisations/navbar.js#L133) which is injected into auspice [at build time](https://github.com/nextstrain/nextstrain.org/blob/master/build.sh#L45).

**Comment by tomoyuki-nezu** [comment]
Ultimately, it may be useful to be able to select another weekly report from the one report people are viewing. On the other hand, weekly reports are increasing, and I think that summary pages are becoming necessary (as @emmahodcroft says).

After the summary page is created, if the report page has a link to the summary page, the first step will be cleared.

**Comment by trvrb** [comment]
I believe this issue has been superseded by work on `nextstrain.org` to provide a reports directory in `/sars-cov-2`. I'm closing this now.
