### ISSUE TITLE
it's possible to zoom the Tree?

### ISSUE THREAD

**Issue by lollerollo** [nextstrain/ncov#272]
Hi, first of all Many Thanks for this great Site.

I was trying to zoom the Tree to see more in detail some parts,
but I wasn't able to find a way more then "Chrome Zoom"

is there any way to do it or could it been implemented?

Newly Many, many thanks!!!!

**Comment by jameshadfield** [comment]
Hi @lollerollo -- if you click on a branch in the tree then you'll zoom into the clade defined by that branch 😄 You can get back to the entire tree by then clicking on "reset zoom" (top right of tree) and we're adding some more functionality to improve zooming out in the coming days (https://github.com/nextstrain/auspice/pull/1001)
