### ISSUE TITLE
Add accents to March 20 report (Spanish)

### ISSUE THREAD

**Issue by aabrego-sfdc** [nextstrain/ncov#277]
I really appreciate the work done to make these reports available in multiple languages, specially in Spanish. (See #236). I noticed that in some instances of the [March 20 report (Spanish)](https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep_es_2020-03-20.md) the accent marks are missing. For example:

[Contenidos](https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep_es_2020-03-20.md#contenidos)

- Como los brotes de una epimedia crecen  [...] -> C**ó**mo los brotes de una epimedia crecen [...] 
- Este informe analiza 723 genomas [...] ->  **É**ste informe analiza 723 genomas [...] 
- Esto ultimo solo puede lograrse [...] ->  Esto **ú**ltimo solo puede lograrse [...] 

I would like to review the [March 20 report (Spanish)](https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep_es_2020-03-20.md) again and add the missing accent marks. Also I would be interested on proofreading and/or help with the translation to Spanish of upcoming reports (See #275). @cassiawag 

Thanks for doing this project!

**Comment by cassiawag** [comment]
Thank you @aabrego-sfdc! 

@miparedes, can you review this?

**Comment by cassiawag** [comment]
Sorry @aabrego-sfdc, in the craziness of it all I thought this was a PR with accent marks, even though it's very clearly under Issues. My bad! I hope you'll forgive me.

I really appreciate your offer to help with translations. I think we're okay for now on more Spanish proofreaders/translators for upcoming reports. I'll add you to our list of backups though! 

In regards to the accent marks on the March 20 report, if you'd like to submit a PR with edits, we'd definitely welcome it.

**Comment by aabrego-sfdc** [comment]
Sounds good, thanks for giving me a chance to contribute. 😃 For the accent marks on the March 20 report should I create a PR against `master` or any other branch?

**Comment by cassiawag** [comment]
Against `master` would be great. Thank you!
