### ISSUE TITLE
[BUG] Please change the tree root to RaTG13

### ISSUE THREAD

**Issue by shenweima** [nextstrain/ncov#280]
![WechatIMG9697](https://user-images.githubusercontent.com/8536868/77830044-b2df5000-7160-11ea-96c6-1766f5a1fc8f.jpeg)

**Comment by trvrb** [comment]
Thanks for the suggestion. However, we've investigated this strategy and have found that RaTG13 is too divergent to reliably root the SARS-CoV-2 tree.
