### ISSUE TITLE
Translate March 27 report to Spanish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#281]
Hello @miparedes @doyarzun00 @Chjulian  @Cholokiwi !
 
The situation report from 2020-03-27 is ready to be translated to Spanish. A branch exists as `sit-rep_es`  where this can be done, and the file to translate is `ncov_sit-rep_es_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_es/narratives/ncov_sit-rep_es_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_es/sit-rep/es/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Spanish-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Spanish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by cassiawag** [comment]
Also, I'd like to welcome @doyarzun00 to the Spanish team this week! We're glad to have you.

**Comment by doyarzun00** [comment]
Hello there team, are we editing directly here or in hackmd?

**Comment by miparedes** [comment]
Hey @doyarzun00 welcome to the team! We’ve been mostly splitting up the work amongst ourselves and then pushing the translation for people to proofread but I’m more than happy to try hackmd if you prefer. I can split the translations this weekend with you if you’d like; I can translate the second half if you want to do the first half up to “central/south America)

**Comment by doyarzun00** [comment]
Hi @miparedes no worries, just did it in the file itself, not hackmd. 

I went all the way the first half, just before central/south america. I can have a look again tomorrow Sunday night (UK time).

saludos, D

**Comment by Cholokiwi** [comment]
Hi all,
I'm happy to proof read all the document. I'll start now with the first
part @doyarzun00 <https://github.com/doyarzun00> (nice job in doing it this
fast!).
Cheers,

Roy

**Comment by doyarzun00** [comment]
Great, then @miparedes can do the second half (if that's ok). Let me know I
should have another look tomorrow night

**Comment by Cholokiwi** [comment]
Hi all,

@cassiawag quick question, the "How to read a phylogeny." narrative is referenced twice, left and right, in the same slide (https://nextstrain.org/narratives/ncov/sit-rep/2020-03-27?n=2). Was this on purpose?

@miparedes how are you going? Except for an issue with the markdown, I just finished proofreading the first part. I'm going to bed now so could have a look again in 7 hours :)

Cheers,

Roy

**Comment by cassiawag** [comment]
@Cholokiwi: It was! It may seem a little over the top,  but it's pretty important if readers don't know how to read trees, and on mobile view, only left side text is shown.

**Comment by miparedes** [comment]
@Cholokiwi, I just pushed the completed draft for your proofreading! Thanks for the good work everyone!

**Comment by Cholokiwi** [comment]
Hi all,

I've done the proofreading and in terms of translation it's good to go. Well done!

@cassiawag here's still problem with the live preview which is not showing the first slide (TOC and the executive summary). Could you please have a look? 

@doyarzun00 for the next time, could you please check that preview works ok when making changes? Markdown language is easy to break but not so easy to fix. Thanks!

Cheers and well done again to everyone!

Roy

**Comment by doyarzun00** [comment]
@Cholowiki no problem, understood. Even a space can make a big difference
in MD!
Thanks everybody
Diego

**Comment by cassiawag** [comment]
And preview's back. The culprit was a misplaced period. Publishing this now.

**Comment by cassiawag** [comment]
We're live here: https://nextstrain.org/narratives/ncov/sit-rep/es/2020-03-27

Amazing job, team! Thanks for the hard work.
