### ISSUE TITLE
Translate March 27 report to Russian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#282]
Hello @dtaliun @frogtraveler @vpuller @irina95511 !
 
The situation report from 2020-03-27 is ready to be translated to Russian. A branch exists as `sit-rep_ru`  where this can be done, and the file to translate is `ncov_sit-rep_ru_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ru/narratives/ncov_sit-rep_ru_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ru/sit-rep/ru/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Russian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Russian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by frogtraveler** [comment]
I've started translating "Note on Sampling"

**Comment by frogtraveler** [comment]
@dtaliun let's coordinate. I think I just lost all my changes I made. Should we notify each other before commit?

**Comment by dtaliun** [comment]
> @dtaliun let's coordinate. I think I just lost all my changes I made. Should we notify each other before commit?

Sorry for this. This is strange, because we were working on a different sections which don't overlap. I will let you know before I am ready to commit next time.

**Comment by frogtraveler** [comment]
No worries, I think I'm still figuring it out. So, I've just committed. If you are editing right now when you will try to commit it will tell you that there was a commit before you've started working on your version. Do you know how to merge it so that both parts are there? I believe what happened before: I had the sampling part translating and your version didn't have the translation- so it returned the sampling part to a not-translated state.

**Comment by frogtraveler** [comment]
I've tried installing hackmd. I made a group, but I can't add members. Do GitHub users need to install hackmd before I can add them?

**Comment by dtaliun** [comment]
> No worries, I think I'm still figuring it out. So, I've just committed. If you are editing right now when you will try to commit it will tell you that there was a commit before you've started working on your version. Do you know how to merge it so that both parts are there? I believe what happened before: I had the sampling part translating and your version didn't have the translation- so it returned the sampling part to a not-translated state.

One workaround I found is to open "See what changed" in a new tab and copy your changes into my version before committing.

**Comment by frogtraveler** [comment]
Ok, that works. I've started working on "Continued spread across borders in the last 3-5 weeks"

**Comment by frogtraveler** [comment]
@dtaliun I'm going to start "Transmission across the U.S. is complex and not well-understood"

**Comment by frogtraveler** [comment]
Started "Multiple transmission chains circulating in Washington state"

**Comment by frogtraveler** [comment]
Started "Likely two local transmission chains in California"

**Comment by frogtraveler** [comment]
Started "Primarily travel-related cases sampled in South America"

**Comment by frogtraveler** [comment]
Started "Export of COVID-19 from Iran"

**Comment by frogtraveler** [comment]
Doing Takeaways

**Comment by frogtraveler** [comment]
I'm going to take a break. Left: Africa, Oceania, and Iceland + Scientific credit.

**Comment by dtaliun** [comment]
> I'm going to take a break. Left: Africa, Oceania, and Iceland + Scientific credit.

I will finish what is left

**Comment by dtaliun** [comment]
Finished remaining sections

**Comment by frogtraveler** [comment]
@irina95511 you are the best at grammar, could you please look through? :)

**Comment by irina95511** [comment]
@frogtraveler sure, i am happy to walk through right now

**Comment by irina95511** [comment]
@frogtraveler and @dtaliun great and super fast translation! I've checked typos and grammar, but, in fact, haven't done much, the text was correct and very clear! 

Probably, only one question that I had was about an alternative term for SARS-CoV-2. Is it **h**Cov-19 or **n**Cov-19?
@cassiawag

**Comment by cassiawag** [comment]
hCov-19 for human coronavirus

**Comment by irina95511** [comment]
thanks @cassiawag, I've just made the last correction on hCov-19.
all look good to me

**Comment by cassiawag** [comment]
@frogtraveler, @dtaliun -- I'll publish when I've got your go ahead.

**Comment by dtaliun** [comment]
> @frogtraveler, @dtaliun -- I'll publish when I've got your go ahead.

Looks good

**Comment by frogtraveler** [comment]
@cassiawag Looks good to me! Thank you! 
when you post, could you pls tweet at @varvarakozyreva- I'll spread the word

**Comment by cassiawag** [comment]
It's published here: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-03-27

Thank you all! Hope you had a safe and restful weekend.
