### ISSUE TITLE
Translate March 27 report to Portuguese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#283]
Hello @EricaBarroso @TNNeto @7glaucio @andersonbrito !
 
The situation report from 2020-03-27 is ready to be translated to Portuguese. A branch exists as `sit-rep_pt`  where this can be done, and the file to translate is `ncov_sit-rep_pt_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_pt/narratives/ncov_sit-rep_pt_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pt/sit-rep/pt/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Portuguese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Portuguese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by cassiawag** [comment]
I'd especially like to welcome @TNNeto and @EricaBarroso to GitHub this week! I now @7glaucio & @andersonbrito might be a bit busy this week, perhaps you can all coordinate how to best complete the translation?

**Comment by TNNeto** [comment]
Hi Cassia

I've tried to upload the translated file to GitHub - not being a regular
user of it, and finding the entire interface/procedures a bit of a
horrendous mess, I forked out the file to edit, but couldn't find a way to
push it to someone else.

I'm attaching it just in case. I've compared it with the original MD file
and looked good in my end, but I was unable to live preview it due to the
aforementioned.

Kind regards,

- Tiago

**Comment by cassiawag** [comment]
@TNNeto -- Thanks for the translation! Yeah, GitHub can be a bit confusing if you're not used to it :( Unfortunately, you can't attach files to GitHub messages. Why don't you email me the file? I can then put it up. To avoid GitHub messes in future, I would recommend, editing online at the link shared to avoid the GitHub messes.

**Comment by cassiawag** [comment]
I've pushed @Tiago's translation. Thanks so much for it. @andersonbrito or @EricaBarroso, are either of you able to proofread?

**Comment by cassiawag** [comment]
I've just pushed @EricaBarroso's partial edits. Thank you so much for them! Are you finished reviewing the translation? 

@andersonbrito, want to take a look? I'd love to get this published :)

**Comment by cassiawag** [comment]
@TNNeto, @EricaBarroso, and @7glaucio -- It sounds like it's a little bit challenging working with both Brazilian & European Portuguese. Since I don't speak Portuguese, I'm not sure how challenging this is. But I really appreciate you all working on this, and I'm very open to re-thinking the Portuguese translation workflow so that it works well for all.

**Comment by 7glaucio** [comment]
I had some computer issues lately, but I'm available now for the next report. Who speaks European Portuguese? I think (since it's extremely similar except for a few words or expressions) we should keep doing it as one version for both, because it's understandable. A portuguese could translate and the Brazilian proofread to check whether there are any expressions we don't understand, and vice versa. I think we can establish a version that works for both.

**Comment by 7glaucio** [comment]
@cassiawag I just proofread this one. You can publish. Nothing in particular to point out

**Comment by cassiawag** [comment]
Thanks @7glaucio!!
