### ISSUE TITLE
Translate March 27 report to Dutch

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#285]
Hello @roanvanscheppingen @rvosa @shenii  @JSHuisman @JiscaH !
 
The situation report from 2020-03-27 is ready to be translated to Dutch. A branch exists as `sit-rep_nl`  where this can be done, and the file to translate is `ncov_sit-rep_nl_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_nl/narratives/ncov_sit-rep_nl_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_nl/sit-rep/nl/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Dutch-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Dutch; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by JiscaH** [comment]
I won't have time til the end of the afternoon, so it would be great if someone else could have a go, or make a start!

**Comment by roanvanscheppingen** [comment]
Give me an hour to start up. Sleep deprived and should get the coffee
running :)

Op zo 29 mrt. 2020 08:11 schreef JiscaH <notifications@github.com>:

**Comment by JiscaH** [comment]
Wasn't meant as a whip! Just a notification :) 

Coffee is essential.

**Comment by roanvanscheppingen** [comment]
Haha, no worries about that whip! 

I'll use this post to update or point to things I am not sure about.
Slide 5 (Iceland) EXPOSURE HISTORY --> how to translate
In general: Updates for --> translated to 'updates over' and not to 'updates van(uit)'. 
Slide 7 WELL UNDERSTOOD --> onduidelijk? 

Row 175, Additional data (I'm lost at this point...)

I've pushed it for now, and will be offline to organize my personal life for a bit :) Good luck for the next one picking things up!

**Comment by JiscaH** [comment]
I've spell-checked @roanvanscheppingen 's bit, and translated a few extra slides. 

I've translated 'Exposure history' as 'blootstellingsgeschiedenis' (is dat 1 woord?), en 'not well-understood' als 'slecht begrepen'. 

Good luck to the next one! Besides translating the last few slides, the whole rapport also still needs an expert-check

**Comment by roanvanscheppingen** [comment]
I'll take it from here for a minute or 20. How are the others in their time? I could contribute again tomorrow afternoon, the earliest (after this run)

**Comment by JiscaH** [comment]
Allright! @rvosa @shenii @JSHuisman  could either of you please read it through, to make sure all technical terms are translated correctly, and we didn't inadvertently change the meaning anywhere? Thanks!

**Comment by JSHuisman** [comment]
I could take a look in the afternoon (around 13 o'clock, or after 15 o'clock) - but if others have time earlier, please go ahead.

**Comment by JSHuisman** [comment]
Ok, will go through it now

**Comment by JSHuisman** [comment]
Finished going through ("expert review") - think it's ready to be uploaded.

**Comment by cassiawag** [comment]
Amazing! Thanks for the collaborative effort all. I'll work on getting this published.

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-03-27

Thank you for another excellent translation!
