### ISSUE TITLE
Translate March 27 report to Italian

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#286]
Hello @al-epo @sarameiqi  @whispererindarkness @aliceLedda !
 
The situation report from 2020-03-27 is ready to be translated to Italian. A branch exists as `sit-rep_it`  where this can be done, and the file to translate is `ncov_sit-rep_it_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_it/narratives/ncov_sit-rep_it_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_it/sit-rep/it/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Italian-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Italian; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by aliceLedda** [comment]
@whispererindarkness <https://github.com/whispererindarkness>,@sarameiqi
<https://github.com/sarameiqi>,@al-epo <https://github.com/al-epo>,
Come ci organizziamo?
Ci dividiamo i capitoli e io poi rileggiamo tutto tutti?
Io ci sono soprattutto ora di pranzo e notte UK time!
Buon lavoro a tutti!
Alice

**Comment by sarameiqi** [comment]
Ciao a tutti,
per me possiamo dividerci il testo; poi ciascuno si rilegge tutto direttamente dalla preview (gli errori si notano meglio). 
Farei:
1. chi ha meno tempo può curare le parti poco impegnative e quelle che rimangono quasi uguali alle traduzioni precedenti (sommario, nota sulla raccolta campioni, cosa puoi fare, ringraziamenti etc)
2. proporrei ad @aliceLedda di fare la parte sugli Stati Uniti che ho visto già "intermigled" e significa che è più tecnica - su queste parti è già stata preziosissima in passato
3. uno può fare Europa e Asia
4. un altro può fare America del Sud e Oceania
Chiaramente è un'ipotesi di divisione così a occhio, se pensiamo di dividerlo diversamente va bene uguale!!
Che ne dite?

Io penso di poter dedicare parecchio tempo domenica, invece lunedì potrò riprendere questa traduzione solo dopo cena.

**Comment by aliceLedda** [comment]
Ok, deal!
Io inizio dagli Stati Uniti! Poi se serve vado avanti... Pero' lo faccio
domani se riesco mattina sennò primo pomeriggio.
Buona notte!
Alice

**Comment by al-epo** [comment]
Buongiorno!
Posso iniziare dal punto 4. nella lista di @sarameiqi  e se incontro difficoltà su alcuni termini tecnici  vi chiedo aiuto. ( @aliceLedda ) .
Posso lavorare da ora fino verso le 12 UK time e credo anche in serata. 
In caso posso ritagliare un po’ di tempo anche lunedì. 

Buon lavoro!

Alessia

**Comment by sarameiqi** [comment]
Ok, allora io faccio il 3, ci lavoro dalle 12 in poi (teniamo sempre UK time).
Magari appena finiamo ci mandiamo un messaggio qui così non ci sovrapponiamo, ok?
Buon lavoro!
Sara

**Comment by al-epo** [comment]
Ho finito ora Oceania e America del Sud.  
Faccio una pausa, rileggo e magari faccio l'Africa? 
Ho una "lista" di parole che potrebbero essere ambigue nella traduzione e forse @aliceLedda  le ha già discusse, ma non riesco a ritrovare dove. Magari alle 12 le posto così possiamo controllarle insieme? 

A dopo!

**Comment by aliceLedda** [comment]
Vai tu posta o segnala le frasi che ti dico come le vedo!
Alice

**Comment by sarameiqi** [comment]
Ok!
Intanto io aggiungo la traduzione dell'Europa e Islanda. Hai ragione Alessia, mi è sfuggita l'Africa, se ti va falla pure! ;)

Tra le raccomandazioni, da parte mia vi chiederei di usare la maiuscola per indicare Paesi o Stati quando indicano entità nazionali, e usare la minuscola per i nomi dei mesi (anche se forse non ci sono).

**Comment by sarameiqi** [comment]
Io ho finito la mia parte.
Se vi serve una mano per tradurre qualche altra cosa fatemi sapere!
A presto,
Sara

**Comment by al-epo** [comment]
Fatto l'Africa! 
La mia lista di "parole difficili"
- sampling : la traduzione  come campionamento non mi piace e mi sembra avessimo già discusso come non fosse sempre appropriata. Ho tradotto con "raccolta dati" che ne pensate?
- evidence / show evidence: la traduzione con evidenze mi sembra un po tecnica  in italiano. Meglio prove/ provano / mostrano prove ? 
- Sampled:  di nuovo " campionati " non mi convince come traduzione. Cosa mettereste ? per ora ho tradotto come Casi osservati/ misurati
- patterns in  patterns are starting to emerge: stanno iniziando a emergere schemi/ motivi  ? 
- phylogeny  ho tradotto  con filogenetica, ok? 

Grazie mille!

**Comment by sarameiqi** [comment]
Per "evidence-show evidence" usiamo "provare, mostrare, dimostrare" a seconda dei contesti (queste parole in italiano sono tutte un po' diverse). "There is evidence" lo tradurrei sempre con "ci sono prove".

Mi pare che per sampling avevamo detto "raccogliere campioni";
sampled "campioni raccolti" o casi, a seconda del sostantivo che va insieme a sampled;
invece "sample" lo traducevamo con "sequenze".

Phylogeny, mi sa che @aliceLedda l'altra volta aveva suggerito di tradurlo come "albero filogenetico", ma non sono certa al 100%.

Se per voi è ok, io inizio la revisione dei testi tradotti direttamente dalla preview, e vi scrivo i dubbi che mi vengono.

**Comment by whispererindarkness** [comment]
Ciao, arrivo un po' in ritardo. Posso occuparmi di rivedere e tradurre i paragrafi più simili allo scorso report:

- Covid19 resources
- A note on sampling
- What you can do
- Scientific credit

Ho un paio d'ore a disposizione dalle 16 alle 18 UK time.

**Comment by aliceLedda** [comment]
Si mi sa che sono d'accordo su quasi tutto!
There's evidence a volte può essere tradotto come sembra (anche se, sono
d'accordo, e' meno forte) oppure i dati suggeriscono che, dai dati sembra
che. Ci sono prove mi sembra troppo forte al momento, perché alla fine sono
solo inferenze basate sui dati (ah anche basandosi sui dati si può
concludere che e' traduzione accettabile)
Sampling si e' raccogliere campioni (immagino che anche raccogliere dati
possa funzionare)
Sample lo stavamo traducendo con sequenze però anche dati e casi a volte
potrebbe funzionare.
Phylogeny e' albero filogenetico e clade e' ramo, e root e' radice.
Patterns ci sto pensando...
Io metto a nanna la bimba e traduco la mia parte!
Alice

**Comment by sarameiqi** [comment]
Ok, grazie mille!!
@al-epo ti va bene se ti faccio un post con tutte le mie osservazioni sulla tua parte (così poi le discutiamo qui e ciascuno si modifica direttamente la propria parte (così evitiamo sovrapposizioni e correzioni incrociate...)?

Fammi sapere!
Sara

**Comment by al-epo** [comment]
@sarameiqi  perfetto! 
I traduttori francesi mi hanno suggerito di usare hackmd. Può gestire modifiche in tempo reale da parte di piu utenti. Magari lo potremmo provare anche noi. Intanto cerco di capire come funziona...

**Comment by whispererindarkness** [comment]
@al-epo, @aliceLedda, @sarameiqi: ho terminato con le mie sezioni, non ci sono variazioni significative nel testo originale, ma se volete dare un'occhiata ne sarei felice.

Ho un solo dubbio: nella sezione relativa alla raccolta dei campioni, si parla di "sequences from viral isolates", che per il momento ho tradotto come "sequenze". Tuttavia l'espressione è diversa rispetto allo scorso report, e penso meriti la traduzione di una persona più esperta di me in questo campo.

**Comment by aliceLedda** [comment]
Sequenze (estratte) da campioni virali?
Scusate sono in ritardo con tutto oggi...
Alice

**Comment by sarameiqi** [comment]
@aliceLedda tranquilla, sono giorni incasinati!!
Se hai bisogno di una mano con la traduzione facci sapere! =)

**Comment by sarameiqi** [comment]
@al-epo ho provato a segnare qualche "errore" ma passarcele qua in chat è un mezzo casino...vogliamo fare che tu leggi la mia parte e la correggi e io faccio altrettanto con la tua? Solo correzioni di cui siamo certe, le cose più "complesse/dubbie/non sono sicura se questa frase è scritta bene" le facciamo in un secondo momento..?

**Comment by al-epo** [comment]
@sarameiqi  va bene! Come facciamo ad evitare che ci sovrapponiamo? 
Ci dovrebbe essere un modo per fare un merge delle modifiche fatte da diversi utenti, ma io ancora non l'ho trovato. Voi?

**Comment by sarameiqi** [comment]
Allora, possiamo lavorare direttamente sui commit, non sul file originale.
Tu prendi il mio e mi aggiungi i commenti, poi io rivedo i vari commenti e li integro direttamente nella mia parte. Se non ci troviamo d'accordo, possiamo discutere senza modificare mille volte.
Che ne pensi?

**Comment by al-epo** [comment]
ok! nn mi è arrivata nessuna email per ora, a volte mi arrivano con un certo ritardo. 
Ora leggo i tuoi commenti poi guardo la tua parte :-)

**Comment by al-epo** [comment]
@sarameiqi  Concordo con tutti i tuoi commenti !

**Comment by al-epo** [comment]
@sarameiqi  ho aggiunto i miei commenti alla tua parte sull'Europa e l'Islanda. ;-)

**Comment by al-epo** [comment]
@sarameiqi  ho commentato anche la parte sull'Asia. Dimmi che ne pensi

**Comment by aliceLedda** [comment]
Non trovo i vostri commenti.
Ho modificato una frase  sull'Europa


Si puo notare che alcuni piccoli gruppi sono caratterizzati dalla
provenienza dallo stesso Stato, ma molte sequenze provenienti da stati
diversi sono in realta' molto mescolate sull'albero.

E map secondo me e' meglio tradurlo con cartina, che mappa mi suona di
quella del tesoro...

Sugli US lo traduciamo Stati Uniti?
Solano County lo lasciamo com'e' o mettiamo Conta di Solano?

Questo e' un problema di inglese mio personale. Non pensate che voglia dire
che grazie ai loro sforzi riusciamo ad avere un dettaglio che in altri
posti non vediamo? (Potrei essere io, che avendo il dente avvelenato sulle
sequenze che l'Italia non rilascia vedo cose che in realta' non ci sono...)

L'eccelente lavoro dell' Istituto Nazionale per la Ricerca Biomedica(INRB)
nel sequenziamento del virus fin dai primi campioni disponibili ci permette
di osservare come la trasmissione nella comunità sia nascosta in molti
altri luoghi.
L'eccelente lavoro dell' Istituto Nazionale per la Ricerca Biomedica(INRB)
nel sequenziamento del virus fin dai primi campioni disponibili ci permette
di osservare  la trasmissione nella comunità come non si riesce altrove

Infine, qualcuno mi puo' mettere gli accenti che o usato (di nuovo) la
tastiera sbagliata?
Senno' li cambio domani!

Scusate per il ritardo e buona notte!
Alice

**Comment by al-epo** [comment]
Buongiorno !
@aliceLedda  molti dei tuoi commenti sono quelli che avevo fatto anche io :-) 

sulla traduzione  di mappa non so...se è relativa  solo a quella geografica cartina va bene ma se è una mappa di quache altra cosa forse mappa e un aggettivo che la descriva magari è meglio.  Mappa dei dati ?  Credo dipenda anche dal contesto, a me mappa non fa pensare a quella del tesoro perchè probabilmente sono abituata  a sentire questo termine usato in fisica e matematica.  Detto ciò se vuoi usare cartina non c'è problema. 

US o si lascia US oppure credo Stati Uniti vada bene
Solano County lo lascerei così  

Sulla frase sull'Instituto di ricerca biomedica non ne ho idea...potrebbe essere giusta l’interpretazione  che ne dai te. Non conosco a sufficienza  il contesto per capirlo. 

Posso sistemare gli accenti ora e tradurre qualche paragrafo che è sfuggito ( L'executive summury mi sembra) 

A dopo!

Alessia

**Comment by sarameiqi** [comment]
US mettiamo Stati Uniti
Posso tornare su tutto il testo dopo le 3 pm UK time (le 4pm in Italia).
Riguardo tutto bene e vi dico la mia sulle cose che segnala Alice.
Se gli altri hanno tempo e gli va, rileggete anche voi e commentate nei commit, così faccio l'ultima lettura "professional" sulla traduzione e chiudiamo.
A dopo e buon lunedì di quarantena!

**Comment by al-epo** [comment]
Ho tradotto i titoli nel indice dei contenuti e anche il sommario all 'inzio. Tradotto qualche altro titolo che era sfuggito e dovrei aver sistemato gli accenti di Alice ( magari ri-controllate se avete tempo).
Ho aggiunto Alice e Sara come traduttori, i nomi sono in ordine alfabetico ma se volete mettere diversamente non c'è problema per me. Aggingete i vostri tweeter o siti. 
Non sono sicura di poter dare una mano piu tardi, cerco comunque di controllare i messaggi. 
A presto!

**Comment by sarameiqi** [comment]
grazie @al-epo.
Per voi va bene se ripasso su tutta la traduzione e inserisco correzioni direttamente sul testo originale?

**Comment by aliceLedda** [comment]
Si ok!
Se serve io ora sono davanti al computer...

**Comment by al-epo** [comment]
ok per me. 
grazie!

**Comment by sarameiqi** [comment]
@aliceLedda @cassiawag sorry if I bother you, but a doubts arised about the meaning of COVID-19.
If COVID-19 is the illness cause by SARS-nCov-2, is it correct to say: "We analyzed 1,495 publicly shared COVID-19 genomes."?

**Comment by sarameiqi** [comment]
@aliceLedda fammi sapere se questa traduzione è corretta:
Per esempio, ci sono alcune sequenze raccolte recentemente in Connecticut (foglie evidenziate) che pur essendo antenate di quelle di Washington (foglie non evidenziate) sono anche mescolate con queste ultime.
For example, recent samples from Connecticut (selected tips) are both ancestral to and intermingled with samples from Washington state (faded tips).

@al-epo @whispererindarkness mi dite se la traduzione è chiara per voi?

**Comment by al-epo** [comment]
@sarameiqi  per me è abbastanza chiara. 
Forse potrebbe essere ancora piu chiaro come: 
Per esempio, ci sono alcune sequenze raccolte recentemente in Connecticut (foglie evidenziate) che sono sia antenate di quelle di Washington (foglie non evidenziate) che mescolate con queste ultime.

**Comment by aliceLedda** [comment]
i think you're right... But by the time the name was decided we were all
calling it different names...
What did they write in the english version?

**Comment by cassiawag** [comment]
@aliceLedda & @sarameiqi -- you are correct, we're actually analyzing SARS-Cov-2 virus genomes that cause the disease COVID19. We were a bit sloppy about it in the English version of the report. Feel free to be precise in the Italian version! Thanks for all the work btw!

**Comment by aliceLedda** [comment]
Io l'avevo rigirata perche cosi non si capisce bene.
Se metti:
Alcune delle sequenze draccolte in Connecticut sono mescolate sull'albero
con quelle dello stato di Washington, mentre altre sono loro antenate.
Vi sembra piu' chiaro?

**Comment by sarameiqi** [comment]
A me sembra che la tua traduzione abbia un significato diverso da quella in inglese. Dice both, quindi io capisco che sono contemporaneamente antenate e mescolate. Però non so che voglia dire nel tecnico, quindi non so se quello che capisco io ha senso oppure no.

**Comment by al-epo** [comment]
si era quello che stavo scrivendo, ma forse non ne capisco l'aspetto tecnico

**Comment by aliceLedda** [comment]
Vai alla pagina in inglese e Guarda il disegno. Alcuni punti evidenziati
sono alla base e altri sono sulle foglie mischiati a quelli non
evidenziati. Both significa parte delle sequenze del c. Sono mischiate e
parte no.
Spiego la biologia.
Se l'outbreak si fosse evoluto in c. E solo recentemente fosse stato
trasmesso a e. Te le aspetteresti tutte verso la base.
Viceversa se lo scambio stesse avvenendo solo ora te le aspetteresti tutte
sulle foglie.
Vedere un segnale così e' strano perché ti dice che c'e' uno scambio
continuo nel tempo tra i due stati...
Forse lo dovevo scrivere in inglese perché era utile anche agli altri...
Alice

**Comment by sarameiqi** [comment]
Ok, ora è più chiaro. Non avevo capito che fossero due gruppi, uno che si mescola e uno che non si mescola ed è più "antico".
Grazie mille!

**Comment by sarameiqi** [comment]
> @aliceLedda & @sarameiqi -- you are correct, we're actually analyzing SARS-Cov-2 virus genomes that cause the disease COVID19. We were a bit sloppy about it in the English version of the report. Feel free to be precise in the Italian version! Thanks for all the work btw!

Ok, I substituted COVID-19 with SARS-Cov-2 in the sentence we talked about. I feel it important because there is a lot of confusion in Italy and sharing the right words can be of help for common readers...
For me the text is ok, @al-epo @aliceLedda or @whispererindarkness do you want to read it again or we can publish it?

**Comment by al-epo** [comment]
it is ok for me too!
great to work with you @aliceLedda @sarameiqi @whispererindarkness !

**Comment by aliceLedda** [comment]
Fine by me!
Alice

**Comment by cassiawag** [comment]
I'm going to go ahead and publish. @whispererindarkness if you have any more edits, please add them as PR. Thanks for the great work all!

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-27

Thank you all for a lot of hard work and another excellent translation!
