### ISSUE TITLE
Translate March 27 report to Japanese

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#290]
Hello @tomoyuki-nezu @satotake @fzhang12 !
 
The situation report from 2020-03-27 is ready to be translated to Japanese. A branch exists as `sit-rep_ja`  where this can be done, and the file to translate is `ncov_sit-rep_ja_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ja/narratives/ncov_sit-rep_ja_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ja/sit-rep/ja/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Japanese-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Japanese; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by tomoyuki-nezu** [comment]
Thanks @cassiawag 

@satotake @fzhang12 There are about two hours from afternoon to night in JST. If it has not been translated, it will be translate roughly throughout. If it has been translated, it will be checked in Japanese.

**Comment by satotake** [comment]
@tomoyuki-nezu  I am trying now. I will translate as much as I can until noon (JST).
Please check it

**Comment by satotake** [comment]
I have pushed first draft. Could you check and revise it, @tomoyuki-nezu ?

**Comment by tomoyuki-nezu** [comment]
Thank you @satotake I'ii check it now.

**Comment by tomoyuki-nezu** [comment]
@satotake Changed Japanese wording and fixed type.

@satotake @fzhang12 About Japanese translation of "exposure history". Is "曝露歴" a medical term? In Japanese, the words are "strong" and "bad impression", so if it is not a medical term, "露見歴" would be good I think. If it is "判明歴", the sentence may be slightly different.

**Comment by fzhang12** [comment]
Thanks both, I will take a quick look. if there is no big mistakes, the report could be pushed without my name.

**Comment by fzhang12** [comment]
I finished my proofread. Both of you have done an excellent job. Just one last sentence was forgot to translate so I updated the file (but it is not so related to the main part so I didnt add my name). 
Happy to work with all of you again :)

**Comment by satotake** [comment]
Thank you, @fzhang12 @tomoyuki-nezu 

@tomoyuki-nezu 

> Is "曝露歴" a medical term?

[Yes](https://lsd-project.jp/weblsd/o/begin/%E6%9B%9D%E9%9C%B2%E6%AD%B4). 
[3rd meaning](https://dictionary.goo.ne.jp/word/%E6%9A%B4%E9%9C%B2/)
But I admit that it sounds unusual as you pointed. So how about `ウイルスとの接触歴` ?


@fzhang12 

> (but it is not so related to the main part so I didnt add my name).

I am not sure about nextstrain's criteria .. but it is better to add your name because reviewing is tough task, IMO

@cassiawag Do you have any idea for crediting?

**Comment by tomoyuki-nezu** [comment]
Yes, I think I should also credit @fzhang12 name :)
I knew that my exposure history (暴露歴) was a medical term. Thank you @satotake

**Comment by cassiawag** [comment]
I also agree that @fzhang12's name should be on it. We couldn't do this without reviewers.

Is this ready to publish?

**Comment by tomoyuki-nezu** [comment]
Yes, I think I should also credit @fzhang12 name :)
Thank you @satotake  for letting me know that your exposure history is a medical term.
Where would you like to summarize our translation terms, including the past?

**Comment by tomoyuki-nezu** [comment]
@fzhang12 I added your name and link from the previous md file.
@cassiawag Status changed to Ready for Publish.

Thank you again everyone!!!

**Comment by satotake** [comment]
> Where would you like to summarize our translation terms, including the past?

Of course, I will help you to do it if it is needed.
But I do not have any ideas about where or how...
(You may mean the new translation system, which I have never seen)

...Anyway, I am appreciating your and @fzhang12 's  review of this situation report for now.
Thanks all

**Comment by cassiawag** [comment]
And it's live here: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-03-27 Thank you all for the fast translation and wonderful team work!

P.S. I'm working on a better communication system for all of you; we should soon have a forum-style like place for translators where you can post a dictionary.
