### ISSUE TITLE
Translate March 27 report to Korean

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#291]
Hello @hanbin973  @kyobinkang @minkyuxyz, @taehoonh !
 
The situation report from 2020-03-27 is ready to be translated to Korean. A branch exists as `sit-rep_ko`  where this can be done, and the file to translate is `ncov_sit-rep_ko_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_ko/narratives/ncov_sit-rep_ko_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ko/sit-rep/ko/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Korean-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Korean; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by taehoonh** [comment]
@hanbin973 @KyobinKang @minkyuxyz 

Hope you are doing well. In the midst of working on 03-27 report, minor typos in 03-20 report drew my attention:

1.  In the 'COVID-19 Resources(코로나바이러스감염증-19 관련자료)' section, 
이 정보들은 저희가 이 보고서에서 제시한 내용을 *이*하는데 도움을 줄 것입니다.

이 -> 이해

2. In 'as an official (지도자와 관료들이 할 일)' under the 'What you can do(우리가 할 수 있는 것들)' section, 
third bullet point -- * Fund and implement extensive contact tracing efforts. -- was missing.
* 광범위한 접촉 경로 추적에 재정을 지원하고 실행하십시오. was used in the 03-27 report.

As I do not have access to 03-20 report, I would appreciate it if somebody corrects/adds those to the 03-20 report. Thank you in advance.

**Comment by minkyuxyz** [comment]
Hi everyone, I'm a bit distracted by other businesses at this particular moment and will only be available to contribute ~12 hrs later.

**Comment by taehoonh** [comment]
Hi all,

Just completed the first draft. It would be grateful if you start reviewing. Likewise, any feedback is welcome.

Thanks,
TH

**Comment by minkyuxyz** [comment]
Done reviewing, made terminologies & grammar more consistent. Great job, thank you!
This report seems ready to go. @cassiawag , you can decide whether or not we need more reviews.
I also fixed the March 20 report in this branch. Please make sure that is merged together when you merge this to the main branch.

Minkyu

**Comment by taehoonh** [comment]
@minkyuxyz  Thanks. I appreciate that.

**Comment by cassiawag** [comment]
@KyobinKang -- any chance you could proofread rapidly?

**Comment by KyobinKang** [comment]
@cassiawag I'll proofread within a few hours and let you know.

**Comment by KyobinKang** [comment]
@cassiawag Made it. I agree it's ready to be published!

**Comment by cassiawag** [comment]
And it's published here: https://nextstrain.org/narratives/ncov/sit-rep/ko/2020-03-27

Thanks for the excellent translation all. I've also updated the March 20 report.
