### ISSUE TITLE
Translate March 27 report to Mandarin

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#292]
Hello @fillorkill @alvinxhan @lxy0107 @fzhang12 !
 
The situation report from 2020-03-27 is ready to be translated to Mandarin. A branch exists as `sit-rep_zh`  where this can be done, and the file to translate is `ncov_sit-rep_zh_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Mandarin-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Mandarin; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by lxy0107** [comment]
Hi all, I will start working on it now. Anyone else joining could start on page 10.

**Comment by lxy0107** [comment]
reporting a bug : the link to "north america" in the index is linking to iceland report.

**Comment by lxy0107** [comment]
> reporting a bug : the link to "north america" in the index is linking to iceland report.

so are all the links below..

**Comment by cassiawag** [comment]
Thank you very much @lxy0107! And I can fix them here when I publish.

**Comment by lxy0107** [comment]
Finished translation until text 11 (South America)... people are welcome to continue:)
see you tomorrow!

**Comment by fzhang12** [comment]
Thanks @lxy0107 ! I will take over the job from now.

**Comment by fzhang12** [comment]
I have finished the rest of the text (and also read through @lxy0107 part). 
@lxy0107 or others may proofread it again and change the progress to ready for publication.

**Comment by lxy0107** [comment]
Great! I can proofread your part @fzhang12

**Comment by lxy0107** [comment]
I checked everything - maybe we wait for a few hours to see if anyone else want to read it, and I can change the status (maybe around 21-22h CET).

**Comment by lxy0107** [comment]
pull request created:)

**Comment by cassiawag** [comment]
Excellent work, ladies! It's live here: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-27

A process note for future, please update Table of Contents links to this form: `https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-27?n=1`. Rather than the community narratives link. These links will not work prior to publishing, but we don't want to send people to the pre-publication version of the site.

Thanks as always!
