### ISSUE TITLE
Translate March 27 report to Polish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#293]
Hello @aniafijarczyk @M-nied7 @balwierz !
 
The situation report from 2020-03-27 is ready to be translated to Polish. A branch exists as `sit-rep_pl`  where this can be done, and the file to translate is `ncov_sit-rep_pl_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_pl/narratives/ncov_sit-rep_pl_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pl/sit-rep/pl/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Polish-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Polish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by aniafijarczyk** [comment]
I started translation, I can continue or do some proofreading tomorrow evening (eastern time zone)

**Comment by M-nied7** [comment]
@aniafijarczyk, I have finished the rest of the text, please do proofreading.

**Comment by aniafijarczyk** [comment]
finished proofreading, can you confirm if it's ready to go @M-nied7 ?

**Comment by cassiawag** [comment]
And it's published here: https://nextstrain.org/ncov/2020-03-27

Thanks for the fast work all!
