### ISSUE TITLE
Translate March 27 report to German

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#294]
Hello @astridgall @Hirthe @rneher @nicfel !
 
The situation report from 2020-03-27 is ready to be translated to German. A branch exists as `sit-rep_de`  where this can be done, and the file to translate is `ncov_sit-rep_de_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_de/narratives/ncov_sit-rep_de_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_de/sit-rep/de/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your German-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in German; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by astridgall** [comment]
@Hirthe @rneher @nicfel I'll start working in the file

**Comment by Hirthe** [comment]
@astridgall I could continue in a couple of hours. Let me know, when you are done 👍

**Comment by astridgall** [comment]
@Hirthe I am happy to finish this today. Maybe we could take a report in turns over the next weeks?

**Comment by astridgall** [comment]
@Hirthe @rneher @nicfel It's ready for proofreading

**Comment by Hirthe** [comment]
@astridgall thanks a lot for the translation. I proofread it. You can always contact me, when my help is needed. Otherwise I can also leave this totally to you.

**Comment by astridgall** [comment]
@Hirthe Thanks! I think a good system may be to alternate each week as the main translator. What do you think?

**Comment by Hirthe** [comment]
@astridgall Sounds like a plan :) Then I will do the next one :)

**Comment by astridgall** [comment]
Perfect @Hirthe !
I've made a PR to master for the above

**Comment by cassiawag** [comment]
Thank you @astridgall, @Hirthe, and @nicfel  for the translation! I hope you all are well this weekend.

It's now live at: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-27
