### ISSUE TITLE
Translate March 27 report to Turkish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#295]
Hello @zeynephrc @oyku-gencay !
 
The situation report from 2020-03-27 is ready to be translated to Turkish. A branch exists as `sit-rep_tr`  where this can be done, and the file to translate is `ncov_sit-rep_tr_2020-03-27.md` under the `narratives` folder: https://github.com/nextstrain/ncov/blob/sit-rep_tr/narratives/ncov_sit-rep_tr_2020-03-27.md
 
You can translate directly in this file, but please remember to push often as other people may be working on the translation!
 
After pushing changes, you can preview them here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_tr/sit-rep/tr/2020-03-27
 
A few new process things for this week:
- We’ve created a translations project board here:  https://github.com/nextstrain/ncov/projects/1 As you work on the translation, please adjust its location in the project board.  
- Please assign yourself to the translation issue if you’re working on it this week. This will help me keep track of which translations are in progress.
- When a translation is ready for publication -- at minimum meaning two people have worked on it and both agree that it’s ready -- please create a pull request to merge to `master` and tag me and the issue in it!
 
**Standard rules for translation:**
Note that the file to translate is in Markdown. In general, it is important _not_ to change any formatting or links. (Although it is okay to update Wikipedia or CDC links to the appropriate language version.) Comments to help with translation are noted in comment symbols like `<! -- Comment -->`. 
 
Please add your name under `translators:` with a tab, dash, and new line, formatted just like authors are. Please also add a link to your professional page (can use Twitter) under `translatorLinks:`.
 
After the report is translated and proofread, we’ll publish it to https://nextstrain.org/ and post on Twitter. Please share the report with your Turkish-speaking colleagues, so we can get the information out there!
 
Note: You may know of other great resources available in Turkish; please don’t add them to the situation report. We need to keep content the same across all translations, so we can be confident in the accuracy of what we publish. Thanks for understanding.
 
At minimum, I require two sets of eyes on every translation; one of those people should have a background in the field. Although if you have more, that’s fine too.
 
Please coordinate amongst yourselves to create and adjust a workflow that is suited for your translation team. You can trade off weeks; you can use a live, online editor like [hackmd](https://hackmd.io/) (sign in with GitHub) to translate together, etc. Whatever works best for you.
 
**Thank you so very much for the excellent translations; it’s a pleasure to work with you all! I hope you and your loved ones are well.**

**Comment by cassiawag** [comment]
@benuraa is also going to join in on translations. Thank you! We're glad to have you.

**Comment by zeynephrc** [comment]
Hello all, 
In the previous report, I translated it by myself. But now, I am very grateful to work with you on this report. If you want, we can divide the sections for translating.

**Comment by erenada** [comment]
Sure! I can translate Europe & the Americas.  If you push your changes frequently on the file as you work on it, it would be easier for us to track. Thank you!

**Comment by benuraa** [comment]
Hi all, Thanks for this great project! I am happy to help as much as I can. Have you guys started to work on ncov_sit-rep_tr_2020-03-27.md file? All I see is in English so far (i may be on the wrong place though). Cheers!

**Comment by zeynephrc** [comment]
Hi @benuraa!
I've started to work on the March 27 report, but currently, I'm in the beginning. I will be pushing changes when I'm done.

@erenada has chosen to work on Europe & the Americas and I've taken the Asia and Africa. 

Thanks for joining us!

**Comment by benuraa** [comment]
Great, thanks a lot!  I am a wee bit busy with a bunch of deadlines for the next couple of days. But I will definitely the proofreading and, if I can, a little bit of translation. Thanks a lot, guys!

**Comment by zeynephrc** [comment]
By the way, if you want, you can take a look at the previous report that we worked on to proofread.

**Comment by benuraa** [comment]
sure, I will proofread the previous report first.

**Comment by benuraa** [comment]
I just finished proofreading the previous report and suggested some translation for the scientific terms. Well done, it was very well translated!

**Comment by benuraa** [comment]
@zeynephrc and @erenada  let me know when you want me to start working on the proofreading of the current report. I need to have a lunch break and I can start in an hour or so earliest.

**Comment by cassiawag** [comment]
Thanks all! Amazing work. 

@benuraa, can you add your name and a professional link to this report?

@zeynephrc & @erenada, let me know when this is good to publish.

**Comment by erenada** [comment]
> @zeynephrc and @erenada let me know when you want me to start working on the proofreading of the current report. I need to have a lunch break and I can start in an hour or so earliest.

hi all! I'll be finishing my part in ~1 hour. then we can do a quick proof-read & get this ready for the publication.

**Comment by zeynephrc** [comment]
Hello, 
I've finished my parts and while @erenada is finishing his parts, maybe @benuraa can proof-read my parts.
Thank you everybody for putting in the hard work!

**Comment by erenada** [comment]
Hi! I've just pushed my changes, please feel free to read-over @benuraa & @zeynephrc!

**Comment by benuraa** [comment]
I am working on the text now. Is there a way to see the original English text?

**Comment by cassiawag** [comment]
Here's the original text @benuraa: https://nextstrain.org/narratives/ncov/sit-rep/2020-03-27

**Comment by benuraa** [comment]
I think we are done! I did the proofreading and changed bits and bobs! if everybody is happy with that it should be ready to be published. Cheers guys!

**Comment by zeynephrc** [comment]
Thanks!

**Comment by zeynephrc** [comment]
Thanks @benuraa, I did the last check and it seems great!

I moved the report to ready for publishing.

And also, thank you @erenada for the changes in my parts. It looks awesome!

**Comment by erenada** [comment]
Hi all, looks great! Thank you both @zeynephrc  @benuraa. I am reading the report one more time and I'll add some minor corrections in a minute. Then it's ready to go!

**Comment by benuraa** [comment]
let us know if u want us to check @erenada. honestly, guys, it's great job u are doing!

**Comment by cassiawag** [comment]
#DreamTeam. Thank you all! Incredibly impressive effort.

**Comment by zeynephrc** [comment]
I feel really privileged to work with both of you and gain experience by learning from you as a high school student!

Thanks again!

**Comment by cassiawag** [comment]
Anyone want to translate the Twitter post for me? And @benuraa, do you have a twitter handle I can tag?

Pleased to announce that the latest #COVID19 situation reports are now available in Turkish. A big thank you to @zharcanoglu, @erenada, and Benura Azeroglu for making these translations happen.

**Comment by benuraa** [comment]
i don't have a tweeter :/

**Comment by zeynephrc** [comment]
En son #Covid19 durum raporlarının artık Türkçe olarak da sunulduğunu duyurmaktan memnuniyet duyuyoruz. Bu çevirinin gerçekleşmesini sağlayan  @zharcanoglu, @erenada, ve Benura Azeroglu'na büyük teşekkürlerimizi sunuyoruz.

@cassiawag

**Comment by cassiawag** [comment]
Here's the published version: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-03-27

Posting on twitter now! Amazing work all.
