### ISSUE TITLE
[BUG] SyntaxError in line 84 of /home/josephus/ncov/Snakefile: invalid syntax

### ISSUE THREAD

**Issue by gwangjinkim** [nextstrain/ncov#315]
Something is wrong with the Snakefile.

In ubuntu do:
```
sudo apt install snakemake
snakemake --version
4.3.1
```
OR do in a conda environment
```
conda install -c bioconda snakemake
snakemake --version
5.3.0
```

git clone this repo
```
cd
git clone https://github.com/nextstrain/ncov.git
cd ncov
```

```
# then do:
snakemake -p
# SyntaxError in line 84 of /home/josephus/ncov/Snakefile:
# invalid syntax

# this is the error!

```

So, something is wrong with the Snakefile! But what?
line 84 is 
```
checkpoint partition_sequences:
```

I really don't get it why there is an invalid syntax ...

(I tried using the docker version etc. - nothing helped. I realized, this is a Snakefile and snakemake problem).

**Comment by brianpardy** [comment]
Hi @gwangjinkim, do you have the ability to install a newer version of snakemake?  It appears from the [snakemake changelog](https://snakemake.readthedocs.io/en/stable/project_info/history.html) that the `checkpoint` keyword was added in release 5.4.0 of snakemake.  The Snakefile processes cleanly without errors on my system running snakemake 5.10.0.

**Comment by gwangjinkim** [comment]
@brianpardy Thank you so much! And sorry that I answer right now.
A nwer Version of snakemake did it. I am now stucking on some other error but will try to find a way first.
Thank you so much that you answered quickly!
