### ISSUE TITLE
can't download data from aws

### ISSUE THREAD

**Issue by michelegentili93** [nextstrain/ncov#319]
**Current Behavior**  
After running 
snakemake -s Snakefile --cores 3
the query to aws to fetch data is not working:

fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
[Tue Mar 31 11:16:21 2020]
Error in rule download:
    jobid: 8
    output: data/sequences.fasta, data/metadata.tsv
    shell:
        
        aws s3 cp s3://nextstrain-ncov-private/sequences.fasta data/sequences.fasta
        aws s3 cp s3://nextstrain-ncov-private/metadata.tsv data/metadata.tsv
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Expected behavior**  
It should cp data from aws

**How to reproduce**  
the query to aws :
aws s3 cp s3://nextstrain-ncov-private/sequences.fasta data/sequences.fasta
aws s3 cp s3://nextstrain-ncov-private/metadata.tsv data/metadata.tsv

**Comment by tsibley** [comment]
Unfortunately we can't make those data files public, so this is expected. Please see the [developer guide](https://github.com/nextstrain/ncov/blob/master/DEV_DOCS.md#developer-guide) for how to run on public data.
