### ISSUE TITLE
Translate "How to interpret phylogenetic trees" to Turkish

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#320]
We’d like to translate “How to interpret phylogenetic trees” into Turkish. This narrative is referenced in the latest hCov-19 report, and we hope it will help make that one and future situation reports more accessible. The file to translate is `ncov_trees-background_tr.md` in branch `background_tr` under the narratives folder: https://github.com/nextstrain/ncov/blob/background_tr/narratives/ncov_trees-background_tr.md

After pushing your changes to GitHub, you can preview the translation here: https://nextstrain.org/community/narratives/nextstrain/ncov@background_tr/trees-background/tr/

Since this narrative explains something more technical, it would be great if the phylogenetics experts can keep their eyes especially on this translation :)

If more than one of you are working on the document at a time feel free to use a live, online editor like hackmd (sign in with GitHub) to work. The French translation group has found this especially helpful, whatever works best for you.

Thanks so much all! Really impressed with what you did with the last translation.

@zeynephrc @oyku-gencay @erenada @benuraa

**Comment by benuraa** [comment]
Hi guys, I have a lab meeting for next 3 hours but after that, I am happy to proofread/help if needed.

**Comment by erenada** [comment]
Hi all, 

Great idea @cassiawag! I was thinking to offer to translate that document too because I've already received some messages on Twitter about that; it seems like a lot of people are interested!

I can start it today & finish (possibly tomorrow). It would be great if we can work together with you guys @zeynephrc & @benuraa again! 

You can be 100% sure of the translation accuracy & quality @cassiawag! My Ph.D. research completely focuses on phylogenetic methods; I have done translations for a couple of book chapters on evolution, taxonomy & phylogenetics from English to Turkish. I did teach evolution and phylogenetics classes & workshops in Turkish (especially how to read a phylogenetic tree etc.). I will also make sure some other experts proof-read the document!

**Comment by zeynephrc** [comment]
Hello everyone!
Obviously, I am not an expert on this field but still, I will be trying my best to translate some of the parts that are easier. 
Thanks!

P.S: @erenada thank you so much for the support on twitter. It made me really happy:)

**Comment by erenada** [comment]
You deserve more @zeynephrc! I am really impressed by what you are doing, keep it going! 

I've created a hackmd translation team folks. I've already sent an email to @zeynephrc.

@benuraa & @oyku-gencay, please give me your e-mail addresses so I can add you to the team. There will be another person joining us, Onur, he is a Ph.D. student at Max Planck Institute who works on host-pathogen interactions from an evolutionary perspective. I believe his contributions will help greatly.

**Comment by benuraa** [comment]
you are doing a great job @zeynephrc! @erenada emailed you just now. If you want me to proofread something let me know I have 2 hours before my next meeting (I have a feeling I am having more meetings now that 'normal times')

**Comment by zeynephrc** [comment]
Hey all!
I've finished my parts and I guess @benuraa can now proofread.

**Comment by erenada** [comment]
Hi all, thanks for the hard work you've been doing! It's almost done. 

However, I noticed a possible mistake on the original text - before I continue, I wanted to let you know @cassiawag, I might be wrong.

On slide 9 (sampling issue), it says "In the last example, we have only one sequence from orange, which could lead us to think that there was one introduction from orange into blue." 

I thought that example (rightmost tree) indicates that there was one introduction from blue to orange, not orange to blue. What do you think? If the original text is true, I can translate as it is but I wanted to make sure!

**Comment by cassiawag** [comment]
Hi @erenada, you are correct. The original is mistaken. It should be from blue --> orange. Please translate it correctly! Thanks!

**Comment by erenada** [comment]
Hi @cassiawag, thanks for checking it! 

The translation has finished and ready to publish then! Thank you @zeynephrc & @benuraa! 

One more person has proof-read to make sure there are no scientific/technical language mistakes: Dr. Hakan Gür (https://twitter.com/hgur_ecology -- I wasn't sure where to thank him in the translated page but maybe you guys can mention him in the tweet?) Thank you!

**Comment by cassiawag** [comment]
Amazing work everyone! Thank you for the special attention to make sure this was accurate; really appreciate it. It's now published here: https://nextstrain.org/narratives/trees-background/tr

I've also updated the links in the most recent narrative: https://nextstrain.org/narratives/ncov/sit-rep/tr/2020-03-27

We don't usually post on Twitter about publishing How To Interpret Phylogenetic Trees or the translations of it. But if you'd like to share yourself, that would be just fine.
