### ISSUE TITLE
[BUG] Single "region" label set to "USA" in meta file

### ISSUE THREAD

**Issue by hringbauer** [nextstrain/ncov#322]
**Current Behavior**  
EPI_ISL_418865 has "region" USA in meta file.

**Expected behavior**  
All North American samples have "North America".

**Possible solution**  
Change region label for EPI_ISL_418865 to "North America".

**Comment by emmahodcroft** [comment]
Hi @hringbauer ! Thanks for your comment here. I've checked this in the most recent `metadata.tsv` file, and it seems like the region is listed as North America now. This may have been fixed in one of our recent pushes. But thanks for pointing this out - hopefully it's fixed now!
