### ISSUE TITLE
Make output Phylogeny downloadable

### ISSUE THREAD

**Issue by michelegentili93** [nextstrain/ncov#326]
**Context**  
We want to do some research on the Phylogeny. How can we download only the final output?

**Description**   
I've tried to rerun myself the package, but it's not possible, because we don't have the input data. How can we build our analysis on top of your Phylogeny output, so that to let research advance?

**Examples**  
A Json with the hierarchy evolution of the mutation with geographical information would be enough

**Comment by emmahodcroft** [comment]
Hi @michelegentili93 ! You should indeed be able to download the final-format data you are looking for. If you go to https://nextstrain.org/ncov - and scroll to the very, very, very bottom of the page (past a lot of blue text), you should see this:

![image](https://user-images.githubusercontent.com/14290674/78115824-aa5a7400-7403-11ea-9a71-b1fde743c17a.png)

This will open up an option to download two types of tree (time-resolved or not) and the accompanying metadata. It sounds like this should solve your problem, but let us know if it doesn't!

**Comment by jameshadfield** [comment]
In addition to what Emma said, if you want the input JSON which auspice uses you can look at `data.nextstrain.org/ncov.json` (which fits [this schema](https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json))
