### ISSUE TITLE
[Language translation request]

### ISSUE THREAD

**Issue by sentausa** [nextstrain/ncov#327]
**What language would you like the situation reports to be translated into?**  
Indonesian

**Are you available to help translate?** (Either way is alright, just let us know! :)
Yes

**Comment by cassiawag** [comment]
Hello @sentausa, thanks for the message! We would LOVE to get an Indonesian translation started. 

New situation reports come out every Friday at 5pm, and we start translations right away. Our goal is to have everything published within 48 hours, but many groups finish sooner.

All translations must be approved by at least two people. One of those individuals should have an advanced biology background, preferably in phylogenetics. What's your background if you don't me asking? Do you know of anyone else who might be able to work on translations with you?

**Comment by sentausa** [comment]
Thanks @cassiawag. I am a bioinformatician. So, I am quite confident that I have an advanced biology background, including in phylogenetics. For now I don't know anyone else who might be able to work on translations with me, but I can try to look for one.

**Comment by cassiawag** [comment]
I'll need their GitHub contact info. You can also have them reach out to me. via Twitter: https://twitter.com/wcassias

Thanks for reaching out. I'll tag you in a relevant issue when we publish the next weekly report (tomorrow).

**Comment by sentausa** [comment]
Thanks. And could you please tell me in which time zone the situation reports are usually released on Friday?

**Comment by cassiawag** [comment]
Yes of course, 5pm PDT. So if you're in Europe, people are working on them Saturday morning.

**Comment by sentausa** [comment]
And one more thing: do we need to translate the previous situation reports as well? Thanks again.

**Comment by sentausa** [comment]
I've found another volunteer: @kumincir

**Comment by kumincir** [comment]
Hi, all. I'm in. My backround is chemistry, but have been working in molecular biology for years.

**Comment by cassiawag** [comment]
@kumincir & @sentausa, I've added you both to the Translators team and given you access to push to the relevant branches under the `translations` repo, where we're coordinating translations. Looking forward to getting an Indonesian report out!

re: Translating previous reports, this is not necessary. Although we do occasionally refer back to previous reports in the most recent one. I would focus on newest report first, and after that, if you want to work on other reports, go ahead.
