### ISSUE TITLE
 pruning leaf : Samples were removed during augur refine steps

### ISSUE THREAD

**Issue by shameem356** [nextstrain/ncov#328]
Hello Team,
we have assembled covid genome which we collected from  our region and tried to run with nextstrain. But  samples were removed from during augur refine steps.Please can you suggest what will be the reason for removing our assembly. below are the log file messages.
Note :  I have modified metadata.tsv, ordering.tsv, lat_longs.tsv according to my samples.Please can you suggest me that what will be the reason for pruning leaf

**
39.10   TreeTime.reroot: with method or node: ['Wuhan-Hu-1/2019',
        'Wuhan/WH01/2019']

42.77   TreeTime.reroot: with method or node: ['Wuhan-Hu-1/2019',
        'Wuhan/WH01/2019']
pruning leaf  XXXX/yyyy-S20/2020
pruning leaf  XXX/yyyy-S21/2020**

**Comment by emmahodcroft** [comment]
Dear @shameem356 , thanks for reaching out! Yes, the code we use in `refine` automatically removes sequences which are too divergent from the clock model. It depends a little on the background sequences you are using and the root you are using - but if you are using our standard pipeline, and are able to access all or most of the sequences we use, then this is a sign that your sequences are too divergent (or not divergent enough) - more than expected. This means they will not fit the clock model and are being excluded from the analysis as there seems to be something wrong with them and they may negatively affect the run. 

If you want to include these to see how it looks (be *sure* to check divergene view in Auspice if you do so - you may see they are very divergent), you could remove this line from the Snakefile temporarily: `--clock-filter-iqd {params.clock_filter_iqd}` - this will stop any filtering of sequences at this stage. However, beware that if they are being filtered this may be for very good reason and you should be cautious about including them!
I hope this helps!

**Comment by shameem356** [comment]
Hello @emmahodcroft 

Thank you so much for quick reply. It helped me to solve the issue as well as genome divergence issue.Once again thank you so much.
