### ISSUE TITLE
Metadata: Host field has "Human" as well as "human"

### ISSUE THREAD

**Issue by hringbauer** [nextstrain/ncov#331]
**Current Behavior**  
The metadata "host" field has "Human" and in a few cases "human". All other hosts start with an upper case character  as well.

**Expected behavior**  
Consistent labeling, to avoid that case-sensitive matching (often default) fails.

**Possible solution**  
Switch all "human" to "Human" in host column.

**Comment by emmahodcroft** [comment]
Hi @hringbauer ! I just checked the `data/metadata.tsv` file which is online now, and I can't find lowercase 'human' instances in this copy. Can you check you're using a recently pulled (or downloaded) version of the file? If you're still finding lowercase 'human' instances, can you let us know the strain name they're associated with? Thanks!

**Comment by hringbauer** [comment]
Great, the newer versions don't have lowercase "human" anymore, it must have been fixed by someone already!
