### ISSUE TITLE
[BUG] Some data provided by Japan is not displayed.

### ISSUE THREAD

**Issue by tomoyuki-nezu** [nextstrain/ncov#332]
At the end of the report is a list of data provided by Japan. There is a group "Japanese Quarantine Stations (Japan/DPXXXX/2020)" in it, but this data cannot be searched and displayed in "Genomic epidemiology" menu.

The information is also included in the metadata (https://github.com/nextstrain/ncov/blob/master/data/metadata.tsv), why is it not displayed? Is some data incomplete and hidden?

In the same situation last week, I thought that it would be improved by updating the data, but this week remains the same.

**Comment by tomoyuki-nezu** [comment]
A side note. It would be great if someone could create a tag like "report". The word "bug" is strong for us, I want a more gentle tag :)

**Comment by acx01b** [comment]
In https://github.com/nextstrain/ncov/blob/master/config/exclude.txt the cruise sequences are excluded, I don't know if trevor explained why

**Comment by tomoyuki-nezu** [comment]
@acx01b Thank you for information. Then close here and discuss with https://github.com/nextstrain/ncov/issues/279 if necessary.
