### ISSUE TITLE
Some metadata cleanups to avoid inconsistencies in lab filtering/credit

### ISSUE THREAD

**Issue by brianpardy** [nextstrain/ncov#333]
A few metadata elements have typos or other data-entry issues that are causing near-duplicate entries in the various filter options available at the bottom of the report. I am listing them here in this issue and submitting a PR to resolve the ones that seem like obvious fixes.

- Strain Hangzhou/HZ185/2020 submitting lab "Insepction Center" -> "Inspection Center"
- "University of Wisconsin - Madison AIDS Vaccine Research Laboratory" appears with five different spacing/punctuation variants, normalized them
- "State Key Laboratory for Diagnosis and Treatment of Infectious Diseases, National Clinical Research Center for Infectious Diseases, First Affiliated Hospital, Zhejiang University School of Medicine, Hangzhou, China. 310003" appears with and without trailing period after 'China'
- "Sequencing and Bioinformatics Service and Molecular Epidemiology Research Group. FISABIO-Public Health" appears with and without a trailing period
- "National Influenza Center, Indian Council of Medical Research - National Institute of Virology" has inconsistent spacing in two strains
- "Laboratoire Nationale de Sante, Microbiology, Virology" spelled both 'National' and 'Nationale'
- "Instituto Adolfo Lutz Interdisciplinary Procedures Center, Strategic Laboratory" inconsistent use of commas, inconsistent inclusion of letter "s" in interdisciplinary
- "Department of Laboratory Medicine, Lin-Kou Chang Gung Memorial Hospital, Taoyuan, Taiwan" extra period after "Taiwan" in one case
- "Department of Infection, Immunity and Cardiovascular Disease, The Florey Institute, The Medical School, University of Sheffield" extra space in two records
- "Instituto Nacional de Salud, Universidad Cooperativa de Colombia, Instituto Alexander von Humboldt, Imperial College-London, London School of Hygiene & Tropical Medicine" - inconsistent use of commas

**Comment by trvrb** [comment]
Thanks for the suggests @brianpardy. This curation work has been subsumed into ongoing curation happening as part of `ncov-ingest`. Closing now.
