### ISSUE TITLE
[BUG]An error related with State number

### ISSUE THREAD

**Issue by JosephLee815** [nextstrain/ncov#335]
**Current Behavior**  
When we tried to build the tree with TreeTime, we encountered with an error saying that "180 or more distinct discrete states found. TreeTime is currently not set up to handle that many states". All the process before this one was finished.  

**Expected behavior**  
The evolution tree should be generated after the tree.nwk file was obtained.

**How to reproduce**  
<img width="861" alt="WechatIMG2475" src="https://user-images.githubusercontent.com/25347700/78473520-d95e4600-7773-11ea-8d0b-5411fd79e033.png">

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   centos 7 
 - Browser:  Chrome
 - Version (e.g. `auspice 2.7.0`):  nextstrain 1.14.0a

**Additional context**  
We are not sure if some strains in the dataset led to this error. Since we are not only using the strains from GISAID but there are 10 more strains from other source in our dataset. But they have been in our dataset for a while but this error never shown up before.

**Comment by brianpardy** [comment]
Hi @JosephLee815, I believe you need to upgrade the release of [augur](https://github.com/nextstrain/augur) that you are running and likely also the version of [treetime](https://github.com/neherlab/treetime), please see https://github.com/nextstrain/augur/pull/495 for more details.

**Comment by emmahodcroft** [comment]
@JosephLee815 , @brianpardy is right! This should solve your problem - but make sure you update both. Let us know if this doesn't fix things!

**Comment by JosephLee815** [comment]
@brianpardy @emmahodcroft Thank you very much for your help. We believed that this should solve the problem we have. However now we have a new issue with updating these two stuff. Actually we installed the docker you provided (including the auspice and augur). But the augur and treetime seemed to be the old version even if we update the docker to the latest version. How can we get the new version of augur and treetime in the docker?
Thank you very much!

**Comment by emmahodcroft** [comment]
@tsibley I know you're very busy, but could you possibly help with this - updating augur/treetime inside of docker, when upgrading the docker hasn't helped? Thank you!

**Comment by tsibley** [comment]
A new release of Augur is needed, as the change made in https://github.com/nextstrain/augur/pull/495 is currently unreleased. Doing a release of Augur will automatically publish a new Docker image.

**Comment by tsibley** [comment]
@JosephLee815 A new version of Augur was just released, and now the latest Docker image, `nextstrain/base:build-20200407T184050Z`, has the fixes you need.

**Comment by JosephLee815** [comment]
@tsibley Thank you very much for your help. We will immediately try the new version.

**Comment by JosephLee815** [comment]
@tsibley Sorry to bother you guys again. Here we have a new problem after updating the latest version of Augur. 
<img width="935" alt="WechatIMG2668" src="https://user-images.githubusercontent.com/25347700/78856476-77465f00-7a59-11ea-948a-be3fc88df915.png">
I'm not sure if this weights file was generated halfway in the process. Or is it something we should update somewhere with nextstrain?

**Comment by jameshadfield** [comment]
Hi @JosephLee815 -- this may be a problem on our side (too many missing values in `weights.tsv`). In the meantime, you should be able to add in those missing demes to the TSV file yourself & give them a weight of `1.0` to proceed.
