### ISSUE TITLE
Missing connection between divisions

### ISSUE THREAD

**Issue by EricFournier3** [nextstrain/ncov#338]
**Current Behavior**  
With the ncov build (Canada dataset), we lost connections in auspice when we change Geographic resolution to divisions (in the Map Option) instead of Country

**Expected behavior**  
we want to keep connection between divisions
**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open / run ...  
2.   
3.  

**Possible solution**  
(optional)  

**Your environment: if browsing Nextstrain online**  
 - 

**Your environment: if running Nextstrain locally**  
 - Operating system:   Linux Centos
 - Browser:  Chrome
 - Version: auspice 2.11.4

**Additional context**

**Comment by trvrb** [comment]
This is intended behavior. Builds with different geographies purposely have phylogeography run on different resolutions. For North America, Canada connections can be seen here: https://nextstrain.org/ncov/north-america?c=division&transmissions=show
