### ISSUE TITLE
two minor bugs to follow the instructions

### ISSUE THREAD

**Issue by jiehuang001** [nextstrain/ncov#339]
1.   On https://nextstrain.org/docs/tutorials/tb, the example command “augur export” needs to be followed by “v2”, and then the “--output-tree” and “--output-meta” commands need to be replaced with a single “--output” command.

2.   On https://github.com/nextstrain/ncov/blob/master/DEV_DOCS.md，it says that “can be visualized by running auspice view --datasetDir auspice”. However, I need to add “/” at the end of this command. Otherwise, it won’t work.

Although these are really minor issues, this could be very frustrating for newcomers like me, because new users would expect that all the commands written on your website should work as is. 

Thank you very much!

Best regards,
jie

**Comment by jameshadfield** [comment]
Hi jie -- `auspice view --datasetDir auspice` works fine for me (MacOS) -- what OS are you using?

**Comment by jiehuang001** [comment]
Hi, I use Ubuntu coming with Windows 10.

Best regards,
Jie

**Comment by emmahodcroft** [comment]
Hm. I am also using Ubuntu Windows 10, for me running without the slash works:
`auspice view --datasetDir auspice`

However, running with the slash seems to work too:
`auspice view --datasetDir auspice/`

**Comment by emmahodcroft** [comment]
@jiehuang001 Thanks so much for your detailed information about how to get the `export` commands for the tutorials working! We have just pushed a change for this onto the site, so hopefully it will be showing up correctly soon!
We really appreciate your help knowing what to change!

I'll leave this issue open for the moment in case there's more to be said about the second point you raise, but hopefully the first is fixed!

**Comment by jameshadfield** [comment]
The documentation has now been updated with the correct `augur export ..` syntax. If you are still having an error running `auspice view --datasetDir auspice` please reopen this issue! thanks
