### ISSUE TITLE
[BUG] MissingInputException

### ISSUE THREAD

**Issue by halilozercan** [nextstrain/ncov#341]
**Current Behavior**  
- First clone the repository to a new directory `ncov`
- Copy `/example_data/sequences.fasta` to `/data` 
- Run `nextstrain build ncov/`

```
MissingInputException in line 23 of /nextstrain/build/Snakefile:
Missing input files for rule all:
auspice/ncov_tip-frequencies.json
auspice/ncov.json
```

**Expected behavior**  
Build should complete successfully.

**Possible solution**  
3 days ago when I first cloned this repository, there was no problem and I checked Snakefile and recently there was a cleanup of input files. 

**Your environment: if running Nextstrain locally**  
 - Operating system: Ubuntu 16.04

**Comment by brianpardy** [comment]
Hi @halilozercan, it looks like this appeared with https://github.com/nextstrain/ncov/commit/c0f773807f051f15165730421802026da25358d8 , specifically with the change at the top of the Snakefile from 
`REGIONS = ["_africa", "_asia", "_europe", "_north-america", "_oceania", "_south-america", ""]`
to
`REGIONS = ["_africa", "_asia", "_europe", "_north-america", "_oceania", "_south-america", "_global"]`

I believe this is an artifact of the changes to support subsampling sequences, but it is interfering with local runs of the full dataset.  On my side, I restored the empty last element by changing this line to read:

`REGIONS = ["_africa", "_asia", "_europe", "_north-america", "_oceania", "_south-america", "_global", ""]`

Once I did that, I was able to run snakemake as usual and complete a full analysis. I am not sure if this will also work for nextstrain cli users like you described, nor am I sure of the actual consequences of this change other than making my build work again.

**Comment by halilozercan** [comment]
Thanks a lot @brianpardy , that did the trick :)

**Comment by emmahodcroft** [comment]
Dear both - thank you for spotting this! This was indeed an oversight from our recent migration to the regional builds. We've taken a slightly different route to fix, so it doesn't interfere with the Regional builds which are now generated as our regular runs, but should still allow you to run the 'base' build as before. @trvrb pushed this a few minutes ago - I hope it solves your problems, and sorry about that!
You can see the modification here: https://github.com/nextstrain/ncov/commit/5cb4cc19044fb9f2857ef06596534e233b707e3a

Again, thanks for catching it!
