### ISSUE TITLE
Duplicated sequence name MN908947 error

### ISSUE THREAD

**Issue by ajaybabu27** [nextstrain/ncov#343]
I recently pulled the latest version of the repo and ran the sequences downloaded from gisaid. I am running into this following error during the iqtree step:

`(nextstrain) [kumara22@vanbah01-1 ncov]$ cat results/subsampled_alignment-delim.iqtree.log
IQ-TREE multicore version 1.6.12 for Linux 64-bit built Aug 15 2019
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.

Host:    vanbah01-1 (AVX2, FMA3, 755 GB RAM)
Command: iqtree -ninit 2 -n 2 -me 0.05 -nt 4 -s results/subsampled_alignment-delim.fasta -m GTR
Seed:    491175 (Using SPRNG - Scalable Parallel Random Number Generator)
Time:    Wed Apr  8 10:00:11 2020
Kernel:  AVX+FMA - 4 threads (36 CPU cores detected)

Reading alignment file results/subsampled_alignment-delim.fasta ... Fasta format detected
Alignment most likely contains DNA/RNA sequences
WARNING: 184 sites contain only gaps or ambiguous characters.
Alignment has 4193 sequences with 29903 columns, 16907 distinct patterns
946 parsimony-informative, 1811 singleton sites, 27146 constant sites
ERROR: Duplicated sequence name MN908947`

Looks like the reference sequence is detected as a duplicate sequence in the aligned fasta file (two entries), but I don't see that sequence in my input "sequence.fasta" file. I have run into this issue one other time previously and it went away after a repo update. Any help in resolving this would be appreciated.

**Comment by cassiawag** [comment]
Hi @ajaybabu27, what version of augur are you using? I got the same error until I updated to augur 6.4.3. You should be able to do this via: `pip install --upgrade nextstrain-augur`

**Comment by ajaybabu27** [comment]
@cassiawag, Yes that update solved the issue for me. Thanks !
