### ISSUE TITLE
[BUG] Mutation at pos 13401 is likely erroneous

### ISSUE THREAD

**Issue by hringbauer** [nextstrain/ncov#346]
**Current Behavior**  
When screening SNPs that are "incompatible" with others in my own alignment, position 13401 (to Wuhan-Hu-1) popped up a very clear red flag. When checking on nextstrain's tree, there is obviously also something faulty, see [nextstrain](https://nextstrain.org/ncov/global?c=gt-ORF1a_4379&gmax=14037&gmin=13134&l=radial). This mutation pops up on multiple branches; intriguingly almost exclusively in Belgian samples.

**Expected behavior**  
A variant cannot fall into a large number of distinct branches, there is no way this is a recombination or recurrent mutation.  And such a spurious locus will obviously hurt several downstream analysis.

**Possible solution**  
Manually correct this mutation/flag out that position, or possibly re-check submissions from the Belgian lab.

**Comment by emmahodcroft** [comment]
Thank you for reporting this! We will definitely look into it

**Comment by hringbauer** [comment]
Great! [pos 15323](https://nextstrain.org/ncov/global?branchLabel=aa&c=gt-nuc_15324&l=unrooted&m=div) (I use python indexing in my alignment, so always add 1 for nextstrain Position) has some Belgium outliers over multiple clades too. I would hope it is some really cool biology, but I guess more likely these are sequencing artifacts. :)

**Comment by acx01b** [comment]
@hringbauer  Belgium pop-ups also when looking at reversions of the 14408 Italian-European mutation https://nextstrain.org/ncov/global?c=gt-nuc_14408&l=radial

**Comment by rneher** [comment]
13402 has been masked.
