### ISSUE TITLE
[BUG] Snakefile for ncov throwing import error at partition_sequences stage

### ISSUE THREAD

**Issue by tonbar** [nextstrain/ncov#347]
**Current Behavior**  
When running the Snakefile with the command `snakemake -p --cores 1`, I receive the following error:
```
Traceback (most recent call last):
  File "scripts/partition-sequences.py", line 4, in <module>
    from augur.align import read_sequences
ImportError: cannot import name 'read_sequences'
[Thu Apr  9 09:01:06 2020]
Error in rule partition_sequences:
    jobid: 18
    output: results/split_sequences/pre/
    shell:
        
        python3 scripts/partition-sequences.py             --sequences results/filtered.fasta             --sequences-per-group 150             --output-dir results/split_sequences/pre/
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Expected behavior**  
Successful completion of Snakemake process. 

**How to reproduce**  
Steps to reproduce the current behavior:  
1.   Clone master branch of nextstrain/ncov (0790d442dc1700d56fd3c7f940f2c2877c8be1bd)
2.   Run snakemake -p --cores 1 in .../ncov/ directory
3.   See error  

**Your environment: if running Nextstrain locally**  
 - Operating system:   Ubuntu 18.04 in Oracle VirtualBox VM (host OS Microsoft Windows 10)
 - Browser:  Firefox
 - Version (e.g. `auspice 2.7.0`):  augur 6.3.0

**Additional context**  
I have a local installation of augur (v6.3.0) downloaded from GitHub releases and built from source that appears to be working correctly. I ran through the Zika tutorial without any apparent errors and successfully ran the tests for that build.

**Comment by tsibley** [comment]
@tonbar I believe you'll need to upgrade to at least Augur 6.4.3. The latest version is 7.0.2.
