### ISSUE TITLE
[BUG] Croatia isn't shown as part of Europe

### ISSUE THREAD

**Issue by Maijin** [nextstrain/ncov#351]
**Current Behavior**  
Croatia isn't shown as part of Europe

**Expected behavior**  
Croatia is shown as part of Europe

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Open https://nextstrain.org/ncov/europe
2. Observe Croatia is in a shade of gray
<img width="84" alt="image" src="https://user-images.githubusercontent.com/1408600/78980571-70355480-7b1e-11ea-8403-254d57ab96a1.png">

**Your environment: if browsing Nextstrain online**  
 - Operating system:  Mac Os
 - Browser:  Firefox

**Comment by jameshadfield** [comment]
Thanks @Maijin -- this does seem to be a bug. Note that we don't currently have any genomes from Croatia, rather we have an Icelandic sample (Iceland/318/2020) with travel history to Croatia which seems to be causing this.

**Comment by jameshadfield** [comment]
This should have been fixed by https://github.com/nextstrain/ncov-ingest/pull/38 which should be reflected in updated builds over the next ~12 hours
