### ISSUE TITLE
[BUG] Unable to reproduce results in running.md

### ISSUE THREAD

**Issue by cornhundred** [nextstrain/ncov#355]
**Current Behavior**  
I downloaded the sequencing data for SARS-CoV-2 from GISAID and I'm trying to use the metadata from this repo to reproduce the results (I was able to reproduce the results of the Zika tutorial). I made a directory called data with the fasta file and the metadata file and tried running 

```
snakemake -p -s Snakefile --cores 2 auspice/ncov.json
```

but I'm getting the error 

```
Error: Snakefile "Snakefile" not found.
```

**Expected behavior**  
Reproduce the results described here https://github.com/nextstrain/ncov/blob/master/docs/running.md

**How to reproduce**  
Steps to reproduce the current behavior:  
1. Download fasta sequences from GISAID
2.  Run command from above

**Possible solution**  
(optional)  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  MacOS
 - Browser:  Chrome

**Your environment: if running Nextstrain locally**  
 - Operating system:   
 - Browser:  
 - Version (e.g. `auspice 2.7.0`):  

```
➜  nextstrain_local_ncov nextstrain check-setup                
nextstrain-cli is up to date!

Testing your setup…

# docker is supported
✔ yes: docker is installed
✔ yes: docker run works
⚑ warning: containers have access to >2 GiB of memory

  Containers appear to be limited to 2.0 GiB of memory. This
  may not be enough for some Nextstrain builds.  On Windows or
  a Mac, you can increase the memory available to containers
  in the Docker preferences.                        
✔ yes: image is new enough for this CLI version

# native is not supported
✔ yes: snakemake is installed
✔ yes: augur is installed
✘ no: auspice is installed

# aws-batch is not supported
✘ no: job description "nextstrain-job" exists
✘ no: job queue "nextstrain-job-queue" exists
✘ no: S3 bucket "nextstrain-jobs" exists

Supported Nextstrain environments: docker

```

**Additional context**

**Comment by cornhundred** [comment]
I tried cloning this repo and running `snakemake -p -s Snakefile --cores 2 auspice/ncov.json`, but 
I'm getting an error that appears to be related to not having access to aws files 

```
Error in rule download:
    jobid: 13
    output: data/sequences.fasta, data/metadata.tsv
    shell:
        
        aws s3 cp s3://nextstrain-ncov-private/metadata.tsv data/metadata.tsv
        aws s3 cp s3://nextstrain-ncov-private/sequences.fasta data/sequences.fasta
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I'm looking into how to disable this copying and just use my local fasta file (obtained from GISAID).

**Comment by cornhundred** [comment]
I tried filtering for only sequences that appeared in the metadata tsv and am now getting the following error. 

```
[Sun Apr 12 10:10:55 2020]
Job 17:
        Filtering to
          - excluding strains in config/exclude.txt
          - minimum genome length of 25000



        augur filter             --sequences data/sequences.fasta             --metadata data/metadata.tsv             --include config/include.txt             --exclude config/exclude.txt             --exclude-where date='2020' date='2020-01-XX' date='2020-02-XX' date='2020-03-XX' date='2020-04-XX' date='2020-01' date='2020-02' date='2020-03' date='2020-04'            --min-length 25000             --group-by division year month             --sequences-per-group 500             --output results/filtered.fasta

[Sun Apr 12 10:10:57 2020]
Error in rule filter:
    jobid: 17
    output: results/filtered.fasta
    shell:

        augur filter             --sequences data/sequences.fasta             --metadata data/metadata.tsv             --include config/include.txt             --exclude config/exclude.txt             --exclude-where date='2020' date='2020-01-XX' date='2020-02-XX' date='2020-03-XX' date='2020-04-XX' date='2020-01' date='2020-02' date='2020-03' date='2020-04'            --min-length 25000             --group-by division year month             --sequences-per-group 500             --output results/filtered.fasta

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/nickfernandez/Documents/ncov/.snakemake/log/2020-04-12T101055.212684.snakemake.log
~                                                                                                                                                                                                                                                                               
~                                                                                                              
```

**Comment by brianpardy** [comment]
Hi @cornhundred, it's not clear from your last post what errors occurred as none seem to appear in the log. But for your prior post with the indication of a duplicate key "hCoV-19/Hong", it looks like you are using the GISAID sequences download file and have not normalized the sequence names from the format provided by GISAID to the format expected by the nextstrain/ncov pipeline. Specifically what you are hitting there are embedded spaces in the strain names from GISAID that are stripped out in the metadata.tsv strain names.

If you run `scripts/normalize_gisaid_fasta.sh path-to-GISAID-download-file data/sequences.fasta` then the normalize_gisaid_fasta.sh script should make all the necessary adjustments to strain names in the GISAID fasta file and place the results in data/sequences.fasta.

You may need to run `snakemake clean` to clean up your working directory from these errored-out attempts.

Regarding the 'download' Snakefile rule, that rule is only run if no sequences.fasta file exists, so once you have produced the sequences.fasta file either by hand or from normalize_gisaid_fasta.sh script, the download rule will not be run.

**Comment by cornhundred** [comment]
Thanks for your help @brianpardy! I'll let you know if I can get that working.

**Comment by cornhundred** [comment]
Update: I reset the repo, ran the 

```
scripts/normalize_gisaid_fasta.sh path-to-GISAID-download-file data/sequences.fasta
```

command and then re-ran the 

```
snakemake -p -s Snakefile --cores 2 auspice/ncov.json
```

command but got the following error 

```

using mafft to align via:
	mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/5.fasta.to_align.fasta 1> results/split_alignments/5.fasta 2> results/split_alignments/5.fasta.log 

	Katoh et al, Nucleic Acid Research, vol 30, issue 14
	https://doi.org/10.1093%2Fnar%2Fgkf436


ERROR: b''
shell exited 127 when running: mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 2 results/split_alignments/5.fasta.to_align.fasta 1> results/split_alignments/5.fasta 2> results/split_alignments/5.fasta.log
Are you sure this program is installed?

Error during alignment
[Sun Apr 12 14:48:42 2020]
Error in rule align:
    jobid: 38
    output: results/split_alignments/5.fasta
    shell:
        
        augur align             --sequences results/split_sequences/post/5.fasta             --reference-sequence config/reference.gb             --output results/split_alignments/5.fasta             --nthreads 2             --remove-reference             --fill-gaps
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job align since they might be corrupted:
results/split_alignments/5.fasta
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message

```
It sounds like there might have been an error with `mafft`.

**Comment by cornhundred** [comment]
Update: Sorry for the messy issue. This time I ran snakemate clean first and then got the following error

```
Error in rule align:
    jobid: 38
    output: results/split_alignments/5.fasta
    shell:

        augur align             --sequences results/split_sequences/post/5.fasta             --reference-sequence config/reference.gb             --output results/split_alignments/5.fasta             --nthreads 2             --remove-reference             --fill-gaps

        (exited with non-zero exit code)
```

**Comment by brianpardy** [comment]
Is `mafft` installed/accessible by the user running snakemake? I had a few problems with old versions, but it is working for me now with:

```
% mafft --version
v7.453 (2019/Nov/8)
```

I don't recall that truncated looking error message though. You may also need to confirm the version of nextstrain/augur you are running, just in case.

```
% augur --version
augur 7.0.2
```

It doesn't seem like error messages are making it to your screen so you may also have to dig through the logs generated in `./.snakemake/log/` to see the root causes of some of these.

**Comment by cornhundred** [comment]
Hi @brianpardy, I'm seeing 

```
$ mafft --version
zsh: command not found: mafft
```

So I guess mafft is not installed. I'll look into how to install it

```
$ augur --version
augur 7.0.2
```

**Comment by brianpardy** [comment]
Perfect!  If you're also missing iqtree you will run into a similar error once you hit the tree step, so make sure that is installed as well.

```
% iqtree --version
IQ-TREE multicore version 2.0-rc2 for Linux 64-bit built Mar 28 2020
Developed by Bui Quang Minh, Nguyen Lam Tung, Olga Chernomor,
Heiko Schmidt, Dominik Schrempf, Michael Woodhams.
```

I'm using 2.0-rc2 but the stable 1.6.12 release works just fine too.

**Comment by cornhundred** [comment]
I was missing that (ran `conda install -c bioconda iqtree`), we'll see if installing it mid-run works :)

**Comment by cornhundred** [comment]
thanks @brianpardy! those instructions worked. It took ~10 hours to run on two cores of laptop.

**Comment by AngelaYoon** [comment]
I also downloaded SARS-CoV-2 from GISAID. I updated all mafft (v.7.471), augur (v.9.0.0) and iqtree (v.2.0.3).
However I got the error below which seems slightly different from others. Also I am fairly new to the nextstrain tree building so I'd appreciate for some explanation on Error: b".
```
using mafft to align via:
        mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 1 results/aligned.fasta.to_align.fasta 1> results/aligned.fasta 2> results/aligned.fasta.log

        Katoh et al, Nucleic Acid Research, vol 30, issue 14
        https://doi.org/10.1093%2Fnar%2Fgkf436


ERROR: b''
shell exited 1 when running: mafft --reorder --anysymbol --nomemsave --adjustdirection --thread 1 results/aligned.fasta.to_align.fasta 1> results/aligned.fasta 2> results/aligned.fasta.log  

Error during alignment
```

**Comment by tsibley** [comment]
@AngelaYoon There should be more information in mafft's error log. After that error happens, what does `results/aligned.fasta.log` contain?

**Comment by AngelaYoon** [comment]
@tsibley Thank you for the quick reply! My ```results/aligned.fasta.log``` contained 
```
inputfile = orig
69567 x 32238 - 29016 d
nthread = 1
nadd = 0
inputfile = infile
thresholdtorev = 0.000000
reflim = 5000
mode = a
generating a scoring matrix for nucleotide (dist=200) ... done

Allocation error( 32239 int vec )
directionfile = _direction
inputfile = infile
subalignment = 0
subalignmentoffset = 0
69567 x 32238 - 29016 d
Format error!
```
I'm not sure what format error mean since I passed the augur filter subcommand with no problem.

**Comment by tsibley** [comment]
@AngelaYoon Sorry that this issue fell through the cracks. I'm sure you've moved on one way or another by now, but for posterity, this looks to me like a case where mafft ran out of available memory (particularly because of the `Allocation error( 32239 int vec )` message in the log).
