### ISSUE TITLE
[Language translation request]

### ISSUE THREAD

**Issue by thaodoanng** [nextstrain/ncov#356]
**What language would you like the situation reports to be translated into?**  

I would love to translate the report into Vietnamese

**Are you available to help translate?** (Either way is alright, just let us know! :)

Yes, I would love to help out with the translation as I’m a native Vietnamese speaker and I’ve studying in the States for 4 years so that would help me to fluently translate the report.

**Comment by cassiawag** [comment]
Hello @thaodoanng, we would love to have translations in Vietnamese! Thank you so much for offering. 

What's your professional background and do you have anyone else who can help with the translation? Standard rules for translation are that each translation must be seen by at least two people, and one of those people should have a background in phylogenetics.

**Comment by thaodoanng** [comment]
I'm a second year nursing student in Vietnam and I do have peers with master degrees that can help with translation. For the background in phylogenetics, does it require both of the peers to be in those exact same two major related to phylogenetics? Both of my desired peers are studying for Biology MD and their focus are on Virology and Microbiology. Thank you for answering my request!

**Comment by cassiawag** [comment]
Hi @thaodoanng, both translators do not need background in phylogenetics, but at least one definitely does. We actually may be able to produce Vietnamese translations shortly, via another mechanism. So let's hold off for now, but I'll reach out later this week to let you know.

**Comment by thaodoanng** [comment]
Hi @cassiawag, I just want to see if there is an update on this. Thank you and have a great day!

**Comment by cassiawag** [comment]
Hi @thaodoanng, thanks for reaching out! We do not have a plan to produce a Vietnamese narrative this week; though we're open to it :) Did you find anyone for proofreading?

This week's narrative is on North America btw. So I think it could still be useful for Vietnamese speakers, but less than useful than our previous globally focused reports.

Best,
Cassia
