### ISSUE TITLE
[Language translation request] Polish

### ISSUE THREAD

**Issue by mstefaniak** [nextstrain/ncov#363]
**What language would you like the situation reports to be translated into?**  
Polish

**Are you available to help translate?** (Either way is alright, just let us know! :)
Yes

**Comment by mstefaniak** [comment]
I'm sorry. I was thinking about translating auspice front-end part.

**Comment by cassiawag** [comment]
That would be fantastic! Here's the guide on how to do so: https://github.com/nextstrain/auspice/blob/master/DEV_DOCS.md#contributing-to-internationalization-and-localization-i18nl18n
