### ISSUE TITLE
non-subsampled .json output on nextstrain.org 

### ISSUE THREAD

**Issue by arpoe** [nextstrain/ncov#364]
I have been using the nextstrain.org global output (.json) for another project. This approach is now very limited due to the subsampling. 
I understand that for visualisation this is the way to go, but would it be possible to generate the full output as a .json anyway? 
This would not also provide the data I need for my project, but also allow others to visuallise the trees with custom subsampling. 
It would be highly appreciated as it would save me the time to run everything locally.

**Comment by emmahodcroft** [comment]
Hi @arpoe , thanks for reaching out! We are currently thinking about some ways to support this. We will try to update everyone if we find a way to go forward with this kind of idea!

**Comment by arpoe** [comment]
Thank you very much! I am looking forward to it! 
Your decision to subsample coincided with the moment that the mutations just got enough numbers for this project so that the results improved a lot and we started wrapping up ;-)
Please keep me posted, because as you can imagine, I am eager to through our findings out there.

**Comment by emmahodcroft** [comment]
As a short term alternative, if you have access to a cluster, I'd highly recommend running there! If you set 16 cores for the main, not-subsampled build, you can multi-thread IQTree, which will speed things up (it'll still take hours, unfortunately, but hopefully <5). Pass through the number of cores you are able to use with `--set-threads tree=16` (or whatever the number is) to overrule our default use of 4 (if 4 are available).

I hope that might help in the short-term!

**Comment by arpoe** [comment]
Thank you, this is indeed my backup plan ;-) 
Currently it is not possible, because my GISAID login data seem to have been deleted from their system.... but I am also working on fixing that.

**Comment by arpoe** [comment]
@emmahodcroft, are there by chance any updates on this? 
I now have access again to GISAID, but can still not bulk download the data, so I am still keen on non-subsampled nextstrain output...

**Comment by emmahodcroft** [comment]
Hi @arpoe - I'm afraid not! Unfortunately we are a fairly small team with a fairly big job at the moment, and a big priority on the immediate functionality & maintenance of the site, so, new things don't happen as quickly as we'd like sometimes :) 
If we introduce this I will try to ensure you know about it, though!

**Comment by arpoe** [comment]
And indeed you are doing a great job with that! Thank you very much!

**Comment by jameshadfield** [comment]
@arpoe you can see a non-subsampled build I ran yesterday at https://dev.nextstrain.org/ncov/non-subsampled -- a few outliers, missing lat-longs etc but may help you!

**Comment by arpoe** [comment]
Oh, thank you, you are an Angel! I still dont have access to the GISAID download button, so this will be so helpful! 
Where would I find the .json with it? I am using the .json file for further processing. 
From there I think I can just remove outliers by excluding every virus with more than 10 mutations since the last node. So outliers should not be a problem.

**Comment by arpoe** [comment]
I have now processed it to extract the mutations. That the nodes are not assigned to a country is indeed a bit of a problem, because now I have 1/4 of the mutations without association to a country. Would it be possible to include that?

**Comment by emmahodcroft** [comment]
Hi @arpoe,unfortunately due to the size of the tree we aren't doing ancestral trait reconstruction on this true. However, one should be very wary at putting weight on these ancestral reconstructions anyway - they are highly influenced by sampling, which we know is not even across the tree (lots of clades trace back to being USA/England/Netherlands just due to sampling numbers). We really can't say with confidence where a mutation may have arisen geographically, except in a few cases! So I'd use that data with great caution :)

**Comment by arpoe** [comment]
Thank you, for my question this insecurity was ok. However, I think I should also be fine without the regional reconstruction.

**Comment by jameshadfield** [comment]
Yesterday's GISAID dataset: https://nextstrain.org/ncov/non-subsampled/2020-04-30 with 12.3k tips!

**Comment by trvrb** [comment]
With over 300k genomes, subsampling for phylogenetics is unavoidable. We're looking into strategies to mitigate this general issue, but believe this specific GitHub issue can be closed without resolving due to technical lift required.
