### ISSUE TITLE
3 minor features

### ISSUE THREAD

**Issue by jiehuang001** [nextstrain/ncov#365]
Hi, there:

I have 3 feature requests. Hopefully you guys echo some of these.

1. It would be nice to have an "export" button, to export the aligned sequences. I understand that the web version might not be able to do that, since the GISAID data has access control. But hopefully users could have such a button when they install nextStrain locally with their own data.

2. At the top, under “showing 3958 of 3958 genomes sampled between Dec 2019 and Apr 2020”, it would be nice to have a little bit more information, such as: a total of XXX mutations, XXX haplotypes, XXX haplogroups. I still don't know how to find the total number of haplotypes and haplogroups.

3. Right now, when I move mouse over a dot, a new small pop-up window shows some text. However, there is no way for me to take a screenshot, because the pop-up window will disappear when I move my mouse to use my screenshot tool. It would be nice to allow single clicking to display the pop-up window. That is available in IGV.

Finally, I have a question: after I click the “RADIAL”layout, I found the dot in center shows “Country confidence: 77% Belgium, 22% China”. What does this mean? It is more likely that the virus origins from Belgium than from China?
  
Best regards,
Jie

**Comment by emmahodcroft** [comment]
Dear Jie,
I hope I can help you out quickly with some of these.
1. Online we cannot supply any sequencing data as per the GISAID agreement, as you understand. If you are running locally, you can always see a copy of the aligned sequences by looking for a file in the `results` folder called `aligned.fasta` (or `masked.fasta` if you prefer a masked version). 
2. The total number of mutations across all sequences is not, scientifically, a very useful number usually, so I'm afraid we are unlikely to include this. We do not classify any haplotypes so we will not report these.
3. If you click on a dot, then you will have a pop-up that shows you all of the information about that strain - and this remains until you click elsewhere over the tree. I hope this helps you to record the data better! If you want to take a screenshot of a mouseover, I'd suggest using a screenshot program which allows a 'delay' in the screenshot - this allows you a few seconds to position your mouse after clicking the screenshot button. 

Regarding the radial view, in this view it is hard to draw the root correctly, and so what you are mousing over is not truly the root - there are too many points at the 'center' of the graph to be able to mouse over them correctly. The best view is the rectangular view, which more clearly shows which point is the root. If you view this here, you can see the root is 100% Chinese, as we expect.
![image](https://user-images.githubusercontent.com/14290674/79465034-20adc780-7ffb-11ea-911f-961cb52e5ec9.png)


I hope this helps!

**Comment by jiehuang001** [comment]
Dear Emma:

Thank you very much again for your detailed explanation. . Here is my follow-up:

1. I think the “total number of mutations across all sequences” is actually a very good summary. A lot of publications report such statistics, something like "we examined 100 genomes, found 20 mutations, 10 of them are protein-coding. And we found these 100 genomes belong to 11 haplogroups". So, it would be really nice if there is a way for nextstrain to display key summary info like this.  I can see that the total number of mutations is different from "divergence". For example, if A is ancestry, B has 5 divergence from A, and C also has 5 divergence from A. There could be a total of 5 to 10 mutations in total depending on the overlap between B and C.

2. Since you mentioned that users can find aligned sequence data locally in the results/ folder, maybe can you please give some hint on how to generate such summary statistics from the alligned.fasta file?

3. A related question: how sequencing error is dealt with by nextstrain, especially given the fact that 3rd generation using nanopore has a relatively high sequencing error rate and virus genome data was uploaded by users world-wide without a good way to double check. As we can imagine, if a genome got a root-level mutation by sequencing error rather than a real mutation, it could get pushed from the branches to the root of the tree. Is there an algorithm to deal with this? 

4. I understand “substitution” is just one type of “mutation”, and there are more complicated types of mutations such as insertion and deletion and maybe also copy number variation. Will nextstrain be able to use any other mutation types such as insertion and deletion for making the phylogenic tree?  

5. What does the word "nextstrain" exactly intend to mean? In human genome sequencing, people use the world "next" generation sequencing to mean a new technology. Does "strain" here mean a species type, therefore "nextstrain" literally means that you guys intend to use this method to analyze more species?

6.  Please see the screenshot below. When I click on a dot, the pop-up window got enlarged and blocked the whole window. I am wondering how you generated the screenshot that you showed in the previous message.

You guys really made an extraordinary contribution to the scientific community!

Best regards,
Jie


![捕获](https://user-images.githubusercontent.com/26947455/80422170-43e84900-8910-11ea-92f7-7c38b073b9ce.JPG)

**Comment by jielab** [comment]
I would deeply appreciate if someone could quickly reply to the above message that I posted 10 months ago. Vow, time flies. Certainly the pandemic will end in 2021, no more !

Best regards,
jie
