### ISSUE TITLE
Spanish

### ISSUE THREAD

**Issue by sofiamuller93** [nextstrain/ncov#370]
**What language would you like the situation reports to be translated into?**  
Spanish

**Are you available to help translate?** (Either way is alright, just let us know! :)
Yes!

**Comment by cassiawag** [comment]
Hi Sofia! Thank you so much for your offer; we __use__ some help with the Spanish translations.

Reports are published weekly on Friday around 5 p.m. PDT. Our goal is to publish translations by Monday morning PDT, but for many languages we're publishing sooner. I've got a three phylogenetics folks who have been translating the Spanish reports, but they all have pressing time constraints. If you could do the first translation and then the folks in the field could proofread it for scientific accuracy, that would help us out a lot. 

Knowing more about the commitment, are you still interested in helping to translate?

**Comment by cassiawag** [comment]
Hi @sofiamuller93, just want to follow-up and see if you're still interested in helping with translations? This week's situation report is out, and we would love your help with the translation!

**Comment by cassiawag** [comment]
@msaavedra1026 - awhile ago, you offered to help with Spanish translations of the Nextstrain situation reports. Any interested in still helping out? We could use a few more translators!

**Comment by msaavedra1026** [comment]
Hi, yeah absolutely.

I also know at least one other person that could also help as well.

**Comment by cassiawag** [comment]
Awesome -- remind me of your background again?

**Comment by msaavedra1026** [comment]
Psychology B.A

Experience in sales & risk management with a fluent background in Spanish

**Comment by cassiawag** [comment]
@msaavedra1026 -- I've added you to the Nextstrain org and tagged you in a couple issues. Please accept the invitation!
