### ISSUE TITLE
rule ancestral: not inferring ambiguous mutations? 

### ISSUE THREAD

**Issue by mohammedkhalfan** [nextstrain/ncov#374]
Hello,

Thank you for the easy to use tools and great documentation. I have a question about one of the rules in the main Snakemake file. In the message it says "not inferring ambiguous mutations", but then the `--infer-ambiguous` flag is used, which according to the doc: infer nucleotides at ambiguous (N,W,R,..) sites on tip sequences and replace with most likely state. (default: False). Either the message is incorrect, the flag should not be passed, or I misunderstand. Here is the rule: 

```
rule ancestral:
    message:
        """
        Reconstructing ancestral sequences and mutations
          - not inferring ambiguous mutations
        """
    input:
        tree = "results/tree{region}.nwk",
        alignment = rules.mask.output
    output:
        node_data = "results/nt_muts{region}.json"
    params:
        inference = "joint"
    shell:
        """
        augur ancestral \
            --tree {input.tree} \
            --alignment {input.alignment} \
            --output-node-data {output.node_data} \
            --inference {params.inference} \
            --infer-ambiguous
        """

```

**Comment by emmahodcroft** [comment]
@mohammedkhalfan , Thank you for spotting this! Yes, this discrepancy is an oversight on our part - we used to *not* infer ambiguous mutations, but about a month ago we changed this - and clearly forgot to update the message! I will change this now so it's more consistent.

Thanks so much for your kind words about our program - it's really great to hear that it's being useful and easy to implement! And thanks again for catching this!
