### ISSUE TITLE
Russian Translation of 30 Jan Situation Report

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#38]
Thanks to @ivan-aksamentov, we have a Russian translation! I will push live tomorrow if we are ready. Ivan, if you hadn't seen it yet, here's the preview link, so you can check it out: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ru/sit-rep/ru/2020-01-30

A couple of the markdown links are broken (space between the ] and ( in `[link text](link)` ). I can fix this very easily tomorrow if needed - don't worry about it!

I think Vadim may proofread before push - will tag him here when added! @vpuller

**Comment by ivan-aksamentov** [comment]
@emmahodcroft thanks.
I will push an update with md links corrected and some other little adjustments soon.

**Comment by emmahodcroft** [comment]
When this is ready to go, what would you suggest as the 'card' title, which will appear on the main Nextstrain.org page? https://nextstrain.org/
From the narrative translation, my guess would be "Ситуационный отчет 2020-01-30" - would this work?

**Comment by ivan-aksamentov** [comment]
@emmahodcroft Yes this will work

**Comment by emmahodcroft** [comment]
Situation Report in Russian now live at : https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-01-30

The tiles on the main page have also been updated, and the Nextstrain Twitter account has tweeted! 

Thank you for the hard work!
