### ISSUE TITLE
Mutations mentioned in Clades.tsv are not matching with the phylogenetic tree in nextstrain

### ISSUE THREAD

**Issue by ravichandranori** [nextstrain/ncov#383]
Schema mentioned for labeling clades in clades.tsv file is not matching with the mutations mentioned in the phylogenetic tree in the nextstrain website. 

Are there any other criteria for labeling clades other than the mutations in clades.tsv. If so, please let me know that would be very helpful.

Thank you

**Comment by emmahodcroft** [comment]
Hi @ravichandranori , I'm sorry you are having trouble. However, the clade definitions that are part of `config/clades.tsv` are indeed the ones which we use to designate the clades on the website. 

Do note that if more than one mutation is used to define a clade, it will only be where both mutations are present that the clade is defined. Mutations are cumulative from the root, so one mutation may arise, then another further up the tree - the clade definition would be at the second one. 

I hope that helps!

**Comment by ravichandranori** [comment]
So just to reconfirm, you mean there is no functional link for the given clade names and these names are given just for visualization purpose.
Thank you!

**Comment by emmahodcroft** [comment]
Yes, these clades are just for viz purposes, you are correct! We will be moving to a more long-term clade naming system very soon!
