### ISSUE TITLE
[Feature request] nextstrain build with Docker using multicore

### ISSUE THREAD

**Issue by TrentBrick** [nextstrain/ncov#384]
Given that the number of SARS-Cov-2 sequences is increasing so rapidly I want to use multicore to run my analysis. 

I found with Nextstrain CLI the call to `snakemake` allows for `--cores 8` to set the number of desired cores. 

But could not find similar documentation for using Nextstrain with Docker. I got it working with `nextstrain build . --cores 8` but also had to be sure to allow my Docker environment to use this number of cores. These things were both found through trial and error. Sorry if there is some clear documentation I missed here but in case there isn't I wanted to flag that there should be somewhere.

Thank you.

**Comment by tsibley** [comment]
@TrentBrick Thanks for the feedback! The interaction of options can indeed be confusing, but we'd definitely like to improve our documentation.

We're in the process of improving how the build works to make it easier for other folks, like yourself, to run it. Part of this is a re-organization of the workflow and the other part is more docs. I do think this particular point of confusion will be addressed by that effort.

**Comment by trvrb** [comment]
We've updated parameters specifying cores in `ncov`. We now use a snakemake `config.yaml` file that takes an option for `cores`. I _think_ this resolves this issue. Will close now, but could be re-opened.
