### ISSUE TITLE
[Feature request] Support local data injection in workflow

### ISSUE THREAD

**Issue by tsibley** [nextstrain/ncov#390]
The [documented steps for injecting local data into the workflow](https://github.com/nextstrain/ncov/blob/20974e93a647cc17595718561a69eb02a42a4e5a/docs/running.md#combining-the-data) are currently manual and fraught with peril such as line ending mismatches, the lack of final newlines in files, and column orderings.

It would be less error-prone and more robust to add first-class support for local data injection into the workflow rules. This support would be able to make sure that all the above problems and more are handled properly (or that they at least raise an obvious error).

**Comment by huddlej** [comment]
This issue was mostly addressed by #550, but we still need to update the tutorial to reflect the support for multiple inputs via the configuration file and to remove references to manually concatenating sequences and metadata.

**Comment by huddlej** [comment]
This is now documented better in [the data prep guide](https://github.com/nextstrain/ncov/blob/ecded90fd3af632ca9c73c79aaac762022a15eca/docs/src/analysis/data-prep.md).
