### ISSUE TITLE
[BUG] metadata.tsv file was removed

### ISSUE THREAD

**Issue by pwrose** [nextstrain/ncov#396]
We automatically upload this file on a daily basis for data analysis.

Manual download from GISAID it not a solution!

In a time of crisis, it is irresponsible to add barriers to data access!

Please add this feature back.

**Comment by emmahodcroft** [comment]
Dear @pwrose , I'm very sorry this is frustrating. I realise this is providing a hitch in workflows for some people. Unfortunately, GISAID requested that we stop sharing this file as it broke the terms of use specifying "You agree not to distribute Data to any third party other than Authorized Users as contemplated by this Agreement."

As we use GISAID data, we must comply with the user agreement terms. The data is now available through the GISAID site - you can find the instructions here: https://github.com/nextstrain/ncov/blob/master/docs/running.md#obtaining-global-data-through-gisaid

I hope this helps!

**Comment by pwrose** [comment]
Thanks for the explanation, Emma.
