### ISSUE TITLE
[BUG] GISAID Acknowledgement Table

### ISSUE THREAD

**Issue by TrentBrick** [nextstrain/ncov#399]
GISAID requests all data providers are acknowledged in publications. With the new GISAID nextstrain sequence and metadata specific downloads, where is the acknowledgement table for this data? 
Trying to download the GISAID acknowledgement table from the download section of their website directly restricts me to 10,000 sequences. 

Thank you,
Trenton

**Comment by emmahodcroft** [comment]
Hi @TrentBrick - thanks for reaching out. Unfortunately we are not involved with generating the GISAID acknowledgement table. We are happy to provide the files (metadata and sequences) which can be used by registered GISAID users for analyses, but those are the only files on the GISAID website that we compile at Nextstrain. 

I would suggest you reach out directly to GISAID to let them know about this issue with the acknowledgement table limit, and hopefully they can assist you!

**Comment by ytye2010** [comment]
the same question for the limitation of 10,000 to attain the acknowledgement table. May I ask how do you sort this problem? @TrentBrick
