### ISSUE TITLE
getting an error when running default pipeline with assign-colors.py[BUG]

### ISSUE THREAD

**Issue by cychiu98** [nextstrain/ncov#400]
**Current Behavior**  
I have installed Augur, Auspice, and nextstrain and am running the pipeline using metadata and sequences for SARS-CoV-2 downloaded from GISAID. When I run the default pipeline (using "snakemake --profile profiles/default"), it halts because of this error:

        python3 scripts/assign-colors.py             --ordering config/ordering.tsv             --color-schemes config/color_schemes.tsv             --output config/colors_global.tsv             --metadata data/metadata.tsv 2>&1 | tee logs/colors_global.txt
        
Traceback (most recent call last):
  File "scripts/assign-colors.py", line 59, in <module>
    color_array = schemes[len(trait_array)]
KeyError: 554
[Sat May  9 22:01:07 2020]
Error in rule colors:
    jobid: 7
    output: config/colors_global.tsv
    log: logs/colors_global.txt (check log file(s) for error message)
    shell:
        
        python3 scripts/assign-colors.py             --ordering config/ordering.tsv             --color-schemes config/color_schemes.tsv             --output config/colors_global.tsv             --metadata data/metadata.tsv 2>&1 | tee logs/colors_global.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of fail

**Expected behavior**  
I expected the pipeline to finish.  

**How to reproduce**  
Steps to reproduce the current behavior:  
1. You can reproduce the current behavior with running assign-colors.py on the command line:

(nextstrain) charles@MacBook-Pro ~/Desktop/ncov> python3 scripts/assign-colors.py --ordering config/ordering.tsv --color-schemes config/color_schemes.tsv --output config/colors_global.tsv --metadata data/metadata.tsv 
Traceback (most recent call last):
  File "scripts/assign-colors.py", line 59, in <module>
    color_array = schemes[len(trait_array)]
KeyError: 554
 
**Possible solution**  

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   macOS Cataline 10.15.3
 - Browser:  Google Chrome
 - Version (e.g. `auspice 2.7.0`):  

nextstrain.cli 1.16.5
auspice 2.15.0
augur 7.0.2

**Additional context**

**Comment by emmahodcroft** [comment]
Hi @cychiu98 - thanks for posting the bug! I'm sorry about this - it looks like we've exceeded the number of colours that are available by having too many divisions in the default build! We should be able to fix this by generating some more colours and adding them to the file - you should be able to update with this change.

I'm tagging @trvrb as he should be able to update the colour list and let you know when this is done so you can update (`pull`) and try again! 

I apologise once again for this delaying you!

**Comment by trvrb** [comment]
Sorry about this @cychiu98. I've updated the `colors_schemes.tsv` file with 7377334c77cdf14cfb5f78e4be2936c0567d8b87. Updating to `master` should resolve your error.

**Comment by rneher** [comment]
I think this was resolved. please reopen if not.
