### ISSUE TITLE
GISAID sequences from Croatia not shown on the tree

### ISSUE THREAD

**Issue by NoaCemeljic** [nextstrain/ncov#407]
**Current Behavior**  
I am using Nextstrain to construct phylogenetic trees of GISAID CoV sequences. I've used a lot of sequences from various countries and they all work fine, except for the sequences from Croatia. When I run a tree-time command on a set of sequences, those from Croatia are just thrown out from the further analysis (e.g." pruning leaf hCoV-19/Croatia/7R-S8/2020"). I've also noticed that Croatia is not featured on your phylogenetic tree (https://nextstrain.org/ncov), although the sequences are uploaded on GISAID. Do you know what could be the reason for this?

**Expected behavior**  
GISAID SARS-CoV-2 sequences from Croatia to be featured in the constructed phylogenetic trees.

**Comment by emmahodcroft** [comment]
Dear @NoaCemeljic , thank you for reaching out! During the `refine` step sequence are removed from the run if they are 4 or more interquartile distances away from the estimated substitution rate. This means that these sequences are either far more divergent or far less divergent than we expect, given what we know about the evolution of SARS-CoV-2. This usually indicates some kind of sequencing, mapping, or alignment error, so they are automatically removed. You can change the  `clock_filter_iqd` setting to a higher number in `config/config.yaml` (or remove the argument altogether from `refine` in `rules/builds.smk`). I hope this helps!

**Comment by NoaCemeljic** [comment]
It works now, thanks a lot for the help!

**Comment by emmahodcroft** [comment]
Great! Glad that helped!
