### ISSUE TITLE
GISAID not allowing access to data

### ISSUE THREAD

**Issue by zawy12** [nextstrain/ncov#411]
About a month ago I tried to register in GISAID but they will not approve the registration. I assume it's because they say using yahoo mail and not including an institution lowers your "priority" for permission to get access.  

Is there a publicly available repository for the sequences?

**Comment by emmahodcroft** [comment]
Hi @zawy12  - I'm sorry to hear that you've had trouble accessing the data. However, we don't control data access - the data we use comes from GISAID, and they regulate access to their data. I can only recommend that you contact GISAID to ask about your application for registration. Unfortunately, we can't help you here. 

As the data on GISAID is protected by the Terms of Service for using GISAID, it is only available through GISAID, not through other sources. However, there is public SARS-CoV-2 data available on Genbank. This isn't as many samples as area available on GISAID, but perhaps this can be useful to you.

I'm sorry this doesn't solve your inquiry, but wish you luck.

**Comment by zawy12** [comment]
The $230k Open Science Award you won for this work in 2017 is to promote open data, that is, "to unleash the power of open content and data". I'm not sure how to view "open source" that depends exclusively on closed data.

**Comment by emmahodcroft** [comment]
@zawy12 I realise this is frustrating for you, and I'm sorry. However, we have no control over where people submit their data, nor the exact restrictions data repositories use to protect their data and the data submitters. 

I cannot comment on why your application for GISAID may be delayed, but I know thousands of people have been granted access to the data, and use our open-source pipeline and tools to study SARS-CoV-2. I'm sorry that we can't help you further.

**Comment by zawy12** [comment]
Do you have plans to support publicly-available data like Genbank?

**Comment by emmahodcroft** [comment]
Yes, we are working on this. At the moment, de-duplication is an issue, as naming isn't consistent. However, we know this is something in demand, and we are working hard to try to get it up and running!
