### ISSUE TITLE
[BUG] Syntax error while running default build

### ISSUE THREAD

**Issue by Addicted-to-coding** [nextstrain/ncov#416]
Hi,
I'm trying to run a default build using a test file containing one fasta sequence and a metadata file with one entry according to the described format. When I run the command snakemake --profile profiles/default, I get the error:
SyntaxError in line 161 of /home/vs/ncov/rules/builds.smk:
invalid syntax
  File "/home/vs/ncov/Snakefile", line 53, in <module>

I tried replacing return f"results/ with return "results/ on line 161 of builds.smk, which resolved the error but many such similar errors appeared in all the three smk files in the rules folder. How can I fix this?
 My OS is ubuntu and nextstrain, auspice and augur have been installed successfully.

**Comment by rneher** [comment]
thanks. What python, snakemake version are you using? 

`f"results/{wildcards.build_name}/proximity_{subsampling_settings['priorities']['focus']}.tsv"`

should be a valid f-string in python >=3.6

**Comment by Addicted-to-coding** [comment]
I'm using snakemake version 5.10.0. I've also got Python 3.7.6 installed

**Comment by rneher** [comment]
strange. I can't reproduce this. Also on Ubuntu with snakemake  5.10 but python 3.6.10.

**Comment by Addicted-to-coding** [comment]
That's weird. Here's a screenshot 
![Screenshot from 2020-05-23 21-55-10](https://user-images.githubusercontent.com/28642161/82735559-43d93e80-9d40-11ea-82e4-5f05065ddca3.png)

**Comment by rneher** [comment]
could you try running it in the nextstrain conda env?

https://nextstrain.org/docs/getting-started/local-installation#install-augur--auspice-with-conda-recommended

just to limit the number of moving parts?

**Comment by Addicted-to-coding** [comment]
Thanks, that worked. Now, all of my samples are being dropped from the analysis during the filter step. The exclude file does not exist, could you please upload it?

**Comment by emmahodcroft** [comment]
Hi @Addicted-to-coding - the exclude file that we are using is here: https://github.com/nextstrain/ncov/blob/master/config/exclude.txt

You could try adding your sequences to the `include.txt` file (same location), which should prevent them getting dropped, but it would be good to know why they are being dropped. For example, if they do not have a full date (year, month, day) then they'll be excluded.

**Comment by Addicted-to-coding** [comment]
Thanks a lot, that worked!

**Comment by Addicted-to-coding** [comment]
Hi,
I'm trying to run a default build again for the most recent version of the github repo. However, when I run :

snakemake --cores 4 --profile ./my_profiles/getting_started

I get the error:

SyntaxError in line 35 of /home/vc/Downloads/COVID/ncov/workflow/snakemake_rules/main_workflow.smk:
invalid syntax
  File "/home/vc/Downloads/COVID/ncov/Snakefile", line 94, in <module>

I'm running the analysis in the nextstrain environment and I'm using snakemake version 5.25.0 and python version 3.6.12. How can I fix this?

**Comment by emmahodcroft** [comment]
Hi @Addicted-to-coding - oh dear. This one's on me - my apologies! While fixing something this morning I managed to omit a comma, and for some reason our checks didn't fail due to this. I've just pushed a fix and done a dry run on our cluster - hopefully it should work now!

`git pull` the latest to the `ncov` directory and hopefully the `snakemake` command should work now without the error!

**Comment by Addicted-to-coding** [comment]
Thanks for the quick reply, it works now!
