### ISSUE TITLE
Augur refine error when running the default build

### ISSUE THREAD

**Issue by NoaCemeljic** [nextstrain/ncov#417]
**Current Behavior**  
Hello, I am encountering an error when running your default build with my GISAID sequences on Job 6: Refining Tree.  The job can't be finished because it returns a "ValueError: target 'Wuhan-Hu-1/2019' is not in this tree".  The command under Job 6 is as follows:

augur refine             --tree results/global/tree_raw.nwk             --alignment results/global/subsampled_alignment.fasta             --metadata data/metadata.tsv             --output-tree results/global/tree.nwk             --output-node-data results/global/branch_lengths.json             --root Wuhan-Hu-1/2019 Wuhan/WH01/2019             --timetree             --clock-rate 0.0008             --clock-std-dev 0.0004             --coalescent skyline             --date-inference marginal             --divergence-unit mutations             --date-confidence             --no-covariance             --clock-filter-iqd 4 2>&1 | tee logs/refine_global.txt

**Expected behavior**  
Finishing Job 6 and proceeding on with the build.

Can you tell me what is the cause of this issue? Thanks a lot!

**Comment by rneher** [comment]
Could you confirm whether  'Wuhan-Hu-1/2019' is or is not in the tree and the alignment?

**Comment by NoaCemeljic** [comment]
The alignment and building tree jobs were performed without problems. When proceeding to this step, this error occurs.

**Comment by rneher** [comment]
yes. please check whether the seqences Wuhan-Hu-1/2019 and Wuhan/WH01/2019 are in your data.

**Comment by NoaCemeljic** [comment]
I don't think they are, how do I add them there? This was put by default under augur refine --root when running the build.

**Comment by emmahodcroft** [comment]
@NoaCemeljic These sequences are available on GISAID - you can search for the strain names in the `Virus name` box of the GISAID interface, and there you can download and add them to your larger dataset (copy the contents of these files into `sequences.fasta` and `metadata.tsv`). I hope that helps!

**Comment by NoaCemeljic** [comment]
Thank you for your help. However, when I copy the GISAID contents of these two strains into sequences.fasta and metadata.fasta (containing the info on GISAID sequences I'd like to analyze) I get the error on Job 11:
WARNING: no valid year, skipping hCoV-19/Wuhan-Hu-1/2019 Human
WARNING: no valid year, skipping hCoV-19/Wuhan-Hu-1/2019 Human
And then a bit later:
ValueError: time data '' does not match format '%Y-%m-%d'
After that the build stops and I can't proceed to the augur refine step which was causing me the problems before.

**Comment by emmahodcroft** [comment]
Hi @NoaCemeljic! Ah, I think I know the problem. The metadata is not formatted correctly. Are you able to download the metadata file from GISAID? This is our metadata which is formatted correctly? You can find the instructions to do this here: https://github.com/nextstrain/ncov/blob/master/docs/running.md#obtaining-global-data-through-gisaid

This would give you the metadata in the correct format. Then you can copy and paste the corresponding rows (for these sequences) into the metadata.tsv file you already have, and this should work. I hope that helps!

Otherwise, we also have instructions for how the metdata must be formatted, and this could be done manually for these two rows: https://github.com/nextstrain/ncov/blob/master/docs/metadata.md

**Comment by NoaCemeljic** [comment]
Hey @emmahodcroft, I managed to find the solution with your help :) The problem was that the sequences for these two viruses were named **hCoV-19**/Wuhan-Hu-1/2019 and **hCoV-19**/Wuhan/WH01/2019 in GISAID fasta files, while in GISAID metadata.tsv they didn't have the "hCoV-19" prefix. Manually deleting the "hCoV-19" in fasta files for these two sequences solved the problem.
Thank you so much for your help!
