### ISSUE TITLE
[Feature request] Clade update

### ISSUE THREAD

**Issue by yhkim1006** [nextstrain/ncov#429]
The clade definition used in GISAID seems to have changed recently.
(ex. O, A2, A2a, B, B1 -> 19A, 19B, 20A, etc.)
I want to get the new clade name with the assign_clades.py, but script provide only the old clade (A2a, B, B1 etc.).
Can I get the new clade result in this pipeline ?
(E.g. 19A, 19B, 20A, etc.)

**Comment by emmahodcroft** [comment]
Dear @yhkim1006, Thanks for reaching out! I'm not entirely sure of what's going wrong here. Have you ensured you have the latest copy of the `ncov` Github repository? The script `assign_clades.py` uses the clade definitions in `config/clades.tsv`, so really the only way it can be giving you old clades is if this file is outdated. Ensure yours matches the copy online: https://github.com/nextstrain/ncov/blob/master/config/clades.tsv

Let me know if this helps!

**Comment by yhkim1006** [comment]
Dear @emmahodcroft , I updated config/clades.tsv and It works perfectly !
Thank you so much!
