### ISSUE TITLE
[BUG] Trying to use a Subset of strains

### ISSUE THREAD

**Issue by HarmanDotpy** [nextstrain/ncov#430]
**Current Behavior**  
I have used last 3000 strains from the GISAID fasta file as my sequences.fasta and my metadata.tsv has info about all 40k genomes on GISAID.
I ran into an error towards the end of the process while the process was making auspice sons (I think)
Heres the error - 
![image](https://user-images.githubusercontent.com/50492433/84042869-3fa95400-a9c3-11ea-9ca5-4b08c2bd2500.png)

Previously I have been able to run the example data correctly

**How to reproduce**  
Steps to reproduce the current behavior:  
1. copy last 3k sequences from GISAID fasta file to sequences.fasta
2. run snakemake command   

**Your environment: if running Nextstrain locally**  
 - Operating system: Windows (using WSL - Ubuntu)
 - Version (e.g. `auspice 2.7.0`) :   auspice 2.16.0, nextstrain 2.0.0

**Questions**  
I would like to know how to use a smaller subset of the global data and run it using nextstrain?
Do I have to have to subsample the metadata too? to have info of only those sequences in the sequences.fasta file.

Thanks
Harman

**Comment by emmahodcroft** [comment]
Dear @HarmanDotpy - thanks you for reaching out! I'm very sorry about this, this was an error which was introduced this morning accidentally. I've just fixed this on master, and if you `git pull` the latest from the repository, the issue should be resolved, and the last few steps of your run should finish without issue! Again, apologies for this inconvenience!

**Comment by HarmanDotpy** [comment]
I pulled the latest just about half an hour ago I think, I'll try to do it once more.
Thanks for the prompt response

**Comment by emmahodcroft** [comment]
The fix is in commit `705627ca7f9b27cbf508e80c8a6a99200d283d97` - the [most recent commit](https://github.com/nextstrain/ncov/commits/master), which I only pushed about an hour ago. Our own builds just crashed due to the bug, and the pulled fix seems to get them going again, but let me know if not!

**Comment by HarmanDotpy** [comment]
Yes it worked, Thanks
