### ISSUE TITLE
Disable subsamling for a specific country?

### ISSUE THREAD

**Issue by biocyberman** [nextstrain/ncov#435]
I looked at issue #431 , this question is related but different: What would my custom subsampling scheme looks like if I want to keep all samples from a specific country and subsample other countries?

**Comment by rneher** [comment]
Our subsampling scheme currently requires the arguments `group-by` and `sequences-per-group`. But you can avoid subsampling by setting the value of `sequences-per-group` to a very high value. This would happen here (or an analogous place):
https://github.com/nextstrain/ncov/blob/master/config/config.yaml#L168

**Comment by biocyberman** [comment]
Thanks for the hint, @rneher . That would disable subsampling for all countries? I just one to enable subsampling for all countries but Denmark for example. Would it be something like the following: 

      seq_per_group: 200
      exclude: "--exclude-where 'country == Denmark'" 

I haven't found the documentation part for `exclude`, or the source code that handles excludes, so the syntax looks incorrect.

**Comment by rneher** [comment]
I see, I think what you are looking for is something like this solution for Switzerland:
https://github.com/neherlab/ncov-swiss/blob/master/profiles/swiss/builds.yaml#L7
https://github.com/neherlab/ncov-swiss/blob/master/profiles/swiss/builds.yaml#L52

this takes 200 sequences from each canton of Switzerland per month (there aren't that many, so it takes everything) and then adds a sample from European countries and the rest of the world.

some more general docs are here:

https://github.com/nextstrain/ncov/blob/master/docs/running.md#configuring-your-build

**Comment by biocyberman** [comment]
@rneher  Thanks. I could figure it out with your hints.
