### ISSUE TITLE
Can we download the whole webpage generated by auspice?

### ISSUE THREAD

**Issue by PeterWu-Biomath** [nextstrain/ncov#441]
I'm working on a cluster,everything runs well,but it is not possible to run browser. I'm trying to dump the webpage and view it at my laptop. I've successfully run auspice and tried wget -r http://localhost:4000/ but what I've got is essentially empty. Is it possible to remedy this?

 file attached is what I've got from wget
[localhost_4000.zip](https://github.com/nextstrain/ncov/files/4811483/localhost_4000.zip)

Thanks very much.

**Comment by jameshadfield** [comment]
Hi @PeterWu-Biomath  -- if you wish to run auspice locally then the best way is to [install auspice](https://nextstrain.github.io/auspice/introduction/install) on your laptop and then visualise the JSON (which is generated by this repo) locally. Instructions [here](https://nextstrain.github.io/auspice/introduction/how-to-run). 

Feel free to reopen if you're still having trouble!

**Comment by PeterWu-Biomath** [comment]
Thanks very much for your reply. 
The case for me is a bit strange, I'm working on windows and I haven't figure out how to run auspice locally. And for some cases I also need to share my results to my colleges and they might need to inspect the result but be unwilling to install auspice. So I'm still curious to know whether dumping webpage is possible.

**Comment by emmahodcroft** [comment]
Hi @PeterWu-Biomath - If you're running Windows it's important you're installing `auspice` and running via Windows Subsystem for Linux (WSL) - you can find the instructions here to set up WSL: https://nextstrain.org/docs/getting-started/windows-help

However, you can then look for `localhost:4000` in your usual browser in Windows. I hope that helps you get it running!

For sharing with colleagues, once you have generated a JSON, you can use http://auspice.us/ and drag-and-drop it here. (You can also use this to view JSONs on your own machine, if that's helpful)

**Comment by PeterWu-Biomath** [comment]
> Hi @PeterWu-Biomath - If you're running Windows it's important you're installing `auspice` and running via Windows Subsystem for Linux (WSL) - you can find the instructions here to set up WSL: https://nextstrain.org/docs/getting-started/windows-help
> 
> However, you can then look for `localhost:4000` in your usual browser in Windows. I hope that helps you get it running!
> 
> For sharing with colleagues, once you have generated a JSON, you can use http://auspice.us/ and drag-and-drop it here. (You can also use this to view JSONs on your own machine, if that's helpful)

Thanks very much, this works for me now!

**Comment by emmahodcroft** [comment]
Glad to hear it!

**Comment by jameshadfield** [comment]
If you'd like to avoid installation altogether the best solution is to share the JSONs then ask people to just drag & drop them onto https://auspice.us 😉
