### ISSUE TITLE
Use of Python system executable prevents rules from accessing Python modules in Snakemake conda environments

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#442]
## Description of the problem

[Discussion in a PR about how to reference Python executables ](https://github.com/nextstrain/ncov/pull/274) originally included a plan to standardize on `python3` instead of `python`. Continued discussion led to [an alternate solution](https://github.com/nextstrain/ncov/pull/412) where the system `python` would be used when it was defined or `python3` would be used. After additional testing, it turns out this solution prevents proper behavior of Snakemake’s conda environments with the `--use-conda`  flag.

When running ncov builds with `--use-conda` and the system executable, Snakemake activates the rule’s conda environment but the Python modules and executables installed in that environment are not available to the rule. This is because the `python` executable used in the shell command does not belong to the conda environment but to whatever environment the user executes Snakemake from.

For example, I want to build a subsampled alignment for a county-level ncov build like so:

```
snakemake \
  --use-conda \
  --profile profiles/king-county \
  results/usa_washington_king-county/subsampled_alignment.fasta
```

At the “combine and deduplicate” step of the workflow, snakemake activates the conda environment that has `nextstrain-augur` installed. The environment I’m calling Snakemake from does not have augur installed. The shell command for this rule references the system executable Python, so the command that gets executed is:

```
/Users/jlhudd/miniconda3/envs/nextstrain/bin/python scripts/combine-and-dedup-fastas.py \
  --input [...snip...] \
  --output [...snip...]
```

This execution produces the following error:

```
Traceback (most recent call last):
  File "scripts/combine-and-dedup-fastas.py", line 3, in <module>
    from augur.align import read_sequences
ModuleNotFoundError: No module named 'augur'
```

However, if I modify the shell command to use `python3` , as shown below, everything works as expected.

```
python3 scripts/combine-and-dedup-fastas.py \
  --input [...snip...] \
  --output [...snip...]
```

## Proposed solution

I propose that we revert back to running Python with the `python3` command.

One major reason originally given to not use this approach was that [Anaconda installations on Windows do not always symlink a `python3` executable](https://github.com/nextstrain/ncov/pull/274#issuecomment-622996487). Since we do not officially support augur on Windows anyway, this is does not seem to be a major issue. The inability to use `--use-conda` is a bigger issue, especially for those of us running builds in environments where we can’t use Docker (e.g., a cluster).

**Comment by huddlej** [comment]
@tsibley What are your thoughts on the proposed solution here? We can chat offline, too, and document here if that's easier.

**Comment by tsibley** [comment]
Thanks for the great writeup of your troubleshooting! Since this bug breaks an existing use case, I agree we could revert 74af6ef now to fix the breakage to get back to known-good behaviour.

As for addressing the original issue in #274, we could ignore it or do something like the below instead:

```diff
From 81879191372a3bf8e88036863b162f6f60a41a1e Mon Sep 17 00:00:00 2001
From: Thomas Sibley <tsibley@fredhutch.org>
Date: Mon, 22 Jun 2020 16:07:06 -0700
Subject: [PATCH] Don't use the Snakemake-running Python executable when Conda
 is enabled

The Python executable running Snakemake is different from and outside of
the Conda environment that Snakemake enters to run each rule.  Inside of
the Conda environment, "python3" should always be the right executable,
so just use it.

Resolves #442.
---
 Snakefile | 6 ++++--
 1 file changed, 4 insertions(+), 2 deletions(-)

diff --git a/Snakefile b/Snakefile
index 70ab493e..ea7a90e8 100644
--- a/Snakefile
+++ b/Snakefile
@@ -8,8 +8,10 @@ validate(config, schema="schemas/config.schema.yaml")
 
 # In our shell rules, we try to use the same Python executable running
 # Snakemake, if known, by interpolating {python:q}.  The aim is to prevent
-# issues with multiple Python versions or symlinks for python vs. python3.
-python = sys.executable or "python3"
+# issues with multiple Python versions or symlinks for python vs. python3.  If
+# we're running with --use-conda, however, we can count on python3 (and the
+# Python running Snakemake will be outside of the Conda env).
+python = "python3" if workflow.use_conda else sys.executable or "python3"
 
 # default build if none specified in config
 if "builds" not in config:
-- 
2.27.0

```

**Comment by huddlej** [comment]
After thinking about this more, I'm strongly in favor of sticking with `python3` everywhere. Using `python3` as a standard across all of our pathogen builds should make them easier to read and maintain (and avoid copying the `python = ...` block of code across repos). Looking back at the original issue, the author seemed most concerned that we not mix `python` and `python3` in the same workflow. The Anaconda + Windows issue seemed more theoretical.

If the Python executable is a major issue for Windows users, we can recommend using `--use-conda` as a workaround. We could even recommend that `--use-conda` should be the default for anyone not using the CLI + Docker.

**Comment by tsibley** [comment]
Sounds good to me!

**Comment by huddlej** [comment]
Cool. I'll update this once the epic `tutorial` PR gets merged.
