### ISSUE TITLE
Error while running with clock_filter_iqd set to 0

### ISSUE THREAD

**Issue by haridh** [nextstrain/ncov#446]
Hi,
I get the following error when I run the program with clock_filter_iqd set to 0 in the config.yaml file. It runs fine with higher than 0 number. 
Traceback (most recent call last):
  File "/home/haridh/miniconda3/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/home/haridh/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/haridh/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/home/haridh/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/frequencies.py", line 97, in run
    tip.attr = {"num_date": np.mean(dates[tip.name])}
  File "<__array_function__ internals>", line 6, in mean
  File "/home/haridh/miniconda3/envs/nextstrain/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 3335, in mean
    out=out, **kwargs)
  File "/home/haridh/miniconda3/envs/nextstrain/lib/python3.6/site-packages/numpy/core/_methods.py", line 163, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
Error in rule tip_frequencies:
    jobid: 10
    output: results/usa_cal/tip-frequencies.json
    log: logs/tip_frequencies_usa_cal.txt (check log file(s) for error message)
    shell:
        
        augur frequencies             --method kde             --metadata results/usa_cal/metadata_adjusted.tsv             --tree results/usa_cal/tree.nwk             --min-date 2020.0             --pivot-interval 1             --narrow-bandwidth 0.05             --proportion-wide 0.0             --output results/usa_cal/tip-frequencies.json 2>&1 | tee logs/tip_frequencies_usa_cal.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by emmahodcroft** [comment]
Hi @haridh, Thanks for reaching out! The `--clock-filter-iqd` command removes tips that deviate more than N interquartile ranges from the root-to-tip vs time regression. So, setting this to 0 doesn't make sense. If you don't want to include this at all in your run, you can remove this from the `augur refine` command. Otherwise, you could set it to a very high number, so that essentially no tips will be filtered out. 

I'm not entirely sure why the error is coming when you run `augur frequencies`, but it likely stems from something going wrong during the `refine` step from running it set to `0`. Be sure to force a re-run of `augur refine` once you change this, either by removing the `--clock-filter-iqd` argument altogether, or setting to a high number.

**Comment by haridh** [comment]
I assumed setting 0 would turn off the filter as in treetime. Will try your suggestion. Thank you.

**Comment by emmahodcroft** [comment]
Hi @haridh  - my apologies - I didn't realise this functionality should be working as it does in TreeTime. In this case, this should be working, and I'm unsure where your error stems from. Can you provide the log file that's made when `frequencies` is run?

**Comment by rneher** [comment]
yes, it would be useful to see the refine and frequencies log. It looks as if there are tips that don't get dates assigned, and then `frequencies` doesn't check for a valid date.

**Comment by haridh** [comment]
Attached are the two log files from the logs folder output.
[refine_usa_cal.txt](https://github.com/nextstrain/ncov/files/4838775/refine_usa_cal.txt)
[tip_frequencies_usa_cal.txt](https://github.com/nextstrain/ncov/files/4838776/tip_frequencies_usa_cal.txt)

**Comment by rneher** [comment]
thanks. Any chance there are invalid or incomplete dates in your metadata? These would have been thrown out with the clock-filter, but might have persisted without. That said, augur shouldn't fail so obscurely.

**Comment by haridh** [comment]
Yes. The original metadata downloaded from GISAID has a few samples with YY-MM in the date field. Missing the day.

**Comment by trvrb** [comment]
I'm not sure if this is still an issue. I'm going to close now, but @haridh please feel free to reopen if it's still an issue. Our ability to have user snakemake profiles ala https://github.com/nextstrain/ncov/blob/master/my_profiles/example/builds.yaml should make this easier.
