### ISSUE TITLE
[BUG] Example data throws an `author` error during export

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#449]
**Current Behavior**  
```  File "/Users/Sidney/opt/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur/export_v2.py", line 491, in create_author_data
    node_author_info[node_name]["value"] = author + " {}".format("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"[index])
IndexError: string index out of range
```
```
Error in rule export:
    jobid: 24
    output: results/my_usa_build/ncov_with_accessions.json
    log: logs/export_my_usa_build.txt (check log file(s) for error message)
``` 

**How to reproduce**  
Steps to reproduce the current behavior:  
0. `conda activate nextstrain`
1. `git checkout tutorial` 
2. `snakemake --profile my_profiles/example`  

**Possible solution**  
This appears to be a data-specific bug, but oddly, a quick `pd.fillna('N/A')` does not resolve the index error.  

**Your environment: if running Nextstrain locally**  
 - Operating system: mac os10.15.5  
 - Within provided conda env  
 - Version (e.g. `auspice 2.7.0`):  augur 7.0.2

**Comment by huddlej** [comment]
Thanks, @sidneymbell! I'm working on this within [the augur repository at issue 571](https://github.com/nextstrain/augur/issues/571) and have a plan to address it. I'm going to close this one just to avoid confusion.
