### ISSUE TITLE
[Docs] Update example data and highlight specific case studies  

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#450]
The public health departments I'm working with would really benefit from a heuristic interpretation guide, ideally as a series of case-studies explained in a narrative. 

I'd suggest choosing a dataset (probably with toy metadata) that allows us to walk through possible scenarios like the following:  
- 10 community-acquired cases are sampled. 6 of these had recently visited a local retail store. Can we rule out the store as a source?  
- We recently reopened some businesses and 10 new cases occurred. Were these likely the result of importations, or is there cryptic local transmission happening?  
- A care facility / workplace / gathering led to a superspreader event. How many downstream cases are attributable?  

@batson @alliblk -- any others that should be covered?

**Comment by batson** [comment]
* The Mission study example: case counts are high in a community in a neighborhood. Is this being spread locally (through say shared community spaces)? (In this case, there was significant strain diversity, indicating likely workplace acquisition.)

* Two care facilities have COVID outbreaks. Some patients have been transferred between them and one HCW has worked in both facilities. Was the outbreak in one seeded from the other? Or are these independent events.

* 4 individuals in a meat-packing facility test positive. Is this an outbreak in the facility, or a coincidence?

* A workplace has an outbreak. After a week with no new cases, someone tests positive. Is this a continuation of the outbreak, indicating likely ongoing transmission, or a new introduction acquired elsewhere?

@lucymli may also have some good ideas.

**Comment by sidneymbell** [comment]
Closed in `narratives/` repo
