### ISSUE TITLE
Separate out nextstrain-specific rules/params  

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#451]
Currently, the snakemake rules are configured such that some rules and parameters that are primarily for our own internal use (e.g., `legacy_clades`, `slack_token`)  are still required for all users. I've moved these over to `ncov@tutorial/nextstrain_profiles/nextstrain/builds` per our conversation, but I've had to retain them in the main `ncov@tutorial/defaults/parameters.yaml` to avoid run failure.

I've marked the inputs and params that I believe need to be reshuffled; can you please help me with this? 
https://github.com/nextstrain/ncov/blob/tutorial/defaults/parameters.yaml#L30-L37

**Comment by huddlej** [comment]
I mostly resolved this issue with a86c14b, but I couldn't remember what we decided to do with the legacy clades. Do we still want to keep legacy clades in the default builds for folks, @rneher?

**Comment by emmahodcroft** [comment]
Yes, I think we want to keep legacy clades. There have been papers published using these, so I think we have to maintain them for the foreseeable future...

**Comment by emmahodcroft** [comment]
I like the way you've done this though, thanks @huddlej !
