### ISSUE TITLE
How to download current subsample fasta?

### ISSUE THREAD

**Issue by ripendil-bd** [nextstrain/ncov#454]
Hi,
I can see there is an option to download metadata data from nextstrain.org global analysis webpage. I was wondering how can I download the fasta file for all the genomes displayed in the current subsampled analysis. Can anyone help?

**Comment by emmahodcroft** [comment]
Hi @ripendil-bd , thanks for reaching out! We get our data from GISAID, and their data agreement is that data cannot be redistributed. This is to protect submitters, as anyone who signs up to GISAID agrees to the terms of service about how the data can be used. Thus, there's no way to download the fasta file from the Nextstrain website. However, the data is available on GISAID (though not in the same subsampled format as shown on Nextstrain - this changes every day as we re-run the build). I hope that helps!
