### ISSUE TITLE
phylogenetic tree with specific markers

### ISSUE THREAD

**Issue by yhkim1006** [nextstrain/ncov#462]
Dear team.

Your open source code is so helpful to analyze COVID19. I have one question.
I'm wondering about the phylogenetic tree.

When running 'build ncov', json file is created in auspice folder, and then I can view the phylogenetec tree ...etc on the web.
But all of these results are for the entire genome of COVID19.

I would like to see the phlogenetic tree results only with about 1000 sequence of a specific marker I have selected.

Is there a solution?

**Comment by emmahodcroft** [comment]
Hi @yhkim1006 , Thanks for reaching out! I'm not 100% clear on what you're asking, could you clarify? Are you hoping to only see a tree with 1000 sequences that have a specific marker, or want to see a tree made only with 1000 bases of the sequence?

**Comment by yhkim1006** [comment]
Hi @emmahodcroft ! that is excetly what I want. how can I do that?

**Comment by emmahodcroft** [comment]
Hi @yhkim1006 - Which one is what you want?

**Comment by yhkim1006** [comment]
Hi @emmahodcroft, I want to only  a tree made only with 1000 bases of specific marker. Thanks!

**Comment by trvrb** [comment]
I'm going to close this for now. I'm hopeful you were able to address your scientific question. @yhkim1006, please feel free to reopen if you have further questions. We have specific description of customizing the `ncov` workflow here: https://docs.nextstrain.org/en/latest/tutorials/SARS-CoV-2/steps/customizing-analysis.html
