### ISSUE TITLE
Priorities script throws uninformative Python exceptions instead of exiting cleanly on the command line

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#464]
**Current Behavior**

When a user runs the priorities script with a FASTA file that hasn't been through augur align yet, the script raises a Python exception and exists like so:

```
Traceback (most recent call last):
  File "scripts/priorities.py", line 146, in <module>
    focal_seqs_dict = calculate_snp_matrix(args.focal_alignment, consensus = ref)
  File "scripts/priorities.py", line 68, in calculate_snp_matrix
    raise ValueError('Fasta file appears to have sequences of different lengths!')
ValueError: Fasta file appears to have sequences of different lengths!
```

**Expected behavior**

Instead of exiting noisily, the script should print a helpful error message to the user (explaining *which* FASTA file has the incorrect lengths) and return with a non-zero exit code.

**Comment by rneher** [comment]
this code was removed.
