### ISSUE TITLE
snakemake missing in conda environment installed from nextstrain.yml

### ISSUE THREAD

**Issue by mherold1** [nextstrain/ncov#476]
**Current Behavior**
When running the tutorial https://nextstrain.github.io/ncov/setup and installing the nextstrain environment the recipe `nextstrain.yml` does not contain snakemake. For me this lead to snakemake being run with a different python version (3.6.9.) instead of 3.6.10 installed in the conda environment, this in turn lead to the following error:
```
$ snakemake --cores 4 --profile ./my_profiles/getting_started
ModuleNotFoundError in line 14 of workflow/snakemake_rules/main_workflow.smk:
No module named 'treetime'
  File "ncov/Snakefile", line 52, in <module>
  File "ncov/workflow/snakemake_rules/main_workflow.smk", line 14, in <module>
```

**Expected behavior**
After installing snakemake in the conda environment the example workflow worked as expected. 
To me this was less obvious than it appears now, so maybe this helps someone running into the same issue.

**How to reproduce**
Steps to reproduce the current behavior:
https://nextstrain.github.io/ncov/setup
steps 1 to 3 

**Your environment: if running Nextstrain locally**
 - Operating system: Ubuntu 18.04.3
 - Version : 
```
$ augur --version
augur 9.0.0
$ nextstrain --version
nextstrain.cli 2.0.0.post1
$ auspice --version
2.17.4
```

**Comment by tsibley** [comment]
Hmm. I believe Snakemake should have been pulled in as a transitive dependency via [Augur's dep on it](https://github.com/nextstrain/augur/blob/11149704122e7c24917dd3bfe163845736a8eac2/setup.py#L57). Augur itself is dep in the [Conda environment](https://github.com/nextstrain/conda/blob/37ef76eb9a0707e8504851e11792ed8c5ecc1c68/nextstrain.yml#L22). It's not immediately clear to me why this didn't appear to happen, but @huddlej may have thoughts.

That said, we do plan to remove Augur's dep on Snakemake and instead move Snakemake explicitly into the Conda environment. See https://github.com/nextstrain/conda/pull/8 and https://github.com/nextstrain/augur/pull/557. Those are waiting on some doc updates, I believe.

**Comment by huddlej** [comment]
Thank you for reporting this, @mherold1. As @tsibley said, Snakemake should be installed as a transitive dependency, but given that TreeTime is also missing from the environment when you run the workflow it seems like Augur itself did not get installed or the environment where it was installed was not activated. Would you be willing to try this again with the following steps? These commands will remove your current Nextstrain environment, reinstall it, and run the workflow. If you don't want to mess with your environment right now, I completely understand, though.

```bash
# Remove your current Nextstrain environment
conda env remove -n nextstrain

# Re-create the Nextstrain environment
curl http://data.nextstrain.org/nextstrain.yml --compressed -o nextstrain.yml
conda env create -f nextstrain.yml
conda activate nextstrain
npm install --global auspice

# Run your workflow
snakemake --cores 4 --profile ./my_profiles/getting_started
```

We are about to merge a PR that will fix that specific TreeTime issue (PR #473). Once this is in, you should be able to run the workflow with the following command to have more control over the environment in which your rules run:

```bash
snakemake --use-conda --cores 4 --profile ./my_profiles/getting_started
```

The additional `--use-conda` flag will activate a custom conda environment for each rule. You can control the contents of this environment by modifying the file `workflow/envs/nextstrain.yaml`. When this file changes and you're running Snakemake with the `--use-conda` flag, Snakemake will notice the changes and update your environment accordingly. This allows you to lock specific versions of Augur and other tools in the workflow.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.

**Comment by mherold1** [comment]
Thanks for the replies, the issue can be closed.
