### ISSUE TITLE
map problem

### ISSUE THREAD

**Issue by viperezUru** [nextstrain/ncov#480]
I'm trying to make the nextstrain tree and I have a problem. When I do the global approach, it divides Uruguayan sequences in two parts, on one side the sequences that were in nextstrain and on other side, ours sequences.  
what can I do?
Also I can't see on the map anything corresponding to South America when I want to focus on that region.

**Comment by emmahodcroft** [comment]
Hi @viperezUru  - thanks for reaching out! I'm afraid I don't understand your first question - what do you mean they are divided into two parts? Can you send a screenshot maybe?

For the second part, are you running a build based on the 'global' pipeline, or have you tried to set up a more regionally-focused build as in our tutorial? It seems at least that the sequences from Nextstrain that come from South America should be showing up on the map. But some more info might help us debug!

**Comment by viperezUru** [comment]
In the first part, when I run a global build I see in the map sequences
from Uruguay in two colors, for example my sequences in blue and the
nextrains sequences in red.
For the second part, like you said I tried to set up a more
regionally-focused build as in the tutorial. the problem is that I cant see
in the map the my sequences, but I can see the ones that come from
Nextstrain.

**Comment by emmahodcroft** [comment]
Hi @viperezUru , thanks for the extra info. What colouring do you have displayed when you say you're seeing your sequences in blue and the Nextstrain ones in red? If coloring by country, they should be the same color, and I'm not sure why they would be different. If coloring by division, they may be different - are you adjusting the colors in any way different from the defaults?

For the second part, Are you sequences in the tree, but not appearing on the map, or missing altogether? Can you let me know what geographical scale you are viewing on (on the menu on the left, look for the geographical drop-down box - you can usually select region, country, admin division, location). For your own sequences, to what level (region, country, division, etc) do you have data for?

Hopefully this can help!

**Comment by viperezUru** [comment]
Hi! I send you the screenshots.

**Comment by trvrb** [comment]
Hi @viperezUru. I hope you were able to resolve this issue. I'm going to close this now, but please feel free to re-open if it's still a problem.
