### ISSUE TITLE
Build name wildcard does not support numbers

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#482]
**Current Behavior**

@rneher points out that build names cannot currently have numbers in them or Snakemake will produce an error that is difficult to interpret. These errors are caused by [the overly strict build name wildcard constraints](https://github.com/nextstrain/ncov/blob/667b0ac18863813989dac5d7c6e23034c9609115/Snakefile#L28).

**Expected behavior**

We should support numbers in build names, especially for cases when we want to place dates in the build name (e.g., for historical builds of specific time periods).

**Possible solution**

Changing the current constraints regex to `build_name = r'(?:[_a-zA-Z0-9-](?!(tip-frequencies|gisaid|zh)))+'` should fix the problem. I have not tested this yet though to confirm.

**Comment by emmahodcroft** [comment]
@huddlej I have tried this on our `ncov-swiss` build on a local branch and this does indeed seem to solve the issue and allow builds with number names!

**Comment by huddlej** [comment]
PR #522 fixed this issue for the general case of most individual builds, but it also broke the Nextstrain builds which need to have dates in their path names and _not_ in their build names (e.g., `ncov_global-2020-12-20.json`).
