### ISSUE TITLE
Provide a configuration parameter for auspice JSON prefixes

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#488]
**Context**

[Community builds sourced through nextstrain.org/community](https://nextstrain.org/docs/contributing/community-builds) currently require the prefix of each auspice JSON to match the name of the repository where they are hosted (e.g., `zika-columbia_tree.json` in the [zika-columbia repo](https://github.com/blab/zika-colombia/tree/master/auspice), `covidtracker_ca.json` in the [Biohub California build repo](https://github.com/czbiohub/covidtracker/tree/master/auspice)).

However, the auspice JSONs produced by the ncov workflows [all get prefixed by `ncov_`](https://github.com/nextstrain/ncov/blob/26a77de9594f7b1538a07d0c6c7532f5995c3224/Snakefile#L31). Users who want to provide their builds through the community interface need to manually rename their auspice JSONs or add a custom rule to the workflow to automate this.

**Description**

As an alternative to a custom renaming rule, we could provide a configuration parameter like `auspice_json_prefix` as a top-level setting. This setting could default to `ncov` for backwards-compatibility (defined in `defaults/parameters.yaml`), but users could also override the setting in their custom profiles (e.g., `auspice_json_prefix: zika-columbia`). This setting would allow users to automatically produce JSONs that could be hosted from their GitHub repositories.

**Comment by ignasiialemany** [comment]
I will have a look and try to work on it!

**Comment by huddlej** [comment]
Thanks, @ignasiialemany! We haven't actually discussed this as a group within Nextstrain yet, so I'm not sure it is worth the effort yet.

@jameshadfield or @emmahodcroft, do you have thoughts about the change I proposed above?

**Comment by emmahodcroft** [comment]
I think if this can be implemented, it would be really helpful for those making community builds, without adding downsides for anyone who wants to just leave it 'as-is'. At least, that's how it seems to me! But certainly, as more people start picking up and making local runs and trying to share them as 'community builds', making this easier would seem like removing a speed-bump, to me!

**Comment by ignasiialemany** [comment]
@huddlej @emmahodcroft I have added the new variable "auspice_json_prefix" inside the "default/parameters.yml" and added a bit of code inside the Snakefile to load the prefix if exists in the config file (if not, default "ncov"). Consequently, I have added the extension in the inputs "rule:all"  using the expand function. The issue that I am having is that those files are created before the rule:all and are not modified accordingly leading to an error. Where are those files created?

**Comment by ignasiialemany** [comment]
Nevermind, I believe I have found where those files are outputs. `rule:finalize` , I believe now it has been solved

**Comment by ignasiialemany** [comment]
I have code implemented, the prefix should only be available for the file `{extension}_{build_name}.json`  in the folder auspice? Or also for the tip-frequences / root-sequence?

**Comment by huddlej** [comment]
That's great, @ignasiialemany! The prefix should be available for the tip frequencies and root sequence, too. These sidecar JSONs have to have the same prefix as the main JSON for Auspice to know how to find them (e.g., for a main JSON named `ncov_global.json`, the sidecar files must be named `ncov_global_tip-frequencies.json` and `ncov_global_root-sequence.json`).
