### ISSUE TITLE
augur refine step ends in error

### ISSUE THREAD

**Issue by ajaybabu27** [nextstrain/ncov#496]
I get the following error when I run the augur refine step in the pipeline:

`Inferred a time resolved phylogeny using TreeTime:
        Sagulenko et al. TreeTime: Maximum-likelihood phylodynamic analysis
        Virus Evolution, vol 4, https://academic.oup.com/ve/article/4/1/vex042/4794731

Traceback (most recent call last):
  File "/hpc/users/kumara22/.conda/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 209, in run
    skyline, conf = tt.merger_model.skyline_inferred(gen=args.gen_per_year, confidence=2)
TypeError: 'interp1d' object is not iterable
[Wed Sep 30 03:01:03 2020]
Error in rule refine:
    jobid: 6
    output: results/north-america_usa/tree.nwk, results/north-america_usa/branch_lengths.json
    log: logs/refine_north-america_usa.txt (check log file(s) for error message)
    shell:
        
        augur refine             --tree results/north-america_usa/tree_raw.nwk             --alignment results/north-america_usa/subsampled_alignment.fasta             --metadata results/north-america_usa/metadata_adjusted.tsv             --output-tree results/north-america_usa/tree.nwk             --output-node-data results/north-america_usa/branch_lengths.json             --root Wuhan/Hu-1/2019 Wuhan/WH01/2019             --timetree             --clock-rate 0.0008             --clock-std-dev 0.0004             --coalescent skyline             --date-inference marginal             --divergence-unit mutations             --date-confidence             --no-covariance             --clock-filter-iqd 4 2>&1 | tee logs/refine_north-america_usa.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
`
Here is the output from logs/refine_north-america_usa.txt file:

`/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py:10: DtypeWarning: Columns (8) have mixed types. Specify dtype option on import or set low_memory=False.
  return augur.run( argv[1:] )

368.66	-WARNING: character U is unknown. Treating it as missing information

372.37	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
      	'Wuhan/WH01/2019']

446.58	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
      	'Wuhan/WH01/2019']
pruning leaf  USA/WA-UW-13277/2020
pruning leaf  USA/WA-UW-11399/2020

520.76	WARNING: Previous versions of TreeTime (<0.7.0) RECONSTRUCTED sequences
      	of tips at positions with AMBIGUOUS bases. This resulted in unexpected
      	behavior is some cases and is no longer done by default. If you want to
      	replace those ambiguous sites with their most likely state, rerun with
      	`reconstruct_tip_states=True` or `--reconstruct-tip-states`.

1742.69	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
       	'Wuhan/WH01/2019']

2438.19	###TreeTime.run: INITIAL ROUND

3057.95	TreeTime.reroot: with method or node: ['Wuhan/Hu-1/2019',
       	'Wuhan/WH01/2019']

3149.65	###TreeTime.run: rerunning timetree after rerooting

4086.53	###TreeTime.run: ITERATION 1 out of 2 iterations

11225.87	###TreeTime.run: ITERATION 2 out of 2 iterations

19590.97	Coalescent:optimize_skyline:...failed:     fun: -260861.03533615873
        	jac: array([ 17.16992188, -11.3671875 , -43.87304688,  43.78710938,
        	1.21679688,  -7.31640625, -51.82226562,  -7.07226562,
        	104.15039062,  43.83007812,   5.10546875,  -5.41210938,
        	2.58007812,   3.66015625, -29.43945312,  -1.015625  ,
        	84.10351562,   1.37890625,  15.32421875,   6.12890625])  message:
        	'Iteration limit exceeded'     nfev: 2317      nit: 101     njev: 101
        	status: 9  success: False        x: array([-6.45701798, -8.33423226,
        	-8.34810909, -6.17752026, -5.94551906,        -5.12082465, -4.1551895 ,
        	-2.99310614, -2.01227399, -2.62905549,        -2.23530546, -2.19497514,
        	-2.61958372, -2.88489289, -2.66552363,        -3.122071  , -2.81888657,
        	-3.79599305, -3.69156975, -2.04175525])

25737.13	###TreeTime.run: FINAL ROUND - confidence estimation via marginal
        	reconstruction

Inferred a time resolved phylogeny using TreeTime:
	Sagulenko et al. TreeTime: Maximum-likelihood phylodynamic analysis
	Virus Evolution, vol 4, https://academic.oup.com/ve/article/4/1/vex042/4794731

Traceback (most recent call last):
  File "/hpc/users/kumara22/.conda/envs/nextstrain/bin/augur", line 8, in <module>
    sys.exit(main())
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/__init__.py", line 74, in run
    return args.__command__.run(args)
  File "/hpc/users/kumara22/.conda/envs/nextstrain/lib/python3.6/site-packages/augur/refine.py", line 209, in run
    skyline, conf = tt.merger_model.skyline_inferred(gen=args.gen_per_year, confidence=2)
TypeError: 'interp1d' object is not iterable
`

I have gotten the same error after trying to run this twice. What could be causing this issue ? I am using the following commit version of the ncov repo: 6a60005c3620aa41480e8aabfa2791b36dabde98 and augur 7.0.2.

**Comment by trvrb** [comment]
Flagging @rneher here. I don't know TreeTime well enough to have a guess at what's causing `TypeError: 'interp1d' object is not iterable`.

**Comment by rneher** [comment]
You need to update treetime and augur. I think we have fixed this error a while back.
