### ISSUE TITLE
Mandarin translation

### ISSUE THREAD

**Issue by rneher** [nextstrain/ncov#5]
@alvinxhan -- would be great if we would have a mandarin translation. 

Emma just make placeholders for a spanish and zh translation. Feel free to get going. we can always rename files etc later.

**Comment by alvinxhan** [comment]
@rneher yup, I'll get to it now!

**Comment by rneher** [comment]
Tagging @fzhang12 who is willing to help with this translation. Thank you so much! The task is to translate the English text in here:
https://raw.githubusercontent.com/nextstrain/ncov/master/narratives/ncov_sit-rep-zh_2020-01-25.md

@alvinxhan, maybe you can point @fzhang12 to sections to tackle!

**Comment by alvinxhan** [comment]
Sure! Hey @fzhang12 I have already translated up to Phylogenetic analysis section. Can you start from there to speed things up?

**Comment by fzhang12** [comment]
@alvinxhan absolutely no problem. I've already started a little bit. Could you specify which part (or maybe *which header* is more preferable) I should cover? Maybe `# Within-family transmission`?

**Comment by alvinxhan** [comment]
Would be great if you could translate starting from ```# Phylogenetic Interpretation```!

**Comment by alvinxhan** [comment]
Hey @fzhang12, I have uploaded my part of the translation. Can you give it a quick read as well to make sure they sound right (especially the scientific jargons!)? Sorry for the slow response, was travelling on a flight back home!

**Comment by fzhang12** [comment]
@alvinxhan perfect. That was quick. I will integrate it to my current one. I am 75% done for now

**Comment by rneher** [comment]
fantastic. Since there are several people working on translation right now. I suggest we move this translation into branch https://github.com/nextstrain/ncov/tree/sit-rep_zh

this will avoid conflicts between different people editing and allows us to separate ongoing work from the production version. let us know if you need help.

**Comment by alvinxhan** [comment]
@fzhang12 I had time on my hands during transit so please take your time. happy to go over the whole translation with you once you are done! 

@rneher great and thanks!

**Comment by rneher** [comment]
@fzhang12 if you are unfamiliar with git workflows, you can go here

https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep-zh_2020-01-25.md

press the "edit" button on the top right, and add your changes in the browser. Once you are done, press the "commit" button at the bottom.

**Comment by fzhang12** [comment]
@alvinxhan Thanks for your active reply. I just uploaded my second part and am still going over the whole. My main question: is R0 known as '生殖数' in mainland? I didnt find any result even with Baidu. I had it translated as 'R0值'.

thanks @rneher , for your tip (it was really helpful !!) and all the effort.

**Comment by alvinxhan** [comment]
@fzhang12 - let's go with R0值. I was translating it literally from "basic reproduction number". I'll make the changes now.

**Comment by rneher** [comment]
This is fantastic (not that I understand anything). But please add your names to the author list. we should be able to get this up before Asia wakes up in the morning!

**Comment by rneher** [comment]
btw: you can preview your work here:
https://nextstrain.org/community/narratives/nextstrain/ncov/sit-rep-zh/2020-01-25?n=0

**Comment by alvinxhan** [comment]
Had a readthrough of the entire thing. Looks good to me. Thanks @fzhang12 for working on this together! 

@rneher - added my name to the author list (looks like the order doesn't matter?). Thanks again! Fantastic job with the nCoV updates so far!

**Comment by rneher** [comment]
I'll finalize this, add @fzhang12 name!

**Comment by rneher** [comment]
here is the report:
https://nextstrain.org/community/narratives/nextstrain/ncov/sit-rep/zh/2020-01-25?n=10
not yet on live site, but as it would appear. @fzhang12 are you happy with your name shown as is?

**Comment by rneher** [comment]
This is up live at 

https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-01-25?n=0

thank you all for your help. We'll make a new issue when there is an update to the English report.
