### ISSUE TITLE
Priorities calculation does not match description

### ISSUE THREAD

**Issue by batson** [nextstrain/ncov#502]
The comments state that the priority of a sequence `x` is the:

1. negative distance to the focal set (call the closest element of the focal set `s`)
2. minus a penalty for masked bases in the contextual sequence (the masked bases in `x`, scaled so that 333 masked sites is equivalent to 1 mutation)
3. minus a penalty for the position of the sequence in a list of neighbors of `s` (ordered by distance + masked base penalty, but random for each such value, scaled by 0.2)

In [line 180](https://github.com/nextstrain/ncov/blob/b9978e6a085e11b8ff15c5cea4246494a77b88b7/scripts/priorities.py#L180
), it appears that the priority is in fact equal to the negative distance (1) minus a penalty for position (3), but weighted by 0.1 instead of 0.2. The penalty for masked bases does not appear in the definition of `minimal_distance_to_focal_set`, and so may not make its way into `priority`. Indeed, inspecting the priority file for a recent run, all values are integer multiples of 0.1, indicating that fractions with denominators that would be given by (2) do not appear.

There is an additional quirk, which I do not believe effects the final result: because of the calculation of `closest_match` in [line 156](https://github.com/nextstrain/ncov/blob/b9978e6a085e11b8ff15c5cea4246494a77b88b7/scripts/priorities.py#L156), a sequence in the focal set may not be its own closest match, and so appear with a priority less than 0.

Perhaps it is also worth mentioning that the priorities are used deterministically by `augur filter`. For some reason, I had assumed they were used as weights in some random scheme, but the [documentation](https://nextstrain.github.io/ncov/customizing-analysis) is accurate, saying "[proximity priority] attempts to selected sequences as close as possible to the focal samples."

**Comment by batson** [comment]
It appears that (2) was a component of the calculation until this [commit](https://github.com/nextstrain/ncov/commit/07b4c77311e735f1f0928053c90c1a908e9a9881#) by @emmahodcroft, so this may just be a case of the comments lagging the code.

I am curious for what the reasoning behind the choice of coefficient (0.1 vs 0.2 vs 0.4) in term (3) and the exclusion of term (2).

The current implementation does have the nice feature that if a focal sequence `s` has some contextual sequence `x` with zero SNPs separating them, then `x` (or another sequence with 0 SNPs and fewer missing bases) will have priority `0`.

**Comment by batson** [comment]
If my understanding here is correct, I'm happy to make a PR updating the comments in the code.

**Comment by trvrb** [comment]
Thanks for the feedback here @batson. I'm going to leave this issue open. @emmahodcroft is the expert on how subsampling code was set up.

**Comment by rneher** [comment]
We have reorganized this code into separate proximities and priorities steps. while documentation is surely not perfect, this issue is probably obsolete.
