### ISSUE TITLE
Bring the config specification closer to the CLI args

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#506]
There are lots of cases where the way parameters are specified in `builds.yaml` don't quite match up with the corresponding CLI arguments take under the hood. This is most notably an issue when CLI arguments aren't represented in the existing parameter schema for builds (Example: #505). 

I recognize this is a discussion we've had before, and there are some valid arguments for avoiding this path (e.g., legacy / backwards compatibility, etc). However, we've run into this issue quite a bit, and I figured it might be worth re-examining.

**Comment by emmahodcroft** [comment]
I think we can continue to elevate arguments up to the `ncov` parameters as we need, but I'm hesitant to change what's already there. We do have people (even if not so many) running local builds now, and even with all our help, this still is not a small task for many - I really hate to break things for them.

**Comment by rneher** [comment]
there is a risk here making the config similarly long and complicated as the workflow itself. So I'd rather address this one by one. elevating the polytomies flag makes sense.

**Comment by sidneymbell** [comment]
Thanks, both. Make sense.
