### ISSUE TITLE
augur: error: unrecognized arguments: --weights config/weights.tsv when build with augur6.3.0 

### ISSUE THREAD

**Issue by notebooklinda** [nextstrain/ncov#51]
After installing augur 6.3.0 via pip, when build again with command nextstrain build . 
job 12 failed: 
Job 12:
        Inferring ancestral traits for division
          - increase uncertainty of reconstruction by 2 to partially account for sampling bias
        augur traits             --tree results/tree.nwk             --metadata data/metadata.tsv             --weights config/weights.tsv             --output results/traits.json             --columns division             --confidence             --sampling-bias-correction 2
usage: augur [-h]
             {parse,filter,mask,align,tree,refine,ancestral,translate,reconstruct-sequences,clades,traits,sequence-traits,lbi,distance,titers,frequencies,export,validate,version,import}
             ...
augur: error: unrecognized arguments: --weights config/weights.tsv

I did not encounter this issue with augur 6.2.0. After checking augur traits -h, seems --weights is a valid argument. Could you please help with this issue? Thanks.

**Comment by notebooklinda** [comment]
Running `nextstrain update`, and then build again solved the problem.

**Comment by trvrb** [comment]
Great! Glad this was resolved for you.
