### ISSUE TITLE
Priorities.py script clarification

### ISSUE THREAD

**Issue by mollyhetheringtonrauth** [nextstrain/ncov#510]
Hi! 

I'm a bioinformatician with the Colorado Department of Public Health and Environment. I'm looking for some clarification on the priorities.py script, to better understand how context sequences are selected.

The calculate_snp_matrix function (line 38) returns a snp matrix as a sparse matrix, which is used as an argument in the calculate_distance_matrix function (line 99).  The calculate_distance_matrix function (line 99) returns a distance matrix, which is calculated from a several related distance matrices calculated within the function. Two such matrices are a distance matrix of the number of shared missing sites (n's which are represented as the value 110) (line 112) and a distance matrix of the number of total missing sites between each sequence (line 121-124).  This seems odd to me, because in the calculate_snp_matrix function, all missing sites were removed (line 71). That is the calculate_snp_matrix defines a snp as a site that doesn't match the consensus sequence and is also not an 'n' (or value 110) (line 71). These are the sites and values recorded in the sparse matrix (lines 81-83 & 95)  This means that the sparse snp matrix returned in calculate_snp_matrix does not contain any value equal to 110. So, why does the calculate_distance_matrix function, calculate matrices related to finding the value 110 in the sparse matrix, when that value doesn't exist in the sparse matrix.   

Thanks for the help!

**Comment by rneher** [comment]
I think you are right. The lines on `n` comparisons won't have an effect. It has been a while, but I think we introduced 

https://github.com/nextstrain/ncov/blob/master/scripts/priorities.py#L71

to avoid storing a large number of `n` SNPs. The number of `n`s are then taken into account later

https://github.com/nextstrain/ncov/blob/master/scripts/priorities.py#L156

to de-prioritize sequences with lots of `n`s.

but we need to clean this up -- thanks for the pointer!

**Comment by mollyhetheringtonrauth** [comment]
That all makes sense! Thanks for the clarification!

**Comment by trvrb** [comment]
It looks like @rneher's response resolved the issue. I'm going to close, but please @mollyhetheringtonrauth re-open if this remains an issue.
