### ISSUE TITLE
Are new subclades 20A.EU2 & 20B.OC2 in merge 509 correct?

### ISSUE THREAD

**Issue by richardtillett** [nextstrain/ncov#514]
I left a comment on the commit itself, but thought it wise to also flag the change that has me puzzled here too

[Here's my comment on the commit](https://github.com/nextstrain/ncov/commit/efae11e907f168666710874c773b2741d3728ddd#commitcomment-44283458)

and here's what I wrote:

> I noticed that this commit changed the subclades a lot, and while my interest was piqued first by the elimination of 20A/20268, I'm puzzled by the relationships between some of the new subclades. New **20A.EU2 has 18877T and 22992A**, and **20B.OC2 also has 22992A** (and one other, it looks like). Is the idea that this site mutated from G to A in two different lineages? Or am I reading this wrongly?

**Comment by rneher** [comment]
Yes, we updated the emerging clades to reflect more recent developments and drop variants that don't seem of continued importance. The 22992A mutation (corresponding to position 477 in spike) has arisen multiple times, so this is in line with what we want to highlight. The Oceania subclades are not displayed at the moment.
