### ISSUE TITLE
`--filter` rule fails because of misformatted default `--max-date` arg

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#515]
**Current Behavior**
```
augur filter             --sequences data/sequences.fasta             --metadata data/metadata.tsv             --include defaults/include.txt             --max-date 2020-11-18             --min-date 2019.74 .....
```
throws an error about `2020-11-18` being an invalid date / format. 

This value of `--max-date` is set to the current date in `YY-MM-DD` format here:      
https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L32

**Comment by rneher** [comment]
What version of augur are you running?

**Comment by rneher** [comment]
you need to update augur
