### ISSUE TITLE
About json data using  in "ncov \ auspice"

### ISSUE THREAD

**Issue by hackerchenzhuo** [nextstrain/ncov#54]
@emmahodcroft 
Sorry to bother you again. We are currently engaged in scientific research and analysis of related new coronaviruses, hoping to help solve the epidemic situation in China. After learning about your data set and visualization, we have  have benefited a lot.  Would you mind us using the json results of your data in "ncov \ auspice"? We won't use it for commercial purposes and will sign the data source. 
Thank you so much.

**Comment by emmahodcroft** [comment]
Hi @hackerchenzhuo . You are welcome to use the JSON data from `ncov/auspice` for open sharing, but yes, please do credit Nextstrain where possible.
It's also very important to credit GISAID and to credit the data contributors that provide the sequences to GISAID so we can include them in our analyses. You can see the list of contributing labs at the bottom of the `ncov` page and it is also in the JSON file.

Do note that if you want to *publish* on any of this data, you may need to register as a member of GISAID and follow their [Terms of Use](https://www.gisaid.org/registration/terms-of-use/), which includes contacting the original submitters and involving them in analyses leading to publication. If you intend to publish it may be worth having a more in-depth conversation to ensure you don't unintentionally go on the wrong side of the GISAID terms :)

**Comment by hackerchenzhuo** [comment]
> Hi @hackerchenzhuo . You are welcome to use the JSON data from `ncov/auspice` for open sharing, but yes, please do credit Nextstrain where possible.
> It's also very important to credit GISAID and to credit the data contributors that provide the sequences to GISAID so we can include them in our analyses. You can see the list of contributing labs at the bottom of the `ncov` page and it is also in the JSON file.
> 
> Do note that if you want to _publish_ on any of this data, you may need to register as a member of GISAID and follow their [Terms of Use](https://www.gisaid.org/registration/terms-of-use/), which includes contacting the original submitters and involving them in analyses leading to publication. If you intend to publish it may be worth having a more in-depth conversation to ensure you don't unintentionally go on the wrong side of the GISAID terms :)

thanks for your permission again@emmahodcroft
and yes, I have register as a member of GISAID the day before yesterday , and get the sequence there to runs the snakmake project of ncov in local enrivonment. 
I will follow your advice and won't publish the detail data there : )
