### ISSUE TITLE
reserve more ram for priorities.py by default in snakefile

### ISSUE THREAD

**Issue by dpark01** [nextstrain/ncov#546]
**Current Behavior**
When running a build with proximity-based sampling on modern day inputs (e.g. alignments with >400k genomes), I often find I need to feed much more RAM to the priorities.py calculations than what the main snakemake rules are reserving. If I have a build definition with more than one proximity score to calculate, the default ncov snakemake workflow will allow multiple proximity_score rules to run simultaneously (believing that they only takes 4GB of RAM each), resulting in the priorities.py processes being killed for requiring too much RAM.

**Expected behavior**
Given available RAM resources (assuming snakemake is told about them), the ncov workflow should not attempt to run more simultaneous priorities.py processes than the compute environment can handle.

**How to reproduce**
Steps to reproduce the current behavior:
1. Spin up a VM with 32GB RAM, pull the nextstrain/base docker image and ncov github repo
2. Pull a nextfasta/nextmeta data set with at least 400k ncov genomes.
3. As an example, pull the builds.yaml from https://github.com/CDCgov/spheres-augur-build/blob/master/spheres_profile/builds.yaml
4. Place an aligned, filtered, masked MSA in ncov/results/filered.fasta (skip all the upstream rules in the dag)
5. run `snakemake -j $(nproc) --resources mem_mb=32000 --profile <profile dir> results/california/subsampled_alignment.fasta` (skip all the downstream rules in the dag: this should just run a bunch of subsample and proximity_score rules
6. Watch as snakemake tries to run multiple proximity_score rules simultaneously. If your compute environment kills processes that exceed available RAM, priorities.py will be killed.
7. Fake it with `snakemake` with `--resources mem_mb=4000` and they will be run serially

**Possible solution**
The ncov snakemake should allot more [mem_mb to proximity_score](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L435). In my observation, it should be increased to about 24GB per invocation to handle modern data sets, but given the growth rate of global data, this may need some headroom built in or dynamic calculation based on input size.

**Your environment: if running Nextstrain locally**
 - Operating system: `nextstrain/base:build-20210127T135203Z`
 - Version (e.g. `auspice 2.7.0`): github.com/nextstrain/ncov 5dbca8a45a64e39057c22163f154db981f7ed5c1

**Comment by dpark01** [comment]
Update: actually in some builds I'm doing it seems a single invocation of priorities.py is closer to 40GB RAM... I assume it's roughly `O(MxN)` where `M` is the size of the focal set and `N` is the size of GISAID? `M` is upper bound by the runtime constraints of treetime and will never be more than a couple thousand (unless the runtime of treetime improves), but `N` has no real upper limit.

**Comment by tsibley** [comment]
@dpark01 Thanks for this detailed report! Sorry you're running into trouble here. I agree that some dynamic calculation for `mem_mb` should happen, though not sure what the formula should be.

In the meantime, one workaround is to define a custom "cluster config" in your profile (or via the `--cluster-config` command-line option), which overrides the `mem_mb` resource declaration for the `proximity_score` rule. For example (with other rules), see: https://github.com/nextstrain/ncov/blob/master/nextstrain_profiles/nextstrain-scicore/cluster.json

**Comment by huddlej** [comment]
Thank you, @dpark01! @tsibley's plan should help address this issue in the short-term.

For the long-term solution, @rneher is working on a replacement for this priority script that scales better with input size.

**Comment by rneher** [comment]
yes, priorities can gobble up a lot of memory. For my Europe build it uses 46GB:
```
s       h:m:s   max_rss max_vms max_uss max_pss io_in   io_out  mean_load       cpu_time
834.1618        0:13:54 39943.06        46460.56        39933.05        39935.40        0.00    0.00    98.90   825.46
```
The amount of memory needed depends quite strongly on the size of the data set and possibly also diversity (it uses some sparse matrix logic such that is a little hard to predict how much space is actually needed).

**Comment by rneher** [comment]
I ran into this as well and now increased it 10-fold on master. 

https://github.com/nextstrain/ncov/commit/c12e57dba344b4e10bc81278105c36e9b3168e2e

as John said, we are looking to replace this completely.
