### ISSUE TITLE
why SARS2 clade/subclade SNPs definition is not complete?

### ISSUE THREAD

**Issue by igortru** [nextstrain/ncov#547]
https://github.com/nextstrain/ncov/blob/master/defaults/clades.tsv

or you have different place?
number of pangolin SNPs much higher.

**Comment by emmahodcroft** [comment]
Hi @igortru - Thanks for writing. This is our complete definition of clades - we have many fewer than the Pango lineages. We do use a different file for our subclades, see here: 
https://github.com/nextstrain/ncov/blob/master/defaults/subclades.tsv

And some of the regional builds use additional clades files - you can see them in this folder:
https://github.com/nextstrain/ncov/tree/master/nextstrain_profiles/nextstrain

At the moment we just have one for the Europe build:
https://github.com/nextstrain/ncov/blob/master/nextstrain_profiles/nextstrain/subclades_EU.tsv

I hope this helps!
