### ISSUE TITLE
Pulling pre-computed pangolin is spotty; add flag to enable bespoke pangolin run

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/ncov#557]
**Context**
Currently, if running a build with any samples with non-GISAID identifiers, pangolin lineage assignments are very spotty and confusing in the tree.

**Description**
Either generate or at least incorporate results from a bespoke pangolin run as needed.

**Possible solution**
1. add a flag to [`rule pangolin`](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L712) to optionally trigger shell command `pangolin rules.combine_samples.output.alignment` before calling `scripts/add_pangolin_lineages.py`

2. add a conditional [here](https://github.com/nextstrain/ncov/blob/master/scripts/add_pangolin_lineages.py#L16) to optionally fetch the output of (1) instead of always pulling from the pre-made list 

cc @ttung

**Comment by trvrb** [comment]
I don't see how this would change things. Unless I'm confused. Whether we run `pangolin` during build step or whether `pangolin` is run on the database you should get the same lineage output. `pangolin` is rerun on GISAID database quite frequently as new versions of the software are released.

**Comment by sidneymbell** [comment]
Sorry, to clarify: if I have samples in my build that are either not on
gisaid for privacy reasons or *are* on gisaid but are currently named using
internal accession numbers (e.g., to be able to match back to epi data),
these don't have a preassigned lineage

**Comment by sidneymbell** [comment]
My lovely colleague, Dan Lu, pulled some examples of how the current implementation can be spotty. 

Tree is colored by the ncov-assigned pangolin lineages; running `pangolin subsampled_aligned.py` filled them in correctly (shown as labels / arrows). 

https://docs.google.com/presentation/d/1SUuxesnVYzanAnkLQSnFjea1nxSGhcYwFGDTeodq2ns/edit

**Comment by jameshadfield** [comment]
Looking at our workflow, I believe the current situation is that we rely on GISAID annotation to extract pangolin lineage, and perform no modification of this during the run. We have some legacy code (`rule pangolin` which calls `scripts/add_pangolin_lineages.py`) which is no longer run. 

Given the recent changes to facilitate mutliple inputs, it would be beneficial to allow pangolin lineage assignment. My suggestion would be an opt-in config flag, `config["assign_pango_lineage"]` or similar. The [`_get_node_data_by_wildcards`](scripts/add_pangolin_lineages.py) would add a pangolin node-data JSON if this flag were set, and you could re-write the `rule pangolin` to produce it (which would presuppose the user had the `pangolin` program installed).

**Comment by huddlej** [comment]
This was resolved by #593 for Conda users, but broadly supporting Pangolin annotations remains [an open issue for the Nextstrain Docker image](https://github.com/nextstrain/docker-base/issues/33).
