### ISSUE TITLE
ValueError: target 'wuhan/hu-1/2019' is not in this tree

### ISSUE THREAD

**Issue by abattenhouse** [nextstrain/ncov#563]
I'm trying to run the default ncov build to get global contextual sequences.  Logs for the refine step for all region builds error out with "ValueError: target 'wuhan/hu-1/2019' is not in this tree"

I cloned the ncov repo and downloaded all GISAID data today (2/22) and have verified that hCoV-19/Wuhan/Hu-1/2019 is in both the metadata tsv and the fasta file.

Since the names weren't an exact match, I tried changing the refine rule's root parameter to include the hCov-19 prefix (in nextstrain_profiles/nextstrain/parameters.yaml), but now just get the message "target 'hCov-19/wuhan/hu-1/2019' is not in this tree".

I can also see "hCov-19/Wuhan/Hu-1/2019" in region results files subsampled_alignment.fasta, metadata_adjusted.tsv and subsampled_alignment.fasta.

I'm suspicious that the error refers to 'hCov-19/wuhan/hu-1/2019', while the actual sequence is referred to as 'hCov-19/Wuhan/Hu-1/2019'

Apologies if this is answered somewhere else. I'm brand new to this and have tried to troubleshoot as much as I can myself using online resources.

I'm running nextstrain.cli 3.0.2, augur 11.1.2, auspice 2.23.0, in a conda.

Thanks, Anna

**Comment by abattenhouse** [comment]
Correction to the above: The messages always have the correct capitalization (e.g. "ValueError: target 'Wuhan/Hu-1/2019' is not in this tree").

I would appreciate a prompt response to this issue. I'm a member of the Bioinformatics Consulting Group at the University of Texas at Austin, and am working with the Texas Department of State Health Services to assist with their surveillance efforts.

Thanks, Anna

**Comment by rneher** [comment]
I think the pipeline is looking for `Wuhan/Hu-1/2019` while you seem to have `hCoV-19/Wuhan/Hu-1/2019` in your tree. Does it work if you add the prefix `hCoV-19` t0

https://github.com/nextstrain/ncov/blob/master/defaults/parameters.yaml#L70

**Comment by abattenhouse** [comment]
I tried that exactly (which I mentioned in my post), but got the same
message but with the sample name 'hCoV-19/Wuhan/Hu-1/2019'. And as I
indicated, that id can be found in all the region files (fasta, metadata
tsv, nwk). So I'm stuck.

**Comment by abattenhouse** [comment]
Any progress on this issue? I'm stuck, and need to get this Nexstrain build up and running to support TX DSHS. I'm happy to provide more info, or zoom with someone, if needed. Emma Hodcroft may be the right person to help, since it is her build I'm trying to replicate (and running the main ncov build to start).

Regards, Anna

**Comment by jameshadfield** [comment]
Hi @abattenhouse -- could you post the actual command that is printed out by Snakemake which results in an error (it will start with `augur refine`)?

The error `ValueError: target 'Wuhan/Hu-1/2019' is not in this tree` does implicate the [tree rooting](https://github.com/nextstrain/ncov/blob/master/defaults/parameters.yaml#L70), but you seem to have tried modifying that without success.

**Comment by abattenhouse** [comment]
Ha! It only took a good night's sleep for me to notice that my refine root change was 'hCov' instead of 'hCoV'!!  

So I made that adjustment and tried to run again. Unfortunately, I also made the mistake (??) of updating my ncov, conda and nextstrain (per instructions at https://docs.nextstrain.org/en/latest/guides/install/local-installation.html). After that my ncov build failed because /bin/bash/nextalign was not found.

I should have known better, after I spent hours figuring out why my Cecret run failed after updating that repo. Take-away: never update software without saving a "working" copy. Or: "Good judgement comes from experience. Unfortunately, experience comes from bad judgement."

So I went back to my nextstrain conda and installed nextalign specifically, then re-ran my ncov build with the adjusted 'hCoV-19' prefiex and all is good now!!! (Or at least so far, the build is still running).

So one question I have is how to get that refine root change made, given that all the GISAID files I've now downloaded have names prefixed with hCoV-19. I have a public github account but have never done a pull request. Can you just make that change while I figure out how to set up to do that? The same change may need to be made to defaults/include.txt unless it's a sub-string match.

A second question is why my nextalign went away when I updated.

Meanwhile, I'm settling back with a bourbon cocktail (long week after our TX snowpocalypse), waiting for my ncov build to complete (it has already completed the refine steps successfully). So you may be hearing more from me later :) 

Regards, Anna

**Comment by jameshadfield** [comment]
> So one question I have is how to get that refine root change made

In the `builds.yaml` file you are using for your pipeline (e.g. `./my_profiles/TX/builds.yaml`) you can set parameters which will override [the defaults](https://github.com/nextstrain/ncov/blob/master/defaults/parameters.yaml). In this case,

```yaml
refine:
  root: "hCoV-19/Wuhan/Hu-1/2019 hCoV-19/Wuhan/WH01/2019" # check names match!
```

> So I went back to my nextstrain conda and installed nextalign specifically, then re-ran my ncov build with the adjusted 'hCoV-19' prefiex and all is good now!!! (Or at least so far, the build is still running).

🎉 👍

**Comment by abattenhouse** [comment]
Thanks for the my_profiles tip -- I remember seeing it in one of the tutorials but it had slipped my mind (like I said, I'm new at this and coming up to speed is rather like drinking from a fire hose). And thanks for your patience with a newbie!

**Comment by emmahodcroft** [comment]
Dear Anna,
My apologies for a slow reply on this, and I'm extremely glad to see you got it sorted! Good luck recovering from the snowpocalypse, enjoy the bourbon, and good luck running the builds for Texas!! We'll be happy to include them in the larger Nextstrain map in future if you like!
Best wishes,
Emma
