### ISSUE TITLE
Allow curated alignments as a starting point for analyzing new local sequences (as with nextclade)

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#564]
As one user reports:

> For some of the focused stuff defining a backbone like nextclade does would be helpful or being able to use previous alignments w/o restarting the whole snakemake when you want to force include/exclude single sample.

**Comment by jameshadfield** [comment]
This should be possible with #550, but the tree will still need to be rerun. If a computationally quicker solution is needed then I think nextalign is the tool for the job. We could write a tutorial specifically for this, and including nextclade as well if that would be helpful?

**Comment by huddlej** [comment]
I think the user was looking for something like #550 plus a pre-built global context alignment that they could spike in their new local sequences to. Maybe we could expand the current multiple inputs tutorial to include an example of starting the "worldwide" section of the workflow from the `filtered` input instead of `sequences`.

The faster solution would maybe involved updating an existing tree and/or refine model with new sequences.

**Comment by jameshadfield** [comment]
In the context of a multiple-input build where new worldwide metadata/sequences have not been downloaded but the "local" sequences have been updated, then snakemake should automatically know to use the pre-aligned global data. However I do agree this could be made explicit in the tutorial - e.g. after running the build one could `cp results/filtered_worldwide.fasta data/pre-computed_filtered_worldwide.fasta` and update the config inputs accordingly.
