### ISSUE TITLE
Default multiple input file setup hinders 'snakemake --unlock'

### ISSUE THREAD

**Issue by mbosm** [nextstrain/ncov#578]
Switched to a multiple input setup recently. Followed the example file. This is with nextstrain software up to date and files pulled from github last week. Aborted runs normally can be 'unlocked' with the 'snakemake --unlock' command. However, possibly because there is no longer a metadata or fasta file specified in config.yaml, snakemake is looking for the default files, and thus is erroring out.

This is after a run was aborted because the server crashed:
>Error: Directory cannot be locked. Please make sure that no other Snakemake process is trying to create the same files in the following directory:
>/nextstrain/build
>If you are sure that no other instances of snakemake are running on this directory, the remaining lock was likely caused by a kill signal or a power loss. It can be removed with the --unlock argument.

>nextstrain:/nextstrain/build $ snakemake --unlock

>localrules directive specifies rules that are not present in the Snakefile:
>	upload
>	download
>
>Building DAG of jobs...
>MissingInputException in line 140 of /nextstrain/build/workflow/snakemake_rules/main_workflow.smk:
>Missing input files for rule align:
>data/sequences.fasta`

My files were data/sequences_gisaid.fasta, data/sequences_lab.fasta, data/metadata_gisaid.tsv, and data/metadata_lab.tsv.

Because the plain sequences.fasta file was absent, the unlock command refused to proceed. Putting a dummy blank data/sequences.fasta file in the directory allowed the command to proceed further, but then it had the same problem with a missing data/metadata.tsv. Putting dummy files for both allowed the unlock command to proceed as normal.

Here's my config.yaml and build.yaml files for reference:

config.yaml:
>configfile:
>  - defaults/parameters.yaml
>  - my_profiles/lab/builds.yaml
>
>printshellcmds: True
>reason: True
>show-failed-logs: True
>cores: 12

builds.yaml
>inputs:
>  - name: "lab" 
>    metadata: "data/metadata_lab.tsv"
>    sequences: "data/sequences_lab.fasta"
>  - name: "gisaid"
>    metadata: "data/metadata_gisaid.tsv"
>    sequences: "data/sequences_gisaid.fasta"
>
>builds:
>  lab:
>  subsampling_scheme: lab
>    geographic_scale: division 
>    region: North America
>    country: USA
>    division: Illinois
>    title: "Lab Sequences with regional subsampling"
>
>filter:
>  lab:
>    skip_diagnostics: True
>
>subsampling:
>  lab:
>    Illinois:
>      exclude: "--exclude-where 'division!={division}'"
>
>files:
>  auspice_config: "my_profiles/lab/auspice_config.json"
>  colors: "my_profiles/lab/colors.tsv"
>
>skip_travel_history_adjustment: True

I tried this with several other profiles and intentionally aborted the run with ctrl-Z. Each time, the snakemake --unlock failed until I put the dummy files back.

**Comment by rneher** [comment]
did you try?
`snakemake --unlock --profile <my-profile>`

**Comment by emmahodcroft** [comment]
I ran into this same problem yesterday and using `snakemake --unlock --profile <my-profile>` worked for me.

I admit, though, that this may not be intuitive to users -- it had me stumped for a bit.

**Comment by bsiranosian** [comment]
In general (haven't tested in this specific case), you can run snakemake with the `--nolock` parameter to ignore lockfiles entirely and get around this issue.
