### ISSUE TITLE
There seems to have been an error accessing that dataset.  Details: Couldn't load JSONs 

### ISSUE THREAD

**Issue by sofiabanu** [nextstrain/ncov#588]
![nextstrain_error](https://user-images.githubusercontent.com/38123605/111596633-5e126a80-87f3-11eb-84fa-e0057f5bac06.png)

After exporting the JSON to github, we aren't able to visualize our analysis. The error details are attached in the image.

Hope to resolve this issue soon!

**Comment by jameshadfield** [comment]
Apologies! This was fixed by auspice v2.24.1 which has just been released to nextstrain.org
