### ISSUE TITLE
Using R packages to download sequence data from GISAID

### ISSUE THREAD

**Issue by BryanTegomoh** [nextstrain/ncov#598]
Are you aware of any folks using R packages to directly download genomic data from GISAID and/or GenBank? 

My guess is, probably some R package might exist for downloading directly from GISAID/GenBank? 

Thanks

**Comment by rneher** [comment]
You are probably better off asking this question in an R forum.

But there are tools for genbank, see here for example:

https://bioconductor.org/help/course-materials/2011/BioC2011/LabStuff/publicDataTutorialOverview.pdf
