### ISSUE TITLE
Error running the basic analysis on example data.

### ISSUE THREAD

**Issue by riju-maiti** [nextstrain/ncov#608]
Hi. I'm current postgraduate getting familiar with running phylogenetic analysis using Nextstrain. However, when trying to run the basic analysis on the example data, I'm getting the following errors:

[Fri Apr 16 10:23:28 2021]
Error in rule subsample:
    jobid: 14
    output: results/global/sample-global.fasta, results/global/sample-global.txt
    log: logs/subsample_global_global.txt (check log file(s) for error message)
    shell:

        augur filter             --sequences results/filtered.fasta             --metadata data/example_metadata.tsv             --sequence-index results/combined_sequence_index.tsv             --include defaults/include.txt             --exclude defaults/exclude.txt                                                                                                        --group-by country year month             --sequences-per-group 20                                       --output results/global/sample-global.fasta             --output-strains results/global/sample-global.txt 2>&1 | tee logs/subsample_global_global.txt

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/subsample_global_global.txt:
usage: augur [-h]
             {parse,index,filter,mask,align,tree,refine,ancestral,translate,reconstruct-sequences,clades,traits,sequence-traits,lbi,distance,titers,frequencies,export,validate,version,import}
             ...
augur: error: unrecognized arguments: --output-strains results/global/sample-global.txt

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /root/ncov/.snakemake/log/2021-04-16T102324.018031.snakemake.log

I'm not sure why this error is coming up. I believe I have installed the required packages correctly (I get the version numbers when I run augur). I think it's because the command should be --export rather than --output, but I'm not sure how to change this nor am I sure if that is correct!

**Comment by jameshadfield** [comment]
Hi @riju-maiti - this is due to an out-of-date version of augur. [This issue](https://github.com/nextstrain/cli/issues/119) ran into the same problem.

You can update augur via:
* `snakemake --use-conda` will let snakemake install the required dependencies automagically
* `conda install -c bioconda augur=12.0` will install an updated augur version into your current conda env

**Comment by riju-maiti** [comment]
Thank you! Seems to have worked now. Apologies for bringing up the issue again.

**Comment by jameshadfield** [comment]
No worries - glad to hear it's working!
