### ISSUE TITLE
logistic growth needs units and symmetric color map

### ISSUE THREAD

**Issue by rneher** [nextstrain/ncov#617]
Our logistic growth coloring 
![image](https://user-images.githubusercontent.com/8379168/116118140-4c0ecc00-a6bd-11eb-919c-4b25cdbc221d.png)

should specify the unit in the legend (presumable %/week) and ideally would use a color map where no-growth has a neutral color.

**Comment by trvrb** [comment]
It would be good to update the "Color by" title with to be `Logistic growth per year`.

In terms of color ramp, I think this requires an Auspice fix. We had originally considered a `range` for https://github.com/nextstrain/augur/blob/master/augur/data/schema-export-v2.json#L157, but it was never implemented. Given that this is a continuous coloring, we don't have a way to enforce color ramp at the moment. cc @jameshadfield

**Comment by jameshadfield** [comment]
Couple of improvements should really help here:
- [ ] Allow `unit` to be specified in the `colorings` (e.g. "%/year") and then Auspice would add this to the legend entries
- [ ] We currently allow non-continuous scales to provide a scale where values are given hexes, and missing values are given greys. For continuous scales we could allow one to define certain values and have d3 interpolate between them.

E.g. for this example the following would look good:
```js
      {
        "key": "logistic_growth",
        "title": "Logistic growth",
        "unit": "%/year",
        "type": "continuous"
        "scale": [
          ["-20", "#3350ff"], // blue
          ["-0.11", "#38d076"], // green
          ["-0.1", "#d0d0d0"], // grey
          ["0.1", "#d0d0d0"], // grey
          ["0.11", "#f7e944"], // yellow
          ["10", "#ff0808"] // red
        ]
      },
```

**Comment by jameshadfield** [comment]
@huddlej -- I'm confident that the spec in #1340 will be available in live nextstrain.org within the next few days, but to close this issue we'll need a `scale` and `legend` entry added to the coloring info for `logistic_growth`.

P.S. There's something funny going on with the dataset JSON that's produced from the pipeline. The coloring definition for `logistic_growth` (and others, like `S1_mutations`) is repeated in the dataset JSON. Presumably the first one comes from the `global_auspice_config.json` (or similar) and the second is added to the array by one of our scripts.
