### ISSUE TITLE
Genomic epidemiology of novel coronavirus (HCoV-19)

### ISSUE THREAD

**Issue by Fungker** [nextstrain/ncov#62]
Sorry to bother you,  I want to know that how can I get the date information about the branch(i. e.  
the original gene generate the first branch) in the website (https://nextstrain.org/ncov) . We did not find it in the github data, but you can hover over the branch to show the inferred date.

**Comment by Cholokiwi** [comment]
I think it is in the Genomic epidemiology notes
https://www.ncbi.nlm.nih.gov/nuccore/MN908947
Hope it helps,

Roy

**Comment by trvrb** [comment]
You can always download the complete analysis data set at http://data.nextstrain.org/ncov.json. This is what the nextstrain.org front-end renders. Nodes in this tree have date information. More information on this schema is described here: https://github.com/nextstrain/ncov#developer-notes. Good luck!
