### ISSUE TITLE
Repeatedly getting "Nothing to be done message from Snakemake"

### ISSUE THREAD

**Issue by riju-maiti** [nextstrain/ncov#624]
Hello,

For the past few weeks Nextstrain has been creating the phylogenetic trees with no hitch. However, when I have tried running it today, it's outputting the following message: 

localrules directive specifies rules that are not present in the Snakefile:
        upload
        download

Building DAG of jobs...
Nothing to be done.
Complete log: /root/ncov/.snakemake/log/2021-05-04T183805.182767.snakemake.log

The trees don't seem to be building despite providing new data, so I'm not sure why it keeps saying "Nothing to be done". Is there something I need to specify in the command, or is there something I need to delete/move around to get this to work?

Best,
Riju

**Comment by jameshadfield** [comment]
Hi @riju-maiti -- snakemake _should_ pick up that there is new data based on the timestamps of the input files. Troubleshooting why it doesn't work as expected can be hard, but there are two easy things to try:
1. Run snakemake with `-r` which should print out the reason why a job is not running
2. Make a backup of the `results` and `auspice` directories if needed, then run `rm -rf auspice results`

**Comment by huddlej** [comment]
@riju-maiti, you can also try forcing Snakemake to run the whole workflow from the beginning with:

```
snakemake --forceall [... your other workflow flags ...]
```

This approach can reveal missing inputs that Snakemake might not otherwise look for when other intermediate files already exist.

**Comment by riju-maiti** [comment]
> Hi @riju-maiti -- snakemake _should_ pick up that there is new data based on the timestamps of the input files. Troubleshooting why it doesn't work as expected can be hard, but there are two easy things to try:
> 
> 1. Run snakemake with `-r` which should print out the reason why a job is not running
> 2. Make a backup of the `results` and `auspice` directories if needed, then run `rm -rf auspice results`

The second option of deleting the results and auspice directories seemed to do the trick

I tried "-r" and "--forceall" based on the Snakemake documentation but it didn't seem to do anything - just printed out the same message. Regardless, managed to create the trees now, thank you @jameshadfield!

**Comment by BryanTegomoh** [comment]
Just ran into this issue and the second option by @huddlej worked for me

**Comment by Rajan-sust** [comment]
```
ncov$ mkdir backup
ncov$ mv results backup
ncov$ mv auspice backup
```
