### ISSUE TITLE
nextstrain_ncov_timetree file(1) and nextstrain_ncov_tree(2)

### ISSUE THREAD

**Issue by Fungker** [nextstrain/ncov#63]
I want to know how to read the file with pyhon. Currently, I use the Phylo libary to load, but we did not find differences between the two files, how can i find the time information

**Comment by trvrb** [comment]
I'd recommend parsing http://data.nextstrain.org/ncov.json. This has time, location and mutation information. Otherwise, you can get time information from the file `results/branch_lengths.json` generated during the build process. Hope this helps.
