### ISSUE TITLE
No module named 'augur.io'

### ISSUE THREAD

**Issue by ArnieBerg** [nextstrain/ncov#637]
After installing Nextstrain and the ncov builds on a new machine, I get the following error when running ‘snakemake  --cores 2 --profile ./my_profiles/getting_started -p’:

        python3 scripts/sanitize_sequences.py             --sequences data/example_sequences.fasta.gz             --strip-prefixes hCoV-19/ SARS-CoV-2/             --output /dev/stdout             | nextalign             --jobs=2             --reference defaults/reference_seq.fasta             --genemap defaults/annotation.gff             --genes ORF1a,ORF1b,S,ORF3a,M,N             --sequences /dev/stdin             --output-dir results/translations
--output-basename seqs_example-data             --output-fasta results/aligned_example-data.fasta             --output-insertions results/insertions_example-data.tsv > logs/align_example-data.txt 2>&1
Traceback (most recent call last):
  File "/home/pds_wimmer/ncov/scripts/sanitize_sequences.py", line 2, in <module>
    from augur.io import open_file, read_sequences, write_sequences
ModuleNotFoundError: No module named 'augur.io'

Although augur is successfully installed on this computer, the file augur.io does not exist.  Where should it be?

**Your environment: if browsing Nextstrain online**
 - Operating system: Ubuntu 18.04 running on WSL2 

**Your environment: if running Nextstrain locally**
 - Running Nextstrain CLI native
 - Version (e.g. `auspice 2.7.0`):  augur 11.1.2

**Comment by huddlej** [comment]
Hi @ArnieBerg! Sorry about this issue. The `io` module was added in Augur 11.3.0. If you update Augur to its latest version (via `conda update augur` or `python3 -m pip install --upgrade nextstrain-augur`), this should resolve the issue. Alternately, you can run your Snakemake workflow with `snakemake --use-conda ...other args here...` and Snakemake will create a Conda environment for you on the fly and maintain this at the correct Augur versions in the future.

**Comment by ArnieBerg** [comment]
Yes!  Problem solved.  The conda update method did not work, but the pip install upgrade did.

Thank-you!

Arnie Berg
