### ISSUE TITLE
Sequences shorter than 25000

### ISSUE THREAD

**Issue by lasupernova** [nextstrain/ncov#638]
**Context**  
Looking into (viral) substructures, such as spike proteins or others, is often used as opposed to whole genome sequences. However, viruses and viral substructures are often of shorter length (in our case  the **whole** virus genome of a Rotavirus is  only 12.000 - 18.000 bp). 

**Description**   
Decreasing the limit of 25000 bp or having a flag/option to also include and analyze shorter sequences would be very helpful.

**Possible solution**   
Is there a way to modify the code in a way that shorter sequences can also be included in the analysis? In which of the scripts is the limit of 25.000 bp defined? Would it be as simple as changing the hard-coded value here (in which case I could clone the repository and change this only locally)?

**Comment by huddlej** [comment]
Hi @lasupernova! You can override the ncov workflow's default minimum length of 27,000 bp by setting [the `filter: min_length` parameter](https://nextstrain.github.io/ncov/configuration.html#filter) in your build configuration file. For example, if you have created a file named `builds.yaml` to define your analysis, you can add the following lines to that file:

```yaml
filter:
  # Define minimum length that allows shorter genomes than the default.
  min_length: 5000
```

This parameter will override the default parameter in your analysis.

You may also want to check out [our complete list of parameters you can configure in the workflow](https://nextstrain.github.io/ncov/configuration.html).

**Comment by lasupernova** [comment]
Thanks a lot! That list is exactly what I needed :)
