### ISSUE TITLE
Remove travel history (exposure)

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/ncov#646]
[Fifteen months ago](https://github.com/nextstrain/ncov/commit/d0c75376bb87996e5d25542a510e5a8a87f1cc3b) we implemented an ad-hoc approach to dealing with samples which were travel associated (e.g. were sequenced in country B but had recently arrived from country A where the infection was believed to have been acquired). At this time we had few sequences, and were actively tracking the travel history for all of them. This implementation required new metadata fields being introduced, e.g. `country_exposure`, and the DTA was performed on this data. We modified the tree such that terminal nodes actually became 2 nodes: an internal node with the country of exposure, and a single child node with the country of sampling (ditto for other geographic resolutions); a solution which was less than ideal for Auspice (e.g. mutations went on _one_ of those branches, so tips often appeared to have no mutations!). 

The situation now is very different. We have exposure information for a vanishingly small minority of sequences, and for some data sources (genbank) we don't have this at all. We also avoid DTA reconstructions for most builds. The time is right to remove this from our workflow. This issue represents a (potentially incomplete) checklist of what needs to be done.

- [ ] Remove the `incorporate_travel_history` rule, remove the script it calls (`./scripts/modify-tree-according-to-exposure.py`, remove the function `_get_exposure_trait_for_wildcards`, and modify the input to the rule `finalize` so that it now uses the auspice JSON from an upstream rule.
- [ ] Update `adjust_regional_meta.py` to no longer rely on or modify `{trait}_exposure`. This may also necessitate further changes. 
- [ ] Add helpful error messages for the main snakemake file (or an imported `deprecations.smk` or similar) which,
  - [ ] If the config file sets `skip_travel_history_adjustment=true` the notify that this setting is now unneeded 
  - [ ] If auspice config JSONs define colourings for exposure traits,notify that these should be updated. The workflow should still complete if these aren't updated, but the colouring will either be unwanted or will be dropped by `augur export` if it no longer appears in the metadata.
  - [ ] If a `builds.yaml` has a top-level key `exposure` then warn that this is no longer used & should be removed
  - [ ] If a `builds.yaml` defines `traits` which use `{trait}_exposure` then either (i) warn that these are no longer used & modify the config data on the fly to use `{trait} instead` or (ii) print an error & exit.
  - [ ] If any subsampling schemes use `{trait}_exposure` in their exclude rules / group-by rules (etc) then we should print an error & exit. 
- [ ] Modify the ingest scripts / workflows to remove the `{trait}_exposure` fields from the metadata. (Not essential to roll out these changes, but it should simplify things for us.)

**Comment by emmahodcroft** [comment]
I agree that travel history is no longer as useful as it once was. Couple of things I'd say:
- A lot of this information was fairly painstakingly curated so I'd vote to keep it around in `metadata` & etc. It may be useful for those in the future who are looking back.
- This may one day be useful once more, depending on how low transmission ends up falling (or maybe for individual countries, in future) - so while happy to remove, we should avoid doing something that would make it hard to reimplement, or for those who may find it useful in future to reimplement!

**Comment by trvrb** [comment]
I definitely agree that `country_exposure` reconstruction should be removed from the `ncov` workflow. And I see Emma's point about how much work went into our curation of these fields in metadata. It seems like this curated data could be quite helpful for in-depth analyses of early pandemic spread, but I don't know how best to message that starting from date X anything listed for `country_exposure` is almost certainly just `country`. I guess I'd leave fields in provisioned metadata for now, but just don't touch / expect these fields in the `ncov` workflow.
