### ISSUE TITLE
Dead link in doc

### ISSUE THREAD

**Issue by alaindebecker** [nextstrain/ncov#663]
The doc page [ncov/docs/naming_clades.md](https://github.com/nextstrain/ncov/blob/master/docs/naming_clades.md) has a dead link.

The [simple python script](https://github.com/nextstrain/ncov/blob/master/assign_clades.py) on the last but one paragraph points to `ncov/blob/master/assign_clades.py` which do not exists. 

Possible correction: [ncov/blob/master/scripts/assign_clades.py](https://github.com/nextstrain/ncov/blob/master/scripts/assign_clades.py), although this script is flaged as obsolete.

**Comment by varshitakolipaka** [comment]
Hi, there!
I believe the [documentation](https://github.com/nextstrain/ncov/blob/master/docs/src/reference/naming_clades.md) points to [this python script](https://github.com/nextstrain/ncov/blob/master/scripts/assign_clades.py), and It appears not to be marked obselete.

**Comment by eharkins** [comment]
Thanks! I believe the latest version of the relevant script is linked on this page: https://docs.nextstrain.org/projects/ncov/en/latest/reference/naming_clades.html.

The link points to https://github.com/nextstrain/ncov/blob/master/scripts/assign_clades.py. Let me know if this is not what you're looking for. In general, the updated docs and tutorial for this repo are now located at https://docs.nextstrain.org/projects/ncov/en/latest/index.html. Please let us know if you find more broken links there or elsewhere on docs.nextstrain.org! 

@rneher do we need to update https://docs.nextstrain.org/projects/ncov/en/latest/reference/naming_clades.html#identifying-nextstrain-clades at all if the above script linked in that section is indeed "obselete"?
