### ISSUE TITLE
Missing link from Germany to Italy nCov occurence on La Gomera?

### ISSUE THREAD

**Issue by Algorithman** [nextstrain/ncov#68]
@trvrb 
I write you here, because i don't have a twitter account (Edit i made an account now)

I think there is a possibility that the missing link for the transmission in europe is on the canary islands.
After the virus was detected at Webasto employees, one contact of a employee went to his holiday to the canary islands with 4 friends, to La Gomera to be precise. (https://www.epochtimes.de/politik/deutschland/coronavirus-erreicht-la-gomera-deutscher-tourist-ist-erster-coronafall-in-spanien-a3142994.html sorry, it's german). He was hospitalized there (and may have infected others on Teneriffe). At least one of the friends went back to germany. I do not know which flight they used or if they were put into quarantine. There was no news report after this.

Sadly it seems neither the strain from La Gomera nor from mainland spain is on the GISAID database. It would be really interesting to see if there was a mutation which fits the others in europe. But i think the chance for that is quite high.
Maybe you have sources you can activate to get a genome analysis for the virus in spain/canary islands.

Thanks for your hard work and for the great tool at nextstrain.org.
Be healthy and good luck

Algorithman
(I watch this if you have questions)

**Comment by Algorithman** [comment]
Addition: on 2020-02-05 one of his friends went back to germany.
https://www.youtube.com/watch?v=kDacUnZxYVc

**Comment by acx01b** [comment]
Did you see the Finish March and Shanghai January sequences matching the Bavaria sequence at the root of the European tree ? Also the mutation from Germany -> Italy is in an amino acid motif of the RdRp which stays the same in many Bat-CoVs. @Algorithman

**Comment by emmahodcroft** [comment]
Hi! While we appreciate this discussion is interesting to people, we really appreciate if the issues log can be kept for issues with the software or data/sequences. I'm going to close this but feel free to continue discussing this elsewhere!
Sorry about that!
