### ISSUE TITLE
portugese translations

### ISSUE THREAD

**Issue by rneher** [nextstrain/ncov#7]
@7glaucio: yes, there is interest in a Portuguese translation. We made a copy of the narrative file

https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep-pt_2020-01-25.md

@andersonbrito is also interested in contributing here and he has expertise in the subject matter. Maybe the two of you can coordinate how to best get this done.

**Comment by rneher** [comment]
Since there are several people working on translation right now. I suggest we move this translation into branch 

https://github.com/nextstrain/ncov/tree/sit-rep_pt

this will avoid conflicts between different people editing and allows us to separate ongoing work from the production version. let us know if you need help.

**Comment by 7glaucio** [comment]
Hey @rneher , the link is not working. Page not found. And as far as I noticed, there is only one branch so far (master).

**Comment by rneher** [comment]
sorry. Must have gotten accidentally deleted as Spanish and Mandarin were merged. the branch is back. feel free to get going.

**Comment by 7glaucio** [comment]
No problem. Thanks, working on it.

**Comment by andersonbrito** [comment]
Hi @7glaucio and @rneher,

I have just finished proofreading the translations that Glaucio did (great job, by the way) :)

The version I see at the [master branch] (https://github.com/nextstrain/ncov/blob/master/narratives/ncov_sit-rep-pt_2020-01-25.md) still shows in English, while the Portuguese version lives in [this branch](https://github.com/nextstrain/ncov/blob/a03c438a296712f03ee9fcdeaa3fb7fbfb79a778/narratives/ncov_sit-rep_pt_2020-01-25.md).

I've been unable to edit the branch above (only the master one). How can we sort that out? I downloaded the raw file in Portuguese, edited it, and I was wondering if I could simply commit on the master "ncov_sit-rep_**pt**_2020-01-25.md" file version.

**Comment by jameshadfield** [comment]
@andersonbrito -- @7glaucio's changes are now in the branch `sit-rep_pt` branch of this repo (nextstrain/ncov) -- you should be able to edit by adding a commit to that branch (I've given you access to this repo).

**Comment by 7glaucio** [comment]
I'm glad to hear that @andersonbrito . I was a little worried, since I ain't specialized in the subject of discussion. I did my best. I hope it helps.

**Comment by rneher** [comment]
merged. Thanks  @7glaucio and @andersonbrito!

**Comment by rneher** [comment]
@7glaucio what is your twitter handle. I was going to announce the report from the nextstrain twitter account and tag you.

**Comment by 7glaucio** [comment]
@rneher My username is @glauciomarcos . Thanks. I use LIn a lot if you're sharing there as well.

**Comment by rneher** [comment]
here is the live version. needed to change the header slightly:
https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-01-25?n=0

**Comment by andersonbrito** [comment]
Is this header fixed, no matter the language?
By the way, I have just fixed a few markdown issues. New version committed now.

**Comment by rneher** [comment]
yes. header fields are fixed. non ascii characters not allowed. I'll push your changes live. Please make a branch there were problems with the header. To avoid conflicts in master, please make a new branch if further changes are required
