### ISSUE TITLE
Suggesting a strain to add to exclude.txt

### ISSUE THREAD

**Issue by danrlu** [nextstrain/ncov#704]
**Description**
Ran into a strain `Egypt/NRC-6631/2020` that was collected in Sep 2020 and has 60 mutations
![image](https://user-images.githubusercontent.com/20667188/128603424-21d727eb-36f4-4859-9aa3-11867d9ada0e.png)

**Comment by emmahodcroft** [comment]
Thanks @danrlu - I agree, this should be in exclude - we'll add it!
