### ISSUE TITLE
Expose crowding penalty from priorities script as a workflow parameter

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#708]
**Context**
[Based on conversations on the discussion site](https://discussion.nextstrain.org/t/proximity-confusion/646), we learned that [the default crowding penalty](https://github.com/nextstrain/ncov/blob/29c09377addbd7fdca5c94ebd8edd2426f56b92f/scripts/priorities.py#L18) prevents users from subsampling many similar contextual strains for variant-specific builds. The crowding penalty technically does its job as expected in these cases, by penalizing too many similar strains in the same group. However, when this behavior is not desired, users have no recourse to change it other than editing the priorities script.

**Description**
Define the crowding penalty in `defaults/parameters.yaml`, [pass this value to the priorities script as an explicit argument](https://github.com/nextstrain/ncov/blob/e7724efa467812294e1fca6ba7993010631d89f7/workflow/snakemake_rules/main_workflow.smk#L482), and document the new parameter in the workflow configuration guide (`docs/configuration.md`).

**Comment by danrlu** [comment]
With this [change](https://github.com/nextstrain/ncov/commit/3544dfd7df44697e231582bd96d3045fabc295c0), we were able to fully surface it [as a parameter](https://github.com/chanzuckerberg/aspen/blob/01cff58f022d1fa3f507305fd2ff3fbea1fbdc8b/src/backend/aspen/workflows/nextstrain_run/patches/crowding_penalty.patch) and set it in our [configs](https://github.com/chanzuckerberg/aspen/blob/01cff58f022d1fa3f507305fd2ff3fbea1fbdc8b/src/backend/aspen/workflows/nextstrain_run/builds_templates/targeted.yaml#L37-L38). All tested to be working. 

I was trying to create a PR to `ncov` but cannot decide how to best describe this in `defaults/parameters.yaml` and `docs/src/reference/configuration.md` (also not sure it's the right file) so I will leave it to you guys to fully complete it. 

Thanks for the help and the changes!!!

**Comment by danrlu** [comment]
Can this be assigned to Sidney and me? I'll get her help to update documentation after the change.

**Comment by huddlej** [comment]
Yes! Thank you for picking this up, @danrlu and @sidneymbell!

**Comment by emmahodcroft** [comment]
Thanks @danrlu & @sidneymbell ! I was working on this but Omicron has arrived and I won't be able to do anything more for the foreseeable future. Thanks!

**Comment by danrlu** [comment]
@emmahodcroft do you have a branch that I can try incorporate what you have already done as well?

**Comment by emmahodcroft** [comment]
Hi @danrlu -- unfortunately not - I'd only gotten so far as sketching out on paper what needed to be added where, but not to coding it. Sorry!

**Comment by danrlu** [comment]
@emmahodcroft no worries! Just want to check so what you already did doesn't go to waste ;)
