### ISSUE TITLE
Error when running a basic analysis with example data

### ISSUE THREAD

**Issue by qiongl-CTDS** [nextstrain/ncov#725]
Hi, I'm new to nextstrain and I was following the [this tutorial](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html) to run a basic analysis of example data.

After activating the nexstrain env using conda as suggested in tutorial, I ran
```
nextstrain build . --cores 4 --use-conda --configfile ./my_profiles/getting_started/builds.yaml
```
 It returns with 
```
CreateCondaEnvironmentException:
The 'conda' command is not available in the shell /bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.
```
I was able to run the pipeline by removing the `--use-conda` . Do you have any idea how to avoid this error by using conda environment?
Thank you

**Comment by jameshadfield** [comment]
Hi @qiongl-CTDS - could you run `nextstrain check-setup` and see if `nextstrain` is running the workflow in a docker container, as conda is not present there (which is normal). If so, [this discussion thread](https://discussion.nextstrain.org/t/installation-issue/626) should solve this issue.

**Comment by qiongl-CTDS** [comment]
oh I see, the current nextstrain container doesn’t support conda.
Thank you for clearing it up!

Qiong
