### ISSUE TITLE
Translate situation report to Italian

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#73]
The narrative from 2020-03-05 should be translated to Italian. A branch exists as `sit-rep_it` where this can be done, and the file to translate is `ncov_sit-rep_it_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_it/narratives/ncov_sit-rep_it_2020-03-05.md

Note this file is in Markdown - it's important to to change any links!

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_it/sit-rep/it/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

**Comment by cassiawag** [comment]
This should be ready to merge (if you can get the internal links to work)! All links are checked, it's had two translators eyes on it, and I added (in inglese) to all our external links.

**Comment by cassiawag** [comment]
I think I properly threaded the internal links, used: [https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-05?n=7](https://nextstrain.org/narratives/ncov/sit-rep/it/2020-03-05?n=7), etc.

**Comment by emmahodcroft** [comment]
That looks good Cassia!
