### ISSUE TITLE
Broken links within documentation tables

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov#734]
**Current Behavior**
Links within the tables on the [orientation files page](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/orientation-files.html) are broken because they are not converted to the appropriate `.html` link. 

**Possible solution**
This bug might be related to sphinx-markdown-tables, see https://github.com/ryanfox/sphinx-markdown-tables/issues/18 for suggested solutions.

**Comment by huddlej** [comment]
We should eventually switch these pages from markdown to restructured text. I wonder if this change would also fix these links...

**Comment by joverlee521** [comment]
> We should eventually switch these pages from markdown to restructured text. I wonder if this change would also fix these links...

Yeah, if the plan is to switch to restructured text then this would no longer be a problem.
