### ISSUE TITLE
Translate situation report to Mandarin

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#74]
The narrative from 2020-03-05 should be translated to Chinese. A branch exists as `sit-rep_zh` where this can be done, and the file to translate is `ncov_sit-rep_it_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_zh/narratives/ncov_sit-rep_zh_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links!

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

**Comment by cassiawag** [comment]
@fzhang12 and @alvinxhan -- hello! We've got a new nextstrain situation report that would be great to be translated into Mandarin. Would either of you be able to help translate it this go around? Thanks very much!

**Comment by cassiawag** [comment]
@fillorkill translated the sitution report; big thanks, btw! Can anyone give a proofread, @fzhang12, @alvinxhan, @wdingx ? It's good to have two people looking at every translation.

**Comment by emmahodcroft** [comment]
Unfortunately this narrative seems broken... https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05 We may have to test locally before continuing.

**Comment by emmahodcroft** [comment]
(Nobody's fault - the markdown is very picky - one stray quote and it's all broken!)

**Comment by fzhang12** [comment]
I am proofreading the work. I have one issue here, the translation of 'divergence'. We don't actually have a Chinese name for it, but it is not "分叉" definitely, "分叉" means branches. Any ideas? @alvinxhan @wdingx . What about “差异程度”?

**Comment by fzhang12** [comment]
@fillorkill , thanks for the translation. Glad working with you.
@emmahodcroft I've finished proofreading. The content itself now could be pushed online.

**Comment by cassiawag** [comment]
Thank you @fillorkill & @fzhang12 -- do either of you have twitter handles we can tag when we post the update?

I got the narrative fixed, so the live preview is working here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_zh/sit-rep/zh/2020-03-05?n=12

**Comment by emmahodcroft** [comment]
Thank you guys for the hard work!

**Comment by fzhang12** [comment]
@cassiawag thanks you too for the effort.
Oh I forgot to add our names on the author list. I just updated the file, adding my name onto it. but I have no idea about @fillorkill
My twitter: fengjun_zhang

**Comment by cassiawag** [comment]
Translation is live: https://nextstrain.org/narratives/ncov/sit-rep/zh/2020-03-05

Thanks for the hardwork @fzhang12 & @fillorkill !
