### ISSUE TITLE
Tutorial/example for combining new sequences with GISAID data

### ISSUE THREAD

**Issue by aamtemp** [nextstrain/ncov#742]
Thank you for all of your incredible resources. I was wondering if it would be possible to add a tutorial or set of example files for explicitly walking beginners through a use case many of them have: when you've sequenced your own samples and want to build a tree using them + some appropriate contextual samples from GISAID. Right now it seems like the tutorials mostly focus on subsampling from GISAID or on preparing your own samples and metadata from scratch, and it's been a little challenging figuring out how to configure YAML files, etc for combining both (for people like us who are not really fluent in this whole ecosystem). If something like this already exists, my apologies and feel free to point me there!

**Comment by jameshadfield** [comment]
Moved to https://discussion.nextstrain.org/t/tutorial-example-for-combining-new-sequences-with-gisaid-data/762/2
