### ISSUE TITLE
Run functional tests in Travis CI

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#753]
## Context

We've started to write Cram-based functional tests for this workflow and associated scripts, but we do not currently run these tests as part of our standard Travis CI.

## Description

Not all critical components of the workflow are tested by the minimal CI profile. We should run functional tests along with the current minimal Snakemake run as part of CI. 

## Possible solution

Naively, we could make this happen by installing Cram with pip and running Cram on all `*.t` files in the `tests/` directory.

Comments in `tests/different-inputs.t` suggest that Cram should be run with `cram --preserve-env tests/different-inputs.t`.

In practice, the "different inputs" test takes >8 minutes to run, more than we typically prefer for CI tests. Maybe we could pare these tests down to more minimal versions that test the same logic?

**Comment by jameshadfield** [comment]
https://github.com/nextstrain/ncov/pull/671 started down this road, but using GitHub Actions, it'd be great to pick this up. (I'd prefer we move to one CI runner where possible, but that's part of a bigger discussion.)

**Comment by huddlej** [comment]
This was mostly resolved by #767. How to handle the "different inputs" tests should be a separate issue.
