### ISSUE TITLE
Install Error: An error occurred while installing package 'conda-forge::ca-certificates-2021.10.8-ha878542_0'

### ISSUE THREAD

**Issue by AMPByrne** [nextstrain/ncov#759]
**Current Behavior**
Hi, I am trying to install the ncov workflow for nextstrain for the first time following the online guide (https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html). 

However, when I run the 'basic analysis with example data' to check the Nextstrain environment is properly configured (nextstrain build . --cores 4 --use-conda \
  --configfile ./my_profiles/getting_started/builds.yaml)

I receive the following output:
Building DAG of jobs...
Creating conda environment workflow/envs/nextstrain.yaml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /home/alexbyrne/mnt/MITeam/Alex/ncov/workflow/envs/nextstrain.yaml:
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
ERROR conda.core.link:_execute(699): An error occurred while installing package 'conda-forge::ca-certificates-2021.10.8-ha878542_0'.
Rolling back transaction: ...working... done

[Errno 95] Operation not supported: 'cacert.pem' -> '/home/alexbyrne/mnt/MITeam/Alex/ncov/.snakemake/conda/01f7ce68e4b2a5519dffc9789a4aee6d/ssl/cert.pem'
()

It appears there's an issue installing 'ca-certificates-2021.10.8-ha878542_0' so I download this from the anaconda webpage and installed it in the nextstrain env, and re-ran the command, but I still get the same error.

**Your environment: if running Nextstrain locally**
 - Operating system: Ubuntiu 20.04.2 LTS
 - Browser: Firefox 93.0
 - Version (e.g. `auspice 2.7.0`): ncov v9

**Comment by tsibley** [comment]
Hmm, that's a strange error indeed. Sorry you're running into it!

It appears to me to be an internal Conda bug and/or packaging issue with that version of `ca-certificates`. The mention of `conda.core.link` and `Operation not supported: 'cacert.pem' -> '/home/…'` in the error suggests to me that the underlying cause may be that the filesystem you're using doesn't support symlinks. Conda may assume that since your host is Linux, all filesystems support symlinks, but that's not always true.

Can you check what filesystem is in use by running

```
findmnt -T /home/alexbyrne/mnt/MITeam/Alex/ncov
```

and reporting the output here?

**Comment by AMPByrne** [comment]
Thanks for getting back to me so quickly.

You response got me thinking, I was trying to run the install from one of my mounted drives, so moved the ncov directory to my hom directory and re-ran the command and it got past that error and finished successfully. 

Just to close the loop though I ran that command and here is the output:
`TARGET                     SOURCE                                               FSTYPE OPTIONS
/home/alexbyrne/mnt/MITeam //fs-03440ceb7991fa26b.int.sce.network/share/fsx-007 cifs   rw,relatime,vers=2.1,sec=ntlmsspi,cache=strict,username=alexbyrne,uid=3001,noforceui`
