### ISSUE TITLE
Translate situation report to Portuguese

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#76]
The narrative from 2020-03-05 should be translated to Portuguese. A branch exists as `sit-rep_pt` where this can be done, and the file to translate is `ncov_sit-rep_pt_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_pt/narratives/ncov_sit-rep_pt_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links!

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_pt/sit-rep/pt/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

**Comment by cassiawag** [comment]
@andersonbrito & @7glaucio -- we've got another nextstrain narrative that would be great to be translated into Portuguese. Are either of you able to translate this go around?

All the information is above. Please let me know if you have any questions. Thank you so much!!

**Comment by 7glaucio** [comment]
I gonna take a look tonight (10 hours from now). @andersonbrito , if you have time to start doing earlier than me, just let me know to make sure of not getting the same parts.

**Comment by andersonbrito** [comment]
Thank you for letting us know, @cassiawag and @emmahodcroft.

@7glaucio, I may only have time over the weekend. Please, feel free to start the translation. In case you find some technical sentences you are unsure about how to translate, you can leave them untranslated, and I'll help translating those and any other remaining sentences. Cheers!

**Comment by 7glaucio** [comment]
Yessir. Any questions I let you know since I have you on my LinkedIn as well.

**Comment by 7glaucio** [comment]
The first version is done, @andersonbrito . Feel free to take a look when you have the chance.

1 - Special attention to the parts "community transmission" is mentioned, because it's a technical term which I was unsure on how to deal properly with it. 

2 - About the scientific credit page: Should we translate the labs names? @emmahodcroft @cassiawag

**Comment by cassiawag** [comment]
Thanks @7glauci! It's looking good; don't worry about translating lab names.

**Comment by emmahodcroft** [comment]
Thanks so much @7glaucio ! @andersonbrito  if you have a moment to check that would be great! 

Yes, please don't worry about translating lab names. Just let me know when you guys think it's ready!

**Comment by andersonbrito** [comment]
Nice job, @7glaucio, I just had to fix some minor points.

@emmahodcroft and @cassiawag, the PT translation is now available on the sit-rep_tr branch.

**Comment by emmahodcroft** [comment]
This narrative is fixed and ready go to! @cassiawag  (whenever you have time!)

**Comment by emmahodcroft** [comment]
Can anyone still awake let me know their twitter handles if you'd like to be tagged on release?

**Comment by 7glaucio** [comment]
@emmahodcroft My username on Twitter is `glauciomarcos`, and Anderson's is `AndersonBrito_`.

**Comment by 7glaucio** [comment]
@emmahodcroft Should I request the pull or just wait for @cassiawag do something else?

**Comment by emmahodcroft** [comment]
We'll handle it on our end now - just catching up! We've had a lot of translation action here today, but need to just final-check, push, copy, and update the website for each one.

**Comment by emmahodcroft** [comment]
Live and tweeted - thanks guys! https://nextstrain.org/narratives/ncov/sit-rep/pt/2020-03-05
