### ISSUE TITLE
Translate situation report to German

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#78]
The narrative from 2020-03-05 should be translated to German. A branch exists as `sit-rep_de` where this can be done, and the file to translate is `ncov_sit-rep_de_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_de/narratives/ncov_sit-rep_de_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links!

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_de/sit-rep/de/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

**Comment by cassiawag** [comment]
@nicfel Here's Emma's issue for the german translation

**Comment by cassiawag** [comment]
@tolot27 @rneher -- @nicfel has done rough translation, but needs a proofread. Can anyone help out?

**Comment by rneher** [comment]
sure. Will proofread tomorrow morning!

**Comment by rneher** [comment]
I went through the sit-rep and fixed typos. Looks good to me and can go live.

**Comment by emmahodcroft** [comment]
Thanks @nicfel and @rneher ! Note to self, when ready to announce, twitter handles are @nicfelm and @richardneher

**Comment by cassiawag** [comment]
Translation is live: https://nextstrain.org/narratives/ncov/sit-rep/de/2020-03-05
Thanks for the hard work everyone!
