### ISSUE TITLE
Timestamped builds should represent the day the build was launched

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/ncov#788]
**Current Behavior**
`rule dated_json` produces timestamped build assets by adding the YYYY-MM-DD date to the files. Because this date is generated each time the rule runs, it can produce different dates if the build starts on one day and finishes on the next.

**Expected behavior**
The same date should be used for the entire pipeline, and this should be the day it was launched.

**How to reproduce**

Observed in [this AWS run](https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/9e715ae1-aa5d-4d42-97e6-fdde4a757b56), logs [here](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fbatch$252Fjob/log-events/nextstrain-job$252Fdefault$252Fdc17a0e0de8240c194b6073c7ae5870f). 

~This run produced files such as:~ (see below)

**Possible solution**

As snakemake runs each rule in a separate process, and initialises (?) the snakefile each time, we can't store the output of `get_todays_date()` as a global variable. We could use a `PersistentDict` as I did in #782 - e.g. [code here](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/export_for_nextstrain.smk#L224).

**Comment by tsibley** [comment]
@jameshadfield Are you sure that's the right run / the right logs? If I look at the logs or inspect the file list of the workdir archive, I only see files dated `2021-11-19`.

Additionally, I don't see how the code responsible could generate two different dates, since the `expand()`s are processed first and `get_todays_date()` is called at that point:

https://github.com/nextstrain/ncov/blob/49ac73e90398f873a802558ab0aabbb98e26a7cc/workflow/snakemake_rules/export_for_nextstrain.smk#L26-L36

**Comment by jameshadfield** [comment]
Here's one example from those logs:
```
cp auspice/ncov_gisaid_africa.json auspice/ncov_gisaid_africa_2021-11-19.json
...
Missing input files for rule deploy:
--
auspice/ncov_gisaid_africa_2021-11-20.json
...
```

**Comment by tsibley** [comment]
Ah, ok. It turns out that CloudWatch's filter/search returns nothing when I enter `2021-11-20` but finds lines when I enter `"2021-11-20"`.

**Comment by tsibley** [comment]
Simpler than using a PersistentDict would be to define the date of the build in the environment or config before launching.

**Comment by emmahodcroft** [comment]
FYI - I think this has caused builds to fail on Monday & Tuesday this week - at least that's what I surmise from the error messages. See #ncov-gisaid-updates in the slack. So this might be a more common problem than thought.

**Comment by joverlee521** [comment]
@tsibley Using `envvars` makes the environment variable required for all executions, but the build date is not required for the preprocess jobs which use the `upload` rule within `export_for_nextstrain.smk`. I think it would be confusing to require an environment variable that doesn't get used. 

We can add the build date to the config that that gets added in the GitHub rebuild workflows.
