### ISSUE TITLE
Translate situation report to Russian

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#79]
The narrative from 2020-03-05 should be translated to Russian. A branch exists as `sit-rep_ru` where this can be done, and the file to translate is `ncov_sit-rep_ru_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_ru/narratives/ncov_sit-rep_ru_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links!

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ru/sit-rep/ru/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

**Comment by cassiawag** [comment]
Hello @ivan-aksamentov -- we've got another nextstrain situation report that would be great to be translated into Russian. Are you able to translate again?

All of the information is above. Let me know if you've got any questions. Thanks so much!

**Comment by ivan-aksamentov** [comment]
@cassiawag 
Hi Cassia,
Sure, I'll do my best.

**Comment by ivan-aksamentov** [comment]
@cassiawag Hi Cassia, sorry a lot of stuff going on currently, I don't know when I will be able to do the translation. Not this week, unlikely. But it's on my TODO list.

**Comment by emmahodcroft** [comment]
No worries @ivan-aksamentov ! I'll reach out on twitter and see if we can get a couple of people to start - then maybe you can proofread, which will be much less of your time! :)

**Comment by cassiawag** [comment]
@vpuller -- any chance you're available to help translate this? All of the information should be above in Emma's comment. Thank you!

**Comment by cassiawag** [comment]
@irina95511 -- here's the issue for translating the Russian report. Let me know if you have any questions.

**Comment by emmahodcroft** [comment]
@cassiawag , I've got @frogtraveler who may also be able to help translate and/or proofread!

**Comment by frogtraveler** [comment]
Hi @cassiawag, I'll be happy to help! Forgive me my lack of experience with GitHub editing, it says I dont have access to  edit the file- should I create a new branch to edit it and then ask to pull?

**Comment by cassiawag** [comment]
I've given you permission @frogtraveler! Thanks for your help :)

**Comment by frogtraveler** [comment]
Hi @cassiawag. My last translation was overwritten by dtaliun because I believe the version of that user didn't contain my changes. Could you please advise how should I make the changes so that they appear in the main branch?

**Comment by cassiawag** [comment]
@vpuller -- we've a finished a Russian translation of the 03-05-2020 situation report. Any chance you can proofread it?

**Comment by irina95511** [comment]
yes, can do within an hour!

**Comment by irina95511** [comment]
I have finished proofreading. The file looks good to me!

**Comment by cassiawag** [comment]
The translation is live here: https://nextstrain.org/narratives/ncov/sit-rep/ru/2020-03-05
Please share it with your Russian speaking contacts!

@frogtraveler & @dtaliun -- do you have twitter handles we can tag when we post?

**Comment by frogtraveler** [comment]
will definitively share! My tweeter handle is @varvarakozyreva. thanks!
