### ISSUE TITLE
Metadata: date_submitted 

### ISSUE THREAD

**Issue by fergsc** [nextstrain/ncov#796]
Hi,

Within my meta data I have not been including "date_submitted". To date this was not a problem, nextstrain ran to completion and an auspice json was produced.

I just updated and found if date_submitted is not included an error is made in diagnostic.py on the lines
```
to_exclude |= (rare_mutations>args.rare_mutations)&(~recent_sequences)
to_exclude |= (np.abs(clock_deviation+rare_mutations)>args.clock_plus_rare)&(~recent_sequences)
```
I have changed these back to the previous implementation and things look to be working fine. 
If this field is needed I will generate a date_submitted column and fill it was some numbers.

Thanks.

**Comment by j23414** [comment]
I hit the same `recent_sequences` error. Should we add `date_submitted` to the ["Required metadata" documentation](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/data-prep.html#required-metadata)?

**Comment by jameshadfield** [comment]
This was added ~11 days ago in https://github.com/nextstrain/ncov/commit/724ae1dbd8a11d67f29c6347f960259504504167 and we should wrap these inside a conditional which checks if `recent_sequences` is present, as we do for other steps in that script which rely on that metadata. I can get to this tomorrow.
