### ISSUE TITLE
Example analysis stuck at "Downloading and installing remote packages."

### ISSUE THREAD

**Issue by stevin-wilson** [nextstrain/ncov#797]
I tried installing and running the SARS-CoV-2 Workflow as described in [https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html](https://docs.nextstrain.org/projects/ncov/en/latest/analysis/setup.html).  

On running `nextstrain check-setup --set-default`, the following output was received

`Setting default environment to native.`

However, the program seems to be stuck at the `Downloading and installing remote packages.` step while running the following command

`nextstrain build . --cores 4 --use-conda   --configfile ./my_profiles/getting_started/builds.yaml`.

Output

```
Config file defaults/parameters.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Creating conda environment workflow/envs/nextstrain.yaml...
Downloading and installing remote packages.
```

I tried the same steps on 

1. a cluster (running CentOS Linux 8.4.2105)
2. a Linux desktop (running Linux Mint 20.2)
3. a Macbook pro (running macOS Monterey)

In all three environments, the workflow seems to have frozen at the same step (waited for more than 24 hours). I have also attached the conda `nextstrain` [*environment.txt*](https://github.com/nextstrain/ncov/files/7620400/environment.txt) file.

Thank you so much

**Comment by Koen-vdl** [comment]
I experience the same issue after updating to the latest version of the workflow.
Tried removing and reinstalling the environment with no success.
Tried downloading and installing remote packages listed in `workflow/envs/nextstrain.yaml`  manually as this is where the pipeline breaks.
`conda install augur=13.0.0` and `conda install pangolin=2.3.8 `both can't be solved.

**Comment by stevin-wilson** [comment]
Thank you, @Koen-vdl. The workflow works as expected after installing `epiweeks=2.1.2` and excluding the `--use-conda` argument.
