### ISSUE TITLE
Fasta files appear to have different lengths when using get_distance_to_focal_set.py

### ISSUE THREAD

**Issue by suskraem** [nextstrain/ncov#798]
Hello nextstrain developers, 

**Current Behavior**
I am trying to run the python script get_distance_to_focal_set.py as a standalone to obtain distances between a focal set and a global msa. The calculate_snp_matrix function gives the "fasta files appear to have different length" error. Both the ref and focal alignment fasta files are linearized, aligned and have identical length when checking by hand. I slightly altered the script to show detail of the length error and it appears that the that the length of the focal alignment is inflated.

python ncov/scripts/get_distance_to_focal_set.py --alignment msa_1126.fasta --reference hCoV-19__Wuhan__WIV04__2019_aligned_lin.fasta --focal-alignment test_lin.fasta  --output nh_test_dist
Traceback (most recent call last):
  File "ncov/scripts/get_distance_to_focal_set.py", line 174, in <module>
    context_seqs_dict = calculate_snp_matrix(seqs, consensus=ref, chunk_size=chunk_size)
  File "ncov/scripts/get_distance_to_focal_set.py", line 73, in calculate_snp_matrix
    raise ValueError('Fasta file appears to have sequences of different lengths!   '+str(len(s))+" and  "+str(align_length))
ValueError: Fasta file appears to have sequences of different lengths!   35776 and  30148

**Expected behavior**
Obtaining a distance matrix

**How to reproduce**
Steps to reproduce the current behavior:
1. Open / run python ncov/scripts/get_distance_to_focal_set.py using my small example files test_lin.faasta and reference hCoV-19__Wuhan__WIV04__2019_aligned_lin.fasta. The msa_1126.fasta is obviously too huge, but the script shows the error before we get there, so I don't think the nature of the global alignment is important here.
2.
3.

**Possible solution**
(optional)

**Your environment: if running Nextstrain locally**
 - Operating system: CentOS Linux 7
 - Browser: NA
[focal_seq_test.zip](https://github.com/nextstrain/ncov/files/7634861/focal_seq_test.zip)

 - Version (e.g. `auspice 2.7.0`): nextstrain.cli 3.0.4

**Additional context**

**Comment by tibitoy** [comment]
Hi! Was wondering if you ever found a solution for this. Having the same issue now.

**Comment by suskraem** [comment]
sorry, I unfortunately don't remember if/how I solved this. Best of luck!
