### ISSUE TITLE
Broken link to docs about open data

### ISSUE THREAD

**Issue by fritzo** [nextstrain/ncov#802]
**Current Behavior**
I would like to learn how to use Nextstrain's preprocessed open data.  While navigating your July 2021 blogpost ["Extension of SARS-CoV-2 data processing to incorporate Open Data through GenBank"](https://nextstrain.org/blog/2021-07-08-ncov-open-announcement), the [documentation link](https://github.com/nextstrain/ncov/blob/master/docs/remote_inputs.md) is broken.

**Expected behavior**
Do the docs still exist?  I'd love to read them.

**Comment by jameshadfield** [comment]
Apologies for that @fritzo - [here are those docs](https://docs.nextstrain.org/projects/ncov/en/latest/reference/remote_inputs.html). I'll update the blog post shortly. 

P.S. We'll also be adding more thorough documentation for running nCoV builds over the coming weeks

**Comment by fritzo** [comment]
Thanks @jameshadfield, I eventually found the docs and am successfully using your metadata.tsv.gz 😄
