### ISSUE TITLE
Omicron clade definition 21K/L

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/ncov#806]

**Comment by rneher** [comment]
doesn't https://github.com/nextstrain/ncov/pull/804 address this?

**Comment by corneliusroemer** [comment]
Yes yes, this is just an issue I made when adding it to the projects board

The issue is linked to the PR:
![image](https://user-images.githubusercontent.com/25161793/145277633-78664b37-7b2f-4652-acf0-8928187a9ee3.png)
