### ISSUE TITLE
Masking a few nucleotides in N-protein (Italian lineage)

### ISSUE THREAD

**Issue by acx01b** [nextstrain/ncov#81]
Hi, in [this edit](https://github.com/nextstrain/ncov/commit/1b9af7bf7cb521a855bcf311e7ea6224edd1745d#diff-b0ca7e384af213e2f691bf0435d08557)
` mask_sites = "18529 28881 28882 28883"`

[This tweet](https://twitter.com/arambaut/status/1235645418052014080?s=20) suggests that what you thought was a sequencing artifact could be a major mutation

Or did I miss something ?

**Comment by trvrb** [comment]
Thanks for catching this! We had this mask in place when there was just one virus with this triplet mutation and we doubted it was real. Commit 5c96e0291ba4416aefac2af10115d216aeaae9d2 removed this mask and resolves this issue.

**Comment by jameshadfield** [comment]
@acx01b you can see the unmasked mutations here: https://nextstrain.org/ncov?c=gt-nuc_28881,28882,28883
