### ISSUE TITLE
Use latest Nextclade for post-subsampling alignment instead of Nextalign

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#811]
**Context**
After we move filtering to follow subsampling, we will be applying sequence diagnostics with a smaller dataset than we do currently. Most of our diagnostics assume that the input data were previously processed by Nextclade (i.e., the diagnostics look for Nextclade columns in the metadata), but this is not likely to be the case for most users.

Nextclade uses Nextalign internally already to do clade annotations and QC. The latest version of Nextclade more clearly surfaces the alignment output.

**Description**
We should use Nextclade instead of Nextalign for our post-subsampling `align` step of the workflow, to get the benefits of the alignment and diagnostics that users will need for the filter step.

**Comment by fanninpm** [comment]
It's important to consider that the `nextstrain/base` Docker image currently only has Nextalign, not Nextclade.

**Comment by huddlej** [comment]
Assigning @sidneymbell as an indication that her team at CZI has volunteered to work on this in an upcoming sprint.
