### ISSUE TITLE
the new ncov pipline do not fit the docker image

### ISSUE THREAD

**Issue by lzhwin** [nextstrain/ncov#829]
We normally use a docker imgae "nextstrain/base" on docker hub , to run the ncov analyze pipiline.
But, in the  recent update , the main workflow add a new rule include a pangolin anaylze. this step need the pangolin software . but the nextstrain/base image didn't contain pangolin analyze software. 
so , I wonder how to solve the problem. if I still want to use docker to run this pipline. because it really easy to install and update

**Comment by huddlej** [comment]
Hi @lzhwin, this is [an open issue for our Docker base image](https://github.com/nextstrain/docker-base/issues/33). We plan to add support for these Pangolin annotations within the next week or two. In the short term, you can run the workflow without the pangolin annotations (the default behavior or when you set `run_pangolin: false` in your builds YAML file. You may also want to try Nextclade to get multiple clade annotations either through [the web interface](https://clades.nextstrain.org/) or [the command line interface](https://docs.nextstrain.org/projects/nextclade/en/stable/user/nextclade-cli.html).
