### ISSUE TITLE
Customization of branch labels (Auspice and web vizualisation)

### ISSUE THREAD

**Issue by Jerobou** [nextstrain/ncov#832]
Dear Nextstrain team,

First of all, thanks a lot for this wonderful software ! 

I'm currently trying to customize branch labels by adding the possibility to visualize nucleotide mutations through Auspice. In other words, I would like to add a 'nt' option (along the 'aa' one) on the branch label option in the side bar. So far, I was able to do such implementation in the json file for Auspice, by adding a new 'nt' tag (and putting corresponding values for such new tag) on each 'labels' tag , but I fear that this solution isn't really stable.
![Screenshot from 2022-01-06 16-04-39](https://user-images.githubusercontent.com/19343555/148403696-00bc6ee4-0541-4fd2-bc58-3b03dbbf32c2.png)

Do you know if such customization is already implemented in Nextstrain (Augur, Auspice) ? Indeed, I saw that on previous versions of Auspice (especially the 2.5.0 version), customization of branch labels was possible, but I don't know to which extent ! Did I miss something ?

Thanks in advance !

**Comment by jameshadfield** [comment]
Hi Jerobou - as you've found, auspice will happily display any branch label provided in the JSON. I'm not sure what you mean by "I fear that this solution isn't really stable" but there are no plans for auspice to change in this regard.

Currently augur tools don't allow one to customise exported branch labels, although this [should hopefully change soon](https://github.com/nextstrain/augur/pull/728). Currently the best/only way is by using small scripts to further decorate the JSON files consumed by auspice.

**Comment by Jerobou** [comment]
Hi James ! 

Thanks a lot for your answer, that's perfect ! I was a little bit afraid that the solution won't work following new releases (hence the "isn't really stable"), but if I understood well that's not on the table right now.

Thanks again for this wonderful software. 

Jérôme Bourret
