### ISSUE TITLE
Which algorithm you used to infer the parent/child relationships between different clades?

### ISSUE THREAD

**Issue by wanglu2014** [nextstrain/ncov#847]
Your graph in https://nextstrain.org/ncov/gisaid/global is inspiring. Could you kindly suggest how you infer their parent/child relationships? Related code or paper will be a great help!

**Comment by fanninpm** [comment]
Did you scroll down to the bottom of the page you linked? There's a link to a paper at the bottom, and that paper cites [TreeTime.](https://github.com/neherlab/treetime)

**Comment by jameshadfield** [comment]
Hi @wanglu2014 & thanks @fanninpm - by default ncov uses [IQ-TREE](http://www.iqtree.org/) to infer the tree structure and TreeTime to infer temporal structure & attempt to resolve polytomies.
