### ISSUE TITLE
despite including Wuhan/Hu-1/2019 with metadata in builds.yaml, I still get ERROR: unsupported rooting mechanisms or root not found

### ISSUE THREAD

**Issue by mjfos2r** [nextstrain/ncov#849]
I have read all of the current and previous issues, attempted all recommended fixes, and I still am unable to run my build. 

I have included the references in my builds.yaml file, I have made sure they are in include.txt, there are three names for the same reference in include.txt, and I am still getting the error below. I'm just trying to run a simple local analysis of some sequences generated between me and another lab and I would greatly appreciate any help.

after downloading all of the sequences I wish to analyze from GISAID with "for input to augur" selected, I decompress the files into ncov/data, update builds.yaml to include them and the reference, and run the following command: 

`snakemake --profile my_profiles/ltulocalbuild -p`

and no matter what I do, how I include the reference, where I put it/call it from, I get the following errors:

```
`Config file defaults/parameters.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 7
Rules claiming more threads will be scaled down.
Conda environments: ignored
Job stats:
job                         count    min threads    max threads
------------------------  -------  -------------  -------------
add_branch_labels               1              1              1
all                             1              1              1
ancestral                       1              1              1
clades                          1              1              1
distances                       1              1              1
emerging_lineages               1              1              1
export                          1              1              1
finalize                        1              1              1
include_hcov19_prefix           1              1              1
logistic_growth                 1              1              1
mutational_fitness              1              1              1
refine                          1              1              1
rename_emerging_lineages        1              1              1
tip_frequencies                 1              1              1
traits                          1              1              1
translate                       1              1              1
total                          16              1              1

Select jobs to execute...

[Tue Feb  1 03:33:28 2022]
Job 5: 
        Refining tree
          - estimate timetree
          - use opt coalescent timescale
          - estimate marginal node dates
        


        augur refine             --tree results/north-america_usa_northLA/tree_raw.nwk             --alignment results/north-america_usa_northLA/filtered.fasta             --metadata results/north-america_usa_northLA/metadata_adjusted.tsv.xz             --output-tree results/north-america_usa_northLA/tree.nwk             --output-node-data results/north-america_usa_northLA/branch_lengths.json             --root Wuhan/Hu-1/2019             --timetree                          --clock-rate 0.0008             --clock-std-dev 0.0004             --coalescent opt             --date-inference marginal             --divergence-unit mutations             --date-confidence             --no-covariance             --clock-filter-iqd 8 2>&1 | tee logs/refine_north-america_usa_northLA.txt
        
[Tue Feb  1 03:33:31 2022]
Error in rule refine:
    jobid: 5
    output: results/north-america_usa_northLA/tree.nwk, results/north-america_usa_northLA/branch_lengths.json
    log: logs/refine_north-america_usa_northLA.txt (check log file(s) for error message)
    shell:
        
        augur refine             --tree results/north-america_usa_northLA/tree_raw.nwk             --alignment results/north-america_usa_northLA/filtered.fasta             --metadata results/north-america_usa_northLA/metadata_adjusted.tsv.xz             --output-tree results/north-america_usa_northLA/tree.nwk             --output-node-data results/north-america_usa_northLA/branch_lengths.json             --root Wuhan/Hu-1/2019             --timetree                          --clock-rate 0.0008             --clock-std-dev 0.0004             --coalescent opt             --date-inference marginal             --divergence-unit mutations             --date-confidence             --no-covariance             --clock-filter-iqd 8 2>&1 | tee logs/refine_north-america_usa_northLA.txt
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile logs/refine_north-america_usa_northLA.txt:
augur refine is using TreeTime version 0.8.6

2.33	TreeTime.reroot: with method or node: Wuhan/Hu-1/2019
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/nextstrain/bin/augur", line 10, in <module>
    sys.exit(main())
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/refine.py", line 206, in run
    tt = refine(tree=T, aln=aln, ref=ref, dates=dates, confidence=args.date_confidence,
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/augur/refine.py", line 42, in refine
    tt.clock_filter(reroot=reroot, n_iqd=clock_filter_iqd, plot=False) #use whatever was specified
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/treetime/treetime.py", line 345, in clock_filter
    self.reroot(root='least-squares' if reroot=='best' else reroot, covariation=False, clock_rate=fixed_clock_rate)
  File "/home/michael/miniconda3/envs/nextstrain/lib/python3.9/site-packages/treetime/treetime.py", line 471, in reroot
    raise UnknownMethodError('TreeTime.reroot -- ERROR: unsupported rooting mechanisms or root not found')
treetime.UnknownMethodError: TreeTime.reroot -- ERROR: unsupported rooting mechanisms or root not found


Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/michael/Sequencing/analysis/ncov/.snakemake/log/2022-02-01T033327.843029.snakemake.log`
```
Here is my builds.yaml file 

```
#define inputs for the workflow
inputs:
  - name: LTU
    metadata: data/LTU.metadata.tsv
    sequences: data/LTU.sequences.fasta
  - name: GSU
    metadata: data/GSU.metadata.tsv
    sequences: data/GSU.sequences.fasta
  - name: root
    metadata: data/references_metadata.tsv
    sequences: data/references_sequences.fasta`
```
here is my data folder: 
```
ncov$ ls -1 data                                                                                                                                                                              ─╯
GSU.metadata.tsv
GSU.sequences.fasta
LTU.metadata.tsv
LTU.sequences.fasta
references_metadata.tsv
references_sequences.fasta
```

I honestly have no idea why it isn't working. I would greatly appreciate being pointed in the right direction. Thanks!

**Comment by mjfos2r** [comment]
I thought it might have been due to not including it in the ltulocalbuild/builds.yaml file but no, that hasn't fixed it either.

**Comment by emmahodcroft** [comment]
Hi @mjfos2r ! I'm so sorry you're having trouble with getting this to run. 

Just out of curiosity, have you grepped the fasta files you are including as input, to ensure that one of these contains the reference sequence with the _exact_ name as given in your `builds.yaml`? 

If it's there and largely matches, but it has a prefix (ex: `hCoV-19/`) then you'll want to ensure you're running the `align` [step](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L60) that includes the `sanitize_sequences.py` [script](https://github.com/nextstrain/ncov/blob/master/scripts/sanitize_sequences.py), and that this includes the `--strip-prefixes` option, with the prefixes defined in your `build.yaml` (or that they match those pulled in from the default parameters, [here](https://github.com/nextstrain/ncov/blob/master/defaults/parameters.yaml#L9)). (If you do this, you'll also want to ensure you're [sanitizing the metadata](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L1) so they have the same name in both places, and the code can continue to match up the sequences and metadata.)

Please let us know if you're finding the reference sequence and if stripping the prefix helps!

**Comment by mjfos2r** [comment]
> Hi @mjfos2r ! I'm so sorry you're having trouble with getting this to run.
> 
> Just out of curiosity, have you grepped the fasta files you are including as input, to ensure that one of these contains the reference sequence with the _exact_ name as given in your `builds.yaml`?
> 
> If it's there and largely matches, but it has a prefix (ex: `hCoV-19/`) then you'll want to ensure you're running the `align` [step](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L60) that includes the `sanitize_sequences.py` [script](https://github.com/nextstrain/ncov/blob/master/scripts/sanitize_sequences.py), and that this includes the `--strip-prefixes` option, with the prefixes defined in your `build.yaml` (or that they match those pulled in from the default parameters, [here](https://github.com/nextstrain/ncov/blob/master/defaults/parameters.yaml#L9)). (If you do this, you'll also want to ensure you're [sanitizing the metadata](https://github.com/nextstrain/ncov/blob/master/workflow/snakemake_rules/main_workflow.smk#L1) so they have the same name in both places, and the code can continue to match up the sequences and metadata.)
> 
> Please let us know if you're finding the reference sequence and if stripping the prefix helps!

I tried everything that you suggested and it turns out it was something as simple as needing quotation marks around each field in my builds.yaml file. Thank you for your help! Works perfectly now. 

``
inputs:
  - name: "LA-Tech"
    metadata: "data/LTU.metadata.tsv"
    sequences: "data/ltu.filtered.sequences.fasta"
  - name: "LA-GSU"
    metadata: "data/GSU.metadata.tsv"
    sequences: "data/gsu.filtered.sequences.fasta"
  - name: "Wuhan/Hu-1/2019"
    metadata: "data/references_metadata.tsv"
    sequences: "data/references_sequences.fasta"
``
