### ISSUE TITLE
Allow users to disable clock filter for augur refine

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#852]
## Current Behavior

When users try to build Omicron-specific trees against a background of non-Omicron strains, even the relaxed clock filter settings we now use can lead to strains being unexpectedly filtered out.

## Expected behavior

Users should be able to turn off the clock filter completely through the config file.

## Possible solution
Allow users to set the `clock_filter_iqd` parameter in `refine` section of the configuration file to `false` and then modify the corresponding argument in the refine rule to optionally build a command line argument for the clock filter instead of always using the clock filter argument.

**Comment by danrlu** [comment]
FYI @jgadling will tackle this one this sprint (possibly together with https://github.com/nextstrain/ncov/issues/874 pending coordination with Cornelius). Let us know if that sounds good.

**Comment by huddlej** [comment]
That sounds excellent, @danrlu! I've assigned this to you, so we know it is "in progress". If @jgadling comments on this issue, I can assign it to them, instead. Have a great weekend!
