### ISSUE TITLE
nextclade: command not found

### ISSUE THREAD

**Issue by ktmeaton** [nextstrain/ncov#857]
**Current Behavior**
With the introduction of `nextclade` in v11 (`44223bcd` specifically), I see the following error with `--use-conda`:

```text
Downloading reference files for nextclade (used for alignment and qc).

nextclade dataset get --name sars-cov-2 --output-dir data/sars-cov-2-nextclade-defaults

/usr/bin/bash: line 1: nextclade: command not found
```

**Expected behavior**
`snakemake` should be able to find the `nextclade` executable, and not generate this error.

**How to reproduce**

I see this running any build, example:

```bash
# Clean up nextclade defaults if somehow successfully created before
rm -rf data/sars-cov-2-nextclade-defaults

# Run a build
nextstrain build . \
  --cores 4 \
  --use-conda \
  --configfile my_profiles/getting_started/builds.yaml
```

**Possible solution**

I can fix it by adding a conda environment to the rule `prepare_nextclade`:

```yaml
rule prepare_nextclade:
    message:
        """
        Downloading reference files for nextclade (used for alignment and qc).
        """
    output:
        nextclade_dataset = directory("data/sars-cov-2-nextclade-defaults"),
    params:
        name = "sars-cov-2",
    conda: config["conda_environment"]
    shell:
        """
        nextclade dataset get --name {params.name} --output-dir {output.nextclade_dataset}
        """
```

**Your environment: if browsing Nextstrain online**
 - Operating system: NA
 - Browser: NA

**Your environment: if running Nextstrain locally**
 - Operating system: Linux (CentOs 7)
 - Browser: Chrome
 - Version (e.g. `auspice 2.7.0`): `ncov commit 44223bcd`

**Comment by tsibley** [comment]
Thanks @ktmeaton! I've fixed this in #858.
