### ISSUE TITLE
Rewrite and reorganize ncov tutorial

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#863]
**Context**
The ncov tutorial is now outdated and does not represent the primary use case for most users. Additionally, much of the tutorial's contents belong in separate how-to or reference guides.

**Description**
We plan to rewrite and reorganize the tutorial to reflect modern use cases. This issue serves to track progress toward this goal.

**Comment by abattenhouse** [comment]
As an outside user who relies on your documentation, I have noticed how the code has changed but the documentation has not. For example, the description of how to install Nextstrain in a conda using mamba simply does not work. What I do to rebuild my Nextstrain conda from scratch (which sometimes happen when just updating them doesn't work), I use the workflow/envs/nextstrain.yaml file, and also add auspice.

**Comment by jameshadfield** [comment]
> I have noticed how the code has changed but the documentation has not. 

This is a perpetual struggle -- we have to adapt the workflow as the world changes, and this can lead to documentation (especially text-heavy tutorials) falling out of sync. We are obviously trying to improve things here, and the rewrite should be released in a few weeks.

> For example, the description of how to install Nextstrain in a conda using mamba simply does not work.

Would you mind making this a separate issue? This approach _should_ work.

**Comment by abattenhouse** [comment]
Thanks. I've added a new issue for the mamba install.
