### ISSUE TITLE
Link to CDC and CZI GenEpi training videos from documentation

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#898]
**Context**
During office hours, we often get questions about what training materials exist to help people get started with genomic epidemiology. Outside of our software-focused tutorials, several other resources exist that we should link to from our docs.

**Description**
Add links to [CZI GenEpi](https://czgenepi.org/resources) and [CDC video](https://www.cdc.gov/amd/training/covid-19-gen-epi-toolkit.html) tutorials to our SARS-CoV-2 docs

**Comment by victorlin** [comment]
Done as part of #894. The links are at the bottom of the [tutorial Next Steps page](https://docs.nextstrain.org/projects/ncov/en/latest/tutorial/next-steps.html).
