### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#9]
@PierreBarrat has said he'll have a go at a French translation of the narrative! :)
I've created a page for it in the narratives folder, and will now create a branch as well. This issue is just for any necessary discussion/questions etc.

**Comment by emmahodcroft** [comment]
@PierreBarrat there's now a new branch `sit-rep_fr` that you can work on, and a new file in the `narratives` folder called `ncov_sit-rep_fr_2020-01-25.md` which you can modify with the translation!

**Comment by jameshadfield** [comment]
Thanks @PierreBarrat!

**Comment by CristianPumaES6** [comment]
Hi desde perú,
quisiera traducir algunas narrativas, donde las consigo?

**Comment by Simon-LoriereLab** [comment]
With Pierre technical help, I finished the French translation that he started (in the sit-rep_fr branch).

**Comment by emmahodcroft** [comment]
@Simon-LoriereLab That's amazing! 
You can see a preview of it here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_fr/sit-rep/fr/2020-01-30
If you think it looks good, I can push it live!

**Comment by emmahodcroft** [comment]
Ah - I need to update some of the URLs - let me do that quickly and I'll let you know when to look at the preview! Sorry!

**Comment by emmahodcroft** [comment]
@Simon-LoriereLab Great! I just made a few tiny fixes to the URLs and to some links. 
Can you check out the preview here? https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_fr/sit-rep/fr/2020-01-30
If it all looks good, let me know and I'll push it live!

**Comment by Simon-LoriereLab** [comment]
Everything looks good, you can push it! The only part not translated is on the first page (copied below) but this is the same in other translated versions:
 (Explore the content by scrolling the left hand side (or click on the arrows), and the data visualizations will change accordingly. Clicking "explore the data yourself" (top right of page) will replace this narrative with a set of controls so that you may interact with the data. )

**Comment by emmahodcroft** [comment]
Great, I'll do that now! 

Yes unfortunately this text is pushed on the server-side, and doesn't come in from the page that you guys work on. Long-term we can definitely fix, this, but we just never anticipated needing to implement different languages so suddenly, so it's  not perfect!

However, it's good spotting, and I'll make an issue, so we can remember to get to it!

**Comment by emmahodcroft** [comment]
The link is live here: https://nextstrain.org/narratives/ncov/sit-rep/fr/2020-01-30

And I've tweeted it about it here: https://twitter.com/nextstrain/status/1223287249040760832

And it's live on the Nextstrain site as well! (Sorry, took a few minutes for all that to happen)

Thank you both so much for your help with this - it's fantastic to have a French version!
