### ISSUE TITLE
Translate Situation Report to Japanese

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#92]
The narrative from 2020-03-05 should be translated to Japanese. A branch exists as `sit-rep_ja` where this can be done, and the file to translate is `ncov_sit-rep_ja_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_ja/narratives/ncov_sit-rep_ja_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links! (Links to other-language versions of articles on Wikipedia are ok.)

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ja/sit-rep/ja/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

Please also write your twitter handle and/or full name if you'd like to be attributed when we announce!

**Comment by emmahodcroft** [comment]
@satotake can you Change your PR to merge into the `sit-rep_ja` branch? Once pushed this will then allow us to view a preview live :)

**Comment by emmahodcroft** [comment]
Thanks @satotake! You can preview your work here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_ja/sit-rep/ja/2020-03-05 How is it looking?

**Comment by fzhang12** [comment]
Hi @satotake , I read your translation and it was great. Excellent job!
I just added some Japanese name of the places, remove couple of english lines that you forgot to delete.
thank you @emmahodcroft for your contribution and I think the content is good to go. but I am not sure how to write satotake's name in the author list (Take Sato is my guess). Let's wait for his reply.

**Comment by satotake** [comment]
Hi @fzhang12 .
Your guess is valid but my name is "Takeshi Sato"
Anyway thank you for your comment!

**Comment by fzhang12** [comment]
@satotake Yes I was thinking maybe Takeshi should be more frequent www. 
No problem, I've update your correct name into the author list. 

@emmahodcroft I am glad to announce the Japanese translation is ready.

Happy to work with both of you :)

**Comment by cassiawag** [comment]
@fzhang12 & @satotake -- excellent work!

I'm getting this posted. Do you have twitter handles we can tag in the announcement?

**Comment by emmahodcroft** [comment]
This is great news guys! Can you pass us your twitter handles (Sorry, I know we ask over and over - don't have any good place to store this!), and @cassiawag will coordinate pushing it live - as soon as we have your twitters we can tweet!

**Comment by cassiawag** [comment]
It's live at: https://nextstrain.org/narratives/ncov/sit-rep/ja/2020-03-05

Thanks everyone for the hard work!

**Comment by cassiawag** [comment]
It's now Tweeted at:  https://twitter.com/nextstrain/status/1237061228645711878

@satotake -- we can add your twitter as a comment. Great working with everyone.
