### ISSUE TITLE
Translate Situation Report to Dutch

### ISSUE THREAD

**Issue by cassiawag** [nextstrain/ncov#93]
The narrative from 2020-03-05 should be translated to Dutch. A branch exists as sit-rep_nl where this can be done, and the file to translate is ncov_sit-rep_nl_2020-03-05.md (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_nl/narratives/ncov_sit-rep_nl_2020-03-05.md

Note this file is in Markdown - it's important not to change any links! (Links to other-language versions of articles on Wikipedia are ok.)

Comments to help with translation are noted in comment symbols like 

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_nl/sit-rep/nl/2020-03-05

Please remember to push often as multiple people may be working on this translation!

Please also write your twitter handle and/or full name if you'd like to be attributed when we announce!

**Comment by emmahodcroft** [comment]
@cassiawag  just switch that second `ja` to `nl` in the first link to the file ;)

**Comment by cassiawag** [comment]
Fixed ;)

**Comment by emmahodcroft** [comment]
@roanvanscheppingen I've merged your PR into the `sit-rep_nl` branch, and you can use this link to preview your work: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_nl/sit-rep/nl/2020-03-05

It looks like the first slide is done, but others are incomplete, is that right? (No problem if so, just checking!)

**Comment by roanvanscheppingen** [comment]
I now got to the FAQ and misconceptions (line 78), but I think I should not translate the titles of the articles? Just mention the articles are in English? 

How does committing or pushing things work? Now I have  created a Pull Request for the first 78 lines. Is that how it works? How can I then keep working on the same file?

**Comment by emmahodcroft** [comment]
It's ok, you can keep working on the same file and just make commits, and then push - to the branch that you are working on your own computer. When you push, it'll update the PR - but sorry, I just merged them for you!

**Comment by emmahodcroft** [comment]
If you want You can do a few pushes to the PR and then I'll merge, and you can use the link in the issue to preview!

The FAQs we will want to translate... but later. It's a bit much to coordinate now. Feel free to translate the links or not - but yes, if you can warn they are in English. Most browsers support some kind of translation nowadays anyway....

**Comment by roanvanscheppingen** [comment]
Okay, I think I have most of it right now.
Would be nice if a second Dutch person can go over it (some translations are a bit liberal) or someone else can also check on things that are not translated yet. 

If you have any questions, hit me up on Twitter @RScheppingen

**Comment by cassiawag** [comment]
@roanvanscheppingen thanks for the translation! We're on the lookout for another Dutch translator. Do you have any recommendations?

**Comment by roanvanscheppingen** [comment]
Maybe https://twitter.com/GertvanderHoek
He is often retweeted by Flutrackers about COV. Seems Dutch :)

Good luck on your endevour

**Comment by emmahodcroft** [comment]
A friend has volunteered to read through! But of course, more eyes often better :)

**Comment by emmahodcroft** [comment]
My friend @JiscaH has read and made a few minor edites! @roanvanscheppingen if you are happy with all, can you let us know if it's ok to go live? 
(preview link: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_nl/sit-rep/nl/2020-03-05)

**Comment by JiscaH** [comment]
Disclaimer: I don't know the dutch translation for many technical terms, and suspect that the English words are commonly used. Also my grammar is rusty after living abroad for a decade. 

I've now added some links to dutch wikipedia + RIVM ('dutch CDC') too.

**Comment by roanvanscheppingen** [comment]
I've edited a few double points, a grammar mistake and a change in an abbreviation. 
It seems to be ready for live! 

Thanks also JiscaH. It is true, some technical terms translate really bad into Dutch. I've kept some in English or modified them towards Dutch spelling (clusters/sequencen. English words are commonly used and Dutch people are quite ok with reading English.

**Comment by emmahodcroft** [comment]
This translation is fixed and ready to go! @cassiawag  (whenever you can)

**Comment by cassiawag** [comment]
It's live at: https://nextstrain.org/narratives/ncov/sit-rep/nl/2020-03-05
Thanks all for the hard work!
