### ISSUE TITLE
Translate Situtation Report to Hindi

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/ncov#95]
The narrative from 2020-03-05 should be translated to Hindi. A branch exists as `sit-rep_hi` where this can be done, and the file to translate is `ncov_sit-rep_hi_2020-03-05.md` (you can translate in this file directly). The file is here: https://github.com/nextstrain/ncov/blob/sit-rep_hi/narratives/ncov_sit-rep_hi_2020-03-05.md

Note this file is in Markdown - it's important **not** to change any links! (Links to other-language versions of articles on Wikipedia are ok.)

Comments to help with translation are noted in comment symbols like `<!-- Comment -->`

You can preview your changes (after pushing) here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_hi/sit-rep/hi/2020-03-05

Please remember to *push often* as multiple people may be working on this translation!

Please also write your twitter handle and/or full name if you'd like to be attributed when we announce!

**Comment by ronakb128** [comment]
Hi, I would like to translate this in Hindi but I might need some help

**Comment by cassiawag** [comment]
Thanks for your offer to translate, @ronakb128 ! I'm here to help; please follow Emma's instructions above, and let me know if you run into _any_  issues.

**Comment by emmahodcroft** [comment]
@ronakb128 This looks great! You can preview the translation live here: https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_hi/sit-rep/hi/2020-03-05 And check everything looks as it should. If you need to make any more changes just make another PR and I'll merge it ASAP!

**Comment by emmahodcroft** [comment]
Would you like me to tag you in our release announcement on twitter when it happens? I saw your account had a lock, so no worries if not. (Or please let me know how you might like to be announced - by name, nickname, etc!)

**Comment by ronakb128** [comment]
@emmahodcroft the preview looks excellent. Yeah, it would be great if you can tag my twitter account with the release announcement. Thanks!

**Comment by emmahodcroft** [comment]
Excellent! I'll just see if I can one more pair of eyes to proofread, then we can release!

**Comment by ronakb128** [comment]
Sounds good

**Comment by emmahodcroft** [comment]
@KanikaNahata Would you mind proofreading this version to see if it looks ok? You can view the live preview here: 
https://nextstrain.org/community/narratives/nextstrain/ncov@sit-rep_hi/sit-rep/hi/2020-03-05 

If you see any changes you want to make, fork the `sit-rep_hi` branch, make your changes, then make a PR back to this branch. I'll merge the PR and you can see how your changes look in the preview, and when you feel ready, let me know when it's ready to push live!

**Comment by emmahodcroft** [comment]
I'm about to head to lunch so there might be a little delay if you submit a PR in the next hour, but I'll get on it as soon as I'm back ;)

**Comment by KanikaNahata** [comment]
It looks really good! I do not have suggestions :)

**Comment by emmahodcroft** [comment]
Great, thank you! I'll push live soon!

**Comment by emmahodcroft** [comment]
Thank you both for your hard work! Live and tweeted here!: https://twitter.com/nextstrain/status/1237020133375213568

**Comment by cassiawag** [comment]
@KanikaNahata & @ronakb128 -- any interest in helping out on weekly translations? See issue #118. No worries if you're unable to commit, but would love to get this out into Hindi!

**Comment by ronakb128** [comment]
Hi @cassiawag I am sorry I have other commitments this month. I'll let you know if someone from the lab can do it.

**Comment by KanikaNahata** [comment]
Hi @cassiawag , similar to @ronakb128 I have other commitments this month so I will not be the best support! Good luck!

**Comment by cassiawag** [comment]
@ronakb128 & @KanikaNahata -- very understandable. Thanks for letting me know!
