### ISSUE TITLE
Link out to CDC curated datasets

### ISSUE THREAD

**Issue by huddlej** [nextstrain/ncov#954]
Just a note that Jason Caravas has created [subsampled datasets for US states based on open GenBank data](https://github.com/CDCgov/usa-sars-cov-2-nextstrain-sets/). We should link out to this resource from our "remote inputs" page.

**Comment by j23414** [comment]
I assume these links to sequences & metadata should be added to the table at?

* https://github.com/nextstrain/ncov/blob/master/docs/src/reference/remote_inputs.rst#summary-of-available-genbank-open-files

**Comment by victorlin** [comment]
I created the PR above, putting them in the Data Prep guide since users are more likely to visit that than the remote inputs page.
