### ISSUE TITLE
URL preview from rebuild-gisaid.yml output does not work

### ISSUE THREAD

**Issue by victorlin** [nextstrain/ncov#990]
**Current Behavior**

I ran [rebuild-gisaid.yml](https://github.com/nextstrain/ncov/blob/338e07e0c393f1288da3be61ebce6bca2d7d0ed4/.github/workflows/rebuild-gisaid.yml) to test this workflow running with `augur filter --engine sqlite`, a feature being developed in nextstrain/augur#854.

I see that the Batch job has succeeded, and the files are there under `s3://nextstrain-ncov-private`. However, I don't see anything at the URL provided for preview (https://nextstrain.org/staging/ncov/gisaid/trial/victorlin-test-sqlite).

**Expected behavior**

The URL to view results should work.

**How to reproduce**

This is what I did, copied from https://github.com/nextstrain/augur/pull/854#discussion_r940740077:

1. Created https://github.com/nextstrain/docker-base/commit/ad3f5fbb375137750109aa079d9caa1bb7bc9c97
2. Created https://github.com/nextstrain/ncov/commit/e3490aa9509c244e419a2df490041505467015e5
3. [Ran rebuild-gisaid.yml with](https://github.com/nextstrain/ncov/actions/runs/2821555519):
    - branch: `victorlin/test-augur-filter-sqlite-engine`
    - trial build name: `victorlin-test-sqlite`
    - image: `nextstrain/base:branch-victorlin-test-augur-filter-sqlite-engine`

From the build info:

```
--> Trial name is: victorlin-test-sqlite

--> When completed, the following will be available:
build files: s3://nextstrain-ncov-private/trial/victorlin-test-sqlite/
nextstrain URLs: https://nextstrain.org/staging/ncov/gisaid/trial/victorlin-test-sqlite/REGION_NAME

--> You can attach to this AWS job via:
nextstrain build --aws-batch --attach f4662522-becf-448a-b48b-3c5cca988[31](https://github.com/nextstrain/ncov/runs/7736121686?check_suite_focus=true#step:5:32)3 /home/runner/work/ncov/ncov

--> View this job in the AWS console via
    https://console.aws.amazon.com/batch/home?region=us-east-1#jobs/detail/f4662522-becf-448a-b48b-3c5cca988313
```

4. Log into AWS console for access to S3 and Batch history.
5. Observe that the batch job succeeded.
6. Observe that files are there under `s3://nextstrain-ncov-private/trial/victorlin-test-sqlite/`.
7. Observe that this URL does not serve the datasets: https://nextstrain.org/staging/ncov/gisaid/trial/victorlin-test-sqlite

**Possible solution**

Maybe the URL template is incorrect?

https://github.com/nextstrain/ncov/blob/338e07e0c393f1288da3be61ebce6bca2d7d0ed4/.github/workflows/rebuild-gisaid.yml#L74

**Comment by joverlee521** [comment]
Ah, behavior on staging is a little weird (maybe intentional?) in that you have to provide the _exact_ url to the dataset.

Since the builds are now split into different timespans (`all-time`, `6m`, `2m`), you need to go to `https://nextstrain.org/staging/ncov/gisaid/trial/$TRIAL_NAME/<REGION_NAME>/<TIME_SPAN>`
For example: https://nextstrain.org/staging/ncov/gisaid/trial/victorlin-test-sqlite/global/all-time

**Comment by victorlin** [comment]
Oh ok! I also tried https://nextstrain.org/staging/ncov/gisaid/trial/victorlin-test-sqlite/global but makes sense why that doesn't work now. I'll make a PR to add `<TIME_SPAN>` and maybe a valid example URL too.
